### ISSUE TITLE
tui: support a key 'f' for field change in graph mode

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#1013]
The current tui graph mode only shows "total" by default, but it could show more fields from the command line option `-f`.

It'd be better to provide a way to customize fields in graph mode in interactive mode. I think `f` key can be mapped for this purpose. It could show a new box window just like `h` key for help message, then provide check boxes for each field.

**Comment by nasafix-nasser** [comment]
Hi,
May I work on this?

**Comment by nasafix-nasser** [comment]
Thank you.

**Comment by honggyukim** [comment]
@nasafix-nasser Do you have any update? Please let me know if you have any questions working on this.

**Comment by hjongkim** [comment]
Hello. If there is no update, can I try?

**Comment by honggyukim** [comment]
@hjongkim It's good to see you again. It's thankful if you work on it.

**Comment by honggyukim** [comment]
In addition to this, you can modify tui sort key to set the cursor to the same function. In the current implementation, when `s` key is pressed, the report window is sorted and the cursor goes to the top. But I'd rather want to make the cursor to be set to the same function.

**Comment by qpakzk** [comment]
Hello @honggyukim 
No one seems to have work on this issue, so I tried it.

Is this right what you intended?

https://user-images.githubusercontent.com/20490285/109505716-3f686000-7ae0-11eb-8b23-819837ab7d73.mp4

**Comment by honggyukim** [comment]
@qpakzk Thanks a lot for doing this!

> Is this right what you intended?

Exactly. Could you please send a PR?

**Comment by namhyung** [comment]
@qpakzk nice work!  Thanks for doing this and I'll review the code.
