### ISSUE TITLE
d8 launch failed

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#103]
Hi,

I've found a problem when running d8 with current master uftrace.
```
$ uftrace -vv -t 100ms d8 -e ''
symbol: check trace functions in d8
uftrace: creating 10 thread(s) for recording
uftrace: using libmcount.so library for tracing
uftrace: start writer thread 0
uftrace: start writer thread 1
uftrace: start writer thread 2
uftrace: start writer thread 3
uftrace: start writer thread 4
uftrace: start writer thread 5
uftrace: start writer thread 6
uftrace: start writer thread 7
uftrace: start writer thread 8
uftrace: start writer thread 9
mcount: initializing mcount library
symbol: loading dynamic symbols from /home/honggyu/work/v8/git/v8/out/x64.debug/d8
mcount: opening executable image: /home/honggyu/work/v8/git/v8/out/x64.debug/d8
```
And it doesn't have any response. I've found the commit(9479ec2) that affects this problem as follows:
Please have a look at it!

**Comment by namhyung** [comment]
Hmm.. it worked well before the commit?  Could you please test attached patch?

[mcount-Check-loop-condition-in-segv_handler.patch.txt](https://github.com/namhyung/uftrace/files/1028219/mcount-Check-loop-condition-in-segv_handler.patch.txt)

**Comment by namhyung** [comment]
Oh, I found a stupid bug in `PAGE_ADDR` macro..  The following patch should fix the problem IMHO.

[mcount-Fix-a-bug-in-PAGE_ADDR-macro.patch.txt](https://github.com/namhyung/uftrace/files/1028268/mcount-Fix-a-bug-in-PAGE_ADDR-macro.patch.txt)

**Comment by honggyukim** [comment]
It works fine, but the patch has to simply be as follows:
```
diff --git a/libmcount/plthook.c b/libmcount/plthook.c
index 17ce3da..7e668af 100644
--- a/libmcount/plthook.c
+++ b/libmcount/plthook.c
@@ -27,7 +27,7 @@ static unsigned long got_addr;
 static volatile bool segv_handled;

 #define PAGE_SIZE  4096
-#define PAGE_ADDR(addr)  ((addr) & (PAGE_SIZE - 1))
+#define PAGE_ADDR(addr)  ((addr) & ~(PAGE_SIZE - 1))

 static void segv_handler(int sig, siginfo_t *si, void *ctx)
 {
```
Thanks!

**Comment by namhyung** [comment]
Thanks for confirmation.
