### ISSUE TITLE
check locale setting when installing man pages

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#1039]
The current install build always install English man pages and it can be changed by adding `DOCLANG=ko` for Korean man pages.

But what about checking locale setting when installing man pages? I think it's easier for general users.

**Comment by namhyung** [comment]
I don't want to change default (English) man page installation since it's the default language for "C" locale.  We might do additional installation depending on locale..

**Comment by honggyukim** [comment]
I'm fine with it as well anyway. Thanks.
