### ISSUE TITLE
Enable travis-ci on pull requests

### ISSUE THREAD

**Issue by gonapps** [namhyung/uftrace#1049]
Currently travis-ci is disabled on pull requests.
If you enable it, it will be automatically detect changes that make unittest or build fail.

**Comment by honggyukim** [comment]
If it's possible for the pull requests as well, why not having it?

**Comment by namhyung** [comment]
Yes, that'd be really helpful.  Could you please take a look and figure out how we can enable it?

**Comment by gonapps** [comment]
@namhyung 
You can enable by clicking 'Build pushed pull requests' at https://travis-ci.org/namhyung/uftrace/settings

**Comment by namhyung** [comment]
Hmm.. it seems already enabled.

**Comment by gonapps** [comment]
@namhyung Oh it looks like now travis ci status is shown on github pull requests. Thanks

**Comment by gonapps** [comment]
Hmm.. not sure travis ci check will be shown without checking new pull requests in future

**Comment by namhyung** [comment]
You can see it when you open "All tests have passed" -> "Show all checks"

**Comment by gonapps** [comment]
Yeah but pull requests before #1051 there is only a codefactor check
For example: https://github.com/namhyung/uftrace/pull/1050
Did you changed some settings and is this solved now?

**Comment by gonapps** [comment]
Looks like travis-ci is enabled! I'll close this issue
