### ISSUE TITLE
For better performance, use the hash map instead of rbtree to find the function that caller of mcount.

### ISSUE THREAD

**Issue by ParkHanbum** [namhyung/uftrace#1057]
as you know, hashmap has better performance than rbtree when search value by fixed key. for currently, uftrace use rbtree to find which function call the mcount. because mcount offset in function is not a fixed. but we can use disassemler for now, therefore we can calculate address which has call mcount.

I think it can be guarantee better performance, and significantly save the time.

**Comment by namhyung** [comment]
OK, so you want to use it for non-dynamic tracing case as well, right?  Then yes, I think it's possible when capstone is usable.
