### ISSUE TITLE
kernel event tracing support

### ISSUE THREAD

**Issue by namhyung** [namhyung/uftrace#108]
The linux kernel provides event tracing though tracefs.  As we use ftrace infrastructure for function tracing, event tracing can be supported same way.  Allow -E option can have events contain "@kernel" mark for kernel event tracing.  The event information will be saved in "kernel_header" file in the data directory.

Following example shows scheduler events during sleep 1 second.

```
  $ uftrace -k -E sched:*@kernel --force /usr/bin/sleep 1
  # DURATION    TID     FUNCTION
  ...
     3.529 us [23463] | bindtextdomain();
     2.021 us [23463] | textdomain();
     1.419 us [23463] | __cxa_atexit();
              [23463] | getopt_long() {
              [23463] |   __do_page_fault() {
              [23463] |     /* [sched:sched_waking] comm=uftrace pid=23464 prio=120 target_cpu=003 *  /
              [23463] |     /* [sched:sched_wake_idle_without_ipi] cpu=3 */
              [23463] |     /* [sched:sched_wakeup] comm=uftrace pid=23464 prio=120 target_cpu=003 *  /
    25.903 us [23463] |   } /* __do_page_fault */
     1.478 us [23463] |   smp_irq_work_interrupt();
    32.931 us [23463] | } /* getopt_long */
     0.775 us [23463] | getopt_long();
     1.929 us [23463] | __errno_location();
     1.202 us [23463] | newlocale();
     4.695 us [23463] | strtod_l();
     0.203 us [23463] | __errno_location();
              [23463] | nanosleep() {
              [23463] |   sys_nanosleep() {
     1.560 us [23463] |     smp_irq_work_interrupt();
              [23463] |     /* [sched:sched_stat_runtime] comm=sleep pid=23463 runtime=341360 [ns] vruntime=2911893876206 [ns] */
              [23463] |     /* [sched:sched_switch] prev_comm=sleep prev_pid=23463 prev_prio=120 prev_state=S ==> next_comm=swapper/2 next_pid=0 next_prio=120 */
     1.000  s [23463] |   } /* sys_nanosleep */
     1.000  s [23463] | } /* nanosleep */
    12.491 us [23463] | __fpending();
     3.210 us [23463] | fileno();
     2.337 us [23463] | __freading();
     0.346 us [23463] | __freading();
     4.188 us [23463] | fflush();
              [23463] | fclose() {
              [23463] |   sys_close() {
     3.812 us [23463] |     smp_irq_work_interrupt();
    14.803 us [23463] |   } /* sys_close */
    27.770 us [23463] | } /* fclose */
  ...
```

Pushed the code to [review/kernel-event-v1](https://github.com/namhyung/uftrace/commits/review/kernel-event-v1) branch.

**Comment by Taeung** [comment]
I thought a trivial thing..
We can tell reviewers [review/kernel-event-v1](https://github.com/namhyung/uftrace/compare/master...review/kernel-event-v1) branch compared to master branch,
instead of just [review/kernel-event-v1](https://github.com/namhyung/uftrace/commits/review/kernel-event-v1). How about that ?

**Comment by namhyung** [comment]
I cannot understand.. could you please elaborate?

**Comment by Taeung** [comment]
When you tell branch name at the end of comment on this issue like below,

> Pushed the code to review/kernel-event-v1 branch.

I thought it is better to tell reviewers a branch URL(i.e. https://github.com/namhyung/uftrace/compare/master...review/kernel-event-v1) compared to master branch
instead of just [review/kernel-event-v1](https://github.com/namhyung/uftrace/commits/review/kernel-event-v1) IMHO

**Comment by Taeung** [comment]
I found `NG` from the test `148 event_kernel` but is it just due to difference of kernel version ?
Don't we consider it ?
 
```
$ uname -r
4.5.0-rc4+

$ sudo ./runtest.py -d event_kernel
Test case                 pg             finstrument-fu
------------------------: O0 O1 O2 O3 Os O0 O1 O2 O3 Os
t148_event_kernel: diff result of -pg -O0
--- expect	2017-06-20 23:56:55.544535059 +0900
+++ result	2017-06-20 23:56:55.544535059 +0900
@@ -7,2 +7,3 @@
        usleep() {
+         syscall_trace_enter_phase1();
          sys_nanosleep() {
@@ -10,2 +11,3 @@
          } /* sys_nanosleep */
+         syscall_slow_exit_work();
        } /* usleep */

```

**Comment by namhyung** [comment]
> I thought it is better to tell reviewers a branch URL(i.e. master...review/kernel-event-v1) compared to master branch

Ah, ok.  Thanks for the info! :)

> I found NG from the test 148 event_kernel but is it just due to difference of kernel version ?

I guess it's because you enabled kernel syscall tracing?

**Comment by Taeung** [comment]
Ah.. I got it..

**Comment by namhyung** [comment]
Pushed to [review/kernel-event-v2](https://github.com/namhyung/uftrace/commits/review/kernel-event-v2).

Changelog:
 * enabled kernel tracing without -k option
 * setup event-fork option to follow children

**Comment by namhyung** [comment]
Pushed to [review/kernel-event-v3](https://github.com/namhyung/uftrace/compare/review/kernel-event-v3).

Changelog:
 * adjust print format in accordance with the user event
 * clean-up error handing during record

**Comment by namhyung** [comment]
Pushed [review/kernel-event-v4](https://github.com/namhyung/uftrace/compare/review/kernel-event-v4).

Changelog:

* support (partial) glob matching (e.g. "sched:sched_process_*")
* fixup pid filter update on fork/vfork
* do not imply kernel function tracing

**Comment by namhyung** [comment]
Pushed [review/kernel-event-v5](https://github.com/namhyung/uftrace/compare/review/kernel-event-v5)

Changelog:
 * further fixup for pid filter update
