### ISSUE TITLE
REAME.md update is needed

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#110]
The current limitation is out-dated so needs to be updated.

Limitations
- It can only trace a native C/C++ application compiled with -pg option.
- It cannot trace already running process.
- It cannot be used for system-wide tracing.
- It only supports x86_64 and ARM (v6,7) for now.

**Comment by namhyung** [comment]
What about this?

* It can trace a native C/C++ applications only.
* It cannot trace already running processes.
* It cannot be used for system-wide tracing.
* It supports x86_64, ARM (v6 or later) and AArch64 for now.

**Comment by honggyukim** [comment]
I think it's fine. Thanks!
