### ISSUE TITLE
CI support for multiple arch & compiler

### ISSUE THREAD

**Issue by DanielTimLee** [namhyung/uftrace#1112]
Currently, uftrace is using Travis CI for testing builds and unittests.

Recently, Travis CI released beta version of 
[Multi-cpu arch support](https://blog.travis-ci.com/2019-10-07-multi-cpu-architecture-support) 

Since it only includes amd64, arm64, so it won't support all of our architectures,
But it will help to test briefly.

Also, travis support multiple compiler builds. (Gcc, clang)

For example, adding this derictives to `.travis.yml`
```yaml
language: c

arch:
  - amd64
  - arm64

compiler:
  - gcc
  - clang
```

Will create build matrix of 2x2 : each arch x compilers.

More detailed info can be found at [Here](https://docs.travis-ci.com/user/multi-cpu-architectures/)

**Comment by honggyukim** [comment]
Thanks. It looks very useful.
