### ISSUE TITLE
support debugging info in separate files

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#1144]
In some cases, debug info can be in separate files. Since the current uftrace implementation doesn't support such cases, it can fail to read symbol tables and debug info.

Here is the way how to generate debug info in separate files summarized in [1].

1. Compile with debug information:
```
$ gcc -g -o main main.c
```
2. Separate the debug information:
```
$ objcopy --only-keep-debug main main.debug
       or
$ cp main main.debug
$ strip --only-keep-debug main.debug
```
3. Strip debug information from origin file:
```
$ objcopy --strip-debug main
       or
$ strip --strip-debug --strip-unneeded main
```
4. debug by debuglink mode:
```
$ objcopy --add-gnu-debuglink main.debug main
$ gdb main
```
5. You can also use exec file and symbol file separately:
```
$ gdb -s main.debug -e main
       or
$ gdb
(gdb) exec-file main
(gdb) symbol-file main.debug
```

In this case, the program `main` cannot be traced with uftrace full dynamic tracing feature because it cannot find any function information. So it needs to be supported in the long term.

[1] [How to generate gcc debug symbol outside the build target?
](https://stackoverflow.com/questions/866721/how-to-generate-gcc-debug-symbol-outside-the-build-target) [2] [Debugging Information in Separate Files](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/4/html/Debugging_with_gdb/separate-debug-files.html)

**Comment by honggyukim** [comment]
The separate debug info is found based on `.gnu_debuglink` section.
> A debug link is a special section of the executable file named .gnu_debuglink. The section must contain:
> 
> - A filename, with any leading directory components removed, followed by a zero byte,
> - zero to three bytes of padding, as needed to reach the next four-byte boundary within the section, and
> - a four-byte CRC checksum, stored in the same endianness used for the executable file itself. The checksum is computed on the debugging information file’s full contents by the function given below, passing zero as the crc argument.
>
> Any executable file format can carry a debug link, as long as it can contain a section named .gnu_debuglink with the contents described above.

https://sourceware.org/gdb/onlinedocs/gdb/Separate-Debug-Files.html

**Comment by namhyung** [comment]
Yes, I know there are some more cases to support separate debug files.  Will take a look at them later..

**Comment by namhyung** [comment]
Also there's an on-going work on the debuginfod.

https://developers.redhat.com/blog/2019/10/14/introducing-debuginfod-the-elfutils-debuginfo-server/

**Comment by honggyukim** [comment]
We can find null-terminated string at the `Offset` in `.gnu_debuglink` section.
```
$ readelf -a program
Section Headers:
  [Nr] Name              Type             Address           Offset
       Size              EntSize          Flags  Link  Info  Align
      ...
  [29] .gnu_debuglink    PROGBITS         0000000000000000  005abd38
       0000000000000020  0000000000000000           0     0     4
      ...
```

**Comment by namhyung** [comment]
I think #1406 can be an answer.

**Comment by honggyukim** [comment]
Hmm.. I think it's a different issue. I wanted to get debug info from external files without using pre-recorded `uftrace.data`.

**Comment by namhyung** [comment]
Right, it's different.  But I think it can be helpful in some cases.

**Comment by bernhardkaindl** [comment]
Hello @namhyung and @honggyukim @!!!

After checking out `utils/dwarf.c`, using libdwfl functions (fl: frontend library) is feasible!!!

The libdwfl functions auto-magically find the split debuginfo files behind their doors.

I've started looking at it and working on using it in `utils.dwarf.c` and it looks doable so far!

According to my changelog investigation, the libdwfl functions might be in usable state since about elfutils-0.131,
so thy should work in any modern libdw, [more recent versions were further enhanced to support zstd compression](https://android.googlesource.com/platform/external/elfutils/+/bda19c410f124ba9e871314cd0e1461e181834eb/NEWS).

Are you up for accepting them into uftrace?

**Comment by bernhardkaindl** [comment]
@namhyung :

blueprint for which functions to use, needs to be called with -i to show debug info:
https://gist.github.com/bernhardkaindl/7ea7ebfff29b4a4526ae58fef56ddf7f

I already have done the updates to use dwfl functions to open debuginfo.

It seems I'll need to convert `util/dwarf.c:build_dwarf_info()` into a callback for 
`dwfl_getdwarf (dwfl, &build_dwarf_info, &get_functions, p);`

**Comment by bernhardkaindl** [comment]
This issue is started to be addressed with #1671

**Comment by namhyung** [comment]
Please see [review/separate-dwarf](../compare/review/separate-dwarf).

**Comment by honggyukim** [comment]
The only concern is that @bernhardkaindl's email. It's written as `Bernhard Kaindl <bernhard.kaindl@citrix.com>`, but this email is not linked to his GitHub profile. Can we change it to `Bernhard Kaindl <bernhardkaindl7@gmail.com>` so that his contribution can be shown correctly in our contributor list?
https://github.com/namhyung/uftrace/commits?author=bernhardkaindl

**Comment by namhyung** [comment]
I don't think it's a good idea  It's based on his work and he chose the email address.

**Comment by bernhardkaindl** [comment]
@honggyukim @namhyung: The citrix.com email was an accidental slip on my side from syncing/sharing a `.gitconfig` file that was edited and had the wrong email address.

All my commits should always have been with and Signed-off-by: `Bernhard Kaindl <bernhardkaindl7@gmail.com>` instead.

`Signed-off-by: Bernhard Kaindl <bernhardkaindl7@gmail.com>`

I'm happy if you can correct my Signed-off-by in the commit(s) to it.

I'm also happy to try the new master with the debug information when the work is merged!

**Comment by honggyukim** [comment]
Hi @bernhardkaindl, I'm glad to hear from you again. Your work makes uftrace much more useful when tracing package installed binaries. Thanks for the confirmation!

**Comment by namhyung** [comment]
@bernhardkaindl thanks, I'll update it with your gmail.

**Comment by namhyung** [comment]
Please check [review/separate-dwarf](../compare/review/separate-dwarf) again.
