### ISSUE TITLE
failure on collecting correct kernel-cpuXX

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#1151]
If some cpus are offlined especially from the initial numbers, then current implementation fails to collect correct `kernel-cpuXX.dat`. It's because it just simply count the number of cpus, then collect from `cpu0` by looping over the number of cpus.

Here is the problematic cpu settings.
```
$ cat /sys/devices/system/cpu/possible
0-7

$ cat /sys/devices/system/cpu/offline
0-3,6-7

$ cat /sys/devices/system/cpu/online
4-5
```
In this case, uftrace has to collect `kernel-cpu4.dat` and `kernel-cpu5.dat`, but it just collects `kernel-cpu0.dat` and `kernel-cpu1.dat`, which are empty because they are offlined.

We need to fix this by collecting the online cpus only.

**Comment by honggyukim** [comment]
If this issue is fixed, then it can also be simpler to handle the problem as mentioned in https://github.com/namhyung/uftrace/pull/945#pullrequestreview-304215689.

**Comment by namhyung** [comment]
I'm not sure but if it'd return a specific error code for offline cpus, then we could check it and move onto the next.

**Comment by honggyukim** [comment]
I'm sorry but could you please explain what you mean?

**Comment by namhyung** [comment]
Something like this?

```c
for (i = 0; i < num_cpu; i++) {
   if (check_cpu(i) < 0)  // check error code?
      continue;
   ...
   // creates "kernel-cpu${i}".dat
}
```

**Comment by honggyukim** [comment]
Thank you. The following print statement shows only online cpus so it needs to be changes to find all the available cpus.
```diff
diff --git a/utils/kernel.c b/utils/kernel.c
index d7dc3571..23324563 100644
--- a/utils/kernel.c
+++ b/utils/kernel.c
@@ -651,6 +652,7 @@ int setup_kernel_tracing(struct uftrace_kernel_writer *kernel, struct opts *opts
                return ret;

        kernel->nr_cpus = n = sysconf(_SC_NPROCESSORS_ONLN);
+       fprintf(stderr, "kernel->nr_cpus = %d\n", kernel->nr_cpus);

        kernel->traces  = xcalloc(n, sizeof(*kernel->traces));
        kernel->fds     = xcalloc(n, sizeof(*kernel->fds));
```

**Comment by honggyukim** [comment]
We may have to use `sysconf(_SC_NPROCESSORS_CONF)` and loop over all the available cpus, then decide which cpu is online.

**Comment by namhyung** [comment]
Right!

**Comment by honggyukim** [comment]
I just tested and found that simply changing from `_SC_NPROCESSORS_ONLN` to `_SC_NPROCESSORS_CONF` works fine. It generates some empty `kernel-cpuXX.dat` files, but it's better to keep them during record because some CPUs might be turned on/off during execution.
