### ISSUE TITLE
display the file name of function

### ISSUE THREAD

**Issue by LoisHuang** [namhyung/uftrace#1152]
Hello, whether the output could contain the file name of the function?

**Comment by honggyukim** [comment]
If you record with `--srcline` or `-a` option, then tui command shows the source location info at the bottom.

Please note that the target binary must have debug info, which is generated by `-g` option just like using `gdb` tool.

**Comment by honggyukim** [comment]
#1133 is under review and it shows source location info in `report` command.

**Comment by LoisHuang** [comment]
Thanks for your reply! But I seemingly encountered one problem  when I used `tui `command, that the foot line displayed `uftrace graph: source location is not available [at 0x40063b] `. How can I solve this problem?

**Comment by honggyukim** [comment]
Please make sure the followings:
- if the binary is compiled with `-g` option.
- if the uftrace.data is recorded with one of `--srcline` or `-a` option. You can check if data directory has `.dbg` file inside.

Thanks for using uftrace.

**Comment by LoisHuang** [comment]
Appreciate for your explanation! I used `gcc -finstrument-functions -g test.c` firstly, and it could not display the source line correctly. Then I changed the command to  `gcc -pg -g test.c` , and I can get the source line information now.

**Comment by honggyukim** [comment]
Thanks for finding the problem. 

The problem is that it's not possible to read argument info if the given binary is built with `-finstrument-functions` due to the generated code patterns.

The `.dbg` files contain argument info along with source location info, but the current implementation do not generate `.dbg` file for `-finstrument-functions` built binaries.

But I think uftrace has to produce `.dbg` file only for `-finstrument-functions` built binaries if `--srcline` option is given regardless of argument info.

The following change will be working fine for `-finstrument-functions` built binaries.
```diff
diff --git a/utils/dwarf.c b/utils/dwarf.c
index ace3a63e..8c85d67e 100644
--- a/utils/dwarf.c
+++ b/utils/dwarf.c
@@ -262,9 +262,6 @@ static int setup_dwarf_info(const char *filename, struct debug_info *dinfo,
 {
        int fd;

-       if (!force && check_trace_functions(filename) != TRACE_MCOUNT)
-               return 0;
-
        pr_dbg2("setup dwarf debug info for %s\n", filename);

        fd = open(filename, O_RDONLY);
```

**Comment by honggyukim** [comment]
@LoisHuang I've made a PR to fix this problem. Please see #1155. Thanks very much for reporting this problem.

**Comment by LoisHuang** [comment]
It's very kind of you to offer me so much help. Thank you so much again!

**Comment by namhyung** [comment]
Yes, originally the debug info is only used to detect arguments and return values.  But with `--srcline` it can be used to display file names and line numbers too.  Currently uftrace cannot display arguments/returns for binaries built with `-finstrument-functions` and it remained to refuse debug info parsing.  Thanks to Honggyu for working on this.

**Comment by honggyukim** [comment]
@LoisHuang I'm glad it can be helpful to you. We always want to hear the voice of uftrace users, but it's difficult to get some feedback. Thank you again.
