### ISSUE TITLE
uftrace does not work properly with signals.

### ISSUE THREAD

**Issue by junhyung-lee38** [namhyung/uftrace#1164]
I want to turn trace on / off via signal during process runtime.
However, if I executed uftrace and process through the following command and sent a signal (SIGUSR1, SIGUSR2, ... ) during process running, uftrace is abnormally terminated.

$ uftrace record --disable --signal SIGUSR1@trace_on ./test &
and then, I confirmed process state using ps command.
 1798 ttyHSL0  00:00:00 login
 1859 ttyHSL0  00:00:00 sh
 1944 ttyHSL0  00:00:00 uftrace
 1945 ttyHSL0  00:00:00 test
 1947 ttyHSL0  00:00:00 ps

I send a signal SIGUSR1( signal 10 ) to uftrace pid.
$ kill -USR1 1944
or 
$ kill -10 1944

finally, uftrace is terminated.
root@8x96auto:/var# ps
  PID TTY          TIME CMD
 1813 ttyHSL0  00:00:00 login
 1832 ttyHSL0  00:00:00 sh
 1896 ttyHSL0  00:00:00 test
 1902 ttyHSL0  00:00:00 ps
[1]+  User defined signal 1   ./uftrace record --disable --signal SIGUSR1@trace_on ./test

Is there any problem controlling the uftrace using signals?

**Comment by namhyung** [comment]
Hmm.. ok, I admit that it is confusing..  But in fact, the uftrace process (1944) is not the one running your program and processing the signal.  Instead, you should send it to your test program (1945).  We should update documentation about this..

The internals are bit complex but basically uftrace forks and runs the target process with libmcount library which communicates back to uftrace process.

**Comment by junhyung-lee38** [comment]
Thanks for your reply!

I had to send signal to the test program as you said.
It works!
It was just my mistake;;
Thank you very much!
