### ISSUE TITLE
analysis commands still shows linux:schedule event for caller filter

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#1173]
`linux:schedule` event is disabled for caller filter during record as follows.
- d908312 record: Disable linux:schedule event for caller filter

However, it's still shown in analysis commands such as replay, etc. `linux:schedule` also has to be disabled for analysis commands.

In addition, it has to be applied when caller trigger is enabled as well.

**Comment by namhyung** [comment]
It should be closed by 55ab685b.
