### ISSUE TITLE
configuration failure on system without `pkg-config`

### ISSUE THREAD

**Issue by bavernet** [namhyung/uftrace#1189]
A few features cannot be enabled on a system without `pkg-config` although proper packages are already installed.

For example,
In order to enable TUI feature, I installed libncursesw5-dev package.
The feature (libncursesw) was still disabled as follows:
```
$ sudo apt install libncursesw5-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libncursesw5-dev is already the newest version (6.1-1ubuntu1.18.04).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

$ ./configure               
uftrace detected system features:
...         prefix: /usr/local
...         libelf: [ on  ] - more flexible ELF data handling
...          libdw: [ OFF ] - DWARF debug info support
...      libpython: [ on  ] - python scripting support
...      libluajit: [ OFF ] - luajit scripting support
...    libncursesw: [ OFF ] - TUI support
...   cxa_demangle: [ on  ] - full demangler support with libstdc++
...     perf_event: [ on  ] - perf (PMU) event support
...       schedule: [ on  ] - scheduler event support
...       capstone: [ OFF ] - full dynamic tracing support
```

I found that the check routine uses `pkg-config` and it is not installed on my system, which could make users confused.

The following features are checked by `pkg-config`
```
libluajit, libncurses, libdw, libcapstone
```

I think it would rather to provide warning messages that it could come from `pkg-config`.

**Comment by honggyukim** [comment]
Hi @bavernet, have you tried to run the following command?
```
$ sudo ./misc/install-deps.sh -y
```
You can try again if it shows the same problem. Thanks.

**Comment by bavernet** [comment]
It works!!
I am sorry to confuse you.
I should have read INSTALL.md before creating this issue. Thanks.

**Comment by honggyukim** [comment]
No problem. I'm just wondering why `libncursesw` shows `OFF` although you manually installed `libncursesw5-dev`. `./misc/install-deps.sh` actually installs the same thing.

Thanks for creating the issue anyway :)

**Comment by namhyung** [comment]
The `install-deps.sh` script installs `pkg-config` too.
