### ISSUE TITLE
"undefined reference to `_Py_Dealloc'" with python3.8

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#1190]
There is some compilation errors when python3.8 is installed in the system.
```
$ sudo apt install libpython3.8-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
libpython3.8-dev is already the newest version (3.8.5-1+xenial1).
libpython3.8-dev set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 270 not upgraded.

$ make
  LINK     uftrace
/home/honggyu/work/uftrace/utils/script-python.o: In function `_Py_DECREF':
/usr/include/python3.8/object.h:478: undefined reference to `_Py_Dealloc'
/usr/include/python3.8/object.h:478: undefined reference to `_Py_Dealloc'
/usr/include/python3.8/object.h:478: undefined reference to `_Py_Dealloc'
/usr/include/python3.8/object.h:478: undefined reference to `_Py_Dealloc'
/usr/include/python3.8/object.h:478: undefined reference to `_Py_Dealloc'
/home/honggyu/work/uftrace/utils/script-python.o:/usr/include/python3.8/object.h:478: more undefined references to `_Py_Dealloc' follow
collect2: error: ld returned 1 exit status
Makefile:294: recipe for target '/home/honggyu/work/uftrace/uftrace' failed
make: *** [/home/honggyu/work/uftrace/uftrace] Error 1
```

**Comment by namhyung** [comment]
Why did you install version 3.8 specifically?  Didn't 'python3-dev' work?

It might link with a bad version of the library.. What's the output of `python3-config --libs`?

**Comment by honggyukim** [comment]
I have to manage two different python3 versions for internal reasons. I found that this problem happens because of the difference between python3 and python3-config version difference, which was already shown before.

The PR #1082 actually fixes the problem, but I will close this issue if you don't think this is a problem.

Otherwise, we may be able to check if python3 and python3-config has the same version. The `python3-config --version` doesn't show the correct version though.

**Comment by namhyung** [comment]
I still think it's a unnecessary hack - I assume that a reasonable system should have python3-config to point a correct version.  But maybe I can live with that..

**Comment by honggyukim** [comment]
Okay. I will close this issue.
