### ISSUE TITLE
Python3 config trouble

### ISSUE THREAD

**Issue by namhyung** [namhyung/uftrace#1197]
I found that my system doesn't have python support even if I installed `python3-dev` package.  And I found that from python 3.8 they added `--embed` option for programs embedding the python interpreter.  It seems python3-config is primarily for people who develop python extension module..  So it resulted in failure in the feature check.

Anyway without the `--embed`, python3-config didn't print the python library for `--libs` or `--ldflags`.  But it's only supported for 3.8 or later, we should check the version (otherwise it'd fail).

https://github.com/python/cpython/pull/13500

```
$ python3-config --libs
 -lcrypt -lpthread -ldl  -lutil -lm -lm 

$ python3-config --embed --libs
-lpython3.8 -lcrypt -lpthread -ldl  -lutil -lm -lm 
```

**Comment by honggyukim** [comment]
It may not be a very nice way to fix this but I've added one more check binary `have_libpython3.8_` to handle this. Please have a look at #1198. Thanks.

**Comment by namhyung** [comment]
No, I have something different in mind.  Will post it soon.
