### ISSUE TITLE
New script: retval-histogram.py

### ISSUE THREAD

**Issue by namhyung** [namhyung/uftrace#1199]
I need to measure which values a function returns which running.  So I added retval-histogram.py script to do it in a general way.  However, I found several issues about python scripting.  So there are some fixes and work-around to them as well.  Also it seems that we need to install those script somewhere (like `$prefix/libexec/uftrace/` or `$prefix/share/uftrace/`?) and load from such directory.

The code is available at [review/retval-histogram-v1](https://github.com/namhyung/uftrace/compare/review/retval-histogram-v1)

The retval-histogram.py script shows histogram of return values of given function.

```
$ uftrace script -S scripts/retval-histogram.py
Usage: retval-histogram.py [-- -u <unit>] <function>
  Unit is one of b, k, m, g
```

You need to pass a function name to it.

```
$ uftrace script -S scripts/retval-histogram.py  strlen
histogram of return value of 'strlen'

 <     0b  :          0  (  0.0 %)
 <     2b  :          5  (  2.3 %)
 <     4b  :         11  (  5.1 %)
 <     8b  :         24  ( 11.1 %)
 <    16b  :         41  ( 19.0 %)
 <    32b  :         68  ( 31.5 %)
 <    64b  :         49  ( 22.7 %)
 <   128b  :         16  (  7.4 %)
 <   256b  :          2  (  0.9 %)
 <   512b  :          0  (  0.0 %)
 <  1024b  :          0  (  0.0 %)
 >= 1024b  :          0  (  0.0 %)
```

As you can see, strlen() returns 16 ~ 32 size mostly. The first line (< 0b) is to check functions returning negative numbers for error.
    
The basic unit is 'b' (byte) but you can also pass -u option to do it with k (kilo), m (mega), g (giga) unit.  Note that you should use two dashes ("--") before it to distinguish it from uftrace arguments.

```
$ uftrace script -S scripts/retval-histogram.py -- -u m strlen
```

**Comment by namhyung** [comment]
Pushed [review/retval-histogram-v2](https://github.com/namhyung/uftrace/compare/review/retval-histogram-v2).

Changelog:
* fix build error with earlier python versions
* update some description and comment

**Comment by honggyukim** [comment]
I've tested and got the same output. It looks useful!
