### ISSUE TITLE
Can uftrace read debug symbols after the binary has run?

### ISSUE THREAD

**Issue by bitsmaker** [namhyung/uftrace#1228]
Sorry for the confusing title. I am on a platform that does not have a lot of RAM and makes it nearly impossible to run binaries with debug info. 

Would it be possible to run a release version similar to what the tool "perf" does? Then move the results to an X64 platform where the debug binaries or symbols exist. Then have uftrace read the results and use the debug binaries or symbols to replace the addresses with function names etc.

Thanks for considering,
Bobby

**Comment by namhyung** [comment]
Hello,

Thanks for using uftrace.  I understand your concern and am aware of the situation in the embedded development.  But unfortunately, uftrace doesn't support that as of now.

To make it work, we need to change it to save necessary symbol and debug info files (without running the program) first.  This can be done on a different machine like you said.  And then use the info for the actual runs without parsing the symbol table and debug info section.  It will improve the performance of starting large programs.

I cannot say when I can work on this feature, but I'll consider it as high priority as it's requested a couple of times already.

**Comment by bitsmaker** [comment]
Hi

Thanks for your detailed response. Also thank you for treating this as a high priority. I will be happy to test it for you!

Bobby

**Comment by namhyung** [comment]
Please test [check/with-syms-v1](https://github.com/namhyung/uftrace/compare/check/with-syms-v1).

At first, you can save the data with a binary has full symbol information.  Let's say it as "uftrace.data.syms".

After that you can strip the binary and run uftrace with it.  When replay (or other analysis command) you can use --with-syms option with the name of the directory (like "uftrace.data.syms").

For example:
```
# myprog has symbols
$ uftrace record -d uftrace.data.syms  myprog

$ strip myprog

$ uftrace record myprog

# no symbol in the output
$ uftrace replay

# this will show symbols!
$ uftrace replay --with-syms uftrace.data.sym
```

**Comment by honggyukim** [comment]
@namhyung Thanks for doing this work. It works fine with the example you shared.

I have a few questions.
1. does it work for library symbols?
2. including library symbols that are `dlopen`ed?
3. can we do the same thing for `.dbg` files?

I feel like giving `--with-syms` option all the time looks annoying. Can we install the symbol into the recorded data or can we use `--with-syms` at runtime?

**Comment by honggyukim** [comment]
If the purpose of this requirement is to make the target binary striped, then we can think about separating the symbol info in a separate file. We might be able to handle this issue together if #1144 is completed.

**Comment by namhyung** [comment]
> 1. does it work for library symbols?

Yep, I think so.

> 2. including library symbols that are `dlopen`ed?

Probably.. :)

> 3. can we do the same thing for `.dbg` files?

I'm not sure.. it seems not work currently.  But there's no reason for that, I'll check it in the next version.

Yeah, I'm aware of the #1144 and it's a slightly different issue.  I'll take care of it later.

**Comment by namhyung** [comment]
> I feel like giving --with-syms option all the time looks annoying.

If you find yourself doing the same thing repeatedly, you can add a shell script or an alias for it like:
```
alias uws='__uws() { cmd=$1; shift; uftrace $cmd --with-syms=myprog.syms $*; }; __uws'
```

**Comment by namhyung** [comment]
Currently it cannot use filters or triggers in record time.  I'll add it later so that we can use it like `uftrace record --with-syms ...` and then the result will contain symbols in the with-syms directory.

**Comment by namhyung** [comment]
I'm working on #1406 now.
