### ISSUE TITLE
compiler error on fedora 33

### ISSUE THREAD

**Issue by majianpeng** [namhyung/uftrace#1229]
In fedora 33, i met the following error message when make.
>>/mnt/trace-tools/uftrace/utils/script-python.c: In function ‘__Py_DECREF’:
>>/mnt/trace-tools/uftrace/utils/script-python.c:83:2: error: ‘_Py_DEC_REFTOTAL’ undeclared (first use in this function); did you mean ‘_Py_DECREF’?
   83 |  _Py_DEC_REFTOTAL;
      |  ^~~~~~~~~~~~~~~~
      |  _Py_DECREF

Python 3.9.1 (default, Dec  8 2020, 00:00:00).
Google search:  https://github.com/python-greenlet/greenlet/commit/c644ca6823994b958e004b3e00b587723181b58e.

I try and bug fixed.

**Comment by namhyung** [comment]
Thanks for the report!

According to your info, it seems we need the _Py_DEC_REFTOTAL only if Py_REF_DEBUG is defined.  And we don't build uftrace with it so I think we can simply remove the code.  Do you mind sending a PR?

**Comment by namhyung** [comment]
Will add this:

```diff
diff --git a/utils/script-python.c b/utils/script-python.c
index f5662b69..1812792e 100644
--- a/utils/script-python.c
+++ b/utils/script-python.c
@@ -80,7 +80,6 @@ static PyAPI_FUNC(void) (*__Py_Dealloc)(PyObject *);
 
 static inline void __Py_DECREF(PyObject *obj)
 {
-       _Py_DEC_REFTOTAL;
        if (--obj->ob_refcnt == 0)
                __Py_Dealloc(obj);
 }
```
