### ISSUE TITLE
Support policy for uftrace report diff

### ISSUE THREAD

**Issue by namhyung** [namhyung/uftrace#124]
Add `--diff-policy` option to control `uftrace report --diff` behavior.  Originally it shows diff percentage sorted by total time in base data.  With this change it shows diff values sorted by absolute difference of total time.  Users can control it with the `--diff-policy` option.  Also default sort column was set to 2 in order to sort the result by actual difference.

The code is available at [review/diff-policy-v1](https://github.com/namhyung/uftrace/compare/review/diff-policy-v1).

The old style output can be shown like below:
```
$ uftrace report -d fibo.data --diff fibo.data.old --sort-column 0 --diff-policy percent,no-abs
#
# uftrace diff
#  [0] base: fibo.data    (from uftrace record -d fibo.data fibonacci 5 )
#  [1] diff: fibo.data.old (from uftrace record -d fibo.data fibonacci 5 )
#
                 Total time (diff)                   Self time (diff)                       Calls (diff)   Function
  ================================   ================================   ================================   ================================================
   16.588 us   25.024 us   +50.86%     2.394 us    2.718 us   +13.53%            1          1         +0   main
   12.586 us   19.600 us   +55.73%    12.586 us   19.600 us   +55.73%            9          9         +0   fib
    1.803 us    2.853 us   +58.24%     1.803 us    2.853 us   +58.24%            1          1         +0   __monstartup
    1.731 us    2.194 us   +26.75%     1.731 us    2.194 us   +26.75%            1          1         +0   __cxa_atexit
    1.608 us    2.706 us   +68.28%     1.608 us    2.706 us   +68.28%            1          1         +0   atoi
```

The new style (abs, no-percent) follows:
```
$ uftrace report -d fibo.data --diff fibo.data.old
#
# uftrace diff
#  [0] base: fibo.data   (from uftrace record -d fibo.data fibonacci 5 )
#  [1] diff: fibo.data.old (from uftrace record -d fibo.data fibonacci 5 )
#
                    Total time (diff)                      Self time (diff)                       Calls (diff)   Function
  ===================================   ===================================   ================================   ================================================
   16.588 us   25.024 us    +8.436 us     2.394 us    2.718 us    +0.324 us            1          1         +0   main
   12.586 us   19.600 us    +7.014 us    12.586 us   19.600 us    +7.014 us            9          9         +0   fib
    1.608 us    2.706 us    +1.098 us     1.608 us    2.706 us    +1.098 us            1          1         +0   atoi
    1.803 us    2.853 us    +1.050 us     1.803 us    2.853 us    +1.050 us            1          1         +0   __monstartup
    1.731 us    2.194 us    +0.463 us     1.731 us    2.194 us    +0.463 us            1          1         +0   __cxa_atexit
```

Unfortunately, this data has only positive diff values but with absolute policy negative entries can be put upper in the result.

**Comment by honggyukim** [comment]
Thanks for this work! This is the feature I was waiting for. I've tested it and the output looks very good. But I'm just wondering if the following result is correct.
```
$ uftrace report -d uftrace.data.printf/ --diff uftrace.data --sort-column 2 --sort call
#
# uftrace diff
#  [0] base: uftrace.data.printf/       (from uftrace record lua printf.lua )
#  [1] diff: uftrace.data       (from uftrace record lua sort.lua )
#
                    Total time (diff)                      Self time (diff)                       Calls (diff)   Function
  ===================================   ===================================   ================================   ================================================
  402.951 us  715.478 us  +312.527 us   229.415 us  400.920 us  +171.505 us         1339       1639       +300   luaM_realloc_
  175.918 us  317.116 us  +141.198 us   175.918 us  317.116 us  +141.198 us         1341       1641       +300   l_alloc
   65.165 us  146.228 us   +81.063 us    64.403 us  144.968 us   +80.565 us         1148       1722       +574   save
   57.521 us  121.293 us   +63.772 us    56.405 us  119.032 us   +62.627 us          938       1236       +298   mainposition
   65.029 us  156.998 us   +91.969 us    65.029 us  156.998 us   +91.969 us          896       1565       +669   luaH_getstr
  191.433 us  573.453 us  +382.020 us   139.154 us  410.597 us  +271.443 us          703       1861      +1158   luaH_get
  722.177 us    1.501 ms  +779.052 us   176.852 us  378.750 us  +201.898 us          695        932       +237   newkey
  608.755 us    1.264 ms  +655.963 us   132.130 us  303.274 us  +171.144 us          637        999       +362   luaH_set
  288.665 us  361.560 us   +72.895 us    84.077 us  113.515 us   +29.438 us          520        776       +256   sweeplist
  240.506 us  450.217 us  +209.711 us    95.274 us  182.453 us   +87.179 us          501        708       +207   luaS_newlstr
  204.588 us  248.045 us   +43.457 us    52.266 us   58.718 us    +6.452 us          445        488        +43   freeobj
   25.082 us   67.354 us   +42.272 us    25.082 us   67.354 us   +42.272 us          438        852       +414   index2adr
```
I've tested lua interpreter and executed two different lua scripts. My intention was to make diff sorted by the difference of call counts. But it seems that it's not sorted based on `Calls (diff)` column.

**Comment by honggyukim** [comment]
Thanks. I have a minor preference request. It shows `+` in read and `-` in blue, but I prefer to make `+` in green and `-` in red similar to the color in diff output. :)

**Comment by namhyung** [comment]
I thought about it :).  But I'd like to avoid similar color with time unit - green for 'ms'.  I admit that red is also used for time unit (minutes and hours) but it should be rare.

**Comment by namhyung** [comment]
Hmm.. right, blue is hardly readable.  Maybe cyan is ok.

**Comment by namhyung** [comment]
Pushed the update to [review/diff-policy-v2](https://github.com/namhyung/uftrace/compare/review/diff-policy-v2).

Changes
 * fix bug in sort by calls
 * change color: blue -> cyan
 * update example in man page

**Comment by honggyukim** [comment]
I think cyan is good!

**Comment by Taeung** [comment]
The red "+" and cyan "-" is great !
I thought it'd be better to color not only the sign character but also values.
I can't see well because the colored character is just one..

How you already exclude the colored values with https://github.com/namhyung/uftrace/commit/a7f5c7490ea4d0848a1760c735e2a49d41722505 .. hum

Due to the colored unit ("ms", "s", "m", etc) ?

**Comment by honggyukim** [comment]
@Taeung I agree. I would like to see more color in values as well.

**Comment by namhyung** [comment]
Well, I don't know.  It seems like a preference but I find it annoying if all values/percentages were colored (like in old output).  It's just a mark for a direction (positive or negative) and I think normal text is more readable, isn't it?

**Comment by namhyung** [comment]
OK, I changed to apply color to numbers.  Could you guys please take a look and tell me whether it's better than before?

link: [review/diff-policy-v3](https://github.com/namhyung/uftrace/compare/review/diff-policy-v3)

**Comment by namhyung** [comment]
I changed the color scheme a bit and pushed the code to [review/diff-policy-v4](https://github.com/namhyung/uftrace/compare/review/diff-policy-v4)

Changes:
 * use 4 colors for diff numbers too (for +/-5us and +/-100us respectively)
 * use bright red and blue color
 * add 'func' sort key for function name
 * add test cases
