### ISSUE TITLE
warning in tests/s-dwarf2.cpp

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#1250]
We can fix the following warning in `tests/s-dwarf2.cpp`.
```
$ g++ tests/s-dwarf2.cpp
tests/s-dwarf2.cpp: In function ‘int main()’:
tests/s-dwarf2.cpp:30:17: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   30 |  A(E, FOO, BAR, "debug info test");
      |                 ^~~~~~~~~~~~~~~~~

$ clang++ tests/s-dwarf2.cpp
tests/s-dwarf2.cpp:30:17: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
        A(E, FOO, BAR, "debug info test");
                       ^
1 warning generated
```

**Comment by himanshu007-creator** [comment]
Hi, i would like to work on this issue. please assign me this issue.My solution include usage of **strdup()** function
It will create a copy of string and when used, wont genetrate  an error.
>additions++
><code>include <string.h></code>
>L32 <code>A(E, FOO, BAR, strdup("debug info test"));</code>

Output-->

>...Program finished with exit code 0                                                                                                          
Press ENTER to exit console.

**Comment by kangtegong** [comment]
> Hi, i would like to work on this issue. please assign me this issue.My solution include usage of **strdup()** function
> It will create a copy of string and when used, wont genetrate an error.
> 
> > additions++
> > `include <string.h>`
> > L32 `A(E, FOO, BAR, strdup("debug info test"));`
> 
> Output-->
> 
> > ...Program finished with exit code 0
> > Press ENTER to exit console.

Oh, sorry.. I just saw your comment but I just amended and sent PR on this issue..

**Comment by himanshu007-creator** [comment]
Ah! Missed it , nevermind the issue must me solved, who does it doesn't matter😬

**Comment by honggyukim** [comment]
@himanshu007-creator @kangtegong Thanks both of you!
