### ISSUE TITLE
Flame Graph is misleading

### ISSUE THREAD

**Issue by mattyclarkson** [namhyung/uftrace#1257]
Using `uftrace dump --flame-graph` is misleading it _seems_ to be using the number of function entry/exit times to create the flame graph, not really sure.

When using `uftrace dump --chrome` it is possible to get the [_Call Tree_](https://developer.chrome.com/docs/devtools/evaluate-performance/reference/#call-tree) that represents the percentage of time spent in each function. This does not seem to match up with the corresponding flame graph output.

The question is, _What does the flame graph represent?_. If the answer to that is the proportional time spent in each function, it does not seem to be correct (according to the corresponding Chrome output and `uftrace report` output).

**Comment by mattyclarkson** [comment]
Seems like [--sample-time <period>|https://github.com/namhyung/uftrace/commit/a31ce47f6dc9b174d2295c47286557043bb45d37] is the thing to use here. Might be worth adding to the `README.md`.

**Comment by namhyung** [comment]
Thanks for the report.  I was aware of the issue but forgot to update.

When I added the flame graph support, it was hard to choose the correct sampling period.  If it's too big we might miss some details, while it can be costly if we choose too small.  So I was thinking about dynamic sampling period based on the total trace time or data size.  At the moment it's not available unless it walk through the data, so I ended up using number of function calls.

Now it's available in a part of the info data, I can add the logic.  Will update the doc too!

**Comment by honggyukim** [comment]
This may require to change the existing option but I would prefer to change `--flame-graph` option to reduce confusion.
- By default, `--flame-graph` shows in time unit rather than number of calls. I hope it works like having `--sample-time 1ns`.
- Deprecate `--sample-time` option and reuse `-t`/`--time-filter` option to reduce the time threshold.
-  If user wants to use number of calls, then reuse `-s`/`--sort` option like `-s call`.

The example usages can be
```
$ uftrace dump --flame-graph
(works same as current "uftrace dump --flame-graph --sample-time 1ns")
```
```
$ uftrace dump --flame-graph -t 100us
(works same as current "uftrace dump --flame-graph --sample-time 100us")
```
```
$ uftrace dump --flame-graph -s call
(works same as current "uftrace dump --flame-graph")
```

**Comment by namhyung** [comment]
I've updated the logic to choose a sample time automatically.  PTAL [review/flame-sample-v1](../compare/review/flame-sample-v1).

**Comment by honggyukim** [comment]
@namhyung Sorry for the late feedback. It looks good but it'd be better to add the description about the logic in the `dump` man page.

**Comment by namhyung** [comment]
Thanks for your feedback.  I'll add the description.
