### ISSUE TITLE
tui: Customize fields in report mode interactively

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#1259]
@qpakzk implemented TUI with field customization for graph mode in #1240.

We have to apply the same change to report mode as well.

**Comment by qpakzk** [comment]
@honggyukim Hello.
I'm going to try it in this weekend.

**Comment by honggyukim** [comment]
@qpakzk Sure. Thanks! We actually plan to make a new release soon so wanted to make the features complete as much as possible.
