### ISSUE TITLE
uftrace shared libraries lack a SONAME

### ISSUE THREAD

**Issue by amadio** [namhyung/uftrace#1266]
Hi, I am maintaining a Gentoo Linux package for uftrace. We noticed that uftrace installs shared libraries that lack a SONAME.
Are these libraries expected to be used by something other than uftrace, or are they like plugins? uftrace itself doesn't seem to link against these libraries (libmcount*.so).

See also https://bugs.gentoo.org/724278.

**Comment by honggyukim** [comment]
Hi, sorry for late answer but thanks for reaching us out. I think you're mentioning about `libmcount*.so` libraries. These libraries are preloaded into the target process that is forked by `uftrace` so they are not directly linked by `uftrace` binary. And could you clarify what you mean by lacking a SONAME?

FYI, we made a new release `uftrace-v0.10` a few days ago so if you're trying to make a package for uftrace then it'd be grateful if you could pick this new release.

**Comment by namhyung** [comment]
@amadio thanks for your work on the packaging.  The libmcount*.so libraries are not intended to be linked with others so it doesn't need a SONAME.

**Comment by amadio** [comment]
Ok, thank you, that is what I thought. I changed the package so they are installed into `/usr/lib64/uftrace` rather than `/usr/lib64` directly, where other system libraries go. I also packaged the new version while at it. Cheers,
