### ISSUE TITLE
Compiler warning on utils/script-python.c

### ISSUE THREAD

**Issue by namhyung** [namhyung/uftrace#1268]
Now I'm seeing a repeated compiler warning from the python code.

```
  CC FPIC  libmcount/script-python.op
uftrace/utils/script-python.c:39:1: warning: ‘visibility’ attribute ignored [-Wattributes]
   39 | static PyAPI_FUNC(void) (*__Py_Initialize)(void);
      | ^~~~~~
uftrace/utils/script-python.c:40:1: warning: ‘visibility’ attribute ignored [-Wattributes]
   40 | static PyAPI_FUNC(void) (*__Py_Finalize)(void);
      | ^~~~~~
uftrace/utils/script-python.c:41:1: warning: ‘visibility’ attribute ignored [-Wattributes]
   41 | static PyAPI_FUNC(void) (*__PySys_SetPath)(char *);
      | ^~~~~~
uftrace/utils/script-python.c:42:1: warning: ‘visibility’ attribute ignored [-Wattributes]
   42 | static PyAPI_FUNC(PyObject *) (*__PyImport_Import)(PyObject *name);
      | ^~~~~~
...
```

I guess the attribute is hidden in the PyAPI_FUNC macro.  Also I don't think we need the macro from the beginning..

**Comment by kangtegong** [comment]
I'll remove the macro and perform tests, if you don't mind.
If it's ok to remove, I'll send the patch.

**Comment by namhyung** [comment]
It'd be nice if you work on it, but I'd wait for @honggyukim in case I missed something.

**Comment by honggyukim** [comment]
I don't see such warnings. Which compiler do you use?

Anyway, `PyAPI_FUNC` is defined at [here](https://github.com/python/cpython/blob/4d4be477055d0f9e415407bcd193788fae04dc11/Include/pyport.h#L699) as follows.
```c
/* If no external linkage macros defined by now, create defaults */
#ifndef PyAPI_FUNC
#       define PyAPI_FUNC(RTYPE) Py_EXPORTED_SYMBOL RTYPE
#endif
```
The `Py_EXPORTED_SYMBOL` is defined at [here](https://github.com/python/cpython/blob/4d4be477055d0f9e415407bcd193788fae04dc11/Include/exports.h#L21) as follows.
```c
#if defined(_WIN32) || defined(__CYGWIN__)
    ...
#else
    ...
    #if (defined(__GNUC__) && (__GNUC__ >= 4)) ||\
        (defined(__clang__) && __has_attribute(visibility))
        #define Py_IMPORTED_SYMBOL __attribute__ ((visibility ("default")))
        #define Py_EXPORTED_SYMBOL __attribute__ ((visibility ("default")))
        #define Py_LOCAL_SYMBOL  __attribute__ ((visibility ("hidden")))
    #else
        #define Py_IMPORTED_SYMBOL
        #define Py_EXPORTED_SYMBOL
        #define Py_LOCAL_SYMBOL
    #endif
#endif
```
Do you mean we better drop all the `PyAPI_FUNC` macro in `utils/script-python.c`?

**Comment by namhyung** [comment]
Yes, they are only required for the python code itself.

**Comment by kangtegong** [comment]
I don't think the macro really matter either.
PyAPI_FUNC is set only for python script within the file, 
and It compiles well without any issue when disabling it.

**Comment by namhyung** [comment]
Please send the PR.
