### ISSUE TITLE
Can Uftrace be used to trace multiple processes?

### ISSUE THREAD

**Issue by misang3** [namhyung/uftrace#1289]
In the docs, I see one of the limitations of Uftrace is that it can't be used for system wide tracing. Does this mean it wouldn't work if multiple uftrace instances are executed even with different output directory?

**Comment by honggyukim** [comment]
Hi @misang3, there is no problem running multiple uftrace instances if they do not write the tracing data in the same directory.

The uftrace do not support system wide tracing because it only follows the target process and its children processes and threads.

**Comment by misang3** [comment]
Thanks so much for your prompt reply. Appreciate the work you've done in building this!

**Comment by namhyung** [comment]
You can use `-f time` option to display timestamp in the uftrace replay output.  The default fields are 'duration,tid'.

```
$ uftrace replay -f help
uftrace: Unknown field name 'help'
uftrace:   Possible fields are: duration tid addr time delta elapsed task module

$ uftrace replay -f time
#     TIMESTAMP       FUNCTION
   153400.394046868 | main() {
   153400.394047391 |   a() {
   153400.394047653 |     b() {
   153400.394047755 |       c() {
   153400.394047976 |         getpid();
   153400.394050177 |       } /* c */
   153400.394050296 |     } /* b */
   153400.394050367 |   } /* a */
   153400.394050437 | } /* main */
```

**Comment by honggyukim** [comment]
If you want to see the timestamp along with the existing fields, then you can use `-f +time`. The `+` means add the field with the default fields.
```
$ uftrace replay -f +time
# DURATION     TID        TIMESTAMP       FUNCTION
            [3722683]  4629685.943149107 | main() {
            [3722683]  4629685.943149273 |   a() {
            [3722683]  4629685.943149315 |     b() {
            [3722683]  4629685.943149398 |       c() {
   0.291 us [3722683]  4629685.943149482 |         getpid();
   1.084 us [3722683]  4629685.943150482 |       } /* c */
   1.250 us [3722683]  4629685.943150565 |     } /* b */
   1.375 us [3722683]  4629685.943150648 |   } /* a */
   1.583 us [3722683]  4629685.943150690 | } /* main */
```
You can get more info at https://github.com/namhyung/uftrace/blob/master/doc/uftrace-replay.md#fields.

**Comment by misang3** [comment]
Appreciate the help!
