### ISSUE TITLE
Tracing dynamic function pointers

### ISSUE THREAD

**Issue by misang3** [namhyung/uftrace#1294]
So I have a use case where the binary I'm tracing depends on a shared object library that exposes an interface based on dynamic function pointers. Lets say my app is foo and the library is bar.
```c
// bar.h
typedef int (*Init)();

struct barInterface{
    Init pInit;
};

barInterface* get_bar_interface(void);
```
```c
// bar.c
static int internal_init(void) {

}

const barInterface bar_interface = {.pInit = internal_init};

barInterface get_bar_interface(void) {
    return &bar_interface;
}
```
```c
// foo.c
int main () {

    barInterface = get_bar_interface();
    barInterface->pInit();

    // more stuff ...

    return 0;
}
```

Question:
Will Uftrace be able to record the internal_init function which is defined as static in bar?

In my test, I'm seeing this sort of error:
```
uftrace/arch/arm/mcount-support.c:245:mcount_arch_parent_location
ERROR: cannot find symbol for b3f24c6b
```
I'm suspecting the missing symbol has to do with the handling of function pointer which ultimately  points to a static function. If this is true is there a work-around for something like this?

Appreciate the help!

**Comment by honggyukim** [comment]
Hi @misang3,

> Will Uftrace be able to record the internal_init function which is defined as static in bar?

Yes, it's possible.

> I'm suspecting the missing symbol has to do with the handling of function pointer which ultimately points to a static function.

Did you strip the library? Otherwise, I think the symbol can be found. If not, it might be a problem in uftrace.

Could you specifically write the steps you followed including the build command? You can also show us more detail info with running `-vvv` option for verbose message.

**Comment by namhyung** [comment]
Hello, can you reproduce it on x86_64?  The arm (32-bit) support might be somewhat outdated, so I'm not sure if the problem is in the symbol handling logic or just in the arch-specific code.  In addition, did you use the latest version of the software?

**Comment by misang3** [comment]
Hi guys,
So I've been able to sort of resolve this. It had to do with the library being stripped like @honggyukim intuited. However now I'm not seeing the auto-args working for the functions in that library. Any ideas on how i can debug this? Is there any doc on how the args are captured?

Thanks!

**Comment by namhyung** [comment]
The auto-args works in two ways.  At first, it understands a list of well known functions like C standard library functions and other Linux system functions.  You can see them in [misc/prototypes.h](../blob/master/misc/prototypes.h).

The other way is to use DWARF debug info from your ELF files.  So you cannot use a stripped binary (and/or library) for this.

You can find more details in [wiki/Arguments](../wiki/Arguments).

**Comment by misang3** [comment]
Thanks! I've been able to resolve this. Appreciate the help!
