### ISSUE TITLE
detect libexecinfo on musl platforms

### ISSUE THREAD

**Issue by cz172638** [namhyung/uftrace#1298]
on musl you are getting following errors:
undefined reference to `backtrace'
undefined reference to `backtrace_symbols'

```./configure --prefix=/usr --ldflags="-lexecinfo"``` is workaround.

**Comment by cz172638** [comment]
on alpine 3.14 i'm getting segmentation fault with ```make unittest``` and with ```make runtest``` 2300 build failures:
```
runtime test stats
====================
total  2600  Tests executed (success: 1.85%)
  OK:    48  Test succeeded
  OK:     0  Test succeeded (with some fixup)
  NG:     2  Different test result
  NZ:    10  Non-zero return value
  SG:     0  Abnormal exit by signal
  TM:    50  Test ran too long
  BI:  2300  Build failed
  LA:     0  Unsupported Language
  SK:   190  Skipped
```

**Comment by honggyukim** [comment]
Hi @cz172638, musl seems to be different from glibc. Can you test this change?
```diff
diff --git a/utils/utils.c b/utils/utils.c
index 31726794..6e502eb3 100644
--- a/utils/utils.c
+++ b/utils/utils.c
@@ -888,6 +888,10 @@ char *absolute_dirname(const char *path, char *resolved_path)
        return resolved_path;
 }

+#if !__GLIBC__
+/* we support stacktrace only in glibc. */
+void stacktrace(void) {}
+#else
 void stacktrace(void)
 {
 #if !DEBUG_MODE
@@ -948,6 +952,7 @@ void stacktrace(void)
 #endif
        pr_out("\n");
 }
+#endif

 #ifdef UNIT_TEST
 TEST_CASE(utils_parse_cmdline)
```
I wanted to detect musl but it doesn't have a macro as written in https://wiki.musl-libc.org/faq.html so we can enable `stacktrace` only in glibc.

**Comment by honggyukim** [comment]
> on alpine 3.14 i'm getting segmentation fault with make unittest and with make runtest 2300 build failures:

I don't have Alpine Linux environment so can't test it. Do you know if the older version of uftrace worked fine? For example, `v0.10`, `0.9.4`, etc.

**Comment by namhyung** [comment]
I think we should check libunwind in the check-deps as well.

**Comment by honggyukim** [comment]
Do you mean to use libunwind by default and just disable stacktrace if not exists? That might be also good.

**Comment by cz172638** [comment]
> > on alpine 3.14 i'm getting segmentation fault with make unittest and with make runtest 2300 build failures:
> 
> I don't have Alpine Linux environment so can't test it. Do you know if the older version of uftrace worked fine? For example, `v0.10`, `0.9.4`, etc.

```docker run --rm -it alpine:3.14```

**Comment by cz172638** [comment]
> I think we should check libunwind in the check-deps as well.

google found that [libunwind should be solution as replacement for libexecinfo](https://github.com/JuliaLang/julia/issues/1901)

**Comment by honggyukim** [comment]
> on alpine 3.14 i'm getting segmentation fault with make unittest and with make runtest 2300 build failures:

@cz172638 Please have a look at the below comment.
https://github.com/namhyung/uftrace/issues/1238#issuecomment-897950539

alpine doesn't support `-pg` nor `-finstrument-functions` so the test cannot be done at all. I tested full dynamic tracing[1] in alpine, but it works fine.
```
/uftrace # gcc  tests/s-abc.c

/uftrace # uftrace -P. a.out
# DURATION     TID     FUNCTION
            [  1571] | main() {
            [  1571] |   a() {
            [  1571] |     b() {
            [  1571] |       c() {
   1.410 us [  1571] |         getpid();
   2.861 us [  1571] |       } /* c */
   3.348 us [  1571] |     } /* b */
   3.814 us [  1571] |   } /* a */
   4.836 us [  1571] | } /* main */
```
[1] https://github.com/namhyung/uftrace/blob/master/doc/uftrace-record.md#dynamic-tracing
