### ISSUE TITLE
compiler warning in alpine Linux build

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#1303]
We can reproduce the problem as follows.
```
$ docker run -v $PWD:/uftrace -w /uftrace --rm -it alpine:3.13

/uftrace # apk add build-base linux-headers git bash htop less libunwind-dev

/uftrace # ./configure && make
        ...
/uftrace/utils/debug.c: In function '__pr_err_s':
/uftrace/utils/debug.c:190:21: warning: format '%s' expects argument of type 'char *', but argument 3 has type 'int' [-Wformat=]
  190 |  fprintf(logfp, ": %s\n", strerror_r(saved_errno, buf, sizeof(buf)));
      |                    ~^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                     |     |
      |                     |     int
      |                     char *
      |                    %d
```
man page says.
```c
$ man strerror_r
        ...
       int strerror_r(int errnum, char *buf, size_t buflen);
                   /* XSI-compliant */

       char *strerror_r(int errnum, char *buf, size_t buflen);
                   /* GNU-specific */
        ...
```

**Comment by kangtegong** [comment]
I want to resolve this issue!

**Comment by kangtegong** [comment]
i think this warning comes from alpine linux, not from uftrace.

Althogh man page of strerror_r does says `strerror_r` has two return values depending on the system like below,

```
int strerror_r(int errnum, char *buf, size_t buflen);
                   /* XSI-compliant */

char *strerror_r(int errnum, char *buf, size_t buflen);
                   /* GNU-specific */
```

if i `apk add build-base`, and then see /usr/include/string.h,

```
#if defined(_POSIX_SOURCE) || defined(_POSIX_C_SOURCE) \
 || defined(_XOPEN_SOURCE) || defined(_GNU_SOURCE) \
 || defined(_BSD_SOURCE)
int strerror_r (int, char *, size_t);
```

https://stackoverflow.com/questions/42190156/compatibility-of-strerror-r-on-different-platform

**Comment by namhyung** [comment]
I think we can add a wrapper of the function like `uftrace_strerror()` and check the return value of the strerror_r().  If it's 0, then it's XSI version and the funciton succeeded.  We can return the buf then.  If it's XSI version and failed, the return value would be a positive integer less than 4096.  We might fill the buffer with a default message like "error: %d" and return.

So, if the return value is bigger than 4096 (after casted to long), we can assume it's a GNU version and just use the return value.

**Comment by kangtegong** [comment]
I understood. I'll send the patch ASAP :)
