### ISSUE TITLE
sub-command specific help

### ISSUE THREAD

**Issue by akshit-sharma** [namhyung/uftrace#1316]
It will be useful to have the help specific to use case.

Existing Behavior:
``` uftrace --help ``` and ``` uftrace replay --help ``` gives the same help prompt.

New Behavior:
``` uftrace --help ``` can give the help for entire application.
``` uftrace replay --help ``` can give the  help for uftrace replay only.

Reason:
1. This will help narrow down the options available for subprograms (uftrace reply) as compared to uftrace.
2. Removes unnecessary options from help section. It will avoid showing the options which are not compatible with the subprogram.
3. User can see all the necessary options. Without this, the only way for user to know which configuration is used by going through [wiki\Tutorial](https://github.com/namhyung/uftrace/wiki/Tutorial) but it may also not have all valid configurations. Example: -F helps to focus on particular function. If user is profiling a specific function, with record and report, can he/she use it with both record and report or only with record or only with report. This will also help user to look at help section as oppose to seeing example command line on internet.

Motivation example:
``` git --help ``` v/s ``` git pull --help ```

**Comment by namhyung** [comment]
Thanks for raising this issue.  I totally agree with you.

**Comment by honggyukim** [comment]
We can redirect subcommand help to man pages just like `git` and `perf` does.

**Comment by kangtegong** [comment]
I think I can solve this one, if @namhyung and @honggyukim's ok :)

**Comment by RndelQndel** [comment]
Is it valid Issue?
I made look like this.
![image](https://github.com/namhyung/uftrace/assets/44370237/127b89e3-9d89-45fd-8559-44bb8fab0433)

**Comment by kangtegong** [comment]
hi @RndelQndel, I guess it'll be better if it prints
available options (and explanation) for specific command.

For example,

```
$ uftrace replay --help
 /* prints options for replay ... */
 /* prints options for replay ... */
 /* prints options for replay ... */ 

$ uftrace recv --help
 /* prints options for recv ... */
 /* prints options for recv ... */
 /* prints options for recv ... */ 
```

I once worked on this issue but I lost the work for some reason.🥲
If you want to do this work, you can solve it. If you don't want to, I'll wrap this up.

**Comment by honggyukim** [comment]
Hi @ParkSeungHyeok,

It's good to have subprogram specific help but I think it will require many changes so I cannot recommend you to work on this especially as a new contributor.

If you want to continue to work on this, then try to understand the option system in `perf` and `git` and investigate how they implemented it before trying to jump on this work.

> i made it print the option part of each command description in doc folder.

The way to print the help message is different from man pages so I think it's not a good idea to bring the description from the man pages.

**Comment by ParkSeungHyeok** [comment]
thank you for your comment.
i try to study the option system in perf and git

**Comment by honggyukim** [comment]
I see that `perf record --help` simply redirects to open `man perf record`. The `git clone --help` works the same way. We can think about opening uftrace sub-command man page instead of creating another message.

**Comment by ParkSeungHyeok** [comment]
I'm not sure that i understood exactly
but i found how to redirect in perf and git like below 
perf : https://github.com/torvalds/linux/blob/6b4aa469f04999c3f244515fa7491b4d093c5167/tools/perf/builtin-help.c#L176
git : https://github.com/git/git/blob/master/builtin/help.c#L306

so using execlp() function, i tried to implemented
![uftrace command --help](https://github.com/user-attachments/assets/0eeec20e-382f-4fc1-bd73-8c817d7603c8)


is it okay?

**Comment by honggyukim** [comment]
I think it looks good. You can submit a PR for that.
