### ISSUE TITLE
Add the word „be“ in two sentences of the documentation

### ISSUE THREAD

**Issue by elfring** [namhyung/uftrace#1322]
The wording „will not shown“ is used at two places.
* https://github.com/namhyung/uftrace/blob/a663f491e4be2ccf6c0c3f4563226b0ba035d101/doc/uftrace-record.md#triggers
* https://github.com/namhyung/uftrace/blob/a663f491e4be2ccf6c0c3f4563226b0ba035d101/doc/uftrace-live.md#triggers

I suggest to use the wording „will not be shown“ in these sentences.

**Comment by namhyung** [comment]
It'd be nice if you could send a PR directly.  Or do you want others to do it for you?

**Comment by kangtegong** [comment]
Just fixed this issue, assuming @elfring want others to solve this issue.

And @elfring, if you were working on this issue, please let me know!
