### ISSUE TITLE
Socket connect failed

### ISSUE THREAD

**Issue by JW1031** [namhyung/uftrace#135]
While testing Uftrace with "t151_recv_runcmd.py", I found error.

![image](https://user-images.githubusercontent.com/18061633/29646696-f7ff2b24-88bf-11e7-854d-b8e79ae94c36.png)

 This error is intermittent which occurs 2 of 10.

It seems that the commit a7c98163 is related to this problem.
-----------Commit Content----------------
Author: Namhyung Kim <namhyung@gmail.com>
Date:   Mon Aug 31 16:36:29 2015 +0900

    record: Prepare to support sending data on socket
    
    Signed-off-by: Namhyung Kim <namhyung@gmail.com>

**Comment by namhyung** [comment]
Thanks for the report.  It's a test for `uftrace recv` running a given command when it receives a data from a network socket.  The "connection refused" error usually occurs there's no process listening to the destination port.  I guess there's a race between uftrace recv and uftrace record which were fork'ed in the Python's subprocess module.. 

Could you please test that adding a small sleep before running the record command (something like below) makes any difference?

```
diff --git a/tests/t151_recv_runcmd.py b/tests/t151_recv_runcmd.py
index e7850ac..ca6f352 100644
--- a/tests/t151_recv_runcmd.py
+++ b/tests/t151_recv_runcmd.py
@@ -30,6 +30,8 @@ class TestCase(TestBase):
         recv_cmd = TestBase.ftrace.split() + ['recv', '-d', TDIR, '--run-cmd', TestBase.ftrace + ' replay']
         self.recv_p = sp.Popen(recv_cmd, stdout=self.file_p, stderr=self.file_p)
 
+        import time
+        time.sleep(0.001)   # 1 msec
         record_cmd = '%s record -H %s %s' % (TestBase.ftrace, 'localhost', 't-' + self.name)
         sp.call(record_cmd.split())
         return TestBase.TEST_SUCCESS
```

**Comment by namhyung** [comment]
I'm closing this since you didn't give a feedback for a while.  If you could test the above or had something to say, please reopen.  Thanks.
