### ISSUE TITLE
Runtest Errors!

### ISSUE THREAD

**Issue by choi-jaewon** [namhyung/uftrace#137]
<img width="678" alt="2017-08-24 3 13 39" src="https://user-images.githubusercontent.com/31034469/29652447-6caf0640-88e0-11e7-9bcc-f39fe6d17c9a.png">

This problem is intermittent that occurs rarely when i test `sudo ./runtest.py kernel` on uftrace v0.6.
Could you tell me what problem is?

<img width="613" alt="2017-08-24 4 21 22" src="https://user-images.githubusercontent.com/31034469/29654883-f5d4755a-88e9-11e7-9c17-c43e25ded1ff.png">

And while testing `sudo ./runtest.py kernel`, Only 149_event_kernel2 has NGs. There are version informations of Linux and Ubuntu. Could you inform me what I did wrong ?

**Comment by namhyung** [comment]
Ubuntu 17.04 has an old version of uftrace that has some bugs.  If you have a source code from github, please test it with current master and tell me what still fails.

**Comment by namhyung** [comment]
I'm closing this since you don't give a feedback.  If you still see the same issue with the master, please reopen.
