### ISSUE TITLE
source location filter

### ISSUE THREAD

**Issue by ekyooo** [namhyung/uftrace#1378]
This is issue to discuss the details of the request below.

> (source) location filter 

listed at https://github.com/namhyung/uftrace/wiki/TODO#9-filter-improvement

For now, I've only selected the available options for testing. 
-Y option is to set filter to trace selected source file.
-y option is to set filter not to trace selected source file.

Before:
--srcline option is used to show source location to you.

```
$ uftrace replay --srcline
# DURATION     TID     FUNCTION [SOURCE]
            [ 11746] | main() { /* /home/soft/uftrace/tests/s-libmain.c:16 */
            [ 11746] |   foo() { /* /home/soft/uftrace/tests/s-libmain.c:11 */
            [ 11746] |     lib_a() {
            [ 11746] |       lib_a() { /* /home/soft/uftrace/tests/s-lib.c:10 */
            [ 11746] |         lib_a() { /* /home/soft/uftrace/tests/s-lib.c:10 */
            [ 11746] |           lib_b() { /* /home/soft/uftrace/tests/s-lib.c:15 */
            [ 11746] |             lib_b() { /* /home/soft/uftrace/tests/s-lib.c:15 */
            [ 11746] |               lib_c() { /* /home/soft/uftrace/tests/s-lib.c:20 */
   1.963 us [ 11746] |                 lib_c(); /* /home/soft/uftrace/tests/s-lib.c:20 */
   3.590 us [ 11746] |               } /* lib_c at /home/soft/uftrace/tests/s-lib.c:20 */
   4.091 us [ 11746] |             } /* lib_b at /home/soft/uftrace/tests/s-lib.c:15 */
   4.584 us [ 11746] |           } /* lib_b at /home/soft/uftrace/tests/s-lib.c:15 */
```

After:

set filter to trace requested source file.
```
$ uftrace replay --srcline -Y /home/soft/uftrace/tests/s-libmain.c
# DURATION     TID     FUNCTION [SOURCE]
            [ 29804] | main() { /* /home/soft/uftrace/tests/s-libmain.c:16 */
            [ 29804] |   foo() { /* /home/soft/uftrace/tests/s-libmain.c:11 */
```

set filter not to trace requested source file.
```
$ uftrace replay --srcline -y /home/soft/uftrace/tests/s-libmain.c
# DURATION     TID     FUNCTION [SOURCE]
            [ 11746] | lib_a() {
            [ 11746] |   lib_a() { /* /home/soft/uftrace/tests/s-lib.c:10 */
            [ 11746] |     lib_a() { /* /home/soft/uftrace/tests/s-lib.c:10 */
            [ 11746] |       lib_b() { /* /home/soft/uftrace/tests/s-lib.c:15 */
            [ 11746] |         lib_b() { /* /home/soft/uftrace/tests/s-lib.c:15 */
            [ 11746] |           lib_c() { /* /home/soft/uftrace/tests/s-lib.c:20 */
   1.963 us [ 11746] |             lib_c(); /* /home/soft/uftrace/tests/s-lib.c:20 */
   3.590 us [ 11746] |           } /* lib_c at /home/soft/uftrace/tests/s-lib.c:20 */
   4.091 us [ 11746] |         } /* lib_b at /home/soft/uftrace/tests/s-lib.c:15 */
   4.584 us [ 11746] |       } /* lib_b at /home/soft/uftrace/tests/s-lib.c:15 */
```

set filter to trace requested source file with regex.
```
$ uftrace replay -Y uftrace/tests/s-libmain.c$
# DURATION     TID     FUNCTION
            [ 11746] | main() {
            [ 11746] |   foo() {
```

set filter not to trace requested source file with regex.
```
$ uftrace replay -y uftrace/tests/s-libmain.c$
# DURATION     TID     FUNCTION
            [ 11746] | lib_a() {
            [ 11746] |   lib_a() {
            [ 11746] |     lib_a() {
            [ 11746] |       lib_b() {
            [ 11746] |         lib_b() {
            [ 11746] |           lib_c() {
   1.963 us [ 11746] |             lib_c();
   3.590 us [ 11746] |           } /* lib_c */
   4.091 us [ 11746] |         } /* lib_b */
   4.584 us [ 11746] |       } /* lib_b */
```

Could you share your thoughts on the above results?
Are there any recommended option names?

**Comment by honggyukim** [comment]
Thanks for opening this issue. I think it could be better to use existing option for source location filter. We can currently apply filters with `@` mark for trigger actions as follows.
```
TRIGGERS
       The uftrace tool supports triggering actions on selected function calls (with or without filters) and/or signals.  Currently supported triggers are listed below.  The BNF for trigger specification is as follows:

              <trigger>    :=  <symbol> "@" <actions>
              <actions>    :=  <action>  | <action> "," <actions>
              <action>     :=  "depth="<num> | "trace" | "trace_on" | "trace_off" |
                               "time="<time_spec> | "read="<read_spec> | "finish" |
                               "filter" | "notrace" | "recover"
              <time_spec>  :=  <num> [ <time_unit> ]
              <time_unit>  :=  "ns" | "nsec" | "us" | "usec" | "ms" | "msec" | "s" | "sec" | "m" | "min"
              <read_spec>  :=  "proc/statm" | "page-fault" | "pmu-cycle" | "pmu-cache" | "pmu-branch"
```
I think we can add another `<action>` "src="<source_spec>". For example, your example can be used like this way.
```
$ uftrace replay --srcline -F .@src=/home/soft/uftrace/tests/s-libmain.c
# DURATION     TID     FUNCTION [SOURCE]
            [ 29804] | main() { /* /home/soft/uftrace/tests/s-libmain.c:16 */
            [ 29804] |   foo() { /* /home/soft/uftrace/tests/s-libmain.c:11 */
```
`-F .@src=/home/soft/uftrace/tests/s-libmain.c` means to apply filter to every function `.` from the given source location. I think the `-F` option is to show the specified function and its children function so the other functions below from `/home/soft/uftrace/tests/s-lib.c` should be shown together.

We plan to use `-P` option not only for dynamic tracing but also to apply filter without its children. But it's a future plan.

Likewise, we can hide functions from some specific source location as follows.
```
$ uftrace replay -H .@/home/soft/uftrace/tests/s-libmain.c
```
Then it should hide all the functions from `/home/soft/uftrace/tests/s-libmain.c` during replay. We can use this filter to other `-C` and `-N` option as well.

@namhyung Could you please let us know how you think?

**Comment by honggyukim** [comment]
I also think we can use regex to source location string as well. For example, this should work to the source `s-libmain.c`, but it could be matched with any directory paths.
```
$ uftrace replay -H .@.*/s-libmain.c
```

**Comment by namhyung** [comment]
@ekyooo Thanks for bringing up this issue.  Basically I think it'd be better matching only with a basename unless there's a slash in the path.

About the @honggyukim suggestion, I feel like it's a different case.  The location filter is not an action in the trigger.  It's rather a selector - we select filter/trigger using function name normally, but with this it can be a source location.  Maybe we can add some actions like `hide` or `notrace` there.

For option names, I think we can use an upper case letter for consistency.  How about `-O` (from "location")?

```
# to include functions in the main.cpp
$ uftrace -O main.cpp

# to exclude function in the string header
$ uftrace replay -O string.h@hide
```

**Comment by ekyooo** [comment]
@honggyukim, @namhyung 
Thank you for your comments.

I have additional questions about the exclusion case you suggested.
> to exclude function in the string header
> $ uftrace replay -O string.h@hide


The bash shell treats "$@" in the argument string as a special character as shown below.
```
$ echo hello$@1
hello1
$ echo "hello$@1"
hello1
```
'@$' can be preserved with escape character and single quotes.
```
$ echo hello$\@1
hello$@1
$ echo hello\$@1
hello$@1
$ echo 'hello$@1'
hello$@1
```

So @hide with the regex '$' requires escape character or single quotes.
```
$ uftrace replay --srcline -O tests/s-libmain.c$\@hide
```
or
```
$ uftrace replay --srcline -O 'tests/s-libmain.c$@hide'
```

Do you agree with this or do you have any other opinions?
Thank you.

**Comment by honggyukim** [comment]
> About the @honggyukim suggestion, I feel like it's a different case. The location filter is not an action in the trigger. It's rather a selector

@namhyung I thought about it maybe because we use `@` to specify module name, but I'm fine with your approach.

> The bash shell treats "$@" in the argument string as a special character as shown below.

@ekyooo I think you don't have to worry about `@`. We already use `@` without quote but it works fine as follows.
```
$ gcc -pg tests/s-abc.c -o t-abc

$ uftrace -T b@hide --no-libcall t-abc
# DURATION     TID     FUNCTION
            [ 25338] | main() {
            [ 25338] |   a() {
   0.807 us [ 25338] |     c();
   2.589 us [ 25338] |   } /* a */
   3.524 us [ 25338] | } /* main */
```
But we can't directly use `$` so we need `\` or quote it as follows.
```
$ uftrace -T b$@hide --no-libcall t-abc
Usage: failed to set filter or trigger: bhide
# DURATION     TID     FUNCTION
            [ 25694] | main() {
            [ 25694] |   a() {
            [ 25694] |     b() {
   0.864 us [ 25694] |       c();
   2.193 us [ 25694] |     } /* b */
   2.718 us [ 25694] |   } /* a */
   3.496 us [ 25694] | } /* main */

$ uftrace -T b\$@hide --no-libcall t-abc
# DURATION     TID     FUNCTION
            [ 25712] | main() {
            [ 25712] |   a() {
   0.775 us [ 25712] |     c();
   2.520 us [ 25712] |   } /* a */
   3.433 us [ 25712] | } /* main */

$ uftrace -T 'b$'@hide --no-libcall t-abc
# DURATION     TID     FUNCTION
            [ 25737] | main() {
            [ 25737] |   a() {
   1.213 us [ 25737] |     c();
   3.009 us [ 25737] |   } /* a */
   3.857 us [ 25737] | } /* main */
```

**Comment by ekyooo** [comment]
@honggyukim 
Thank you for your reply.

@namhyung 
I have a question about your comments.
> Basically I think it'd be better matching only with a basename unless there's a slash in the path.

For now it require '$' in argument to trace 's-libmain.c' as below.
```
$ ./uftrace replay --srcline -O s-libmain.c$
# DURATION     TID     FUNCTION [SOURCE]
            [ 29804] | main() { /* /home/soft/uftrace/tests/s-libmain.c:16 */
            [ 29804] |   foo() { /* /home/soft/uftrace/tests/s-libmain.c:11 */
```

Are you saying it's better to get the same result without the '$' as shown below?
```
$ ./uftrace replay --srcline -O s-libmain.c
# DURATION     TID     FUNCTION [SOURCE]
            [ 29804] | main() { /* /home/eslee/soft/uftrace/tests/s-libmain.c:16 */
            [ 29804] |   foo() { /* /home/eslee/soft/uftrace/tests/s-libmain.c:11 */
```

Thank you.

**Comment by honggyukim** [comment]
> For now it require '$' in argument to trace 's-libmain.c' as below.

It can be used as `-O .*s-libmain.c`. The filter match has two different modes. One for exact match and the other is regex match. Please see the following locations.
- https://github.com/namhyung/uftrace/blob/v0.11/utils/filter.c#L368-L369
  - `#define REGEX_CHARS  ".?*+-^$|()[]{}"`
- https://github.com/namhyung/uftrace/blob/v0.11/utils/filter.c#L240
  - `exact_match` flag

If the function name doesn't have characters from `REGEX_CHARS` then it will be exact match, otherwise it will use regex match.

**Comment by ekyooo** [comment]
@honggyukim 
I'm sorry for the confusion. 
I know two different mode and my '$' case was an example of regex mode. 
But I thought @namhyung means if there's no slash in the path, it'd be better apply exact match with just basename though there's no characters from REGEX_CHARS in the argument.
So I checked it.

> Basically I think it'd be better matching only with a basename unless there's a slash in the path.

Thank you.

**Comment by namhyung** [comment]
@ekyooo thanks a lot!  I'll take a look later.

**Comment by ekyooo** [comment]
@namhyung I'll send you a pull request after I check and fix it once more. 
I hope you take a look after it.
Thank you.
