### ISSUE TITLE
Support recording with pre-saved symbols

### ISSUE THREAD

**Issue by namhyung** [namhyung/uftrace#1406]
We have `--with-syms` option for `uftrace replay` to symbolize data using external symbol files.  Extend it to `uftrace record` so we can use stripped binary for recording.  Symbols and debug info should be recorded separately before the strip.  And filenames should not be changed.

Example:
```
$ gcc -o myprog -g -pg myprog.c
$ uftrace record -d myprog-sym.data  myprog

$ strip myprog
$ uftrace myprog
# ... does not have symbols

$ uftrace record --with-syms myprog-sym.data  myprog
$ uftrace replay
# ... it has symbols!!
```

It also supports filtering and debug info.  During the record, libmcount will read symbols and debug info from the files in the symbol directory.  After that it copies the files into the current data directory so that uftrace can read the data as if it has symbols from the beginning.

I've pushed the code to [review/with-syms-v3](../compare/review/with-syms-v3).

**Comment by honggyukim** [comment]
I didn't carefully look into the changes in details, but I tested and found it works as expected. Thanks for the work!
