### ISSUE TITLE
How to disable all tracing in a particular directory or to enable tracing only in a particular directory

### ISSUE THREAD

**Issue by thisisamardeep** [namhyung/uftrace#1415]

**Comment by namhyung** [comment]
I guess you are talking about filtering based on the source code lacation.  Actually #1395 is being worked on so hopefully you can get it in the next version.

**Comment by thisisamardeep** [comment]
yes 
thanks it reallly helps when you have 20 gb of call trace like cpython.

**Comment by namhyung** [comment]
From uftrace v0.13 `-L`/`--loc-filter` is supported.
