### ISSUE TITLE
possible feature proposals for future work

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#142]
Hi @namhyung and @Taeung,

I've been thinking about some possible future works that I want to propose, we can think about it together. It's currently a draft and will keep updating it.

## 1. nested library tracing
- We can see meaningful enough library function tracing record.
- We don't miss some important library calls.
- We can remove the restriction of recompiling with `-pg` or `-finstrument-functions`.
- (almost done by @namhyung )

## 2. automatic argument / retval display for known libc functions
- We can do this for some known functions such as `malloc` and `free`.
- Some functions that use `char*` string such as `strcpy` and `execv` can show eye-catch string output.
- We can support some functions at the beginning and incrementally add one by one.
- As a first step, we can simply provide an option file that contains a list of `-A` and `-R` options for specific functions.
- We can also provide library's return value checker. (such as if `malloc` returns NULL in some cases)

## 3. (python) script enhancement
- arguments / retval support for python
- option handling in python script (in order to make a given script self-contained)
- drawing various charts using `matplotlib`.
\- drawing malloc and free to see memory allocation graph
\- drawing RSS charts by using read trigger
\- many others...
- event handing in (python) script
- script filter (e.g. <symbol>@script=<file> ) or in-script filter
- collecting useful scripts
\- https://github.com/brendangregg/perf-tools

## 4. call graph diff
- We can record twice and compare the summary using `report --diff` as of now.
- We can also compare the call graph diff to identify the specific difference in details.
- We may provide another GUI output for showing the diff efficiently.

## 5. builtin chrome trace viewer
- Currently, showing chrome trace output requires many steps.
\- `uftrace record` -> `uftrace dump --chrome` -> goto `chrome://tracing` -> press `Load` to open file
- I would like to make it as the following steps
\- `uftrace record` -> `uftrace chrome` -> it shows a URL link -> goto the link in any other remote machine.
- It requires integrating chrome trace viewer inside uftrace repo.
- It also requires to write a simple node script to provide a web link.
- It's mainly to make it simple to use for general users.

**Comment by namhyung** [comment]
Thanks to write this up.  I'd like to add some more.

## 6. make filtering more convenient
* currently regex and glob matching is used in a mix
* support to select regex, glob or simple substring match based on user's chioce
* consolidate similar options so users don't need to type function name multiple times

## 7. return-time trigger
* current trigger action is called only at function entry
* reuse `-R` option to allow it called at function exit

## 8. DWARF debug info support
* it can be used to specify argument and return value automatically
* it provides source location info (file:line)
* it might be used as a new filter option - (e.g. filter all functions in this file)

## 9. user interface improvement
* current console based UI lacks user interaction
* maybe (ncurses-based) TUI can be added
* I have no idea about GUI (but welcome contribution!!!)

**Comment by namhyung** [comment]
For item 5, do you think using a (external) web server?

**Comment by Taeung** [comment]
Personally, I wanna try to work item 7 if possible.. 😃

**Comment by Taeung** [comment]
As you said before, in the a bit faraway future (?), we can try to trace running process using `ptrace` like gdb. And new dynamic tracing without `-pg -mfentry -mnop-mcount`, right ?
I think they are amazing supports !!

**Comment by Taeung** [comment]
I think it'd be nice, if we can handle the item 5 by only command lines.
I think we can write a html file from trace data(json file) and run `chrome` with the html file like `trace2html`.
For example,

```
taeung ~/workspace/uftrace-test 
:> uftrace dump --chrome
{"traceEvents":[
{"ts":15133947041.467,"ph":"B","pid":17699,"name":"__monstartup"},
{"ts":15133947043.215,"ph":"E","pid":17699,"name":"__monstartup"},
{"ts":15133947048.707,"ph":"B","pid":17699,"name":"__cxa_atexit"},
{"ts":15133947050.338,"ph":"E","pid":17699,"name":"__cxa_atexit"},
{"ts":15133947051.935,"ph":"B","pid":17699,"name":"main"},
{"ts":15133947052.332,"ph":"B","pid":17699,"name":"puts"},
{"ts":15133947076.562,"ph":"E","pid":17699,"name":"puts"},
{"ts":15133947077.608,"ph":"B","pid":17699,"name":"foo"},
{"ts":15133947078.058,"ph":"B","pid":17699,"name":"printf"},
{"ts":15133947086.116,"ph":"E","pid":17699,"name":"printf"},
{"ts":15133947086.958,"ph":"B","pid":17699,"name":"bar"},
{"ts":15133947087.270,"ph":"B","pid":17699,"name":"printf"},
{"ts":15133947091.167,"ph":"E","pid":17699,"name":"printf"},
{"ts":15133947091.777,"ph":"E","pid":17699,"name":"bar"},
{"ts":15133947092.277,"ph":"E","pid":17699,"name":"foo"},
{"ts":15133947092.579,"ph":"E","pid":17699,"name":"main"}
], "displayTimeUnit": "ns", "metadata": {
"command_line":"uftrace record hello ",
"recorded_time":"Thu Aug 31 09:05:22 2017"
} }

taeung ~/workspace/uftrace-test 
:> uftrace dump --chrome > ~/a.json
```
And then,
```
taeung ~/git/opensource/chromium/src/third_party/catapult/tracing/bin 
:> ./trace2html ~/a.json --output=a.html
a.html

taeung ~/git/opensource/chromium/src/third_party/catapult/tracing/bin 
:> /opt/google/chrome/chrome a.html 
Created new window in existing browser session.
[29727:29756:0904/122935.602682:ERROR:browser_gpu_channel_host_factory.cc(103)] Failed to launch GPU process.

taeung ~/git/opensource/chromium/src/third_party/catapult/tracing/bin 
:> file trace2html 
trace2html: Python script, ASCII text executable

taeung ~/git/opensource/chromium/src/third_party/catapult/tracing/bin 
:> cat trace2html 
#!/usr/bin/env python
# Copyright (c) 2014 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import sys
import os

if __name__ == '__main__':
  tracing_path = os.path.abspath(os.path.join(
    os.path.dirname(os.path.realpath(__file__)), '..'))
  sys.path.append(tracing_path)
  from tracing_build import trace2html
  sys.exit(trace2html.Main(sys.argv))

```
https://github.com/catapult-project/catapult
The above project has `trace2html`.
What do you think about using this external feature ?
or injecting this feature into uftrace ?

**Comment by namhyung** [comment]
@Taeung contributions are always welcome :)

**Comment by honggyukim** [comment]
> For item 5, do you think using a (external) web server?

Internally, we can write a node.js script to run a simple web server.

**Comment by honggyukim** [comment]
> I think it'd be nice, if we can handle the item 5 by only command lines.
I think we can write a html file from trace data(json file) and run chrome with the html file like trace2html.

Hi @Taeung , I didn't write a document of converting json file to html but I always used the same project `catapult`. Thanks anyway!

**Comment by Taeung** [comment]
```c
#include <stdio.h>

void main()
{
}
```

**Comment by Taeung** [comment]
@honggyukim  Ah, you are already using `catapult`.. ok !

**Comment by honggyukim** [comment]
## 10. handling demon programs
- We need to implement a way to trigger tracing on and off using signal or socket.
- I prefer implementing in socket so that it can be used in embedded system.
- It can be used with `recv` command.
- We can trace multiple processes with data file merge feature.

## 11. full dynamic tracing
- compiler support free tracing without recompilation.
- It requires to decode each instruction and emulate.

## 12. attaching to already running process
- dl-library linked or not?

## 13. more C++ support
- STL types support
- std::string (done!)
- std::vector, std::list, std::shared_ptr, std::unique_ptr, etc...

## 14. other language support
- Rust or Go ?
- Python - `$ python -m trace --trace --timing ./runtest.py 161` with python interpreter itself.
- JavaScript (need to modify engine itself)


## etc.
- color for each context
- help with pager
- more auto completion
- value filter

**Comment by honggyukim** [comment]
Hi @namhyung and @Taeung, it was really to to see you together. I think that we better move this summary to a new wiki page. What do you think? : )

**Comment by namhyung** [comment]
I'm ok with it.  We can add a TODO page and update it continuously.

**Comment by honggyukim** [comment]
@namhyung @Taeung I just create a TODO wiki page that are reordered by our priority as of now. Please modify and add whenever you want to change.

**Comment by Taeung** [comment]
Yep, Thank you !!

**Comment by honggyukim** [comment]
I think we can close this. Thanks for your comments!
