### ISSUE TITLE
add function size info to report field (graph, tui are optional)

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#1448]
The function size info is not runtime information but it delivers useful ideas how big the function is.

We can add the function size info to report and graph field.

**Comment by honggyukim** [comment]
@namhyung Please let me know if you don’t like the idea.

**Comment by namhyung** [comment]
I Like the idea!

**Comment by honggyukim** [comment]
The `uftrace_symbol` has `size` info so we can just print it in report and graph command output.
https://github.com/namhyung/uftrace/blob/79a7d940b484be95ded642f9c9a48925c2472281/utils/symbol.h#L50-L55

**Comment by fistki** [comment]
I will try this issue!

**Comment by fistki** [comment]
I add function size like this.
Values are just printing `size` of `uftrace_symbol`.

```
$ ~/func-size/uftrace report -d hello.data -f +func-size
  Total time   Self time       Calls   Func size  Function
  ==========  ==========  ==========  ==========  ====================
   48.661 us    0.320 us           1          45  _GLOBAL__sub_I_main
   48.341 us    1.433 us           1          92  __static_initialization_and_destruction_0
   46.797 us   46.797 us           1          16  std::ios_base::Init::Init
    7.755 us    0.211 us           1          46  main
    7.544 us    7.544 us           1          16  std::operator<<
    0.111 us    0.111 us           1          16  __cxa_atexit
```

Does it fit for purpose? @honggyukim

**Comment by honggyukim** [comment]
@fistki Yes, that's what I meant. Could you upload a PR?

**Comment by fistki** [comment]
> @fistki Yes, that's what I meant. Could you upload a PR?

i uploaded it #1495
