### ISSUE TITLE
make 'uftrace --version' show python version info

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#1464]
Currently, `uftrace --version` shows whether [python scripting](https://github.com/namhyung/uftrace/blob/v0.12/doc/uftrace-script.md#script-execution) is supported, but it doesn't inform whether python2.7 or python3 is supported.

We better distinguish the python version info by modifying the following code.
https://github.com/namhyung/uftrace/blob/v0.12/misc/version.sh#L37-L40

So the expected output of `uftrace --version` is
```
$ uftrace --version
uftrace v0.12 ( x86_64 dwarf python3 ... )
```
or
```
$ uftrace --version
uftrace v0.12 ( x86_64 dwarf python2.7 ... )
```

**Comment by ghojeong** [comment]
I want to try this issue!

**Comment by honggyukim** [comment]
@ghojeong Great. Please go ahead :)
