### ISSUE TITLE
Saving previous failed test result by renaming failed-tests.txt to failed-tests.txt.old

### ISSUE THREAD

**Issue by kangtegong** [namhyung/uftrace#1466]
Currently, uftrace produces failed-tests.txt after running runtest.py
which contians failed test results.

Problem is, failed-tests.txt can be overwritten when we run runtest.py again.
I think it's better to rename failed-tests.txt to failed-tests.txt.old when runtest.py is executed again
to see how results are different than the latest results.

Also, I think we can make a diff command out of it like the example below.

```
$ ./runtest.py --diff 
                         failed-tests.txt       failed-tests.txt.old
212 USER_TEST           : NG                    OK
```
[reference] https://github.com/namhyung/uftrace/wiki/Testing

**Comment by MichelleJin12** [comment]
I'll try this. Thanks!!
