### ISSUE TITLE
tutorial slide missing record command in task graph page

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#1472]
Our tutorial slide has a bug in https://uftrace.github.io/slide/#108.

It says
```
    $ uftrace --force /usr/bin/gcc hello.c
    $ uftrace graph --task
    ========== TASK GRAPH ==========
    # TOTAL TIME   SELF TIME     TID     TASK NAME
      159.854 ms    4.440 ms  [ 82723] : gcc
                                       :  |
       90.951 ms   90.951 ms  [ 82734] :  +----cc1
                                       :  |
       17.150 ms   17.150 ms  [ 82735] :  +----as
                                       :  |
       45.183 ms    6.076 ms  [ 82736] :  +----collect2
                                       :        |
       38.880 ms   38.880 ms  [ 82737] :        +----ld
```
But the first command has to be
```
    $ uftrace record --force /usr/bin/gcc hello.c
```
It needs to be fixed at https://github.com/namhyung/uftrace/blob/v0.12/doc/uftrace.html#L2055-L2084.

Please note that it won't be shown at https://uftrace.github.io/slide until the change is applied to https://github.com/uftrace/uftrace.github.io/blob/master/slide/uftrace.html.

**Comment by valdaarhun** [comment]
Hi. I have never contributed to uftrace before. I would like to tackle this issue.



> It needs to be fixed at https://github.com/namhyung/uftrace/blob/v0.12/doc/uftrace.html#L2055-L2084.

The same issue is also present in the [`master`](https://github.com/namhyung/uftrace/blob/master/doc/uftrace.html#L2055-L2084) branch. Should the change be made in both branches?

**Comment by honggyukim** [comment]
Hi @valdaarhun, changing only master branch is enough. Please go ahead and thanks!

**Comment by valdaarhun** [comment]
> Please note that it won't be shown at https://uftrace.github.io/slide until the change is applied to https://github.com/uftrace/uftrace.github.io/blob/master/slide/uftrace.html.

I have also opened a PR in the website's repo.
