### ISSUE TITLE
create a single root node for graphviz dump output

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#1499]
The current `--graphviz` output for `t-abc` is as follows.
```dot
$ uftrace record t-abc

$ uftrace dump --graphviz
      ...
digraph "t-abc" {
    "__monstartup" [xlabel = "1"]
    "__cxa_atexit" [xlabel = "1"]
    "main" [xlabel = "1"]
    "main" -> "a" [xlabel = "1"]
    "a" -> "b" [xlabel = "1"]
    "b" -> "c" [xlabel = "1"]
    "c" -> "getpid" [xlabel = "1"]
}
```
It has 3 root nodes in total - `__monstartup`, `__cxa_atexit`, and `main` and the output image is as follows.
<img width="452" alt="image" src="https://user-images.githubusercontent.com/19642328/181993170-7ad84281-9e67-43c3-9d52-3b06ff475ffe.png">

But rather than creating multiple root nodes, we better create a single root node with its `basename(exename)`. i.e. `t-abc` in this example. So the output can be rewritten as follows.
```dot
digraph G {
    "t-abc"
    "t-abc" -> "__monstartup" [xlabel = "1"]
    "t-abc" -> "__cxa_atexit" [xlabel = "1"]
    "t-abc" -> "main" [xlabel = "1"]
    "main" -> "a" [xlabel = "1"]
    "a" -> "b" [xlabel = "1"]
    "b" -> "c" [xlabel = "1"]
    "c" -> "getpid" [xlabel = "1"]
}
```
Then this new output image can be shown as follows.
<img width="442" alt="image" src="https://user-images.githubusercontent.com/19642328/181994441-335d1871-6f5b-4166-a268-9167c5540dcb.png">

Similarly, `uftrace graph` command also creates a fake root node `t-abc` as follows.
```
$ uftrace graph
# Function Call Graph for 't-abc' (session: 721637281f8729ec)
========== FUNCTION CALL GRAPH ==========
# TOTAL TIME   FUNCTION
    7.616 us : (1) t-abc
    1.656 us :  +-(1) __monstartup
             :  |
    1.032 us :  +-(1) __cxa_atexit
             :  |
    4.928 us :  +-(1) main
    4.413 us :    (1) a
    3.895 us :    (1) b
    3.236 us :    (1) c
    2.023 us :    (1) getpid
```

**Comment by honggyukim** [comment]
The name of the root node is the `basename(exename)` as follows.
https://github.com/namhyung/uftrace/blob/v0.12/cmds/graph.c#L218

**Comment by namhyung** [comment]
It also needs to check sessions since each session can run different programs (with `execve()` and others).

**Comment by honggyukim** [comment]
We should create fake roots for each session. In addition, we should think about generating multiple `.dot` outputs for each session if possible. But this might be out of the scope in this issue.
