### ISSUE TITLE
Make uftrace markdown docs to uftrace.github.io using Read The Docs

### ISSUE THREAD

**Issue by paranlee** [namhyung/uftrace#1518]
We plan to add the existing markdown documentation(`uftrace.wiki.git`, `uftrace.git/tree/master/doc`) to the `uftrace.github.io` homepage as read the docs. (Like the [Linux kernel documentation](https://docs.kernel.org/))

Resources for reference are as follows.

- Read the Docs's Markdown Tutorial Project
   - https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html#using-markdown-with-sphinx
    - https://github.com/readthedocs/tutorial-sphinx-markdown
    - https://youtu.be/qRSb299awB0?t=3381

When drawing diagrams, We try to use [mermaid](https://mermaid-js.github.io/mermaid/#/) supported by markdown as much as possible.

Markdowned mermaid source code interpreted like this.

```mermaid
stateDiagram-v2
    [*] --> Active

    state Active {
        [*] --> NumLockOff
        NumLockOff --> NumLockOn : EvNumLockPressed
        NumLockOn --> NumLockOff : EvNumLockPressed
        --
        [*] --> CapsLockOff
        CapsLockOff --> CapsLockOn : EvCapsLockPressed
        CapsLockOn --> CapsLockOff : EvCapsLockPressed
        --
        [*] --> ScrollLockOff
        ScrollLockOff --> ScrollLockOn : EvScrollLockPressed
        ScrollLockOn --> ScrollLockOff : EvScrollLockPressed
    }
```

**Comment by kangtegong** [comment]
Similar issue is on #1434. Why don't we discuss about this there?

**Comment by paranlee** [comment]
Mermaid Live Editor
- https://mermaid.live/edit
