### ISSUE TITLE
Wish: add columns for filename and linenumber

### ISSUE THREAD

**Issue by Tux** [namhyung/uftrace#1541]
This tool worked out of the box and almost showed everything I was looking for! Thank you!

`replay -f` currently supports `duration`, `tid`, `addr`, `time`, `delta`,  `elapsed`,  `task`  and  `module`.

I am running two versions of the same proces to find the diff in the call-flow for a very specific situation. The call flow is several thousand lines of output, so visual diff is not an option.

`uftrace report --diff=uftrace.data.old` does not show me the diff in call-flow (or I missed something. I saw timing changes, in which I am not interested right now). FWIW IMHO `uftrace report --diff` with no argument would be swell to default to `uftrace report --diff=uftrace.data.old`

I'd like to see two new columns available for `-f`: `file` and `line`.

`$ uftrace replay -f file,line`

Would be very welcome. I run a project with several 100 source files and having that navigation information present would help me a lot.

Hopes this wish makes sense.

**Comment by honggyukim** [comment]
Hi @Tux, thanks for your feedback. We have considered adding source location as a field, but it tends to be too long to fit into a field.

Instead, we have added an option `--srcline` to show filename and line number together as follows.
```
$ uftrace record --srcline t-abc

$ uftrace replay --srcline
# DURATION     TID     FUNCTION [SOURCE]
            [ 49526] | main() { /* tests/s-abc.c:26 */
            [ 49526] |   a() { /* tests/s-abc.c:11 */
            [ 49526] |     b() { /* tests/s-abc.c:16 */
            [ 49526] |       c() { /* tests/s-abc.c:21 */
   1.884 us [ 49526] |         getpid();
   6.944 us [ 49526] |       } /* c */
   7.425 us [ 49526] |     } /* b */
   7.801 us [ 49526] |   } /* a */
   8.605 us [ 49526] | } /* main */

$ uftrace report --srcline
  Total time   Self time       Calls  Function [Source]
  ==========  ==========  ==========  ====================
    8.605 us    0.804 us           1  main [tests/s-abc.c:26]
    7.801 us    0.376 us           1  a [tests/s-abc.c:11]
    7.425 us    0.481 us           1  b [tests/s-abc.c:16]
    6.944 us    5.060 us           1  c [tests/s-abc.c:21]
    1.884 us    1.884 us           1  getpid
```
Is this what you're looking for?

**Comment by Tux** [comment]
Thanks for taking my quest serious

I already use `-a` (and thus `--srcline`) which was what I missed in all alternatives. **really** useful indeed!

I don't care (at this point) if the field get overly long, I still would see it as a useful addition.
A suggestion might be to name the source file with a max of N trailing path segments, defaulting to e.g. 2, so `/foo/bar/test/try-1/some/sub/folder/send/bobo.c` would show as `send/bobo.c`

**Comment by Tux** [comment]
OK, one last remark:`1.884 us [ 49526] |         getpid();` does not show the line number, so if your code has 200 calls to `getpid ()` in that routine, it will be hard to find the correct one. (I admit `getpid ()` is not a good example. `printf ()` whould be a better example).

**Comment by honggyukim** [comment]
> EDIT: I now added --srcline explicitely, and yes, that is what I was looking for. I probably misread the "implies" in the docs reversely.

So you're fine with using `--srcline`, then I'm glad to hear that.

> one last remark:1.884 us [ 49526] | getpid(); does not show the line number

It's because `getpid` is not a userspace function call, but a library function call. It's captured through PLT so it doesn't provide the source line info inside glibc implementation.

**Comment by Tux** [comment]
I know, I mean the source line of the file it is called from

**Comment by honggyukim** [comment]
Do you mean the call site of `getpid`? I think it would also be useful but uftrace currently doesn't provide call site info yet.

**Comment by Tux** [comment]
Yes. The line where getpid was called. If not available, then it is no option. In that case, a column for it makes no sense.
Thanks again for thinking along. Closing.

**Comment by honggyukim** [comment]
Thanks for your feedback. Please let us know if you have other issues.
