### ISSUE TITLE
-Z option explanation is duplicated in record commands

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#1612]
The `-Z` option is used for dynamic tracing only in record command, but the recent change has made it available for non dynamic tracing. But the current `uftrace-record.md` has two different explanation for `-Z` option so we have to combine and refine the explanation.

**Comment by honggyukim** [comment]
@fistki Could you please have a look at it again?

**Comment by honggyukim** [comment]
In addition, `uftrace-live.md` doesn't have a proper explanation for your change.

**Comment by namhyung** [comment]
I think we can have it in the common options section and discard the dynamic tracing version because it's now a general option.  I'll also update the FILTERS section.

**Comment by namhyung** [comment]
I realized that the `-Z` option does not work with `trace` trigger as described.  Will drop that part for now.

**Comment by fistki** [comment]
@namhyung I just checked the latest commit. It looks so good. Thanks for help!!
