### ISSUE TITLE
symbol file format change - adding symbol size

### ISSUE THREAD

**Issue by namhyung** [namhyung/uftrace#1616]
With the `-Z`/`--size-filter`, it'd be nice if `replay` would work as same as `record` when it comes to the symbol size.  Currently it only saves the symbol addresses and symbol size can be determined from the difference between two adjacent symbols.  It's worked well so far, and we can simply use `/proc/kallsyms` for kernel function symbol table.  But compilers can add padding at then end of functions to align the start addresses.  In this case, `replay` will see larger function size than the real size.

We cannot simply change the symbol file format since it cannot support kernel symbols easily and more importantly, it won't work with the previous data files.  I think we should keep the backward compatibility but extend the format to have size from now on.  New code should understand both old format and new format.

# Old format
Each line consists of
* start address (64 bit hex)
* type (character)
* name
```
$ head uftrace.data/t-abc.sym 
# symbols: 18
# path name: /home/namhyung/tmp/t-abc
# build-id: 798e11e74b8281dde5fe8a119ee9323d71c986e5
000000000000037c d __abi_tag
000000000000039c ? __sym_end
0000000000001030 P getpid
0000000000001040 P __stack_chk_fail
0000000000001050 P __monstartup
0000000000001060 P __cxa_atexit
0000000000001070 P atoi
```
The `__sym_end`, `__dynsym_end` and `__func_end` are special symbols to set the proper symbol size and indicate the symbol type changes.

# New format
Each line consists of
* start address (64 bit hex)
* size (32 bit hex)
* type (character)
* name
```
$ head uftrace.data/t-abc.sym 
# symbols: 18
# path name: /home/namhyung/tmp/t-abc
# build-id: 798e11e74b8281dde5fe8a119ee9323d71c986e5
000000000000037c 00000020 d __abi_tag
0000000000001030 00000010 P getpid
0000000000001040 00000010 P __stack_chk_fail
0000000000001050 00000010 P __monstartup
0000000000001060 00000010 P __cxa_atexit
0000000000001070 00000010 P atoi
0000000000001090 00000022 T _start
```
The new format doesn't need the special symbols anymore.  A compatible parser should try the old format first.  If it detects the type character being a digit, it'd parse the new format.

**Comment by namhyung** [comment]
Uploaded: [review/symbol-format-v1](../compare/review/symbol-format-v1).

**Comment by namhyung** [comment]
Uploaded: [review/symbol-format-v2](https://github.com/namhyung/uftrace/compare/review/symbol-format-v2).

Changed:
 * add `SYM_SIZE` feature bit.

**Comment by honggyukim** [comment]
Thanks for the update. We also also need this to properly dump the data.
```diff
diff --git a/cmds/dump.c b/cmds/dump.c
index 7bb83e19..d7faaa85 100644
--- a/cmds/dump.c
+++ b/cmds/dump.c
@@ -536,7 +536,8 @@ static void dump_raw_header(struct uftrace_dump_ops *ops, struct uftrace_data *h
        struct uftrace_raw_dump *raw = container_of(ops, typeof(*raw), ops);
        const char *feat_str[] = { "PLTHOOK",    "TASK_SESSION", "KERNEL",     "ARGUMENT",
                                   "RETVAL",     "SYM_REL_ADDR", "MAX_STACK",  "EVENT",
-                                  "PERF_EVENT", "AUTO_ARGS",    "DEBUG_INFO", "ESTIMATE_RETURN" };
+                                  "PERF_EVENT", "AUTO_ARGS",    "DEBUG_INFO", "ESTIMATE_RETURN",
+                                  "SYM_SIZE" };
        const char *info_str[] = { "EXE_NAME",     "EXE_BUILD_ID", "EXIT_STATUS", "CMDLINE",
                                   "CPUINFO",      "MEMINFO",      "OSINFO",      "TASKINFO",
                                   "USAGEINFO",    "LOADINFO",     "ARG_SPEC",    "RECORD_DATE",
```
@fistki This is the work we mentioned at https://github.com/namhyung/uftrace/pull/1600#issuecomment-1368432976. You might be interested in this.

**Comment by namhyung** [comment]
You're right, will fix.

**Comment by fistki** [comment]
Thanks for mention. I can deal with this issue but It may take times.

**Comment by namhyung** [comment]
Pushed: [review/symbol-format-v3](https://github.com/namhyung/uftrace/compare/review/symbol-format-v3)

@fistki It should not require any changes.
