### ISSUE TITLE
Function filter support for Python tracing

### ISSUE THREAD

**Issue by namhyung** [namhyung/uftrace#1641]
The function filters like `-F` and `-N` don't work for python functions because it cannot know the function names and addresses in advance.  So it should implement a separate filtering logic to match function names directly.  Also it needs to maintain the filter state so that it can decide whether it would drop the current function or not.

One thing it should consider is multi-thread and/or multi-process support.

**Comment by namhyung** [comment]
Pushed [review/python-filter-v1](https://github.com/namhyung/uftrace/compare/review/python-filter-v1).
 * implement `-F` and `-N` filters

```
$ uftrace -F b abc.py
501469
# DURATION     TID     FUNCTION
            [501469] | b() {
            [501469] |   c() {
   2.676 us [501469] |     posix.getpid();
   6.565 us [501469] |   } /* c */
   9.533 us [501469] | } /* b */

$ uftrace -N b abc.py
501879
# DURATION     TID     FUNCTION
            [501879] | __main__.<module>() {
  10.192 us [501879] |   a();
  14.341 us [501879] |   builtins.print();
  31.564 us [501879] | } /* __main__.<module> */

$ uftrace -F a -N c abc.py
501922
# DURATION     TID     FUNCTION
            [501922] | a() {
   8.128 us [501922] |   b();
  10.923 us [501922] | } /* a */
```

**Comment by honggyukim** [comment]
Thanks. I haven't looked into the details, but my test result looks good with some examples.
