### ISSUE TITLE
warning: ‘forward_option’ defined but not used

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#1673]
Hi @clementguidi, I couldn't look into your changes but I get the following warning.
```
$ make
  CC       cmds/live.o
/home/honggyu/work/uftrace/cmds/live.c:250:12: warning: ‘forward_option’ defined but not used [-Wunused-function]
  250 | static int forward_option(int fd, int capabilities, int opt, void *value, size_t value_size)
      |            ^~~~~~~~~~~~~~
```
It looks `forward_option` is not used anywhere. Can this be removed?
https://github.com/namhyung/uftrace/blob/7bc633ee3afa2511ef40cef1b2c39122eaf19566/cmds/live.c#L241-L319

**Comment by namhyung** [comment]
It'd be used by the upcoming agent changes like in #1645.  But yeah, we should remove the warning in the meantime.

Something like this
```diff
diff --git a/cmds/live.c b/cmds/live.c
index ac16569d..80e33ead 100644
--- a/cmds/live.c
+++ b/cmds/live.c
@@ -341,6 +341,8 @@ static int forward_options(struct uftrace_opts *opts)
                goto close;
 
        /* FIXME Forward user options and set status */
+       if (0)
+               forward_option(sfd, capabilities, 0, NULL, 0);
 
 close:
        status_close = agent_message_send(sfd, UFTRACE_MSG_AGENT_CLOSE, NULL, 0);
```

**Comment by namhyung** [comment]
@clementguidi FYI, please fix your code after this change.  And we should maintain each commit can build without  a warning.

**Comment by clementguidi** [comment]
Sure, sorry about that.
