### ISSUE TITLE
unmapped return address!!!

### ISSUE THREAD

**Issue by shahnejat** [namhyung/uftrace#1681]

**Comment by shahnejat** [comment]
I found out that the problem lies in "mcount_find_code" function. This function is slightly changed as follows:

struct mcount_code{
	void			*insn;
	unsigned long	orig_addr;
};

// void *mcount_find_code(unsigned long addr)
struct mcount_code mcount_find_code(unsigned long addr)                 /* added*/
{
   struct mcount_orig_insn *orig;
   struct mcount_code code;                                                                    /* added*/

   orig = lookup_code(code_hmap, addr);
   if (orig == NULL)
       // return NULL;
       pr_err_ns("Lookup code failed !");                                                   /* added*/
       return code;                                                                                     /* added*/


   code.insn = orig->insn;                                                                        /* added*/
   code.orig_addr = orig->orig_addr;                                                       /* added*/

   // return orig->insn;
   return code;                                                                                         /* added*/
}

So, the size of the return value for "mcount_find_code" is no longer equal to the size of the orig->insn!
Do you have any idea how can I access the proper address of the found code (code.insn)?

**Comment by namhyung** [comment]
I'm closing this.  Please reopen with some information if you have concerns later.
