### ISSUE TITLE
Python tracing test infra

### ISSUE THREAD

**Issue by namhyung** [namhyung/uftrace#1691]
Like we have runtest.py to run test cases for C/C++/Rust programs, we need a similar test infrastructure to test python programs.  I think we can reuse a lot of the runtest.py code, but it doesn't need to build the source code with given compiler and option matrix.

**Comment by namhyung** [comment]
Pushed [review/python-test-v1](../compare/review/python-test-v1).

```
$ make pytest
  TEST     test_python
Start 5 tests without worker pool

Test case                 Result
----------------------------------------
001 basic               : OK
002 filter_F            : OK
003 filter_N            : OK
004 filter_FN           : OK
005 srcline             : OK
```

**Comment by honggyukim** [comment]
Thanks. I think it looks good, but I'm a bit worried that we have too many files directly inside `tests` directory. I think it might be better to have separate directories for C/C++ and Python.

For example, we can have `runtest.py` and `Makefile` only in `tests` and have test scripts and example source files in different directories.

**Comment by namhyung** [comment]
Good point.  But the current test code requires to be in the same directory with `runtest.py`.  Probably we need to copy it to each directory.

**Comment by honggyukim** [comment]
We can keep it in the same directory for now and apply another change that moves the test files properly.

**Comment by namhyung** [comment]
Ok, pushed [review/python-test-v2](../compare/review/python-test-v2).

Changes:
* add `PyTestBase` class to make writing a test even simpler (skipping lang and sort fields).
* add a few more test cases

```
$ make pytest
  TEST     test_python
Start 8 tests without worker pool

Test case                 Result
--------------------------------
001 basic               : OK
002 filter_F            : OK
003 filter_N            : OK
004 filter_FN           : OK
005 srcline             : OK
006 filter_time         : OK
007 filter_depth        : OK
008 file_var            : OK
```

**Comment by namhyung** [comment]
Pushed [review/python-test-v3](../compare/review/python-test-v3).

Changes:
 * add more changes for libcall options

```
$ make -j8 pytest
  TEST     test_python
Start 11 tests with 8 worker

Test case                 Result
--------------------------------
001 basic               : OK
002 filter_F            : OK
003 filter_N            : OK
004 filter_FN           : OK
005 srcline             : OK
006 filter_time         : OK
007 filter_depth        : OK
008 file_var            : OK
009 libcall_single      : OK
010 libcall_none        : OK
011 libcall_nested      : OK
```
