### ISSUE TITLE
warning: ISO C90 forbids mixed declarations and code

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#1716]
There is a simple warning as follows.
```
$ make
  CC FPIC  libmcount/mcount.op
/home/honggyu/work/uftrace/libmcount/mcount.c: In function ‘mcount_filter_init’:
/home/honggyu/work/uftrace/libmcount/mcount.c:382:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  382 |         bool needs_debug_info = false;
      |         ^~~~
```

**Comment by namhyung** [comment]
Hmm.. we are now using C11, so maybe we can get rid of this warning.  Note that we added the warning explicitly in the Makefile.

**Comment by honggyukim** [comment]
Right, but I just feel that we can keep consistency by having the compiler flag. I'm fine either way to drop the compiler flag or change the code to follow the consistency.

**Comment by paranlee** [comment]
I submitted PR #1718
