### ISSUE TITLE
python: Allow tracing under the current and children directories without --nest-libcall

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#1717]
In python tracing, the current way is to limit the tracing in the current source file. But it discards too much tracing info.

For example, the driver script at https://github.com/awslabs/damo/blob/next/damo delegates most of its functionality to other `.py` files and import them.

In this case, we can only trace the functions only inside `damo` script. I think we should also trace all the other files under the same directory and its children directory as well.

**Comment by namhyung** [comment]
Please check [check/python-libcall](../compare/check/python-libcall).

**Comment by honggyukim** [comment]
Thanks very much for working on this! It works great but it breaks the current unit tests as follows.
```
$ ./runtest.py -P libcall
Start 3 tests with 3 worker

Test case                 Result
--------------------------------
009 libcall_single      : NG
010 libcall_none        : NG
011 libcall_nested      : OK
```

**Comment by honggyukim** [comment]
One more thing I would like to ask is that it works great in normal import cases, but it doesn't work with `subprocess` as follows. Let's say there is an example as follows.
```
$ cd tests

$ uftrace s-abc.py 
# DURATION     TID     FUNCTION
            [ 10701] | __main__.<module>() {
            [ 10701] |   a() {
            [ 10701] |     b() {
            [ 10701] |       c() {
   0.662 us [ 10701] |         posix.getpid();
   4.070 us [ 10701] |       } /* c */
   6.805 us [ 10701] |     } /* b */
   8.402 us [ 10701] |   } /* a */
  11.761 us [ 10701] | } /* __main__.<module> */
```
Having this script that runs `s-abc.py` with `subprocess`.
```py
$ cat sp.py
!/usr/bin/env python3
import subprocess as sp

with sp.Popen('./s-abc.py'):
    pass
```
It doesn't show the trace of `s-abc.py` here.
```
$ uftrace sp.py 
# DURATION     TID     FUNCTION
            [ 10810] | __main__.<module>() {
   7.162 ms [ 10810] |   importlib._bootstrap._find_and_load();
 587.913 us [ 10810] |   subprocess.__init__();
   0.383 us [ 10810] |   subprocess.__enter__();
  17.966 ms [ 10810] |   subprocess.__exit__();
   8.867 us [ 10810] |   subprocess.__del__();
  25.751 ms [ 10810] | } /* __main__.<module> */
```
It might be more difficult to support now so it could be done in the next release.

**Comment by honggyukim** [comment]
Another concern is that the following `getenv` is better to be protected in case it returns `NULL`.
```c
    main_file = xstrdup(getenv("UFTRACE_PYMAIN"));
```

**Comment by honggyukim** [comment]
> For the subprocess, let's create an issue for that.

OK. I will create a new issue when this change is merged.

> And did you actually see the getenv returns NULL? I think uftrace.py set it before loading uftrace_python.so so it should not be NULL.

No. I'm fine to keep the current code in this case, but I've generally seen many crashes because of `getenv` returning `NULL`. It might be helpful if we could provide a helper function such as `xgetenv` later.

**Comment by namhyung** [comment]
Updated [check/python-libcall](https://github.com/namhyung/uftrace/compare/check/python-libcall) branch.

**Comment by honggyukim** [comment]
Thanks for the update. It looks great now.

**Comment by honggyukim** [comment]
Hmm.. Sorry, I didn't run the test but it shows as follows.
```
$ ./runtest.py -Pd 011
Start 1 tests without worker pool

Test case                 Result
--------------------------------
p011_libcall_nested: diff result of gcc 
--- expect      2023-06-03 15:39:18.932628528 +0900
+++ result      2023-06-03 15:39:18.932628528 +0900
@@ -5,3 +5,3 @@
          json.dumps() {
-           json.encoder.JSONEncoder.encode();
+           json.encoder.encode();
          } /* json.dumps */
@@ -10,3 +10,3 @@
          json.dumps() {
-           json.encoder.JSONEncoder.encode();
+           json.encoder.encode();
          } /* json.dumps */

011 libcall_nested      : NG
```
It's just a simple naming difference, but better to be handled.

**Comment by namhyung** [comment]
I'll add this:

```diff
diff --git a/tests/p011_libcall_nested.py b/tests/p011_libcall_nested.py
index 3fc2d697..0dc2a9b4 100644
--- a/tests/p011_libcall_nested.py
+++ b/tests/p011_libcall_nested.py
@@ -27,3 +27,6 @@ from runtest import PyTestBase
 
     def setup(self):
         self.option = '--nest-libcall -N ^importlib -D 6'
+
+    def fixup(self, cflags, result):
+        return result.replace(".JSONEncoder", "")
```
