### ISSUE TITLE
Add guide of git-clang-format install & quick usage

### ISSUE THREAD

**Issue by paranlee** [namhyung/uftrace#1721]
We have used [prehook](https://github.com/namhyung/uftrace/blob/master/CONTRIBUTING.md#coding-style). There are clang-format stage.

In my opinion, It would be nice to have something on the guide about preparing for git-clang-format.
I think this way of format checking is more faster to developer. :) like Linux Kernel [scripts/checkpatch.pl](https://github.com/torvalds/linux/blob/master/scripts/checkpatch.pl)

I tested with my rpi4.
```
sudo apt install clang-format -y
# https://github.com/nodesource/distributions#using-ubuntu-2
curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash - &&\
sudo apt-get install -y nodejs
sudo npm install -g clang-format
# not commited
git-clang-format --diff -v
# commited
git-clang-format HEAD~1
```
- [More useful information are here](https://ortogonal.github.io/cpp/git-clang-format/) 
- [git-clang-format tool are in LLVM project](https://github.com/llvm/llvm-project/blob/main/clang/tools/clang-format/git-clang-format)
- [Manual are here](https://clang.llvm.org/docs/ClangFormat.html#git-integration)

**Comment by namhyung** [comment]
I'm not sure if it's covered by the pre-commit already.  @honggyukim ?

**Comment by honggyukim** [comment]
I think we better not to provide this way. It’s because we can use the same clang-format version under pre-commit but there is no way to set the same version. If the clang-format is different then it could possibly apply different coding style.
