### ISSUE TITLE
python tracing needs to be optionally supported

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#1727]
If some systems do not have python installed, then python tracing is broken as follows.
```
$ ./configure --without-libpython

$ make install

$ uftrace tests/s-abc.py 
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/honggyu/work/uftrace/python/uftrace.py", line 26, in <module>
    import uftrace_python
ModuleNotFoundError: No module named 'uftrace_python'
WARN: cannot open record data: /tmp/uftrace-live-dCFzQw: No data available
```
We need a way to optionally support this  feature.

**Comment by honggyukim** [comment]
In addition, I see that `make clean` doesn't remove `python/trace-python.op`.

**Comment by honggyukim** [comment]
One more thing is that we need to minimize confusion between previous python scripting and python tracing. The current `configure` output does not distinguish them and only shows as `libpython`.
```
$ ./configure --without-libpython
uftrace detected system features:
...         prefix: /usr/local
...         libelf: [ on  ] - more flexible ELF data handling
...          libdw: [ on  ] - DWARF debug info support
...      libpython: [ OFF ] - python scripting support
        ...
```

**Comment by namhyung** [comment]
Please try [check/python-build](../compare/check/python-build).

**Comment by namhyung** [comment]
> One more thing that I don't know is that if apt install python3-dev installs libpython3.so only without having python executable.

On ubuntu `python3-dev`  depends on `python3` so I think it should install it if it's not.

About the name change, I don't mind but then it also needs to rename the option name to `--without-python` for consistency.

**Comment by namhyung** [comment]
I think we can rename it later, will merge the current version for now.
