### ISSUE TITLE
Drop the copy of libtraceevent

### ISSUE THREAD

**Issue by namhyung** [namhyung/uftrace#1728]
Now major distros ship libtraceevent library so we don't need to carry the copy in uftrace.  Actually there were lots of incompatible changes in the libtraceevent API so we should change our code.  I believe it's isolated in the utils/kernel.c though.

And then we need to make it a dependent library, and update the `install-deps.sh` script.  This means the kernel tracing is now optional and gracefully reject `-k` and related options if it's not supported.

**Comment by namhyung** [comment]
Uploaded [review/libtraceevent-removal-v1](../compare/review/libtraceevent-removal-v1).

Added libtraceevent check and `--without-libtraceevent` configure option to enable/disable building with system's libtraceevent.  Updated code to use kparser helpers which uses new libtraceevent APIs.  And I didn't disable kernel recording options even when it's not linked with it.  I think it can allow recording but it cannot show the data.  This might be useful when users can run the analysis commands later on other machine.

But I'm seeing this when build **without** libtraceevent.  I don't understand what this means:
```
  CC       utils/fstack.o
/home/namhyung/project/uftrace/utils/fstack.c: In function ‘__read_rstack’:
/home/namhyung/project/uftrace/utils/fstack.c:2375:45: warning: array subscript 0 is outside array bounds of ‘struct uftrace_record[0]’ [-Warray-bounds=]
 2375 |                                 task->rstack->time = min_timestamp - 1;
      |                                             ^~
cc1: note: source object is likely at address zero
```

**Comment by namhyung** [comment]
Pushed [review/libtraceevent-removal-v2](https://github.com/namhyung/uftrace/compare/review/libtraceevent-removal-v2).

* fix memory leak on `kparser->rstacks`.

**Comment by honggyukim** [comment]
Thanks for doing this work!

It might be better to show a warning message when running replay command for uftrace data that has kernel trace information. It looks the current implement silently fails displaying kernel data.

**Comment by namhyung** [comment]
Sounds good.  I'll take a look how to add it.

**Comment by gichoel** [comment]
According to the https://github.com/namhyung/uftrace/commit/f962a2cf999f17f973dcf7f749facf834d4891af that marked this issue as complete, it appears that you removed `libtraceevent` from the existing source tree and updated `misc/install-deps.sh`.

If this is correct, I think the following issues should be closed further to avoid confusion.
https://github.com/namhyung/uftrace/issues/1617

**Comment by honggyukim** [comment]
Right. I have another concern. Some old distros such as Ubuntu 20.04 do not have `libtraceevent-dev`. I feel we removed libtraceevent copy a bit early.

**Comment by namhyung** [comment]
Oh, thanks for letting me know.  I forgot there's a separate issue for that.

**Comment by namhyung** [comment]
> I feel we removed libtraceevent copy a bit early.

Maybe, but I didn't get any complaints yet. :). Probably Ubuntu 20.04 has an old version so it should be fine with that.
