### ISSUE TITLE
uftrace Slides Update

### ISSUE THREAD

**Issue by paranlee** [namhyung/uftrace#1743]
We need to update our uftrace slides to bring them up to date.
- https://uftrace.github.io/slide/

**Comment by paranlee** [comment]
@MichelleJin12 I think it would be a good first issue to share our findings during slides reviews with those who contributed!

**Comment by MichelleJin12** [comment]
@paranlee Good, We can leave the rest of the slides to OSSCA mentees. :D

**Comment by honggyukim** [comment]
Some people write our tool as `Uftrace`, but I think we better not to use it. I always use `u` as lower letter making `uftrace`.
