### ISSUE TITLE
Emitting mcount instructions from Rust on ARM32

### ISSUE THREAD

**Issue by naman-dixit-srib** [namhyung/uftrace#1764]
I am trying to cross-compile some code to ARM32 on x64 machines, and need the compiler to emil `mcount` instructions to be able to use `uftrace`. When I compile the code with `-Zinstrument-mcount -Cpasses=ee-instrument<post-inline>` as indicated in [this issue](https://github.com/namhyung/uftrace/issues/1392#issuecomment-1193697856), I get the following error:

```
   Compiling hello_rs v0.1.0 (/home/naman/UFTRACE/CUSTOM/hello_rs)
LLVM ERROR: Unknown instrumentation function: '__gnu_mcount_nc'
error: could not compile `hello_rs` (bin "hello_rs")
```

The full compilation command is:

```
RUSTFLAGS="-C link-arg=--sysroot=/home/naman/Toolchains/fsl-imx-xwayland/5.15-kirkstone/sysroots/cortexa7t2hf-neon-poky-linux-gnueabi -C link-arg=-Wl,-O1 -C link-arg=-Wl,--hash-style=gnu -C link-arg=-Wl,--as-needed -C link-arg=-Wl,-z,relro,-z,now -g -Zinstrument-mcount -Cpasses=ee-instrument<post-inline> -Clinker-plugin-lto=off -Clto=off" cargo +nightly build --target armv7-unknown-linux-gnueabihf --config target.armv7-unknown-linux-gnueabihf.linker=\"arm-poky-linux-gnueabi-gcc\"
```

I can't find any other documentation of how to get the Rust compiler to emit `mcount` . How should I deal with this error?

Thank you.

**Comment by honggyukim** [comment]
Is your rust cross compiler a nightly compiler? The `-Z` option is only available in nightly compilers.

If it's a nightly compiler, then I'm not sure about it because I haven't tested rust compilation in Arm 32-bit.

**Comment by ChoKyuWon** [comment]
In my case, this is the minimized test case:
```shell
$ cat hello.rs
fn main(){
    println!("hello!");
}
$ rustc test.rs -Zinstrument-mcount -Cpasses=ee-instrument<post-inline> --target armv7-unknown-linux-gnueabihf
LLVM ERROR: Unknown instrumentation function: '__gnu_mcount_nc'
```
I extract the temporal IR and get the follows:
```llvm
define hidden void @_ZN4core3fmt9Arguments6new_v117he807d88819939aefE(ptr sret(%0) %0, ptr align 4 %1, i32 %2, ptr align 4 %3, i32 %4) unnamed_addr #0 { ... }
attributes #0 = { inlinehint nonlazybind uwtable "frame-pointer"="all" "instrument-function-entry-inlined"="\01__gnu_mcount_nc" "target-cpu"="generic" "target-features"="+v7,+vfp3,-d32,+thumb2,-neon" }
```
So the problematic function is `\01__gnu_mcount_nc`, I quickly search the related source code on LLVM.

```cpp
// llvm/lib/Transforms/Utils/EntryExitInstrumenter.cpp
 if (Func == "mcount" ||
      Func == ".mcount" ||
      Func == "llvm.arm.gnu.eabi.mcount" ||
      Func == "\01_mcount" ||
      Func == "\01mcount" ||
      Func == "__mcount" ||
      Func == "_mcount" ||
      Func == "__cyg_profile_func_enter_bare") { ... }
else report_fatal_error(Twine("Unknown instrumentation function: '") + Func + "'");

// llvm/lib/Target/ARM/ARMISelLowering.cpp

case Intrinsic::arm_gnu_eabi_mcount: {
     // call "\01__gnu_mcount_nc"
    ...
}
```
I guess `\01__gnu_mcount_nc` is the implementation of the intrinsic, `llvm.arm.gnu.eabi.mcount`, but the LLVM pass doesn't understand it at that step, so the problem occurs.


I believe it is Rust compiler problem, and should be patched.

**Comment by naman-dixit-srib** [comment]
While the PR is getting reviewed and merged, is there any way to do function tracing without using the `mcount` instructions? I did find the `--patch` argument, but the documentation is not clear whether it can be used as an alternative or not, and how best to use it for trace the entire program.

Also, @ChoKyuWon, I compiled the Rust compiler from your branch (with the fix) and tried to compile a `hello-world` with it. While the compilation and linking succeeded (which wasn't working earlier), it did not emit the `mcount` instruction. I compiled the `hello-world` using `-Zinstrument-mcount -Cpasses=ee-instrument<post-inline>  -Clinker-plugin-lto=off -Clto=off`. I am getting the following error:

```sh
# uftrace --auto-args --libmcount-path=/lib/uftrace --no-sched-preempt --no-libcall --srcline --libname -- hello_rs 1 2 3 4
uftrace: /home/naman/UFTRACE/PACKAGES/uftrace-0.14/cmds/record.c:1671:check_binary
 ERROR: Can't find 'mcount' symbol in the 'hello_rs'.
        It seems not to be compiled with -pg or -finstrument-functions flag.
        You can rebuild your program with it or use -P option for dynamic tracing.
```

**Comment by honggyukim** [comment]
It looks https://github.com/rust-lang/rust/pull/113814 is merged into rustc compiler master. @naman-dixit-srib Could you confirm if it fixes your problem?

Thanks @ChoKyuWon!

**Comment by naman-dixit-srib** [comment]
I had compiled @ChoKyuWon's PR separately, and it did indeed work. But I had encountered another problem: https://github.com/namhyung/uftrace/issues/1774
