### ISSUE TITLE
--no-libcall doesn't seem to work with Rust

### ISSUE THREAD

**Issue by naman-dixit-srib** [namhyung/uftrace#1774]
When I run `uftrace` on a Rust executable with `--no-libcall` argument, I get the following:
```sh
# uftrace --auto-args --libmcount-path=/lib/uftrace --no-sched-preempt --no-libcall --srcline --libname -- hello_rs 1 2 3 4
WARN: cannot open record data: /tmp/uftrace-live-Tv4Ren: No data available
```
When I remove `--no-libcall`, it works but [prints a lot of gunk](https://gist.github.com/naman-dixit-srib/ff33cfa88d79471148152a8a73d23b3b)[^gist].

I am compiling the code with the compiler arguments `-g -Zinstrument-mcount -Cpasses=ee-instrument<post-inline>`. The full compilation command is:

```sh
RUSTFLAGS="-C link-arg=--sysroot=/home/naman/Toolchains/fsl-imx-xwayland/5.15-kirkstone/sysroots/cortexa7t2hf-neon-poky-linux-gnueabi -C link-arg=-Wl,-O1 -C link-arg=-Wl,--hash-style=gnu -C link-arg=-Wl,--as-needed -C link-arg=-Wl,-z,relro,-z,now  -C link-arg=-Wl,--dynamic-linker=/lib/ld-linux-armhf.so.3 -g -Zinstrument-mcount -Cpasses=ee-instrument<post-inline> " cargo build --target /home/naman/UFTRACE/TOOLS/RUST/arm-poky-linux-gnueabi.json --config target.armv7-unknown-linux-gnueabihf.linker=\"arm-poky-linux-gnueabi-gcc\"
```

The platform is ARM32, and I am using the fix by @ChoKyuWon provided at https://github.com/rust-lang/rust/pull/113814 (related to the issue #1764).

[^gist]: Unable to copy the log here due to exceeding the character limit.

**Comment by namhyung** [comment]
You can upload a log file here or somewhere else and add a link.

**Comment by naman-dixit-srib** [comment]
@namhyung You can click on the link above, I have pasted it to a gist ([linking again](https://gist.github.com/naman-dixit-srib/ff33cfa88d79471148152a8a73d23b3b)). Or are you unable to view the gist?

**Comment by ChoKyuWon** [comment]
I quickly tried to reproduce it on x86, and it's not reproduced. I belive you need to provide the target and config `json` file also to solve this problem.

One weird thing is library tracing for uftrace at Rust is now not working (#1777), but your log seems that every library functions traced well. I guess your config file somehow enables the PLT(or it turned on default, I don't have any idea about it.), and `--no-libcall` also affects that config.

Anyway, Rust statically links every library as it can, so I guess `--no-libcall` only remove the libc call or some little stuff, what purpose do you use it for?

**Comment by naman-dixit-srib** [comment]
The JSON used to compile the toolchain is as following:

```json
{
  "abi": "eabihf",
  "arch": "arm",
  "crt-static-respected": true,
  "data-layout": "e-m:e-p:32:32-Fi8-i64:64-v128:64:128-a:0:32-n32-S64",
  "dynamic-linking": true,
  "env": "gnu",
  "features": "+v7,+vfp3,-d32,+thumb2,-neon",
  "has-rpath": true,
  "has-thread-local": true,
  "llvm-target": "armv7-unknown-linux-gnueabihf",
  "max-atomic-width": 64,
  "os": "linux",
  "position-independent-executables": true,
  "relro-level": "full",
  "supported-split-debuginfo": [
    "packed",
    "unpacked",
    "off"
  ],
  "target-family": [
    "unix"
  ],
  "target-mcount": "\u0001__gnu_mcount_nc",
  "target-pointer-width": "32",
  "linker-flavor": "gcc",
  "linker": "/home/naman/Toolchains/fsl-imx-xwayland/5.15-kirkstone/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-gcc",
  "post-link-args": {
      "gcc": [
          "--sysroot=/home/naman/Toolchains/fsl-imx-xwayland/5.15-kirkstone/sysroots/cortexa7t2hf-neon-poky-linux-gnueabi",
          "-Wl,-O1",
          "-Wl,--hash-style=gnu",
          "-Wl,--as-needed",
          "-Wl,-z,relro,-z,now"
      ]
  }
}
```

It was generated with the following command and then edited manually:

```sh
rustc +nightly -Z unstable-options --print target-spec-json --target armv7-unknown-linux-gnueabihf > arm-poky-linux-gnueabi.json
```

We were planning to use UFTrace to understand a foreign codebase with lots of callbacks and lambdas, thus it'll be good to have a clean log.

**Comment by namhyung** [comment]
@naman-dixit-srib @ChoKyuWon Sorry for the late reply.  Do you still see the problem with the latest source?

**Comment by naman-dixit-srib** [comment]
We are not using UFTrace currently, so I'm not sure what the current status is. Feel free to close the issue for now.

**Comment by namhyung** [comment]
Ok, I'll close this for now.  Please reopen if needed, thanks!
