### ISSUE TITLE
--demangle=full (__cxa_demangle) confusedly translates unmangled C symbols, e.g. "f" is translated to "float"

### ISSUE THREAD

**Issue by jyf111** [namhyung/uftrace#1778]
A simple C code `t.c` with symbol "f" and "g":
```c
void f() {}
void g() {}
int main() {
  f();
  g();
  return 0;
}
```

--demangle=full translates "f" and "g" to "float" and "__float128" respectively, which is confusing:
```shell
$ gcc -pg t.c -o t
$ uftrace --demangle=full ./t
# DURATION     TID     FUNCTION
   0.611 us [ 17718] | __monstartup();
   0.210 us [ 17718] | __cxa_atexit();
            [ 17718] | main() {
   0.100 us [ 17718] |   float();
   0.060 us [ 17718] |   __float128();
   0.762 us [ 17718] | } /* main */
```

To prevent this, directly `strdup` the `str` argument not starting with `_Z` in [`demangle_full(char *str)`](https://github.com/namhyung/uftrace/blob/master/utils/demangle.c#L1747) (refer to https://reviews.llvm.org/D22939, since uftrace only resolves function symbols, the problems they discuss do not arise).

**Comment by namhyung** [comment]
Can you please fix it in `demangle_full()` and send a PR?

**Comment by honggyukim** [comment]
It's an interesting issue :)
