### ISSUE TITLE
maybe mistype?

### ISSUE THREAD

**Issue by ParkHanbum** [namhyung/uftrace#181]
hello!

misc/debug-mcount.cmd 
file has been changed in commit 
#caf2c2831541793c164a977ec61b24a0b070ccc2

```
-r record -L. -d xxx tests/t-abc
+r record -L. -d xxx --keep-pid --force tests/t-abc
```

but tests/t-abc does not exist. 
maybe this is mistype? Perhaps s-abc is correct.

**Comment by namhyung** [comment]
@ParkHanbum it'll be created once you run `make test`.

**Comment by ParkHanbum** [comment]
@namhyung I see! sorry for confusing!

**Comment by namhyung** [comment]
@ParkHanbum no need to sorry, please feel free to ask anything.  I really appreciate your contribution!

Just for your information, I create a chat room in gitter for Korean too.
https://gitter.im/uftrace/ko
