### ISSUE TITLE
replay: some symbols are printed with incorrect parentheses, due to logic errors in setting NEEDS_PAREN

### ISSUE THREAD

**Issue by jyf111** [namhyung/uftrace#1827]
## To Reproduce
```cpp
$ cat func.cpp
class F {
public:
  int operator()() {
    return 1;
  }
  int operator+(int) {
    return 2;
  }
};

int main() {
  F()();
  F() + 1;
  auto f = [](int) {
    return 3;
  }(1);
  return 0;
}
$ g++ func.cpp -pg -o func
$ uftrace func
# DURATION     TID     FUNCTION
   0.771 us [  4742] | __monstartup();
   0.290 us [  4742] | __cxa_atexit();
            [  4742] | main() {
   0.120 us [  4742] |   F::operator();
   0.091 us [  4742] |   F::operator+();
   0.080 us [  4742] |   main::$_0::operator();
   1.032 us [  4742] | } /* main */
$ uftrace --demangle=full func
# DURATION     TID     FUNCTION
   0.702 us [  4788] | __monstartup();
   0.191 us [  4788] | __cxa_atexit();
            [  4788] | main() {
   0.080 us [  4788] |   F::operator()();
   0.051 us [  4788] |   F::operator+(int);
   0.050 us [  4788] |   main::{lambda(int)#1}::operator()(int) const();
   0.781 us [  4788] | } /* main */
```

When using simple demangle, `F::operator()` and `main::$_0::operator()` should be `F::operator()()` and `main::$_0::operator()()` respectively. 

When using full demangle, `main::{lambda(int)#1}::operator()(int) const()` should be `main::{lambda(int)#1}::operator()(int) const`.

## To Fix
https://github.com/namhyung/uftrace/blob/58e73072be45f64c0973cb1c9b9a083f7a0977b4/cmds/replay.c#L741-L744

Currently, `NEEDS_PAREN` is set when the last character of `symname` is not ')', since full demangle may add parentheses at the end.

But this does not work with `operator()` (and lambda) under simple demangle, and when using full demangle, the last few characters may be function cv-qualifer (this is a bit annoying).

**Comment by honggyukim** [comment]
Hi @jyf111, it's a bit late response but thanks for the analysis. The logic was introduced at the following commits.
- 48321555 demangle: Use __cxa_demangle for full demangling
- bca429ff replay: Cleanup argument printing

I can also reproduce the problem as follows.
```
$ clang++ -pg -g -o func.clang func.cpp
$ uftrace func.clang 
# DURATION     TID     FUNCTION
            [ 34892] | main() {
   0.129 us [ 34892] |   F::operator();
   0.055 us [ 34892] |   F::operator+();
   0.049 us [ 34892] |   main::$_0::operator();
   1.136 us [ 34892] | } /* main */
```
I think we should remove the logic as follows.
```diff
diff --git a/cmds/replay.c b/cmds/replay.c
index c0ec58f4..e4ff32a0 100644
--- a/cmds/replay.c
+++ b/cmds/replay.c
@@ -738,10 +738,8 @@ static int print_graph_rstack(struct uftrace_data *handle, struct uftrace_task_r
        if (!opts->libcall && sym && sym->type == ST_PLT_FUNC)
                goto out;
 
-       if (rstack->type == UFTRACE_ENTRY) {
-               if (symname[strlen(symname) - 1] != ')' || rstack->more)
-                       str_mode |= NEEDS_PAREN;
-       }
+       if (rstack->type == UFTRACE_ENTRY)
+               str_mode |= NEEDS_PAREN;
 
        task->timestamp_last = task->timestamp;
        task->timestamp = rstack->time;
```
It shows the output as follows with this change.
```
$ clang++ -pg -g -o func.clang func.cpp
$ uftrace func.clang
# DURATION     TID     FUNCTION
            [ 34772] | main() {
   0.058 us [ 34772] |   F::operator()();
   0.042 us [ 34772] |   F::operator+();
   0.042 us [ 34772] |   main::$_0::operator()();
   0.903 us [ 34772] | } /* main */
```
@jyf111 @namhyung Could you confirm if this change is okay for you?

**Comment by jyf111** [comment]
@honggyukim No, this may result in extra parentheses when using full demangle, as follows.

```cpp
$ uftrace --demangle=full func
# DURATION     TID     FUNCTION
   0.972 us [  4713] | __monstartup();
   0.281 us [  4713] | __cxa_atexit();
            [  4713] | main() {
   0.130 us [  4713] |   F::operator()()();
   0.061 us [  4713] |   F::operator+(int)();
   0.070 us [  4713] |   main::{lambda(int)#1}::operator()(int) const();
   1.082 us [  4713] | } /* main */
```

Since `__cxa_demangle()` itself may introduce parentheses, the current logic is used to ensure that no additional parentheses are added.

> But this does not work with `operator()` (and lambda) under simple demangle, and when using full demangle, the last few characters may be function cv-qualifer (this is a bit annoying).

However, I find a simple solution now.

```diff
diff --git a/cmds/replay.c b/cmds/replay.c
index c0ec58f4..8c1a1497 100644
--- a/cmds/replay.c
+++ b/cmds/replay.c
@@ -739,7 +739,7 @@ static int print_graph_rstack(struct uftrace_data *handle, struct uftrace_task_r
                goto out;
 
        if (rstack->type == UFTRACE_ENTRY) {
-               if (symname[strlen(symname) - 1] != ')' || rstack->more)
+               if (demangler == DEMANGLE_SIMPLE || rstack->more)
                        str_mode |= NEEDS_PAREN;
        }

```

The demangler used can be known in `cmds/replay.c`, then we append parentheses only when using simple demangle.
I don't know what `rstack->more` means, so I keep it.

The test results are as follows.

```bash
$ uftrace func
# DURATION     TID     FUNCTION
   0.491 us [  6105] | __monstartup;
   0.230 us [  6105] | __cxa_atexit;
            [  6105] | main {
   0.090 us [  6105] |   F::operator();
   0.050 us [  6105] |   F::operator+;
   0.050 us [  6105] |   main::$_0::operator();
   0.792 us [  6105] | } /* main */
$ uftrace --demangle=full func
# DURATION     TID     FUNCTION
   0.641 us [  6550] | __monstartup;
   0.311 us [  6550] | __cxa_atexit;
            [  6550] | main {
   0.111 us [  6550] |   F::operator()();
   0.070 us [  6550] |   F::operator+(int);
   0.070 us [  6550] |   main::{lambda(int)#1}::operator()(int) const;
   1.072 us [  6550] | } /* main */
```

**Comment by jyf111** [comment]
> However, I find a simple solution now.
> 
> ```diff
> diff --git a/cmds/replay.c b/cmds/replay.c
> index c0ec58f4..8c1a1497 100644
> --- a/cmds/replay.c
> +++ b/cmds/replay.c
> @@ -739,7 +739,7 @@ static int print_graph_rstack(struct uftrace_data *handle, struct uftrace_task_r
>                 goto out;
>  
>         if (rstack->type == UFTRACE_ENTRY) {
> -               if (symname[strlen(symname) - 1] != ')' || rstack->more)
> +               if (demangler == DEMANGLE_SIMPLE || rstack->more)
>                         str_mode |= NEEDS_PAREN;
>         }
> ```

Oh no, this is also wrong. `__cxa_demangle()` does not add parentheses to all symbols, e.g., `__monstartup`.

Now, my idea is to ignore the last potential cv-qualifier first, like `const volatile &&`, and then add parentheses only if the last few characters are not `operator()`. This is a bit complex. 

I don't know if there is a better way.

**Comment by namhyung** [comment]
What about comparing the last part with "operator()" like this?

```diff
diff --git a/cmds/replay.c b/cmds/replay.c
index c0ec58f4..060bbe24 100644
--- a/cmds/replay.c
+++ b/cmds/replay.c
@@ -739,7 +739,10 @@ static int print_graph_rstack(struct uftrace_data *handle, struct uftrace_task_r
                goto out;
 
        if (rstack->type == UFTRACE_ENTRY) {
-               if (symname[strlen(symname) - 1] != ')' || rstack->more)
+               int len = strlen(symname);
+
+               if (symname[len - 1] != ')' || rstack->more ||
+                   (len > 10 && !strcmp(symname + len - 10, "operator()")))
                        str_mode |= NEEDS_PAREN;
        }
 
```

**Comment by jyf111** [comment]
> What about comparing the last part with "operator()" like this?

This is okay under `--demangle=simple`, but wrong under `--demangle=full`, since `__cxa_demangle()` may add a function cv-qualifier after the last parentheses.

```bash
$ cat func.cpp
class F {
public:
  int operator()() const volatile && {
    return 1;
  }
  int operator+(int) {
    return 2;
  }
};

int main() {
  F()();
  F() + 1;
  auto f = [](int) {
    return 3;
  }(1);
  return 0;
}
$ uftrace --demangle=full func
# DURATION     TID     FUNCTION
   6.201 us [ 42234] | __monstartup();
   6.000 us [ 42234] | __cxa_atexit();
            [ 42234] | main() {
   5.901 us [ 42234] |   F::operator()() const volatile &&(); // extra parentheses added
   5.801 us [ 42234] |   F::operator+(int);
   5.701 us [ 42234] |   main::{lambda(int)#1}::operator()(int) const(); // extra parentheses added
  40.707 us [ 42234] | } /* main */
```

**Comment by namhyung** [comment]
Frankly, I don't worry about the full demangle cases much.

**Comment by honggyukim** [comment]
@jyf111 You're right. It looks we need to have a complicated edge case handling logic for `F::operator+(int)` case and cv-qualifier case by examining the C++ mangled symbol.

So none of the above simple solution resolve those edge cases perfectly. But I also think that we can just use simple decent fix for this case.

**Comment by jyf111** [comment]
I agree, most users use the default simple demangler, so this quick fix should be enough.

> What about comparing the last part with "operator()" like this?

**Comment by honggyukim** [comment]
OK. I think we can merge the quick fix first, then keep this issue open although we don't have a plan to make the logic perfect.

**Comment by namhyung** [comment]
I'll merge https://github.com/namhyung/uftrace/issues/1827#issuecomment-1746184852.
