### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by RobertBerger** [namhyung/uftrace#1830]
It looks like at least the test cases require Phython 2 instead of Python 3, so I did something like that to get it to compile with the Yocto Project: 

https://github.com/RobertBerger/manifests/blob/master/meta-openembedded-master/against-aabd1dc4c944c8984397ef8b45add2182f57ee99/0001-uftrace-replace-usr-bin-env-python-with-python3.patch

Do you think this is valid? 

If so I'll clone your uftrace repo, make those changes and send a pull request.

**Comment by namhyung** [comment]
Looks ok, please go ahead.
