### ISSUE TITLE
build error due to low kernel version

### ISSUE THREAD

**Issue by MichelleJin12** [namhyung/uftrace#1834]
I tried to build uftrace on kernel version 3.10.0.

there are some errors below:
```shell
uftrace/cmds/record.c:1592:75: error: ‘EM_RISCV’ undeclared (first use in this function)
  uint16_t supported_machines[] = { EM_X86_64, EM_ARM, EM_AARCH64, EM_386, EM_RISCV };
                                                                           ^
uftrace/cmds/record.c:1592:75: note: each undeclared identifier is reported only once for each function it appears in
make: *** [uftrace/cmds/record.o] Error 1


uftrace/utils/tracefs.c:26:53: error: ‘TRACEFS_MAGIC’ undeclared (first use in this function)
  if (!statfs(TRACEFS_DIR_PATH, &fs) && fs.f_type == TRACEFS_MAGIC) {
                                                     ^
uftrace/utils/tracefs.c:26:53: note: each undeclared identifier is reported only once for each function it appears in
make: *** [uftrace/utils/tracefs.o] Error 1


uftrace/arch/x86_64/mcount-dynamic.c:46:6: error: ‘MAP_FIXED_NOREPLACE’ undeclared (first use in this function)
      MAP_FIXED_NOREPLACE | MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
      ^
uftrace/arch/x86_64/mcount-dynamic.c:46:6: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [uftrace/arch/x86_64/mcount-dynamic.op] Error 1
make: *** [uftrace/arch/x86_64/mcount-entry.op] Error 2
```

It is because the low kernel version, so how about adding macros like this:
```c
#ifndef EM_RISCV
#define EM_RISCV 243
#endif
```
```c
#ifndef TRACEFS_MAGIC
#define TRACEFS_MAGIC 0x74726163
#endif
```
```c
#ifndef MAP_FIXED_NOREPLACE
#define MAP_FIXED_NOREPLACE 0x100000
#endif
```

**Comment by paranlee** [comment]
latest `systemd` also have missing defines. ;)

**Comment by gichoel** [comment]
Hmm... How about using the method you suggested to resolve the error caused by `EM_RISCV` not being declared?

As for `EM_AARCH64`, we were able to confirm that it was declared in the uftrace code in the way you mentioned, and this was also confirmed in `cmds/record.c` and `utils/symbol.c`.
<br>

And the error in `TRACEFS_MAGIC` appears to be caused by the addition of `tracefs` in `Linux kernel v4.1`.
 - Reference link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=2455f0e124d3

So, since before `Linux kernel v4.1` there is no special filesystem called `tracefs`, wouldn't it be better to change the code as below rather than simply adding a macro?
```diff
/* in tracefs.c */
......

static bool find_tracing_dir(void)
{ 
	......

+#ifdef TRACEFS_MAGIC
	if (!statfs(TRACEFS_DIR_PATH, &fs) && fs.f_type == TRACEFS_MAGIC) {
		xasprintf(&TRACING_DIR, "%s", TRACEFS_DIR_PATH);
		return true;
	}
	else if (!statfs(OLD_TRACEFS_DIR_PATH, &fs) && fs.f_type == TRACEFS_MAGIC) {
		xasprintf(&TRACING_DIR, "%s", OLD_TRACEFS_DIR_PATH);
		return true;
	}
+#endif

	......
}
```

**Comment by emniuyk** [comment]
@gichoel right, your suggestion is better. :)

**Comment by namhyung** [comment]
While this is indeed better for performance, I'm incline to add the macros and remove `#ifdef` in the source code (*.c files).  Adding those condition reduces readability and it'd be better if we can avoid it.

**Comment by gichoel** [comment]
Thank you for your feedback.
I will incorporate your feedback the next time I encounter a similar issue.

**Comment by honggyukim** [comment]
> While this is indeed better for performance, I'm incline to add the macros and remove #ifdef

I don't get what you mean clearly. Do you mean that you want to add macros with slightly different names, but have same values? Otherwise, how do we handle redefinition errors having the macros with the same names?

**Comment by namhyung** [comment]
Let me be clearer.  I prefer the original proposal to define some macro in the **HEADER FILE** if it's not defined over adding conditional logics in the SOURCE FILE like in https://github.com/namhyung/uftrace/issues/1834#issuecomment-1766411079.

**Comment by honggyukim** [comment]
@namhyung Do you want to have this?
```diff
diff --git a/arch/x86_64/mcount-dynamic.c b/arch/x86_64/mcount-dynamic.c
index 4da8e543..bec587b4 100644
--- a/arch/x86_64/mcount-dynamic.c
+++ b/arch/x86_64/mcount-dynamic.c
@@ -12,6 +12,10 @@
 #include "utils/symbol.h"
 #include "utils/utils.h"
 
+#ifndef MAP_FIXED_NOREPLACE
+#define MAP_FIXED_NOREPLACE 0x100000
+#endif
+
 static const unsigned char fentry_nop_patt1[] = { 0x67, 0x0f, 0x1f, 0x04, 0x00 };
 static const unsigned char fentry_nop_patt2[] = { 0x0f, 0x1f, 0x44, 0x00, 0x00 };
 static const unsigned char patchable_gcc_nop[] = { 0x90, 0x90, 0x90, 0x90, 0x90 };
diff --git a/cmds/record.c b/cmds/record.c
index 959042b5..81de11af 100644
--- a/cmds/record.c
+++ b/cmds/record.c
@@ -29,6 +29,10 @@
 #include "utils/symbol.h"
 #include "utils/utils.h"
 
+#ifndef EM_RISCV
+#define EM_RISCV 243
+#endif
+
 #ifndef EFD_SEMAPHORE
 #define EFD_SEMAPHORE (1 << 0)
 #endif
diff --git a/utils/tracefs.c b/utils/tracefs.c
index 2b96889e..9486fb70 100644
--- a/utils/tracefs.c
+++ b/utils/tracefs.c
@@ -8,6 +8,10 @@
 #include "utils/tracefs.h"
 #include "utils/utils.h"
 
+#ifndef TRACEFS_MAGIC
+#define TRACEFS_MAGIC 0x74726163
+#endif
+
 #define PROC_MOUNTS_DIR_PATH "/proc/mounts"
 #define TRACEFS_DIR_PATH "/sys/kernel/tracing"
 #define OLD_TRACEFS_DIR_PATH "/sys/kernel/debug/tracing"
```
I think this helps compilation for old systems, but what should be the behaviors when the old system uses those macro values?

For example, if the system doesn't have `TRACEFS_MAGIC` and the current `utils/tracefs.c` expects `fs.f_type` is `TRACEFS_MAGIC`.  However, is it possible the `statfs` in old systems fills `fs.f_type` to `TRACEFS_MAGIC` value?

**Comment by namhyung** [comment]
Yep, please send a PR.

In your example, I think it'd be a rare condition where you have an old system libraries but new kernel.  I think the `fs.f_type` would be filled by the kernel.  And it's possible if you build the kernel image manually on such a system.

**Comment by honggyukim** [comment]
> I think the fs.f_type would be filled by the kernel.

I mean the opposite. In old systems, the kernel won't set the `fs.f_type` to `TRACEFS_MAGIC` because the old kernel doesn't know about it.

**Comment by namhyung** [comment]
Then it won't match, and we are fine, no? :)  I might waste some cycles but I think that's fine as it's not in the hot path.

**Comment by honggyukim** [comment]
OK. I think @MichelleJin12 can send a PR as she originally posted the fix.

**Comment by MichelleJin12** [comment]
Thanks for your help, @paranlee, @gichoel, @honggyukim, @namhyung. :D
I sent the PR as per @honggyukim's advice, and sorry for the late update ;)
