### ISSUE TITLE
plthook `invalid dynsym idx` when profiling php-src

### ISSUE THREAD

**Issue by ilnytskyi** [namhyung/uftrace#1835]
Hello,

I found this profiling while looking a tool to generate visualized timelines for C https://stackoverflow.com/questions/77214379/c-profiler-tracer-with-timeline-view

I tried it and it found that it's the most suitable profiler/tracer.

However I encountered a problem when working with https://github.com/php/php-src

It breaks with the error when doing anything

```
plthook: /home/www/app/uftrace/libmcount/plthook.c:1013:__plthook_exit
 ERROR: <2> invalid dynsym idx: -269488145
```

I profile tried this and it finishes with the error above:
```
uftrace record php -v
uftrace record php index.php
```

When I disable libraries it works but then the call stack has missing my extension and all other extensions despite they were compiled with `-pg` or `-finstrument-functions`
```
uftrace record  --no-libcall php -v
uftrace record  --no-libcall php index.php
```

The php-src is build like this
```
./buildconf --force
./configure CFLAGS="-pg" \
        --disable-phar \
        --enable-debug \
        --prefix=$HOME/php-bin/DEBUG \
        --with-config-file-path=$HOME/php-bin/DEBUG/etc
make -j4 && make install && cd .. && export PATH=~/php-bin/DEBUG/bin:$PATH
```

The extension are also build using 
```
./configure CFLAGS="-finstrument-functions -pg"
#tried both
```
But I do not know how I can fix this problem or bypass this issue.
I attach all logs with different levels of verbosity `-v`.
[v1.log](https://github.com/namhyung/uftrace/files/13056085/v1.log)
[v2.log](https://github.com/namhyung/uftrace/files/13056086/v2.log)
[v3.log](https://github.com/namhyung/uftrace/files/13056087/v3.log)
[v4.log](https://github.com/namhyung/uftrace/files/13056088/v4.log)

in v4 the error is in this part
```
mcount: rstack[2] ENTRY 56304c200700
mcount: rstack[2] EXIT  56304c200700
plthook: [idx:  109] exit  56304c744d2b: strlen     (resolved addr: 7f6a29fd5300)
plthook: [idx:  109] enter 56304c200700: strlen@plt (mod: 7f6a2a51b180)
mcount: <2> enter 56304c200700
mcount:  tr->flags: 0, filter mode: 0, count: 0/0, depth: 2
mcount: <3> exit  56304c200700
mcount: task 72836 recorded 32 bytes (record count = 2)
mcount: rstack[2] ENTRY 56304c200700
mcount: rstack[2] EXIT  56304c200700
plthook: [idx:  109] exit  56304c744d2b: strlen     (resolved addr: 7f6a29fd5300)
demangle: simple demangle failed: (not finished)
__cyg_profile_func_exit
  ^
dd_operator_name:1376: "valid operator name" expected
demangle: current: (null) (pos: 2/23)
demangle:   [00] (000/__) dd_encoding
demangle:   [01] (002/cy)   dd_operator_name
plthook: [idx:  412] enter 56304c2019f0: __cyg_profile_func_exit@plt (mod: 7f6a2a51b180)
mcount: <2> enter 56304c2019f0
mcount:  tr->flags: 0, filter mode: 0, count: 0/0, depth: 2
mcount: <3> exit  56304c2019f0
mcount: task 72836 recorded 32 bytes (record count = 2)
mcount: rstack[2] ENTRY 56304c2019f0
mcount: rstack[2] EXIT  56304c2019f0
plthook: /home/www/app/uftrace/libmcount/plthook.c:1013:__plthook_exit
 ERROR: <2> invalid dynsym idx: -269488145
```

Any advice what I can do to debug/fix the code to omit the issue?
Or it's the problem with profiler that `__cyg_profile_func_exit` not injected somewhere during compilation?

**Comment by namhyung** [comment]
Thanks for the detailed report.  Yeah, the issue is unmatched PLT entry/exit pairs.  But it seems you passed both `-finstrument-functions` and `-pg` which is not good.  Can you please use `-pg` only for your extention and see how it works?

**Comment by ilnytskyi** [comment]
@namhyung I tried with both separately and still got same result.
I suspect it might be related to dynamically some loaded libs or error in any of core libs.

I tried to rebuild php with `-pg` and as few libs included as possible `php -n -m`
```
[PHP Modules]
Core
date
hash
json
pcre
Reflection
SPL
standard

[Zend Modules]
```

And `uftrace` still throws same error even with `--force` :(

> Yeah, the issue is unmatched PLT entry/exit pairs.
Is there a way to ignore unmatched pairs? Or leave some warning instead of stopping the tracing?

**Comment by namhyung** [comment]
Hmm.. ok.  `__cyg_profile_func_exit` should not be called from the plthook code.  In fact, it's updated by `restore_plt_functions()` during init to skip the PLT.

```
plthook: setup PLT hooking "/root/php-bin/DEBUG/bin/php"
plthook: setup plthook data for /root/php-bin/DEBUG/bin/php (offset: 55afadc00000)
plthook: opening executable image: /root/php-bin/DEBUG/bin/php
plthook: "php" is loaded at 0x55afadc00000
plthook: found GOT at 0x55afaeffffe8 (base_addr + 0x13fffe8)
plthook: module id = 0x7f460ca3d180, PLT resolver = 0x7f460ca27610
plthook: overwrite GOT[101] to 0x7f460c9db310 (__cyg_profile_func_enter)
plthook: restore GOT[121] from "unlink"(0x55afae0c9b0f) to PLT(base + 0x200796)
plthook: restore GOT[218] from "waitpid"(0x55afae05667a) to PLT(base + 0x200da6)
plthook: restore GOT[250] from "vasprintf"(0x7f460c3d49f0) to PLT(base + 0x200fa6)
plthook: restore GOT[284] from "valuePush"(0x7f460c9db290) to PLT(base + 0x2011c6)
plthook: restore GOT[359] from "fputc"(0x55afae0c9298) to PLT(base + 0x201676)
plthook: overwrite GOT[415] to 0x7f460c9db500 (__cyg_profile_func_exit)
plthook: restore GOT[436] from "execle"(0x55afae055698) to PLT(base + 0x201b46)
plthook: restore GOT[438] from "xmlParseCharEncoding"(0x55afae11d98c) to PLT(base + 0x201b66)
```

You can see index 101 and 415.  But your change has the function at 412.

```
plthook: [idx:  412] enter 56304c2019f0: __cyg_profile_func_exit@plt (mod: 7f6a2a51b180)
```

**Comment by namhyung** [comment]
Anyway you program looks like not normal.  It saw `__cyg_profile_func_exit()` without `__cyg_profile_func_enter()` which doesn't make sense.  Maybe you need a clean build with `-pg`.

**Comment by namhyung** [comment]
Anyway we should reject those unmatched exit function.  Can you please test [this patch](https://github.com/namhyung/uftrace/files/13061383/discard-unmatched-cygprof-exit.patch.txt)?

```diff
diff --git a/libmcount/mcount.c b/libmcount/mcount.c
index 6347fab3..2bd83130 100644
--- a/libmcount/mcount.c
+++ b/libmcount/mcount.c
@@ -1539,11 +1539,11 @@ static int __cygprof_entry(unsigned long parent, unsigned long child)

        if (filtered == FILTER_IN) {
                rstack->start_time = mcount_gettime();
-               rstack->flags = 0;
+               rstack->flags = MCOUNT_FL_CYGPROF;
        }
        else {
                rstack->start_time = 0;
-               rstack->flags = MCOUNT_FL_NORECORD;
+               rstack->flags = MCOUNT_FL_CYGPROF | MCOUNT_FL_NORECORD;
        }

        mcount_entry_filter_record(mtdp, rstack, &tr, NULL);
@@ -1582,6 +1582,12 @@ static void __cygprof_exit(unsigned long parent, unsigned long child)

        rstack = &mtdp->rstack[mtdp->idx - 1];

+       /* discard unmatched cygprof exit */
+       if (unlikely(!(rstack->flags & MCOUNT_FL_CYGPROF))) {
+               mcount_unguard_recursion(mtdp);
+               return;
+       }
+
        if (!(rstack->flags & MCOUNT_FL_NORECORD))
                rstack->end_time = mcount_gettime();

diff --git a/libmcount/mcount.h b/libmcount/mcount.h
index 920f99de..78d85358 100644
--- a/libmcount/mcount.h
+++ b/libmcount/mcount.h
@@ -38,6 +38,7 @@ enum mcount_rstack_flag {
        MCOUNT_FL_ARGUMENT = (1U << 11),
        MCOUNT_FL_READ = (1U << 12),
        MCOUNT_FL_CALLER = (1U << 13),
+       MCOUNT_FL_CYGPROF = (1U << 14),
 };

 struct plthook_data;
```

**Comment by namhyung** [comment]
> You can see index 101 and 415. But your change has the function at 412.

>> plthook: [idx:  412] enter 56304c2019f0: __cyg_profile_func_exit@plt (mod: 7f6a2a51b180)

Oh,  +3 is for the number of reserved entries in the PLTGOT.  Then it should match to __cyp_profile_func_exit() at 415.

**Comment by ilnytskyi** [comment]
@namhyung thanks for the patch.
With the patch the profiler does not fail whit the original error, but the profiled program does with segfault and some other warnings.
```
WARN: Segmentation fault: address not mapped (addr: (nil))
WARN:  if this happens only with uftrace, please consider -e/--estimate-return option.

WARN: Backtrace from uftrace v0.14-47-gce3a ( x86_64 luajit perf sched dynamic )
WARN: =====================================
WARN: [12] (putenv[5574f4201290] <= plthook_return[7f10be278a39])
WARN: [11] (__ctype_b_loc[5574f42012b0] <= xbuf_format_converter[5574f45ba150])
WARN: [10] (xbuf_format_converter[5574f45ba030] <= php_printf_to_smart_string[5574f45bbe69])
WARN: [9] (php_printf_to_smart_string[5574f45bbe29] <= zend_vspprintf[5574f465dc00])
WARN: [8] (zend_vspprintf[5574f465db8f] <= zend_spprintf[5574f465dd54])
WARN: [7] (zend_spprintf[5574f465dc93] <= php_load_zend_extension_cb[5574f45bf5e0])
WARN: [6] (php_load_zend_extension_cb[5574f45bf4c9] <= zend_llist_apply[5574f464915a])
WARN: [5] (zend_llist_apply[5574f4649119] <= php_ini_register_extensions[5574f45c04de])
WARN: [4] (php_ini_register_extensions[5574f45c04b4] <= php_module_startup[5574f45b5ee2])
WARN: [3] (php_module_startup[5574f45b5655] <= php_cli_startup[5574f47eba15])
WARN: [2] (php_cli_startup[5574f47eb9df] <= main[5574f47ed881])
WARN: [1] (save_ps_args[5574f47f8e6c] <= main[5574f47ed2f3])
WARN: [0] (main[5574f47ed25b] <= __libc_start_main[7f10bdc3ed0a])
```
The logs.
[v4.log](https://github.com/namhyung/uftrace/files/13062823/v4.log)
[v3.log](https://github.com/namhyung/uftrace/files/13062824/v3.log)
[v2.log](https://github.com/namhyung/uftrace/files/13062825/v2.log)
[v1.log](https://github.com/namhyung/uftrace/files/13062826/v1.log)

I tried to recompile php without using jit and for some reason the error persists
```
        --disable-opcache-jit \
        --without-pcre-jit \ 
        --disable-opcache \
```

Everything still works with `--no-libcall`.

From the callstack it seems that php cannot startup and fails during restringing extensions.

![Selection_860](https://github.com/namhyung/uftrace/assets/3192770/3e1340e0-0223-4748-9121-7b3d7c8b123f)

I tried to check what `perf` shows, and there is some kind of fault calls in that place.

 ![Selection_861](https://github.com/namhyung/uftrace/assets/3192770/c6b294d4-4406-4c1d-9c5d-f5bdb711b768)

But there are also similar calls earlier and later.

I will do more tests later, will try profiling after some trigger in my script or by attaching to running process to skip tracing during php bootstrapping.

**Comment by namhyung** [comment]
Thanks for the update.  I found two strange points.

* `__ctype_b_loc()` is a PLT call so it should be a leaf but your data shows it calls `putenv()` inside.  It doesn't make sense and I cannot find such a call in [the code](https://github.com/lattera/glibc/blob/895ef79e04a953cac1493863bcae29ad85657ee1/include/ctype.h#L39).
* In the backtrace, 'child <== parent' addresses doesn't match at index 2.  Something strange might happen in `save_pg_args`.  Looking at the code, I'm not sure if it's safe to change argv and environ just after checking the pointer values.  It seems there's an assumption of no more changes in argv nor env.  Maybe it can confuse uftrace somehow.  Can you make a change not to define `PS_USE_CLOBBER_ARGV` [here](https://github.com/php/php-src/blob/f09340905263d0abb7cb9d60dc2dd1c1a5737215/sapi/cli/ps_title.c#L97)?

**Comment by namhyung** [comment]
Also, please try the current master of uftrace to reduce the debug messages on demangle failures. :)

**Comment by namhyung** [comment]
I tried to reproduce with the latest php-src but failed.  IOW it didn't crash and exited normally.  Can you please share  a minimal reproducer?

**Comment by ilnytskyi** [comment]
@namhyung thanks, for the info, I checked it with `PHP-8.1`, I will try with other versions and share the results.

**Comment by ilnytskyi** [comment]
@namhyung thanks for advise. I confirm there is no problem with latest 8.2 and master branches. So I think the issue can be closed.
