### ISSUE TITLE
Crash on boost conroutines

### ISSUE THREAD

**Issue by molixiaoge** [namhyung/uftrace#1848]
When i run the command like below: 
`uftrace record  ./test`

The program will run few seconds well,but then it crash with:
```
terminate called after throwing an instance of 'boost::system::system_error'
  what():  Operation canceled [system:125]
WARN: child terminated by signal: 11: Segmentation fault
```

Then i change the command with:
`uftrace record -e  ./test`
It will run well without crash.

What causes the program crash without -e option?

**Comment by namhyung** [comment]
It's hard to tell without seeing the code.  But in general, `uftrace` needs to change the return address in the stack in order to intercept the function returns.  That caused some problems in some cases like yours.  The `-e` or `--estimate-return` is not to do that (to avoid the crash).  But it cannot know the exact timing and the location of returns, and just estimate the return using the value of the stack pointer register at the moment.

**Comment by molixiaoge** [comment]
Thx for your reply.
I gues the  project use boost coroutine.

**Comment by namhyung** [comment]
Ah, coroutines are troublesome... :(

**Comment by honggyukim** [comment]
You can compile your program with `-finstrument-functions` instead of `-pg` in this case to avoid return address manipulation. I think your program won't be crashed then.

**Comment by honggyukim** [comment]
Ah. it might also be crashed when the program creates multiple coroutines even with `-finstrument-functions` but you can just try that.

**Comment by molixiaoge** [comment]
@honggyukim 

Rebuild with  -finstrument-functions option.
It also crash with:

```
terminate called after throwing an instance of 'boost::system::system_error'
  what():  Operation canceled [system:125]
================================================================
Stack trace (most recent call last) in thread 81414:
#0    Object "[0x7f05eda0187f]", at 0x7f05eda0187f, in 
Aborted (Signal sent by tkill() 81355 1018)
WARN: child terminated by signal: 6: Aborted
```

**Comment by honggyukim** [comment]
Sorry for the late response. I don't have a good answer then.

It could be a bit more helpful if we can get a simple reproducible example program.
