### ISSUE TITLE
utils: return status checking on callee functions in `load_module_symbol()`

### ISSUE THREAD

**Issue by paranlee** [namhyung/uftrace#1857]
When we review the code on `utils/symbol.c` `load_module_symbol()`
```
void load_module_symbol(struct uftrace_sym_info *sinfo, struct uftrace_module *m)`
{
	...

	/*
	 * Currently it uses a single symtab for both normal symbols
	 * and dynamic symbols.  Maybe it can be changed later to
	 * support more sophisticated symbol handling.
	 */
	load_symtab(&m->symtab, m->name, 0, flags);
	load_dynsymtab(&dsymtab, m->name, 0, flags);
	merge_symtabs(&m->symtab, &dsymtab);
	update_symtab_using_dynsym(&m->symtab, m->name, 0, flags);
```

`int` return type functions `load_symtab()`, `load_dynsymtab()`, `update_symtab_using_dynsym()` are not checking the return status.

Could we add return status checking?

Can @namhyung, @honggyukim give me a guide on how to do check this?

**Comment by namhyung** [comment]
There are cases where binaries don't have symbol tables.  So I think it's ok to ignore the return values.
