### ISSUE TITLE
utils: Old directory problem when recording

### ISSUE THREAD

**Issue by Taeung** [namhyung/uftrace#186]
I found a trivial problem like below.
I don't know the exact case this problem occurs,
but I found this situation during many test case..

Even though `uftrace.data.benchSTL/` not exists,
the below uftrace-record not works because of the old directory `uftrace.data.benchSTL.old/`.
After the old directory manually removed, it works fine.

```
$ uftrace record -D 5 -t 1us -d uftrace.data.benchSTL ./benchmark_STL_containers
WARN: removing old directory failed: Is a directory

$ rm -rf uftrace.data.benchSTL.old/

$ uftrace record -D 5 -t 1us -d uftrace.data.benchSTL ./benchmark_STL_containers
```

**Comment by namhyung** [comment]
Hmm.. I guess the old directory contained a subdirectory?

**Comment by namhyung** [comment]
@Taeung ping?

**Comment by namhyung** [comment]
Any update?

**Comment by Taeung** [comment]
I'm terribly sorry for the late response, @namhyung 

Right, when already old directory existed, the warning message occurred.
However, I think just if there isn't 'uftrace.data',
should we able to run uftrace-record without warning messages ? like below:

```    
$ ls
hello  uftrace.data.old

$ uftrace record hello
$ ls
hello  uftrace.data  uftrace.data.old
```

**Comment by Taeung** [comment]
Additionally,
In the case:
When there is only a 'uftrace.data.old'
('uftrace.data' directory doesn't exist)
```  
$ uftrace record hello && uftrace record hello  
$ rm -rf uftrace.data
$ ls
hello  uftrace.data.old
```

If recording, innocent old directory can be eliminated.
(I tested this case on master branch)

```
$ uftrace record hello
$ ls
hello  uftrace.data
```

I thought they are trivial bugs, no ?

**Comment by namhyung** [comment]
The problem was that it could not remove old directory if it contains a subdirectory inside it (I guess).

**Comment by Taeung** [comment]
I think I understand what you said.
But let me explain what I think, again.

We can think 4 cases (regarding the existence of `uftrace.data` directory):
 * Case 1) Nothing
 * Case 2) Only `uftrace.data`
 * Case 3) Only `uftrace.data.old`
 * Case 4) Both

I think we should able to just run uftrace-record with or without `.old`, in the `Case 3)` and `Case 1)`.

However, this problem I think is that ufrace-record doesn't work, in the `Case 3)` with the warning message.
(`WARN: removing old directory failed: Is a directory`)

I think that if `uftrace.data` doesn't exist, we don't need to rename it and remove `.old`, IMHO

**Comment by namhyung** [comment]
No, uftrace works fine in the case 3 - but it removes the old directory unnecessarily.

**Comment by Taeung** [comment]
OK, understood !

**Comment by namhyung** [comment]
So do you confirm that it was a problem due to a subdirectory?

**Comment by Taeung** [comment]
Right, the above warning message was because of a existing subdirectory `uftrace.data.old`.
But I thought uftrace-record should able to work with or without `.old`, if no `uftrace.data` exists..

Anyway, because of this recent PR, this problem is gone.

**Comment by namhyung** [comment]
No no no.

Removing uftrace.data.old should be ok always.  It's **NOT** because the uftrace.data.old exists - it almost always exists.  But your problem was failed during the removal and the error code was: ENOTEMPTY ("Is a directory").  It was because it tried to delete non-empty directory (uftrace.data.old).  But as you can see `remove_directory` deletes **all files** in the directory before delete the directory itself.  However, if there's a (sub)directory inside the uftrace.data.old (which is not true normally), it  fails to remove the directory.

So my question is that did you put any directory in the `uftrace.data.benchSTL` directory before?

**Comment by Taeung** [comment]
First of all,
> So my question is that did you put any directory in the `uftrace.data.benchSTL` directory before?

I didn't put any directory in the `uftrace.data.benchSTL` directory before.

**Comment by namhyung** [comment]
Hmm.. can you still reproduce the problem?

**Comment by namhyung** [comment]
Hmm.. strange.  Can you still reproduce the problem?

**Comment by Taeung** [comment]
> Hmm.. can you still reproduce the problem?

Sorry, unfortunately I removed this test data, so I can't exactly reproduce same situation.

But I tested it, again regarding this situation.
I found same warning message as you said.
```
# create .old
$ uftrace record hello
$ uftrace record hello

$ mkdir uftrace.data.old/sub
$ uftrace record hello
WARN: removing old directory failed: Is a directory
```
I guess that I could make mistake creating a subdirectory in `.old`..

**Comment by namhyung** [comment]
OK, then could you please make `remove_directory` remove all entries in a directory recursively?

**Comment by Taeung** [comment]
Sure, I'll modify `remove_directory()` 😄
