### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [namhyung/uftrace#187]
I would like to point out that identifiers like “[`__UFTRACE_H__`](https://github.com/namhyung/uftrace/blob/bf488d9bcaf9ca109c755468c8332be406710cee/uftrace.h#L1 "Update candidate")” and “[`__FTRACE_UTILS_H__`](https://github.com/namhyung/uftrace/blob/66d5e54ce3f132a962ef30747ad6c1d212297f9c/utils/utils.h#L9 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by namhyung** [comment]
Thanks for pointing it out.  I'm ok with the suggested change along with remaining "ftrace" -> "uftrace" renames.  Would you mind sending a pull request doing it?

**Comment by elfring** [comment]
Do [any more source code places](https://github.com/namhyung/uftrace/blob/7e4472b9ebb1253dac45d6a827e20d63a3984d16/utils/script-python.c#L130 "Update candidate: import_python_module()") need [further software development considerations](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?")?

**Comment by namhyung** [comment]
Yes, please fix. :)

**Comment by qpakzk** [comment]
I want to try this issue!

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/namhyung/uftrace/commit/8f1d5713f416b6fcfac74fd9f884e72eaef58290 "Renaming of include guards").
Were there [any update candidates left over](https://github.com/namhyung/uftrace/blob/0c88e1bd633f6c2b3acd36aeaa6104d3c292c035/utils/rbtree.h#L27 "Update candidate")?

**Comment by namhyung** [comment]
Yes, I know.  But as they came from the kernel, I don't want touch them as much as possible.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by namhyung** [comment]
Well.. I don't care anymore.

**Comment by elfring** [comment]
Are you going you clarify concerns around standard compliance for the programming language “C” with any other software users (besides me)?

**Comment by namhyung** [comment]
Complying with the standard is good, but maintanence is also important IMO.

**Comment by elfring** [comment]
Which details have you got in mind when you mention “maintenance” in this context?

**Comment by namhyung** [comment]
> they came from the kernel, I don't want touch them as much as possible.

**Comment by elfring** [comment]
* Do we stumble on a target conflict?
* How do you think about to adjust questionable identifiers in the original source files then?
