### ISSUE TITLE
ERROR: ld.so: object '/usr/lib/x86_64-linux-gnu/uftrace/libmcount-fast.so

### ISSUE THREAD

**Issue by LinArcX** [namhyung/uftrace#1874]
I have an elf file(__ELF 32-bit LSB pie executable__) that when I want to run: `uftrace record` on it, I will get this error:

> ERROR: ld.so: object '/usr/lib/x86_64-linux-gnu/uftrace/libmcount-fast.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.

Also, my application needs Ctrl-c to stop. at this point, I get another error:
> Cuftrace: ./cmds/record.c:1437:update_session_maps
 ERROR: cannot find map files: No such file or directory

**Comment by honggyukim** [comment]
You can compile uftrace in `i386` mode to trace 32-bit ELF binaries as follows.
```
$ ./configure --arch=i386
$ make && make install
```

**Comment by namhyung** [comment]
Right, then it'd work only for the 32-bit binaries though.
