### ISSUE TITLE
Clang randomly crashing due to -mno-sse2 applied on x86_64

### ISSUE THREAD

**Issue by truboxl** [namhyung/uftrace#1877]
Hi, it seems that https://github.com/namhyung/uftrace/commit/d17c3e4b538941b3728abb0dca8bce6f1e8ba3a2

Is causing problem for https://github.com/llvm/llvm-project/issues/42971, https://github.com/llvm/llvm-project/issues/29774, https://github.com/android/ndk/issues/1987

Can you help comment on them?

**Comment by namhyung** [comment]
Sure, thanks for the report.

**Comment by MaskRay** [comment]
`-mgeneral-regs-only` (https://reviews.llvm.org/D103943) is probably suitable for your use case. It will place floating-point arguments in general purpose registers.

`-mno-sse2` (without `-mno-sse`) may cause crashes when using floating points.

**Comment by namhyung** [comment]
@MaskRay thanks for your reply.  It'd be good as long as it suppresses the FP/SIMD registers.

One question, is it ok (IOW not to crash) if I add `-mno-sse` too?

**Comment by namhyung** [comment]
Also I realized that script support (both python and luajit) in libmcount uses FP types. :(

It seems the minimal fix is to add `-mno-sse`.  We might consider to drop script support at record.  @honggyukim wdyt?

**Comment by MaskRay** [comment]
My memory has been fuzzy... You probably need to try different code patterns (local variable/parameter float/double, floating point expressions, etc) to figure out whether the combinations of `-mno-sse -mno-sse2`  work as intended...

**Comment by namhyung** [comment]
At the point, I think it's ok not to work as intended.  Higher priority would be not to crash compilers! :)

In my local testing, adding `-mno-sse` makes it stop crashing.  So I'll add it for now.  And then I'll check if it supports `-mgeneral-regs-only` and use it.

**Comment by namhyung** [comment]
Pushed 95cb1112.  Maybe we need to release v0.15.1 with this.

**Comment by honggyukim** [comment]
> We might consider to drop script support at record. @honggyukim wdyt?

Sorry for the late response. I think disabling the entire record time script is not a good idea. How about just dropping floating point argument handling instead?

**Comment by truboxl** [comment]
Btw I think 32bit build need this: https://github.com/termux/termux-packages/pull/18963
Credit to @2096779623

**Comment by namhyung** [comment]
Sure, can you please send a PR?

**Comment by namhyung** [comment]
> How about just dropping floating point argument handling instead?

Something like [check/mcount-nofp](../compare/check/mcount-nofp)?

But I'm not sure if it's ok we leave it as a half-broken state with FP/SIMD.

**Comment by namhyung** [comment]
I'm seeing build errors with v0.15.1 on old distros like CentOS 8.

```
  CC FPIC  libmcount/event.op
In file included from /usr/include/stdlib.h:1010,
                 from /uftrace/libmcount/event.c:4:
/usr/include/bits/stdlib-float.h: In function 'atof':
/usr/include/bits/stdlib-float.h:26:1: error: SSE register return with SSE disabled
 {
 ^
```
