### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [namhyung/uftrace#188]
Would you like to [replace any double quotes](https://github.com/namhyung/uftrace/blob/bf488d9bcaf9ca109c755468c8332be406710cee/uftrace.h#L10 "Check inclusion style") by [angle brackets around file names for include statements](https://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename "What is the difference between #include <filename> and #include “filename”?")?

**Comment by namhyung** [comment]
Why?

My understanding is that `#include <...>` is for header files provided by system and `#include "..."` is for uftrace headers.  So I used `-iquote` compiler option to add search path for the latter.

**Comment by elfring** [comment]
I suggest to reconsider the consequences of [the following wording](http://c0x.coding-guidelines.com/6.10.2.html "Source file inclusion") from [the section “16.2 Source file inclusion”](http://open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3797.pdf "Draft for the C++ standard specification") in the standard specification for the programming language “C++”.

```
…
The named source file is searched for in an implementation-defined manner. If this search is not supported, or if the search fails, the directive is reprocessed as if it read

#include <h-char-sequence> new-line
…
```
- How do you think about to avoid “a duplicated file search” here?
- Would you like to [restrict the searched directories](https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html "Description for include syntax") for header files of your software?

**Comment by elfring** [comment]
How do you think about to move any program parts into additional software libraries?

**Comment by namhyung** [comment]
I don't follow, could you please elaborate?

**Comment by elfring** [comment]
Would you like to distinguish any more if involved software components will be reused by static or dynamic bindings to other libraries?
* [Event](https://github.com/namhyung/uftrace/blob/452b2fbc9233519346b0590b74f31fb4530048bb/libtraceevent/event-parse.h#L2 "libtraceevent from Linux")
* [List](https://github.com/namhyung/uftrace/blob/5cd40f20d8a9ff9eaa25b2235ee492433e9656ad/utils/list.h#L1 "Simple doubly linked list from Linux")
* [Red-black tree](https://github.com/namhyung/uftrace/blob/5cd40f20d8a9ff9eaa25b2235ee492433e9656ad/utils/rbtree.h#L2 "Red-black tree from Linux")
* [mcount](https://github.com/namhyung/uftrace/blob/574f97660f8ea9eec39fcd91d74ea87a6fa9524c/libmcount/mcount.h "Data structures for handling mcount records")

**Comment by namhyung** [comment]
The libtraceevent is a separate library maintained in the kernel source tree but it's not distributed publicly yet so I copied the source code for now.  I'm waiting for Steven to find enough time doing that work.

The libmcount is also built as a library.  It's only used by uftrace and I don't think other tools need it.

The others are general data structure and copied from the kernel source code.  I'm not sure it's worth for me to make them into a library.

**Comment by elfring** [comment]
>I copied the source code for now.

I find that this information triggers important software development consequences.
How much do you care for further evolution of bundled components?


>The libmcount is also built as a library.

How do you think about to make it configurable if it will be used as a shared software library?


>I'm not sure it's worth for me to make them into a library.

I guess that this aspect can evolve further according to the mentioned combination of static (or dynamic) bindings.

**Comment by namhyung** [comment]
> I find that this information triggers important software development consequences.
How much do you care for further evolution of bundled components?

I do care about the changes in libtraceevent, but it's not released so there's not much thing I can do.

> How do you think about to make it configurable if it will be used as a shared software library?

As I said, the libmcount is designed for uftrace specifically.

> I guess that this aspect can evolve further according to the mentioned combination of static (or dynamic) bindings.

Well, it's not my code and I know there's a similar library.  But I didn't use it since it's a bit hard to use and deploy.
