### ISSUE TITLE
python tracing failure with RuntimeError: Too many open files

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#1886]
This python code is based on a GPT generated script, but removed some unuseful parts for this issue.
```py
$ cat cnn-image.py
#!/usr/bin/env python3

import torch
import torchvision
import torchvision.transforms as transforms

# Step 1: Load and Normalize CIFAR-10 Data
transform = transforms.Compose(
    [transforms.ToTensor(),
     transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])

trainset = torchvision.datasets.CIFAR10(root='./data', train=True,
                                        download=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=4,
                                          shuffle=True, num_workers=2)

# Step 4: Train the network
for epoch in range(2):  # loop over the dataset multiple times
    running_loss = 0.0
    for i, data in enumerate(trainloader, 0):
        pass
```
This can be normally executed.
```
$ chmod +x cnn-image.py
$ ./cnn-image.py
Files already downloaded and verified
```
But it shows `RuntimeError: Too many open files` when running with uftrace as follows.
```
$ uftrace record ./cnn-image.py
Files already downloaded and verified
WARN: unpaired cygprof exit: dropping...
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/honggyu/usr/lib/uftrace/uftrace.py", line 42, in <module>
    exec(code, new_globals)
  File "<string>", line 20, in <module>
  File "/home/honggyu/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/honggyu/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1328, in _next_data
    idx, data = self._get_data()
  File "/home/honggyu/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1294, in _get_data
    success, data = self._try_get_data()
  File "/home/honggyu/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1159, in _try_get_data
    raise RuntimeError(
RuntimeError: Too many open files. Communication with the workers is no longer possible. Please increase the limit using `ulimit -n` in the shell or change the sharing strategy by calling `torch.multiprocessing.set_sharing_strategy('file_system')` at the beginning of your code
```

**Comment by honggyukim** [comment]
Just to give more info, removing the following last 2 lines makes the uftrace tracing fine.
```py
    for i, data in enumerate(trainloader, 0):
        pass
```

**Comment by yihong0618** [comment]
@honggyukim 
add these lines worked for `uftrace`

https://github.com/pytorch/pytorch/issues/11201


$ cat cnn-image.py
#!/usr/bin/env python3

import torch
import torchvision
import torchvision.transforms as transforms
import torch.multiprocessing
torch.multiprocessing.set_sharing_strategy('file_system')

# Step 1: Load and Normalize CIFAR-10 Data
transform = transforms.Compose(
    [transforms.ToTensor(),
     transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])

trainset = torchvision.datasets.CIFAR10(root='./data', train=True,
                                        download=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=4,
                                          shuffle=True, num_workers=2)

# Step 4: Train the network
for epoch in range(2):  # loop over the dataset multiple times
    running_loss = 0.0
    for i, data in enumerate(trainloader, 0):
        pass

**Comment by honggyukim** [comment]
Hi @yihong0618, thanks for sharing the tip. Do you mean the comment at https://github.com/pytorch/pytorch/issues/11201#issuecomment-421146936?

I also see that uftrace tracing works fine with `torch.multiprocessing.set_sharing_strategy('file_system')`, but it used to work without uftrace. We can't force users modify their code for uftrace tracing. Do you have any other idea?

**Comment by yihong0618** [comment]
will check it these days

**Comment by yihong0618** [comment]
@honggyukim @namhyung

after some dig its not torch file sharing_strategy caused this problem but `uftrace` python side.

How to find the problem.

1. uftrace cnn-image.py but `./cnn-image.py ` can work perfectly
2. maybe the uftrace and shebang run do not use the same strategy, I added this line `from torch.multiprocessing import get_sharing_strategy
print(get_sharing_strategy())` in front of  cnn-image.py but they all get `file_descriptor` output
3. so I guess some fd do not close but why?
4. I added these two line in torch lib(lib/python3.11/site-packages/torch/utils/data/dataloader.py) 
![image](https://github.com/namhyung/uftrace/assets/15976103/064e173e-c554-4067-b6a1-aff5ffdafc29)
```python
from test.support.os_helper import fd_count
print("!!", fd_count())
```
for uftrace side, it keeps increasing but for `shebang` run it keeps the same
![image](https://github.com/namhyung/uftrace/assets/15976103/001663d1-2442-4498-a5f9-986739d3fd31)
![image](https://github.com/namhyung/uftrace/assets/15976103/daa1f814-7a87-4397-b5e3-a6352d4c816e)

5. so I guessed it maybe the `gc` did not run correctly in `uftrace` side.
6. After some dig, just found that the `code Object` all keeps in the `rb tree` so the `gc` only run after uftrace done
```
	while (*p) {
		parent = *p;
		iter = rb_entry(parent, struct uftrace_python_symbol, node);

		/* just compare pointers of the code object */
		if (iter->code == code) {
			Py_DECREF(code);
			return iter;
		}

		if (iter->code < code)
			p = &parent->rb_left;
		else
			p = &parent->rb_right;
	}

/////// all the code object keep here
	new_sym = xmalloc(sizeof(*new_sym));
	new_sym->code = code;
	new_sym->addr = get_new_sym_addr(func_name, !is_main);
	new_sym->name = func_name;
	new_sym->flag = is_main ? 0 : UFT_PYSYM_F_LIBCALL;
```
so I did some change that we can not store the `code object` in uftrace_python_symbol, and it worked perpectly.

I would like open a PR about this change, but the code side maybe need some work to change, you can do more commit or other better ways to fix it.

**Comment by namhyung** [comment]
Thanks a lot for your detailed analysis and PR!  I never thought keeping code objects would hold file descriptors and result in the error.
