### ISSUE TITLE
How can i  to build   uftrace  with  mingw64 toolchain？

### ISSUE THREAD

**Issue by myseemylife** [namhyung/uftrace#1889]
Hi ~ 
I want to find a profile tool to analysis my c++ project which build by mingw64 toolchain~
Does uftrace fits my way?

**Comment by namhyung** [comment]
Hello, by using mingw64 I guess it runs on Windows environment not WSL?  I'm not sure but I don't think it would run properly due to difference in OS and runtime support.  Does it support `LD_PRELOAD` and POSIX shmem among other things?

**Comment by honggyukim** [comment]
I remember the executable binary in mingw64 is Windows PE format, not Linux ELF. If so, uftrace can't support it.

**Comment by myseemylife** [comment]
thxs all ~ i found another lib which name is minitrace  can help!

**Comment by honggyukim** [comment]
You mean minitrace at https://github.com/hrydgard/minitrace? That looks easy to use. Thanks for sharing the info.
