### ISSUE TITLE
How to use flame graph?

### ISSUE THREAD

**Issue by zszdsze** [namhyung/uftrace#1893]
I use uftrace dump --flame-graph to generate the data. Could you please tell me how to use the dump output to generate the svg file? Thank you!

**Comment by namhyung** [comment]
Hello, you need the flame graph script: https://github.com/brendangregg/FlameGraph.  Then run like this.

    $ uftrace dump --flame-graph | ./flamegraph.pl > output.svg
    
    $ firefox output.svg

**Comment by zszdsze** [comment]
It works! Thanks a lot!

**Comment by namhyung** [comment]
No problem!
