### ISSUE TITLE
-O2: WARN: cannot open record data: /tmp/uftrace-live-7dmS9x: No data available

### ISSUE THREAD

**Issue by vt-alt** [namhyung/uftrace#1894]
While testing separate-dwarf feature I noticed that uftrace sometimes not able to trace binaries compiled with `-O2` without any explanation. (I found minimal example that does not trace even with `-O0`):
```
$ cat a.c
#include <unistd.h>
int main(int argc, char **argv)
{
        _exit(0);
}
$ gcc -O2 -g a.c -o a
$ uftrace -P. ./a
WARN: cannot open record data: /tmp/uftrace-live-dzzwyD: No data available
```
But aren't there is at least a `main` call?
`strace -k` show there is `_exit` and `main` in backtrace:
```
strace -k ./a
...
exit_group(0)                           = ?
+++ exited with 0 +++
 > /lib64/libc.so.6(_exit+0x15) [0xd6575]
 > /home/vt/src/uftrace/a(main+0xc) [0x105c]
 > /lib64/libc.so.6(__libc_start_call_main+0x7b) [0x27c8b]
 > /lib64/libc.so.6(__libc_start_main@@GLIBC_2.34+0x84) [0x27d44]
 > /home/vt/src/uftrace/a(_start+0x20) [0x1080]
```
Also, gdb is able to stop at `main` so the symbols is there:
```
$ gdb -q ./a
Reading symbols from ./a...
(gdb) b main
Breakpoint 1 at 0x1050: file a.c, line 3.
(gdb) r
Starting program: /home/vt/src/uftrace/a
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
=> 0x555555555050 <main>:       push   %rax

Breakpoint 1, main (argc=1, argv=0x7fffffffd9a8) at a.c:3
3       {
(gdb) quit
```
While this simple case is not useful in itself (except as an example) I fear it would miss some calls for a normal tracing, because `-O2` compilation is very common.

**Comment by vt-alt** [comment]
Yes my example is just minified but maybe I minified it too much. I found it first with `rpm --querytags`:
```
$ uftrace -P. rpm --querytags
...
WARN: cannot open record data: /tmp/uftrace-live-LsgHZR: No data available
```
Also with this example code:
```
$ cat a.c
void foo(int a) { }
int main(int argc, char **argv)
{
        foo(1);
        return 0;
}
$ gcc -O1 -g -o a a.c
$ uftrace -P. ./a
# DURATION     TID     FUNCTION
   0.282 us [3595069] | main();
$ gcc -O2 -g -o a a.c
$ uftrace -P. ./a
WARN: cannot open record data: /tmp/uftrace-live-KKs2Bq: No data available
```
Yes `foo` is optimized out for `-O2` (and gdb does not break there) but `main` is still there (gdb breaks there).

**Comment by namhyung** [comment]
Can you share the disassembly of the `main` function with `-O2`?  I'm curious if it has `ret` instruction at the end.

**Comment by namhyung** [comment]
Thanks for sharing this.  You're right, it's too short.  The dynamic tracing (on x86) requires functions at least 5 byte long (that's the size of `call` instruction).

**Comment by vt-alt** [comment]
Thanks for clarification!
