### ISSUE TITLE
Support standard deviation(STDDEV) in report output

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#1897]
The current report output provides AVG, MIN, MAX for each TOTAL and SELF time. It'd be also useful to provide STDDEV for standard deviation.

The STDDEV can be added to report command and report mode in tui command together.

**Comment by honggyukim** [comment]
The downside of calculating STDDEV is it requires more calculation and we need to think about how to minimize the calculation overhead.

**Comment by namhyung** [comment]
In the perf tool, it does like this: https://elixir.bootlin.com/linux/v6.7/source/tools/perf/util/stat.c#L57

**Comment by ziming-zh** [comment]
Hello @namhyung @honggyukim ,

I am a student enrolled in the EECS 481 Software Engineering course at the University of Michigan. I am particularly interested in the enhancement you've discussed regarding the addition of a standard deviation (STDDEV) calculation for TOTAL and SELF time metrics.

Our approach would involve:

- Integrating the STDDEV calculation in both report command and report mode in the TUI command, ensuring consistency across the tool.
- Compute performance metrics to quantify the computational overhead introduced by the STDDEV calculation.
- Exploring optimization techniques (e.g., using efficient algorithms for variance computation that minimize additional passes over the data) to mitigate any identified performance impacts.

We are eager to contribute to your project and would greatly appreciate your feedback on our proposal. Would it be possible for us to work on this issue as part of our course project?

**Comment by namhyung** [comment]
Hello @ziming-zh sorry for the late reply.  I'm more than happy if you can take this item.  Go ahead!

**Comment by honggyukim** [comment]
Hi @ziming-zh, Please go ahead and let us know if you have some issues. Thank you!

**Comment by ziming-zh** [comment]
Hi @namhyung @honggyukim, I have tried to support STDDEV calculation in #1913. Please help review and let me know if you prefer any revisions. It's such a nice project and thank you for your encouragement to let me go ahead!

**Comment by honggyukim** [comment]
Hi @ziming-zh, thanks for your work and encouraged message! I don't have enough time these days but I will have a look when I have some time.

**Comment by ziming-zh** [comment]
Sorry that I did not pay attention to the sort module and the misalignment issue. Thank you for fixing that! @namhyung

**Comment by namhyung** [comment]
No problem!  Thanks for your work and it was a good contribution. :)
