### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [namhyung/uftrace#190]
The function “[pr_warn](https://github.com/namhyung/uftrace/blob/66d5e54ce3f132a962ef30747ad6c1d212297f9c/utils/utils.h#L130 "Logging functions")” does not belong to the list of [async-signal-safe functions](https://www.securecoding.cert.org/confluence/display/c/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers "Call only asynchronous-safe functions within signal handlers").
I guess that a different program design will be needed for your function “[sigsegv_handler](https://github.com/namhyung/uftrace/blob/a1c8472545be0248fa42ec984025a43dca0ade69/cmd-live.c#L62 "Update candidate")”.

**Comment by namhyung** [comment]
You're right.  But SIGSEGV will terminate the process eventually so I don't care about the async-signal-safety, thanks.

**Comment by elfring** [comment]
I would appreciate if software correctness will be taken into account a bit more also at such a place.

**Comment by namhyung** [comment]
I'd be happy to see the patch. :)

**Comment by elfring** [comment]
Would you like to consider other software design options?
- [sigwaitinfo()](http://pubs.opengroup.org/onlinepubs/9699919799/functions/sigwaitinfo.html "Wait for queued signals")
- [Self-pipe trick](http://cr.yp.to/docs/selfpipe.html "The self-pipe trick")
- [Signal-safe locks](https://locklessinc.com/articles/signalsafe_locks/ "Description for signal-safe locks")

**Comment by namhyung** [comment]
The signal-safe lock would be too heavy to be used for stdout/stderr.  I don't know how to apply other two for the SIGSEGV handler.

**Comment by elfring** [comment]
* Is the traced software executed in a separate process?
* How much will the tracing software still work after it was notified about a questionable memory access?

**Comment by namhyung** [comment]
Yes, uftrace traces a child process with libmcount preloaded so SIGSEGV will be handled in a separate process.  I think the child normally will be terminated as soon as it gets the signal.

**Comment by elfring** [comment]
Would you like to improve process communication in any ways?

**Comment by namhyung** [comment]
Of course! :)

**Comment by elfring** [comment]
How do you think about to [concentrate signal handling in a corresponding thread](https://stackoverflow.com/questions/11679568/signal-handling-with-multiple-threads-in-linux "Signal handling with multiple threads in Linux")?

**Comment by namhyung** [comment]
It already blocks signals in writer threads so the main thread will get signals only.

**Comment by elfring** [comment]
* In which time ranges can this “main thread” respond to system changes because of signals?
* Which source file does contain its implementation?

**Comment by namhyung** [comment]
> In which time ranges can this “main thread” respond to system changes because of signals?

For the whole recording time.

> Which source file does contain its implementation?

https://github.com/namhyung/uftrace/blob/master/cmd-record.c#L565

**Comment by elfring** [comment]
>For the whole recording time.

I imagine that the software responsiveness can be still improved by an other application design.

:crystal_ball: Are you willing do [dedicate a thread only for signal handling](https://www.linuxprogrammingblog.com/all-about-linux-signals?page=7 "Article section “Waiting for a signal” (from 2009-03-02) by Damian Pietras") (besides the main task execution)?

**Comment by namhyung** [comment]
I don't think it's needed since the signal delivery should be exceptional and not expected in most of time.

**Comment by elfring** [comment]
I can imagine that we would usually like to invest software development capacity into more interesting functionality. But I hope that a consensus could be achieved on an adjusted program structure where the task distribution will be really safe for better software components.

**Comment by namhyung** [comment]
The only signal it cares is SIGCHLD which should be delivered once a child exits.  Maybe it needs to use the self-pipe trick you mentioned, thanks.

**Comment by elfring** [comment]
* Special constraints need to be considered also for [the self-pipe trick](http://cr.yp.to/docs/selfpipe.html "Description for a “trick”").
* Will [a design approach based on the function “sigwaitinfo”](https://stackoverflow.com/questions/21552600/sigwait-and-signal-handler "sigwait() and signal handler") be easier and safer?

**Comment by namhyung** [comment]
It seems sigwaitinfo() needs a dedicated thread which I don't want.

**Comment by elfring** [comment]
It seems that you are used to working with additional threads already.
Why would you like to exclude software design options around the function “sigwaitinfo” then?

**Comment by namhyung** [comment]
It does have a couple of writer threads but I don't want to block them to handle signals.

**Comment by elfring** [comment]
Would you like to explain your software development concerns a bit more for this use case?

**Comment by namhyung** [comment]
Not to waste resource by a new thread only for signal handling - it's already handled in the main thread and I don't find any problem for now.

**Comment by elfring** [comment]
>Not to waste resource by a new thread only for signal handling

This thread will fulfil an useful task while “the main thread” will be busy with other work.


>… I don't find any problem for now.

I pointed open issues out for this implementation detail. Do you become any more aware about the dependencies in the available software design choices for this use case?

**Comment by namhyung** [comment]
> This thread will fulfil an useful task while “the main thread” will be busy with other work.

The main thread will wait for incoming messages and signals.

**Comment by elfring** [comment]
>The main thread will wait for incoming messages and signals.

I suggest to assign separate execution units to these tasks.
How can we distinguish better between involved items?

**Comment by namhyung** [comment]
> I suggest to assign separate execution units to these tasks.

Why?  That's the only thing the main thread does.

**Comment by elfring** [comment]
How would you like to receive signals in a safe way?

**Comment by namhyung** [comment]
I cannot find a problem in the current implementation - which part do you think it's unsafe?

**Comment by elfring** [comment]
Examples for further considerations:
* The implementation of the function “sigsegv_handler” is broken.
* [The variable “`child_exited`”](https://github.com/namhyung/uftrace/blob/7022f1a8c90f43e07045ad2201aeb503db68e062/cmd-record.c#L1317 "Update candidate") should [use the data type "`sig_atomic_t`"](https://www.securecoding.cert.org/confluence/display/c/SIG31-C.+Do+not+access+shared+objects+in+signal+handlers "Description for usage of sig_atomic_t") (instead of “`bool`”).

**Comment by namhyung** [comment]
Practically I don't think they'll cause a problem but I'm ok with removing `pr_warn()` in `sigsegv_handler()` and changing to `sig_atomic_t` if you want, thanks.

**Comment by elfring** [comment]
* Can you ever implement the function “sigsegv_handler” in a way which would be safe and be also better than the default system configuration?
* I would appreciate if the data type “`bool`” will be replaced by “`sig_atomic_t`” for the variable “`child_exited`” according to the current software design approach. But I wonder [if this variable will ever be checked in the current source code](https://github.com/namhyung/uftrace/search?q=child_exited "Checking the usage of a variable"). Is it not used in a way so far that could be desirable?

**Comment by namhyung** [comment]
It seems github search is broken:
https://github.com/namhyung/uftrace/blob/master/cmd-record.c#L1657

**Comment by elfring** [comment]
>It seems github search is broken:

I'm sorry that I got an inappropriate impression for a moment about the usage of this variable.
Do you care for [a corresponding check frequency](https://github.com/namhyung/uftrace/blob/7022f1a8c90f43e07045ad2201aeb503db68e062/cmd-record.c#L1625 "Implementation of stop_tracing()")?

**Comment by namhyung** [comment]
The "child_exit" variable is only checked once after main loop that means either child was exited or user want to quit.

**Comment by elfring** [comment]
I find that proper signal handling would mean that such status variables will be checked more often so that involved software dependencies can be kept consistent.
🔮 Would you like to achieve the immediate data processing for all “notifications” which your programs might receive?

**Comment by namhyung** [comment]
No I only need it just to check exit status of child.  So doing it at the end of the loop looks enough IMHO.

**Comment by elfring** [comment]
* In which time frame would you like to notice that a child process terminated for any reason?
* Can it make sense to react to changes in the software run time situation quicker?

**Comment by namhyung** [comment]
It doesn't need to be noticed quickly when child died.  It reads the exit status after writing all remaining data in a pipe.

**Comment by elfring** [comment]
>It reads the exit status after writing all remaining data in a pipe.

Do you care to cancel such data processing quicker?

**Comment by namhyung** [comment]
Nope.
