### ISSUE TITLE
add compact diff policy

### ISSUE THREAD

**Issue by namhyung** [namhyung/uftrace#191]
Current report diff output is too verbose as it includes the original data of both data also.  But users may want to focus on differences only.  So let's add "compact" policy for report diff.  The orignal behavior can be requested by "full" policy (and it's the default now) and I'm considering change default to "compact".

The code is avaiable at [review/diff-compact-v1](https://github.com/namhyung/uftrace/compare/review/diff-compact-v1).

```
$ uftrace record -d xxx tests/t-diff 0
$ uftrace record -d yyy tests/t-diff 1

$ uftrace report --data xxx --diff yyy --diff-policy compact
#
# uftrace diff
#  [0] base: xxx   (from uftrace record -d xxx -F main tests/t-diff 0 )
#  [1] diff: yyy   (from uftrace record -d yyy -F main tests/t-diff 1 )
#
   Total time     Self time         Calls   Function
  ===========   ===========   ===========   ================================================
    +0.027 us     +0.027 us             0   atoi
  +158.853 us     +1.319 us             0   bar
    +1.235 ms     +2.749 us             0   foo
    +1.305 ms     +0.319 us             0   main
    +1.300 ms     +1.300 ms            +3   usleep
```

**Comment by honggyukim** [comment]
I think it's very good to show only the difference. I know that current percentage output may have some problem but what about adding diff percentage as well?

**Comment by namhyung** [comment]
Do you mean compact percentage output?  It's already supported by `--diff-policy compact,percent`.

```
$ uftrace report -d xxx --diff yyy --diff-policy compact,percent
#
# uftrace diff
#  [0] base: xxx        (from /home/namhyung/project/uftrace/uftrace -L /home/namhyung/project/uftrace record -d xxx /home/namhyung/project/uftrace/tests/t-diff 0 )
#  [1] diff: yyy        (from /home/namhyung/project/uftrace/uftrace -L /home/namhyung/project/uftrace record -d yyy /home/namhyung/project/uftrace/tests/t-diff 1 )
#
   Total time     Self time         Calls   Function
  ===========   ===========   ===========   ================================================
     +999.99%      +999.99%            +3   usleep
     +999.99%      +418.39%             0   foo
     +999.99%      +897.70%             0   bar
     +999.99%       -27.92%             0   main
      -56.24%       -56.24%             0   atoi
```

**Comment by namhyung** [comment]
Do you agree with changing the default?

Here is the [review/diff-compact-v2](https://github.com/namhyung/uftrace/compare/review/diff-compact-v2) changed to show "N/A" for new (or removed) entries.

```
$ uftrace report -d xxx --diff yyy --diff-policy compact,percent
#
# uftrace diff
#  [0] base: xxx        (from /home/namhyung/project/uftrace/uftrace -L /home/namhyung/project/uftrace record -d xxx /home/namhyung/project/uftrace/tests/t-diff 0 )
#  [1] diff: yyy        (from /home/namhyung/project/uftrace/uftrace -L /home/namhyung/project/uftrace record -d yyy /home/namhyung/project/uftrace/tests/t-diff 1 )
#
   Total time     Self time         Calls   Function
  ===========   ===========   ===========   ================================================
         N/A           N/A             +3   usleep
     +999.99%      +418.39%             0   foo
     +999.99%      +897.70%             0   bar
     +999.99%       -27.92%             0   main
      -56.24%       -56.24%             0   atoi
```

**Comment by honggyukim** [comment]
> Do you mean compact percentage output? It's already supported by --diff-policy compact,percent.

I meant showing the difference and percentage together side by side would be good. In other words, `--diff-policy compact` can include both `abs` and `percent`.

**Comment by honggyukim** [comment]
I think it's good for `N/A` but `Calls` field may be changed a bit.
* Current
```
   Total time     Self time         Calls   Function
  ===========   ===========   ===========   ================================================
         N/A           N/A             +3   usleep
     +999.99%      +418.39%             0   foo
```
* My suggestion
```
   Total time     Self time         Calls   Function
  ===========   ===========   ===========   ================================================
         N/A           N/A             +3   usleep
     +999.99%      +418.39%             -   foo
```
`0` can be represented as the function is not called at all so it can be `-` to say there's no difference in the number of calls.

**Comment by namhyung** [comment]
> I meant showing the difference and percentage together side by side would be good. In other words, --diff-policy compact can include both abs and percent.

Hmm.. it won't be compact anymore. ;-)

> 0 can be represented as the function is not called at all so it can be - to say there's no difference in the number of calls. Otherwise, we can also use . literal instead of -.

Well, I could parse it the opposite way..  What about using `+0`?

**Comment by honggyukim** [comment]
>> I meant showing the difference and percentage together side by side would be good. In other words, --diff-policy compact can include both abs and percent.

> Hmm.. it won't be compact anymore. ;-)

Yes, it could be. And what about using `diff` or `diff-only` instead of `compact`?

>> 0 can be represented as the function is not called at all so it can be - to say there's no difference in the number of calls. Otherwise, we can also use . literal instead of -.

> Well, I could parse it the opposite way.. What about using +0?

`+0` sounds good to me!

**Comment by namhyung** [comment]
> And what about using diff or diff-only instead of compact?

`--diff-policy diff` seems not good IMHO.

**Comment by honggyukim** [comment]
Then using `--diff-policy compact` and `+0` is okay for me.

**Comment by namhyung** [comment]
Pushed [reivew/diff-compact-v3](https://github.com/namhyung/uftrace/compare/review/diff-compact-v3).

Changelog:
* show "+0" when call count is same
* update manpage

**Comment by namhyung** [comment]
What do you think about making "compact" as default?  I saw your presentation about the diff, and I think it'd be nice if it was compact format.

**Comment by honggyukim** [comment]
I also think that compact maybe better by default. And what about making "Function" field shorter?
Before:
```
   Total time     Self time         Calls   Function
  ===========   ===========   ===========   ================================================
    +1.327 ms     +0.812 us            +0   main
    +1.325 ms     +1.325 ms            +3   usleep
    +1.256 ms     +1.265 us            +0   foo
  +156.412 us     +0.650 us            +0   bar
    +0.051 us     +0.051 us            +0   atoi
```
After:
```
   Total time     Self time         Calls   Function
  ===========   ===========   ===========   ========================
    +1.327 ms     +0.812 us            +0   main
    +1.325 ms     +1.325 ms            +3   usleep
    +1.256 ms     +1.265 us            +0   foo
  +156.412 us     +0.650 us            +0   bar
    +0.051 us     +0.051 us            +0   atoi
```
If you make it smarter, let's find the maximum length of "Function" then draw "===" accordingly.

**Comment by namhyung** [comment]
> I also think that compact maybe better by default. 

OK.

> If you make it smarter, let's find the maximum length of "Function" then draw "===" accordingly.

That would be nice, but I think it needs some limit since C++ symbols can be very long..

**Comment by honggyukim** [comment]
> That would be nice, but I think it needs some limit since C++ symbols can be very long..

I think we could set the minimum and maximum length for that case. Thanks!

**Comment by namhyung** [comment]
Pushed [review/diff-compact-v4](https://github.com/namhyung/uftrace/compare/review/diff-compact-v4).

Changelog:
* make "compact" as default
* adjust length of "Function" column

**Comment by honggyukim** [comment]
Thanks for fixing column length. By the way, is this the expected output:
```
$ uftrace report -d yyy --diff xxx -s self
#
# uftrace diff
#  [0] base: yyy        (from uftrace --no-pager -L.. record -d yyy -F main t-diff 1 )
#  [1] diff: xxx        (from uftrace --no-pager -L.. record -d xxx -F main t-diff 2 )
#
   Total time     Self time         Calls   Function
  ===========   ===========   ===========   ====================
    +5.514 us     +5.514 us            +0   usleep
    +5.718 us     +0.329 us            +0   main
    -1.433 us     -0.117 us            +0   bar
    +5.337 us     -0.032 us            +0   foo
    +0.024 us     +0.024 us            +0   atoi

$ uftrace report -d yyy -s self
  Total time   Self time       Calls  Function
  ==========  ==========  ==========  ====================
    1.273 ms    1.273 ms           3  usleep
    1.276 ms    1.373 us           1  main
    1.211 ms    0.915 us           1  foo
  153.361 us    0.493 us           1  bar
    0.362 us    0.362 us           1  atoi

$ uftrace report -d xxx -s self
  Total time   Self time       Calls  Function
  ==========  ==========  ==========  ====================
    1.278 ms    1.278 ms           3  usleep
    1.281 ms    1.702 us           1  main
    1.216 ms    0.883 us           1  foo
    0.386 us    0.386 us           1  atoi
  151.928 us    0.376 us           1  bar
```
It seems that `-s/--sort` option in diff mode automatically applies to diff result by default.

**Comment by namhyung** [comment]
Right, isn't it natural?

**Comment by honggyukim** [comment]
Yes, I think it looks natural. :)
