### ISSUE TITLE
[Linux_terminal] Uftrace manual

### ISSUE THREAD

**Issue by rjs1197** [namhyung/uftrace#192]
Can I take a menual in Linux terminal?

Can`t input '> man uftrace'.

Could you tell me how to call menual?

**Comment by honggyukim** [comment]
Hi @rjs1197,

You can see the manuals for each uftrace commands as follows:
```
$ man uftrace
$ man uftrace record
$ man uftrace replay
$ man uftrace live
$ man uftrace report
$ man uftrace info
$ man uftrace dump
$ man uftrace recv
$ man uftrace graph
$ man uftrace script
```
Please let me know if you need something else.

**Comment by rjs1197** [comment]
Thanks for comments. but, i can`t this command. 

As shown below.

`$ man uftrace`  
`No manual entry for uftrace`  
`See 'man 7 undocumented' for help when manual pages are not available.`

do you know How to fixed this problem?

**Comment by honggyukim** [comment]
Did you run `make install`?

**Comment by rjs1197** [comment]
thank you for answer. :) :100:
