### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [namhyung/uftrace#194]
Would you like to add more error handling for return values from functions like the following?
- [fopen](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fopen.html "Open a stream.") ⇒ [Test case: task_symbol](https://github.com/namhyung/uftrace/blob/86b6701263c1a70a7599dbf16714812d16ada73b/utils/session.c#L896)
- [printf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html "Print formatted output.") ⇒ [print_symtabs](https://github.com/namhyung/uftrace/blob/86b6701263c1a70a7599dbf16714812d16ada73b/utils/symbol.c#L1608)

**Comment by namhyung** [comment]
It'd make the Coverity Scan (or other checkers) happy.  Please send a PR to fix them.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by namhyung** [comment]
Yes, do you have a (automatic) checker for it?

**Comment by elfring** [comment]
- How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for static code analysis") also for your software?
- Are you interested to apply [aspect-oriented software development](https://aspectc.org/ "Software development with AspectC++")?
  
  How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](https://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by namhyung** [comment]
I already use the Coverity scan.  If you could send a patch for AOP, I'd like to take a look at it, thanks.

**Comment by elfring** [comment]
I am also curious then how this software will evolve further because of [source code analysis results by the tool “Coverity Scan”](https://scan.coverity.com/projects/namhyung-uftrace "Analysis results by Coverity").
Does this tool indicate any unchecked return values for POSIX functions at the moment?


Are you familiar with other approaches like aspect-oriented software development?

**Comment by namhyung** [comment]
> Does this tool indicate any unchecked return values for POSIX functions at the moment?

It does AFAIK (at least for some functions).

> Are you familiar with other approaches like aspect-oriented software development?

No.

**Comment by elfring** [comment]
>It does AFAIK (at least for some functions).

How would you like to tackle these open issues?


>No.

How do you think about to extend your knowledge also around aspect-oriented software development?

**Comment by namhyung** [comment]
I'll try to fix open issues and learn AOSD when I find some time.

**Comment by elfring** [comment]
The error detection and corresponding exception handling is still incomplete at source code places like the following.
- [pthread_create](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_create.html "Thread creation") ⇒ [start_tracing](https://github.com/namhyung/uftrace/blob/06ee8d6a770dfa569ac259a06badfc48f79dd66b/cmd-record.c#L1586)
- [__PyDict_New](https://docs.python.org/3/c-api/dict.html#c.PyDict_New "Dictionary creation") ⇒ [python_uftrace_begin](https://github.com/namhyung/uftrace/compare/review/script-info-v2#diff-6453549489d5c9d48d7f99783475b187R482)

**Comment by elfring** [comment]
[The implementation of a function like “tui_search_start”](https://github.com/namhyung/uftrace/compare/review/tui-support-v1#diff-c25c8f3b092cf79c23a41ad3531a8687R1442 "Update candidate: tui_search_start()") is also [incomplete so far](http://pubs.opengroup.org/onlinepubs/7908799/xcurses/derwin.html "Checking return values from window creation functions").
