### ISSUE TITLE
Check usage status of special program information

### ISSUE THREAD

**Issue by elfring** [namhyung/uftrace#195]
[Two variables](https://github.com/namhyung/uftrace/blob/55ee3007c44ff1c833b166ff5256201011137f66/uftrace.c#L42 "Delete argp_program_…?") are not read so far after they were initialised. Thus I suggest to delete them.

**Comment by namhyung** [comment]
They are used by the argp implementation.

https://www.gnu.org/software/libc/manual/html_node/Argp-Global-Variables.html#Argp-Global-Variables

**Comment by elfring** [comment]
I am sorry that I overlooked [this implementation detail](https://github.com/namhyung/uftrace/blob/2c31928910fb4a03ee00338f99339a96ba1c5ae5/cmd-info.c#L908 "Using command_info()").

Would it make sense to move these variables closer to the relevant header file inclusion?

**Comment by namhyung** [comment]
They are already at the top of the file.  Maybe you want the following:

```
diff --git a/uftrace.c b/uftrace.c
index fa13899..4a06fa6 100644
--- a/uftrace.c
+++ b/uftrace.c
@@ -39,7 +39,10 @@
 #include "utils/fstack.h"
 #include "utils/filter.h"
 
+/* output of --version option (generated by argp runtime) */
 const char *argp_program_version = "uftrace " UFTRACE_VERSION;
+
+/* (a part of) output in --help option (generated by argp runtime) */
 const char *argp_program_bug_address = "https://github.com/namhyung/uftrace/issues";
 
 static bool dbg_domain_set = false;
```

**Comment by elfring** [comment]
Yes, in principle. - Your change example would be nice.

Can [the relationship with the Argp software](https://www.gnu.org/software/libc/manual/html_node/Argp.html "Parsing program options with Argp") become also obvious if the corresponding include statement will be placed directly besides these variables (instead of a duplicate comment)?

**Comment by namhyung** [comment]
That would be a coding style choice.  I'd like to keep header files (system and uftrace) together before statements.
