### ISSUE TITLE
Support for special configuration options around data export

### ISSUE THREAD

**Issue by elfring** [namhyung/uftrace#196]
[Tabular display](https://github.com/namhyung/uftrace/wiki/Tutorial "Basic usage of the uftrace tool") is offered by the program for some data.

It would be occasionally nice to [get the determined data in formats](https://en.wikipedia.org/wiki/Comparison_of_data_serialization_formats "Comparison of data serialization formats") with which further processing is easier.
* CSV
* JSON
* XML

I imagine that it can also help to omit a few details then.
* Brackets around process numbers
* Unit for the shown durations

**Comment by namhyung** [comment]
Did you mean output of `uftrace replay`?  Please take a look at `uftrace script` command to have complete control of uftrace data.

**Comment by elfring** [comment]
* Will any more user documentation become available than the information “runs a script for recorded trace data”?
* Can other commands provide the determined data in a preferred format directly?

**Comment by honggyukim** [comment]
Hi @elfring, `uftrace dump --chrome` generates the traced output in JSON format for chrome trace viewer. You can also see more detail information in `man uftrace script` for script command.

**Comment by elfring** [comment]
Can any [dump options](https://github.com/namhyung/uftrace/blob/c67c2be0280c2a406911d06b9b118fb3bca8b2aa/doc/uftrace-dump.md "Description for uftrace dump") make sense also for the other subcommands in this software?

**Comment by namhyung** [comment]
Maybe `uftrace report` can support other formats like CSV.

**Comment by honggyukim** [comment]
We support `dump --chrome` and `dump --flame-graph` as of now but It's good to have more. If it's really needed, then you can write a python script to dump it as CSV or XML format. Please see [script command](https://github.com/namhyung/uftrace/blob/c67c2be0280c2a406911d06b9b118fb3bca8b2aa/doc/uftrace-script.md).

**Comment by elfring** [comment]
Would you like to pass any further context information to the Python script by other means than environment variables?

**Comment by namhyung** [comment]
As you can in the doc, it passes following information to the script by function argument (a python dictionary):
* tid
* (call) depth
* timestamp
* function address
* symbol name
* duration (at exit)
* argument and/or return value (if recorded)

**Comment by elfring** [comment]
I spot the terse description for [the mentioned dictionary “`script_context`”](https://github.com/namhyung/uftrace/blob/master/doc/uftrace-script.md#examples "script execution") in the meantime. I would appreciate if the explanation could also become clearer for the usage of script options.

**Comment by namhyung** [comment]
As a non-native English speaker, I always welcome grammar fixes or other word polishing.  Would the following be better?

```
diff --git a/doc/uftrace-script.md b/doc/uftrace-script.md
index 776a9a6..61a2fea 100644
--- a/doc/uftrace-script.md
+++ b/doc/uftrace-script.md
@@ -68,7 +68,7 @@ The user can write four functions. 'uftrace_entry' and 'uftrace_exit' are execut
     def uftrace_end():
         print("program is finished")
 
-The 'ctx' variable is a dictionary type that contains the below information.
+The 'ctx' argument is a (python) dictionary type that contains the below information.
 
     /* context information passed to script */
     script_context = {
```

**Comment by elfring** [comment]
* What is the Python function (or method) signature that is invoked by the implementation of the command “`uftrace script`”?
* How do you think about to describe each data structure member in a table instead?
* How will the function receive extra parameters from the main command?

**Comment by namhyung** [comment]
> What is the Python function (or method) signature that is invoked by the implementation of the command “uftrace script”?

The "uftrace_begin()" and "uftrace_end()" has no argument, and "uftrace_entry()" and "uftrace_exit()" has a single context argument.

> How do you think about to describe each data structure member in a table instead?

OK.

> How will the function receive extra parameters from the main command?

It's not supported yet AFAIK.

**Comment by elfring** [comment]
* Will it be safer to call the mentioned functions as members of a class (methods)?
* Will the needed context data be passed in the constructor then?

**Comment by namhyung** [comment]
I have no idea about safety of class method.  And the context data is changed for each function so it won't be appropriate to pass it in the constructor IMHO.

**Comment by elfring** [comment]
I imagine that it could be occasionally nice if the discussed functions could reuse special data by class attributes.

**Comment by namhyung** [comment]
For static data, it might be beneficial, but it doesn't not any as of now.  Also it'd be require API changes.

**Comment by elfring** [comment]
>Also it'd be require API changes.

This software update will be needed if you would like to support processing of extra data not only by the programming interface of environment variables.
How do you think about corresponding extensions?

**Comment by namhyung** [comment]
It'd be great if you could provide a concrete example of the extensions and usage, thanks.

**Comment by elfring** [comment]
* Would you like to support that a script can offer conversion services for a data format selection (instead of handling only one export variant)?
* Will data displays need any additional metadata from the command line?
* Possible extensions:
  * Passing a context attribute together with each uftrace record.
  * It would be more efficient to receive the extra context information only once by another function (or constructor of a class), wouldn't it?

**Comment by namhyung** [comment]
Yes, I'm thinking about extending uftrace_begin() to pass some information like command line options and uftrace-specific data.

**Comment by namhyung** [comment]
I'm closing this.  If you want to discuss about it more, please do it in #320.

**Comment by elfring** [comment]
Please reopen this feature request so that the clarification can be continued for the initial suggestion (besides [the topic “passing more info into script”](https://github.com/namhyung/uftrace/issues/320 "Passing more info")).

**Comment by namhyung** [comment]
So do you want more options to export data in other formats, right?  Unless there's a major usecase I'd like to keep it for an external script (using the script command).

**Comment by elfring** [comment]
Which additional options could you accept for other data export variants?

**Comment by namhyung** [comment]
I'd like to see a concrete example how it's used.  Also I prefer seeing a patch rather than suggestions.

**Comment by elfring** [comment]
I find that a patch is not so helpful at the moment when we still try to clarify the software design for the handling of additional system parameters.

**Comment by namhyung** [comment]
You could show me an example to clarify the use-cases and design.
