### ISSUE TITLE
User - Process interaction problem on [command-live option]

### ISSUE THREAD

**Issue by vngkv123** [namhyung/uftrace#197]
# sample code
```
#include <stdio.h>
#include <fcntl.h>
#include <unistd.h>
#include <string.h>

int main(){
	char name[24] = {0, };
	for(int i = 0; i < 5; i++){
		printf("Your name : ");
		scanf("%s", name);
		printf("Hello %s\n", name);
	}
	return 0;
}
```
- If i run uftrace with `./uftrace test`( command-live option ), i cant see what i'm typing now, and what program's output is.
- only program print its output after the program is normally ended.

# result
```
Your name : Hello abcd
Your name : Hello asdf
Your name : Hello qwe
Your name : Hello zxcv
Your name : Hello asdf
# DURATION    TID     FUNCTION
   0.358 us [ 2250] | __monstartup();
   0.322 us [ 2250] | __cxa_atexit();
            [ 2250] | main() {
   2.992 us [ 2250] |   printf();
 924.895 ms [ 2250] |   __isoc99_scanf();
   1.383 us [ 2250] |   printf();
   0.111 us [ 2250] |   printf();
 504.095 ms [ 2250] |   __isoc99_scanf();
   1.501 us [ 2250] |   printf();
   0.093 us [ 2250] |   printf();
 343.855 ms [ 2250] |   __isoc99_scanf();
   1.809 us [ 2250] |   printf();
   0.091 us [ 2250] |   printf();
 664.024 ms [ 2250] |   __isoc99_scanf();
   2.037 us [ 2250] |   printf();
   0.081 us [ 2250] |   printf();
 351.948 ms [ 2250] |   __isoc99_scanf();
   1.601 us [ 2250] |   printf();
   2.788  s [ 2250] | } /* main */
```
**And it cant trace some code like this.**
https://gist.github.com/namhyung/ff12959273204a803d2cd78110a7a75d
- If i type "exit" to terminate this program, it didnt work. 
- First, i thought maybe `while(1)` loop is problem, but it's wrong.

- Because below code is normally running.
```
#include <iostream>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

using namespace std;

void interaction(char *_cmd){
	printf("> ");
	scanf("%s", _cmd);
	if( strcmp(_cmd, "exit") == 0){
		abort();
	}
	else if( strcmp(_cmd, "help") == 0){
		printf("I cant help you\n");
	}
	else if( strcmp(_cmd, "out") == 0){
		throw 2;
	}
	else
		throw 1;
}
		


int main(int argc, char *argv[]){
	char cmd[24] = {0, };
	while(1){
		try{
			interaction(cmd);
		}
		catch(int ex){
			if( ex == 1 ){
				printf("Wrong Command\n");
			}
			else{
				break;
			}
		}
	}
}
```
# Question
- Why `uftrace` cant show interaction between user and process?
- Why i cant exit from above code?

**Comment by namhyung** [comment]
Hello, uftrace ("live" command in this case) uses a pager (default `less(1)`) to help users reading the output (from your program and uftrace).  But it hinders interaction via stdin unfortunately.  You can use `--no-pager` option to disable the pager - I don't know how to handle it automatically.  Note that `uftrace record` command disables the pager by default.

**Comment by elfring** [comment]
>You can use `--no-pager` option to disable the pager - I don't know how to handle it automatically.

Could you get further inspiration from the content management software “Git”?

**Comment by namhyung** [comment]
@elfring well, my concern was how to detect from uftrace for child to use stdin.  Do you know how git deals with it (or is there a case for git worry about it)?

**Comment by elfring** [comment]
Did you notice that Git tools change their behaviour depending on output file redirection?

**Comment by namhyung** [comment]
Note that uftrace already detects **stdout** being a tty to setup the pager but not for **stdin**.

**Comment by elfring** [comment]
Will input file “redirection” be handled in a similar way?

**Comment by namhyung** [comment]
It's not simple like stdout since it depends on whether the child process needs to read from input rather than being a tty or not.

**Comment by elfring** [comment]
Can the forking of a subprocess break the desired terminal handling?

**Comment by namhyung** [comment]
It might be possible, but I didn't see any report yet (other than this).

**Comment by namhyung** [comment]
@vngkv123 have you tried `--no-pager` option?

**Comment by vngkv123** [comment]
Sorry for late...
I've try that, and check it works.

2017. 10. 27. 오후 3:14에 "Namhyung Kim" <notifications@github.com>님이 작성:

**Comment by namhyung** [comment]
Thanks for confirming.  Unfortunately I cannot find a way to disable pager automatically for your case, so you need to do it with `--no-pager` when you want to read input from user.  Also note that `uftrace record` runs without pager so you might want to do record and replay separately.

**Comment by elfring** [comment]
* Should all interactive programs be traced only without paging?
* Are additional ideas needed to switch the paging functionality off in any more use cases?

**Comment by namhyung** [comment]
@elfring sorry for late.  I think interactive programs should run without pager and I have no idea to make it automatic.
