### ISSUE TITLE
undefined symbol: pevent_find_event

### ISSUE THREAD

**Issue by BiagioFesta** [namhyung/uftrace#198]
### Source Code:

test.cpp:
~~~
void foo() {}

int main() {
  foo();
  return 0;
}
~~~

### Compiling:
`g++ -pg -O0 -o test test.cpp`

Linux 64 bit.

### Output:
`uftrace -vv ./test`
~~~
symbol: check trace functions in ./test
uftrace: creating 2 thread(s) for recording
uftrace: start writer thread 0
uftrace: start writer thread 1
uftrace: using libmcount.so library for tracing
./test: symbol lookup error: /usr/lib/libmcount.so: undefined symbol: pevent_find_event
uftrace: all process/thread exited
uftrace: child terminated with exit code: 127
uftrace: stop writer thread 0
uftrace: stop writer thread 1
uftrace: ${HOME}/.cache/pacaur/uftrace-git/src/uftrace/cmd-record.c:1279:save_session_symbols
 ERROR: cannot find map files: Success
~~~

**Comment by namhyung** [comment]
> ./test: symbol lookup error: /usr/lib/libmcount.so: undefined symbol: pevent_find_event

Hmm.. strange.  The `pevent_find_event()` is in libtraceevent which is statically linked to the uftrace binary.  And libmcount.so has nothing to do with the libtraceevent.  How did you build and install uftrace?

**Comment by BiagioFesta** [comment]
I installed in Arch-Linux environment. In particular, I've used the AUR repository.
[Here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=uftrace-git) the installation script launched.

**Comment by BiagioFesta** [comment]
### Update:
I've tried to compile manually from the version 0.8. Everything works fine now.
Anyway, I don't know if there is an issue in the building script of AUR repository or in the last git commits.

**Comment by namhyung** [comment]
Thanks for the update.  I also use Archlinux and don't see an issue. :)

**Comment by andrewjss** [comment]
I had this issue building under nix with gcc 6.4. 
I needed to link libtraceevent the libmcount libraries, which failed to link with -Wl,--no-undefined

**Comment by namhyung** [comment]
@andrewjss thanks for the hint.  It indeed had a call to libtraceevent in libmcount and I could reproduce it with the linker option.  It's in the `get_event_name()` in utils.c which is a part of libmcount.  As it's not neccessary for libmcount, I will move it into another place not to linked.
