### ISSUE TITLE
Reconsider final actions for program termination

### ISSUE THREAD

**Issue by elfring** [namhyung/uftrace#199]
I have taken another look at the end of [the implementation for the function “main()”](https://github.com/namhyung/uftrace/blob/55ee3007c44ff1c833b166ff5256201011137f66/uftrace.c#L906 "Update candidate: main()"). I got the impression that only functions are called which should be usually performed by [a regular program termination](http://en.cppreference.com/w/c/program/exit "Description for exit").
Thus I suggest to omit a bit of extra source code.

```diff
diff --git a/uftrace.c b/uftrace.c
index fa13899..6f29e19 100644
--- a/uftrace.c
+++ b/uftrace.c
@@ -1010,14 +1010,6 @@ int main(int argc, char *argv[])
        }
 
        wait_for_pager();
-
-       if (opts.logfile)
-               fclose(logfp);
-
-       if (opts.opt_file)
-               free_parsed_cmdline(argv);
-
-       free_opts(&opts);
        return ret;
 }
 #else
```

:crystal_ball: How do you think about to delete related unnecessary stuff?

**Comment by namhyung** [comment]
But why?

And it would create a lot of warnings from static/dynamic checkers like Coverity Scan or Asan.

**Comment by elfring** [comment]
>But why?

I suggest generally to avoid stuff which is usually not needed in such uses cases.
Do you care for a bit faster program termination?


>And it would create a lot of warnings …

Do you need any additional source code annotations for tools you might be concerned about?

**Comment by namhyung** [comment]
I think the speedup will be negligible and I'd like to release all the resources properly unless it takes too much time.

**Comment by elfring** [comment]
>I think the speedup will be negligible

 You could achieve a small speed change just by performing less work (at the end), couldn't you?


>… I'd like to release all the resources properly …

Would you like to reuse the default clean-up procedure which is specified for the involved programming interface for years?

**Comment by namhyung** [comment]
> You could achieve a small speed change just by performing less work (at the end), couldn't you?

Yes, but it will lose the correctness(?).

> Would you like to reuse the default clean-up procedure which is specified for the involved programming interface for years?

Are you saying that not releasing resource is the default clean-up procedure?

**Comment by honggyukim** [comment]
I also think that the speedup is negligible with this change and also agree that all the resources have to be released before program finishes.

**Comment by elfring** [comment]
>Yes, but it will lose the correctness(?).

No. - Not at the current software development status.


>Are you saying that not releasing resource is the default clean-up procedure?

Not really.


>… that all the resources have to be released before program finishes.

* Are you aware that functionality (which is needed at the moment) is [already provided by the standard procedure](http://pubs.opengroup.org/onlinepubs/9699919799/functions/_Exit.html#tag_16_01_03_01 "Consequences of process termination")?
* Do you miss any explanation for the affected programming interface?

**Comment by namhyung** [comment]
>> Yes, but it will lose the correctness(?).

> No. - Not at the current software development status.

I mean it "in uftrace".  System as a whole is correct anyway - then what's the difference doing it in uftrace and deferrring to the system (other than the negligible speedup).  I think it only makes the program incomplete.

**Comment by elfring** [comment]
>… - then what's the difference doing it in uftrace

Other software run time characteristics (at the end).


>(other than the negligible speedup).

Would we like to measure corresponding effects precisely?


>I think it only makes the program incomplete.

I suggest just to avoid extra work which will be done by other system software components already for you.
[The function “atexit”](http://pubs.opengroup.org/onlinepubs/9699919799/functions/atexit.html "Register a function to run at process termination.") could be called if really non-standard clean-up actions would be required at process termination.

Can it also be nice to maintain a bit less special source code?

**Comment by namhyung** [comment]
You seem to use the word "special" many time but I don't know why do you call it.  It's fairly normal and clear I think.  If you still want to insist the merit please measure and show me the performance gain by yourself, thanks.

**Comment by elfring** [comment]
I interpret an item as “special” if it fulfils a specific purpose.

* Software could evolve in a way so that non-standard clean-up actions will be required at process termination.
* Why do you insist to keep duplicate code so far?
* Can your tool trace itself?

**Comment by honggyukim** [comment]
I think this discussion is not constructive. So please consider how much time you're taking someone else's time for your curiosity.

**Comment by elfring** [comment]
You might get an other impression.

* I am trying to get another bit of development attention also on a general software aspect.
* If you could accept the avoidance of duplicate code more, there would be no extra need for program profiling in the discussed use case.

**Comment by honggyukim** [comment]
Okay. You may think in a different way but you should also respect other's opinion. We don't have enough time and resource for answering your questions over and over again so please understand that. It looks very straight forward for us so I think it's not the issue for further discussion. Thanks anyway!

**Comment by elfring** [comment]
We got also different software development opinions (which is usual).


>We don't have enough time and resource for answering your questions over and over again so please understand that.

Our response times will vary for additional ideas.


>It looks very straight forward for us

You might be used to a programming style for a while which could be improved.


>so I think it's not the issue for further discussion.

🔮 You might reconsider the affected program structure later.

**Comment by namhyung** [comment]
> You might reconsider the affected program structure later.

It might or might not.  But not this time, thanks.
