### ISSUE TITLE
Fail to build for ARM. Error: cannot find 'libelf' (from elfutils)

### ISSUE THREAD

**Issue by kuzminrobin** [namhyung/uftrace#205]
---------- Forwarded message ----------
From: Honggyu Kim <>
Date: Fri, Oct 27, 2017 at 6:13 PM
Subject: Re: Trying uftrace.
To: Robin Kuzmin <>
Hi Robin,
Thanks for using uftrace. But I'm currently outside so cannot answer right now. Could you please write the same one in github issue?
Namhyung may answer for that.

Thanks,
Honggyu

On Sat, 28 Oct 2017 at 8:22 AM Robin Kuzmin <> wrote:
I'm trying to cross-build for ARM. And I get a 'libelf' error. What do I miss?
I do:

**$pwd**
/mnt/extra_disk/dev/3rdparty_tools/uftrace

$**env | grep CROSS**
CROSS_COMPILE=/opt/CodeSourcery/arm-2011.09/bin/arm-none-linux-gnueabi-

$**ls /opt/CodeSourcery/arm-2011.09/bin/arm-none-linux-gnueabi-* **
/opt/CodeSourcery/arm-2011.09/bin/arm-none-linux-gnueabi-addr2line  /opt/CodeSourcery/arm-2011.09/bin/arm-none-linux-gnueabi-gcc        /opt/CodeSourcery/arm-2011.09/bin/arm-none-linux-gnueabi-objcopy
/opt/CodeSourcery/arm-2011.09/bin/arm-none-linux-gnueabi-ar         /opt/CodeSourcery/arm-2011.09/bin/arm-none-linux-gnueabi-gcc-4.6.1  /opt/CodeSourcery/arm-2011.09/bin/arm-none-linux-gnueabi-objdump
/opt/CodeSourcery/arm-2011.09/bin/arm-none-linux-gnueabi-as         /opt/CodeSourcery/arm-2011.09/bin/arm-none-linux-gnueabi-gcov       /opt/CodeSourcery/arm-2011.09/bin/arm-none-linux-gnueabi-ranlib
/opt/CodeSourcery/arm-2011.09/bin/arm-none-linux-gnueabi-c++        /opt/CodeSourcery/arm-2011.09/bin/arm-none-linux-gnueabi-gdb        /opt/CodeSourcery/arm-2011.09/bin/arm-none-linux-gnueabi-readelf
/opt/CodeSourcery/arm-2011.09/bin/arm-none-linux-gnueabi-c++filt    /opt/CodeSourcery/arm-2011.09/bin/arm-none-linux-gnueabi-gdbtui     /opt/CodeSourcery/arm-2011.09/bin/arm-none-linux-gnueabi-size
/opt/CodeSourcery/arm-2011.09/bin/arm-none-linux-gnueabi-cpp        /opt/CodeSourcery/arm-2011.09/bin/arm-none-linux-gnueabi-gprof      /opt/CodeSourcery/arm-2011.09/bin/arm-none-linux-gnueabi-sprite
/opt/CodeSourcery/arm-2011.09/bin/arm-none-linux-gnueabi-elfedit    /opt/CodeSourcery/arm-2011.09/bin/arm-none-linux-gnueabi-ld         /opt/CodeSourcery/arm-2011.09/bin/arm-none-linux-gnueabi-strings
/opt/CodeSourcery/arm-2011.09/bin/arm-none-linux-gnueabi-g++        /opt/CodeSourcery/arm-2011.09/bin/arm-none-linux-gnueabi-nm         /opt/CodeSourcery/arm-2011.09/bin/arm-none-linux-gnueabi-strip

$**./configure ARCH=arm CFLAGS='--sysroot /srv/zoom'**
Error: cannot find 'libelf' (from elfutils): Please install it first.

$**find /srv/zoom -name "libelf*"**
/srv/zoom/usr/lib/libelf.a
/srv/zoom/usr/lib/libelf.so.0
/srv/zoom/usr/lib/libelf.so.0.8.5
/srv/zoom/usr/lib/libelf.so
/srv/zoom/usr/share/locale/de/LC_MESSAGES/libelf.mo
/srv/zoom/usr/include/libelf
/srv/zoom/usr/include/libelf/libelf.h
/srv/zoom/usr/include/libelf.h

$**ls -l /srv/zoom/usr/lib/libelf***
-rw-r--r-- 1 root root 521436 Oct 27 15:31 /srv/zoom/usr/lib/libelf.a
lrwxrwxrwx 1 root root     15 Oct 27 15:31 /srv/zoom/usr/lib/libelf.so -> libelf.so.0.8.5
lrwxrwxrwx 1 root root     15 Oct 27 15:31 /srv/zoom/usr/lib/libelf.so.0 -> libelf.so.0.8.5
-rwxr-xr-x 1 root root 269779 Oct 27 15:31 /srv/zoom/usr/lib/libelf.so.0.8.5

$**file /srv/zoom/usr/lib/libelf.so.0.8.5**
/srv/zoom/usr/lib/libelf.so.0.8.5: ELF 32-bit LSB shared object, ARM, version 1 (SYSV), dynamically linked, not stripped

Then I tried the following:

$**git diff configure** 
```diff
diff --git a/configure b/configure
index 0ec7675..581f70b 100755
--- a/configure
+++ b/configure
@@ -102,8 +102,8 @@ MAKEOVERRIDES=
 
 export CC CFLAGS LD LDFLAGS
 
-make -siC ${srcdir}/check-deps check-clean
-make -siC ${srcdir}/check-deps check-build
+make V=1 -C ${srcdir}/check-deps check-clean
+make V=1 -d -C ${srcdir}/check-deps check-build
 
 if [ ! -e ${srcdir}/check-deps/have_libelf ]; then
     echo "Error: cannot find 'libelf' (from elfutils): Please install it first."
```

$**./configure ARCH=arm CFLAGS='--sysroot /srv/zoom'**
. . . 
    No need to remake target `__clock_without_librt.c'.
   Finished prerequisites of target file `clock_without_librt'.
  Must remake target `clock_without_librt'.
Putting child 0x0193bf30 (clock_without_librt) PID 18486 on the chain.
Live child 0x0193bf30 (clock_without_librt) PID 18486 
make: Reaping losing child 0x0193bf30 PID 18486 
*** [clock_without_librt] Error 1
Removing child 0x0193bf30 PID 18486 from chain.
make: Leaving directory `/mnt/extra_disk/dev/3rdparty_tools/uftrace/check-deps'
Error: cannot find 'libelf' (from elfutils): Please install it first.

**Comment by andrewjss** [comment]
It looks like you've got the wrong libelf installed. Install elfutils. Elfutils comes with a different, incompatible libelf. The current release is 0.170, not 0.8.5.

**Comment by namhyung** [comment]
@andrewjss right, uftrace needs libelf in the elfutils.  Thanks for pointing it out.

**Comment by kuzminrobin** [comment]
I have managed to pass trough this stage and a number of subsequent stages.
I need to report the following:

Your Makefiles use the compiler both for compiling and linking. In my case the compiler does not pass normally the linker arguments to the linker (I tried everything I could (linker options): -L, -rpath, -rpath-link, { -Wl,-L -Wl,path }, -Wl,-Lpath, {-Wl,-rpath -Wl,path}, etc.). That is why I have to compile and link with separate commands. You may want to make the same change in your Makefiles for the compiling an linking to work for the cases like mine:
```diff
diff --git a/check-deps/Makefile b/check-deps/Makefile
index d04366e..7920584 100644
--- a/check-deps/Makefile
+++ b/check-deps/Makefile
@@ -23,7 +23,8 @@ LDFLAGS_have_libpython2.7 = -lpython2.7
 check-build: check-tstamp $(CHECK_LIST)
 
 $(CHECK_LIST): %: __%.c
-   @$(CC) $(CHECK_CFLAGS) -o $@ $< $(CHECK_LDFLAGS) > /dev/null 2>&1
+   $(CC) $(CHECK_CFLAGS) -o $@.o -c __$@.c > /dev/null 2>&1
+   $(LD) $(CHECK_LDFLAGS) -o $@ $@.o > /dev/null 2>&1
 
 check-tstamp: PHONY
    @touch $@
```
Your Makefile is also using the compiler for linking **uftrace**. I had to make the following change (which I also recommend you, probably in a better way than I did):
```diff
diff --git a/Makefile b/Makefile
index 1254949..09e083a 100644
--- a/Makefile
+++ b/Makefile
@@ -195,7 +195,7 @@ $(objdir)/version.h: PHONY
    @$(srcdir)/misc/version.sh $@ $(VERSION_GIT)
 
 $(objdir)/uftrace: $(UFTRACE_OBJS) $(UFTRACE_ARCH_OBJS) $(objdir)/libtraceevent/libtraceevent.a
-   $(QUIET_LINK)$(CC) $(UFTRACE_CFLAGS) -o $@ $(UFTRACE_OBJS) $(UFTRACE_ARCH_OBJS) $(UFTRACE_LDFLAGS)
+   $(QUIET_LINK)$(LD) -o $@ $(UFTRACE_OBJS) $(UFTRACE_ARCH_OBJS) $(UFTRACE_LDFLAGS)
 
 install: all
    $(Q)$(INSTALL) -d -m 755 $(DESTDIR)$(bindir)
```

Now (after my changes above) I hit the following issues:
1. During `make` the following output seems to me suspicious See the 5th line 
`/opt/CodeSourcery/arm-2011.09/bin/arm-none-linux-gnueabi-ld: mode armelf_linux_eabi` and the last line 
`warning: cannot find entry symbol _start; defaulting to 0000ad9c`.
```
  . . .
  CC FPIC  libtraceevent/kbuffer-parse.o
  LINK     libtraceevent/libtraceevent.a
  LINK     uftrace
/opt/CodeSourcery/arm-2011.09/bin/arm-none-linux-gnueabi-ld: mode armelf_linux_eabi
/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/uftrace.o
/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/cmd-dump.o
/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/cmd-graph.o
/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/cmd-info.o
/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/cmd-live.o
/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/cmd-record.o
/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/cmd-recv.o
/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/cmd-replay.o
/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/cmd-report.o
/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/cmd-script.o
/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/utils/data-file.o
/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/utils/debug.o
/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/utils/demangle.o
/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/utils/filter.o
/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/utils/fstack.o
/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/utils/kernel.o
/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/utils/pager.o
/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/utils/perf.o
/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/utils/rbtree.o
/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/utils/script.o
/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/utils/script-python.o
/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/utils/session.o
/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/utils/symbol.o
/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/utils/utils.o
/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/arch/arm/uftrace.o
-lelf (/srv/zoom/usr/local/lib/libelf.so)
-lrt (/opt/CodeSourcery/arm-2011.09/arm-none-linux-gnueabi/libc/usr/lib/librt.so)
-ldl (/opt/CodeSourcery/arm-2011.09/arm-none-linux-gnueabi/libc/usr/lib/libdl.so)
libgcc_s.so.1 (/opt/CodeSourcery/arm-2011.09/arm-none-linux-gnueabi/libc/lib/libgcc_s.so.1)
/lib/libc.so.6 (/opt/CodeSourcery/arm-2011.09/bin/../arm-none-linux-gnueabi/libc/lib/libc.so.6)
(/opt/CodeSourcery/arm-2011.09/bin/../arm-none-linux-gnueabi/libc/usr/lib/libc_nonshared.a)atexit.oS
/lib/ld-linux.so.3 (/opt/CodeSourcery/arm-2011.09/bin/../arm-none-linux-gnueabi/libc/lib/ld-linux.so.3)
/lib/libpthread.so.0 (/opt/CodeSourcery/arm-2011.09/bin/../arm-none-linux-gnueabi/libc/lib/libpthread.so.0)
-lz (/srv/zoom/usr/lib/libz.so)
-lstdc++ (/opt/CodeSourcery/arm-2011.09/arm-none-linux-gnueabi/libc/usr/lib/libstdc++.so)
(/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/libtraceevent/libtraceevent.a)event-parse.o
(/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/libtraceevent/libtraceevent.a)trace-seq.o
(/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/libtraceevent/libtraceevent.a)parse-utils.o
(/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/libtraceevent/libtraceevent.a)kbuffer-parse.o
-ldl (/opt/CodeSourcery/arm-2011.09/arm-none-linux-gnueabi/libc/usr/lib/libdl.so)
/opt/CodeSourcery/arm-2011.09/bin/arm-none-linux-gnueabi-ld: warning: cannot find entry symbol _start; defaulting to 0000ad9c
```
This output (above) has managed to link `uftrace` for ARM but I feel that something is unexpected there. Do you have any ideas? The output (above) has been caused by the following link command:
```
/opt/CodeSourcery/arm-2011.09/bin/arm-none-linux-gnueabi-ld \
	-o /mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/uftrace \
	/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/uftrace.o \
	/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/cmd-dump.o \
	/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/cmd-graph.o \
	/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/cmd-info.o \
	/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/cmd-live.o \
	/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/cmd-record.o \
	/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/cmd-recv.o \
	/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/cmd-replay.o \
	/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/cmd-report.o \
	/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/cmd-script.o \
	/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/utils/data-file.o \
	/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/utils/debug.o \
	/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/utils/demangle.o \
	/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/utils/filter.o \
	/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/utils/fstack.o \
	/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/utils/kernel.o \
	/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/utils/pager.o \
	/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/utils/perf.o \
	/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/utils/rbtree.o \
	/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/utils/script.o \
	/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/utils/script-python.o \
	/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/utils/session.o \
	/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/utils/symbol.o \
	/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/utils/utils.o \
	/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/arch/arm/uftrace.o \
	-lelf -lrt -ldl -pthread \
	-L/opt/CodeSourcery/arm-2011.09/arm-none-linux-gnueabi/libc/usr/lib \
	-L/opt/CodeSourcery/arm-2011.09/arm-none-linux-gnueabi/libc/lib \
	-lgcc_s -lc -lpthread \
	-L/opt/CodeSourcery/arm-2011.09/lib/gcc/arm-none-linux-gnueabi/4.6.1 \
	-L/srv/zoom/usr/local/lib \
	-L/srv/zoom/usr/lib \
	-lz -lstdc++ \
	-L/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/libtraceevent \
	-ltraceevent -ldl
```

2. This is currently a blocking issue for me. 
During the `make` (after the output above) I see the following:
```
  CC FPIC  libmcount/demangle.op
  CC FPIC  libmcount/utils.op
  CC FPIC  libmcount/script.op
  CC FPIC  libmcount/script-python.op
  ASM      arch/arm/mcount.op
  ASM      arch/arm/plthook.op
  CC FPIC  arch/arm/mcount-support.op
/tmp/ccYQL77C.s: Assembler messages:
/tmp/ccYQL77C.s:1397: Error: selected processor does not support ARM mode `vstr %d7,[r3,#16]'
/tmp/ccYQL77C.s:1461: Error: selected processor does not support ARM mode `vstr %s3,[r3,#16]'
/tmp/ccYQL77C.s:1472: Error: selected processor does not support ARM mode `vstr %s4,[r3,#16]'
/tmp/ccYQL77C.s:1483: Error: selected processor does not support ARM mode `vstr %s5,[r3,#16]'
/tmp/ccYQL77C.s:1494: Error: selected processor does not support ARM mode `vstr %s6,[r3,#16]'
/tmp/ccYQL77C.s:1505: Error: selected processor does not support ARM mode `vstr %s1,[r3,#16]'
/tmp/ccYQL77C.s:1516: Error: selected processor does not support ARM mode `vstr %s2,[r3,#16]'
/tmp/ccYQL77C.s:1527: Error: selected processor does not support ARM mode `vstr %s0,[r3,#16]'
/tmp/ccYQL77C.s:1538: Error: selected processor does not support ARM mode `vstr %s7,[r3,#16]'
/tmp/ccYQL77C.s:1549: Error: selected processor does not support ARM mode `vstr %s8,[r3,#16]'
/tmp/ccYQL77C.s:1560: Error: selected processor does not support ARM mode `vstr %s9,[r3,#16]'
/tmp/ccYQL77C.s:1571: Error: selected processor does not support ARM mode `vstr %s10,[r3,#16]'
/tmp/ccYQL77C.s:1582: Error: selected processor does not support ARM mode `vstr %s11,[r3,#16]'
/tmp/ccYQL77C.s:1593: Error: selected processor does not support ARM mode `vstr %s12,[r3,#16]'
/tmp/ccYQL77C.s:1604: Error: selected processor does not support ARM mode `vstr %s13,[r3,#16]'
/tmp/ccYQL77C.s:1615: Error: selected processor does not support ARM mode `vstr %s14,[r3,#16]'
/tmp/ccYQL77C.s:1626: Error: selected processor does not support ARM mode `vstr %s15,[r3,#16]'
/tmp/ccYQL77C.s:1637: Error: selected processor does not support ARM mode `vstr %d0,[r3,#16]'
/tmp/ccYQL77C.s:1648: Error: selected processor does not support ARM mode `vstr %d1,[r3,#16]'
/tmp/ccYQL77C.s:1659: Error: selected processor does not support ARM mode `vstr %d2,[r3,#16]'
/tmp/ccYQL77C.s:1670: Error: selected processor does not support ARM mode `vstr %d3,[r3,#16]'
/tmp/ccYQL77C.s:1681: Error: selected processor does not support ARM mode `vstr %d4,[r3,#16]'
/tmp/ccYQL77C.s:1692: Error: selected processor does not support ARM mode `vstr %d5,[r3,#16]'
/tmp/ccYQL77C.s:1703: Error: selected processor does not support ARM mode `vstr %d6,[r3,#16]'
/tmp/ccYQL77C.s:2014: Error: selected processor does not support ARM mode `vstr %s0,[r4,#16]'
/tmp/ccYQL77C.s:2026: Error: selected processor does not support ARM mode `vstr %d0,[r4,#16]'
make[2]: *** [/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/arch/arm/mcount-support.op] Error 1
make[1]: *** [/mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/arch/arm/mcount-entry.op] Error 2
make: *** [all] Error 2
```
I investigated and found out the following:
+ The `vstr` instruction deals with the floating point hardware named NEON and VFP, see details here http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0489i/CIHCJCFG.html .
+ My ARM chip is ARM Cortex-A8 core, details are here - http://www.ti.com/product/dm3730 .
+ ARM Cortex-A8 (ARMv7-A architecture) supports (or has) both NEON and VFPv3 FPU hardware - https://en.wikipedia.org/wiki/List_of_ARM_microarchitectures .
+ I tried multiple different command line args for the compiler (with and without `-mcpu=cortex-a8`, `-march=armv7-a`, `-mthumb`, `-mfpu=vfpv3`, `-mfpu=neon`, `-msoft-float`) to work around the issue but I still fail - `man -a gcc`.
+ The file `uftrace/README.md` tells me that uftrace `supports ... ARM (v6 or later)`. In my case it is ARMv7-A, see again https://en.wikipedia.org/wiki/List_of_ARM_microarchitectures.

What can I do else to work around the issue?

The output above is caused by the command:
```
/opt/CodeSourcery/arm-2011.09/bin/arm-none-linux-gnueabi-gcc \
    -O2 -g -D_GNU_SOURCE \
    -march=armv7-a -mfpu=vfpv3 -msoft-float \
    -I/opt/CodeSourcery/arm-2011.09/arm-none-linux-gnueabi/libc/usr/include \
    --sysroot /srv/zoom  \
    -iquote /mnt/extra_disk/dev/3rdparty_tools/uftrace/uftrace \
    -iquote /mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build \
    -iquote /mnt/extra_disk/dev/3rdparty_tools/uftrace/uftrace/arch/arm \
    -W -Wall -Wno-unused-parameter -Wno-missing-field-initializers \
    -DHAVE_CXA_DEMANGLE   -fPIC -fvisibility=hidden -c -o \
    /mnt/extra_disk/dev/3rdparty_tools/uftrace/arm_build/arch/arm/mcount-support.op \
    /mnt/extra_disk/dev/3rdparty_tools/uftrace/uftrace/arch/arm/mcount-support.c
```

**Comment by kuzminrobin** [comment]
I have just noticed https://github.com/namhyung/uftrace/issues/148 and https://github.com/namhyung/uftrace/compare/review/arm-softfp-v1.
I commented out the `vstr`-related code (similar to this - https://github.com/namhyung/uftrace/compare/review/arm-softfp-v1#diff-5b01828b57aae713d6c9ffac03773d27) and managed to compile. I installed the `uftrace` on the device but it fails to run.
```sh
DM-37x# ./uftrace --help
-sh: ./uftrace: No such file or directory

DM-37x# ls -l ./uftrace
-rwxr-xr-x    1 root     root        960397 Oct 31 22:40 ./uftrace
```
I see the following difference from the other executables on the device:
```sh
$file uftrace 
uftrace: ELF 32-bit LSB executable, ARM, version 1 (SYSV), dynamically linked (uses shared libs), not stripped

# Other executables:
sx: ELF 32-bit LSB executable, ARM, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.16, not stripped
```
The difference is that other executables have `for GNU/Linux 2.6.16`.
I'm investigating. This seems to me related to the issue 1 I mentioned in my previous comment.

**Comment by honggyukim** [comment]
@kuzminrobin Thanks for the report. We had the same issue but made it as a second priority. We will try to fix it first so I will first write a script that downloads and builds libelf for easy compilation for cross compile environment. Thanks for the detailed report.

**Comment by namhyung** [comment]
> In my case the compiler does not pass normally the linker arguments to the linker (I tried everything I could (linker options): -L, -rpath, -rpath-link, { -Wl,-L -Wl,path }, -Wl,-Lpath, {-Wl,-rpath -Wl,path}, etc.).

@kuzminrobin It's strange that gcc doesn't pass the linker options.  Could you please show me the exact command line the make runs and the error messages?  I really appreciate your detailed report and sorry for the inconvenience.

**Comment by honggyukim** [comment]
@namhyung What about adding one more option in `configure` script as follows:
```
$ ./configure --help
Usage: ./configure [<options>]
    ...
  --with-elfutils    configure elfutils after downloading tarball
    ...
```
It can download and configure elfutils with given configure setting. If you agree, I will send a PR for that. Thanks!

**Comment by honggyukim** [comment]
In that case, `make` will compiles `elfutils` first then `uftrace`. `make install` will install `libelf.so`, `libdw.so`, `libasm.so`, and many other `elfutils/libebl_{arches}.so`.

**Comment by namhyung** [comment]
@honggyukim I'm ok building elfutils with uftrace if needed.  However traditionally `--with-XXX` option was used for slightly different usage (in autotools) AFAIK, how about `--build-elfutils`?

**Comment by honggyukim** [comment]
I'm okay with `--build-elfutils`. But do you think we better remove unnecessary libraries such as `libasm.so` and `elfutils`/libebl_{arches}.so` after installation? I think we only need `libelf.so` and `libdw.so` for dwarf support later on.

**Comment by namhyung** [comment]
I'd rather keep them.

**Comment by honggyukim** [comment]
Okay. Would you like me to include the patches from [review/arm-softfp-v1](https://github.com/namhyung/uftrace/compare/review/arm-softfp-v1)?

**Comment by namhyung** [comment]
Please do if you need it.

**Comment by honggyukim** [comment]
@namhyung I just wrote a draft version in #218. Could you give me some feedback on it? I know it has to be change more but I'm leaving it because I have to go now :)

**Comment by namhyung** [comment]
I'm closing this assuming current code fixed the problem.  If you still see the same problem, please reopen.
