### ISSUE TITLE
wiki: typo in Tutorial

### ISSUE THREAD

**Issue by flavono123** [namhyung/uftrace#206]
Find a small typo in [Tutorial](https://github.com/namhyung/uftrace/wiki/Tutorial).
Guessing 'Basic usage' should be \<h1\>.

<img width="724" alt="tutorial_ _namhyung_uftrace_wiki" src="https://user-images.githubusercontent.com/20619567/32141538-80ff3362-bcc6-11e7-9b6f-f2a1b113eba7.png">

**Comment by namhyung** [comment]
@flavono123 thanks for the report, fixed now! :)
