### ISSUE TITLE
 uftrace doesn't work on Windows Subsystem ubuntu linux 

### ISSUE THREAD

**Issue by KimKiHyuk** [namhyung/uftrace#216]
Hello, I'm using Windows Subsystem Ubuntu

introducing about Windows Subsystem ubuntu, 
It provide to windows user Linux environments ( Not virtual machine )

the official document [url](https://msdn.microsoft.com/en-us/commandline/wsl/about)

    $ uname -a 
    Linux DESKTOP-CTQAOT3 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux
    
When I run uftrace in my system, I met this error message

    $ sudo uftrace test

    ERROR: ld.so: object 'libmcount-fast.so' from LD_PRELOAD cannot be preloaded 
    (cannot enable executable stack as shared o
    Inconsistency detected by ld.so: rtld.c: 628: init_tls: Assertion `i == GL(dl_tls_max_dtv_idx)' failed!
    uftrace: /home/rlgur41/uftrace/cmd-record.c:1279:save_session_symbols
     ERROR: cannot find map files: Success

can i fix this error???

Thank you

**Comment by namhyung** [comment]
I don't know about the WSL but it seems there's an issue for `LD_PRELOAD` or TLS (Thread-Local Storage) handling.  You'd better write a tiny example code to verify them working on WSL first.

**Comment by ParkHanbum** [comment]
reference below link.
https://github.com/Microsoft/WSL/issues/307

**Comment by namhyung** [comment]
It seems WSL has very limited support and I don't think we can do much about it.

**Comment by honggyukim** [comment]
It works great with WSL2 now!

![image](https://user-images.githubusercontent.com/19642328/63985807-4342ad00-cb0c-11e9-89c0-c8a7e8fdcd1d.png)

**Comment by namhyung** [comment]
Wow, that's great!

**Comment by honggyukim** [comment]
It seems that we don't need to have a separate Linux machine to develop uftrace.
