### ISSUE TITLE
[question] Comparing two traces

### ISSUE THREAD

**Issue by illera88** [namhyung/uftrace#222]
Hi,

I'm just wondering if you have done some diff to compare traces and see where the instruction flow differs between two different executions and if there is something more sophisticated than doing a simple diff.

I just discovered this tool and it's great!

**Comment by namhyung** [comment]
Thank you for using uftrace.

The `report` command provides `--diff` option to compare execution stats.  But more work needs to be done to improve this kind of usage.

You can also `dump` the data to visualize using `--chrome` or `--flame-graph` option and compare the outputs on your eyes.  Or it maybe helpful if you use `graph` command and pass the outputs to the diff tool with some preprocessing.
