### ISSUE TITLE
uftrace v0.8.1-52-g1f51c: Typo upon "uftrace --help": sampliing (double 'i', expected single).

### ISSUE THREAD

**Issue by kuzminrobin** [namhyung/uftrace#226]
In `uftrace v0.8.1-52-g1f51c` upon the command `uftrace --help` there is a typo in the line
    --sample-time=TIME     Show flame graph with this sampliing time
in the word `sampliing` I expected a single `i` but I see double `ii`.

**Comment by namhyung** [comment]
Thanks for the report.  Will fix soon! :)
