### ISSUE TITLE
support for full-graph

### ISSUE THREAD

**Issue by namhyung** [namhyung/uftrace#228]
The full-graph is a function call graph of entire program.  Instead of default 'main' function, now graph command will enter to the full-graph mode if no function name was given on the command line.  The difference to 'main' is that it is now able to show initialization and finalization functions.

The code was pushed to [review/graph-full-v1](https://github.com/namhyung/uftrace/compare/review/graph-full-v1).

For example, the below is a toy program:
```
$ cat hello.cpp
#include <iostream>

int main(void)
{
  std::cout << "Hello world\n";
  return 0;
}

$ g++ -pg -o hello-cpp hello.cpp
$ uftrace record hello-cpp
Hello world
```

The original graph output is like below:
```
$ uftrace graph main
# Function Call Graph for 'main' (session: f35f2ad29576eff5)
=============== BACKTRACE ===============
 backtrace #0: hit 1, time  15.488 us
   [0] main (0x5647e00d0934)

========== FUNCTION CALL GRAPH ==========
  15.488 us : (1) main
  14.559 us : (1) std::operator <<
```

Now graph command is use full-graph mode when no function name was given:
```
$ uftrace graph
# Function Call Graph for 'hello-cpp' (session: f35f2ad29576eff5)
========== FUNCTION CALL GRAPH ==========
 103.084 us : (1) hello-cpp
  87.596 us :  +-(1) _GLOBAL__sub_I_main
  86.704 us :  | (1) __static_initialization_and_destruction_0
  82.084 us :  | (1) std::ios_base::Init::Init
            :  | 
  15.488 us :  +-(1) main
  14.559 us :    (1) std::operator <<

```

**Comment by honggyukim** [comment]
@namhyung Thanks for doing this work! I think it's most great but I would like to have a way to combine the call graph from the entire tasks. Otherwise, it would be better to show the list of tasks at the top so that user can understand how many sub-tasks they can see from each graph.

**Comment by namhyung** [comment]
How do you want to look like?

**Comment by honggyukim** [comment]
I found that it already combines multi-threaded trace into one single graph. I will tell you later if I have a better idea.  I'm fine with the current output.  Thanks a lot for this work!
