### ISSUE TITLE
not installed bash-completion

### ISSUE THREAD

**Issue by rjs1197** [namhyung/uftrace#234]
Hi~ :-)

I am wondering about the flow of commands executed by 'bash-completion' in `MAKEFILE` as shown below.

```
install: all
	$(Q)$(INSTALL) -d -m 755 $(DESTDIR)$(bindir)
	$(Q)$(INSTALL) -d -m 755 $(DESTDIR)$(libdir)
	$(Q)$(INSTALL) -d -m 755 $(DESTDIR)$(etcdir)/bash_completion.d
        ...
        $(call QUIET_INSTALL, bash-completion)
	$(Q)$(INSTALL) -m 644 $(srcdir)/misc/bash-completion.sh 
        $(DESTDIR)$(etcdir)/bash_completion.d/uftrace
```

First of all I use uftrace as `zsh`.

when using `zsh`, I get the` INSTALL` message. but, it does not actually install.

```
$ sudo make install
  INSTALL  uftrace
  INSTALL  libmcount
  INSTALL  bash-completion
  ...
```
```
$ ls /etc/bash_completion.d/    
apt-linux-mint  cryptdisks  desktop-file-validate  dkms  git-prompt  grub  insserv  libreoffice.sh  openvpn
```

I think, this message will be confusing to users who use shell other than bash.

I wonder if it has the ability to examine the shell during this process.

I don't seem to have the ability to check the shell during the install 'bash-completion' in `MAKEFILE`, right?

I want to solve this problem. Should I fix `MAKEFILE`?

also, I would like to implement the `zsh completion`. but, So if you are looking at this ISSUE, I'd like to get some advice on how to make completion function in `zsh` or other shell.

**Comment by namhyung** [comment]
You can run the make with setting 'V' to 1 in order to verify what is actually going on.

```
$ sudo make install V=1
```

For zsh, I have no idea how completion works.  But you can refer existing scripts for other command like in https://github.com/zsh-users/zsh-completions.

**Comment by rjs1197** [comment]
thank you for answer. :)
