### ISSUE TITLE
Irregular comments next to preprocessors

### ISSUE THREAD

**Issue by qpakzk** [namhyung/uftrace#236]
I discovered a few irregular comments next to preprocessors among header files.

First, almost all #endifs have [comments acknowledging what is matching macro identifiers](https://github.com/namhyung/uftrace/blob/master/uftrace.h#L514), but a few #endifs don't have [them](https://github.com/namhyung/uftrace/blob/master/libtraceevent/event-utils.h#L81). 

Second, some #elses have comments and others have [no comments](https://github.com/namhyung/uftrace/blob/master/utils/list.h#L51).

And some #elses which own comments is [having __!__ in front of macro identifiers](https://github.com/namhyung/uftrace/blob/master/utils/perf.h#L65), but [the others] (https://github.com/namhyung/uftrace/blob/master/utils/script-python.h#L20) not.

Would you(@namhyung) mind adding comments and unifying them?

**Comment by namhyung** [comment]
Actually I don't care much about these irregularities especially #else is placed closed to #if.  Also codes in utils/list.h, utils/rbtree.h and libtraceevent/* are copied from the Linux kernel source and I don't want to touch them unless there's a major issue.

**Comment by qpakzk** [comment]
OK! Thank you.
