### ISSUE TITLE
Dynamic trace issues with gcc on i386 architectures

### ISSUE THREAD

**Issue by ParkHanbum** [namhyung/uftrace#238]
"-pg -fentry -mnop-mcount" need to make 5byte nop instruction. 
but in 32bit, it make only 4byte nop instruction. 

```
=======================================================
080485c5 <main>:
 80485c5:       0f 1f 04 00             nopl   (%eax,%eax,1)
 80485c9:       8d 4c 24 04             lea    0x4(%esp),%ecx
 80485cd:       83 e4 f0                and    $0xfffffff0,%esp
```
It seems that need to patch gcc to use it.
I have fix it with gcc 5.5 and work well. 

```
=======================================================
08048598 <main>:
 8048598:       0f 1f 44 00 01          nopl   0x1(%eax,%eax,1)
 804859d:       8d 4c 24 04             lea    0x4(%esp),%ecx
 80485a1:       83 e4 f0                and    $0xfffffff0,%esp
```

and test result is ok also.

```
m@ubuntu:~/uftrace/tests$ ./runtest.py 136
Test case                 pg             finstrument-fu
------------------------: O0 O1 O2 O3 Os O0 O1 O2 O3 Os
136 dynamic             : OK OK OK OK OK OK OK OK OK OK

```

**Comment by namhyung** [comment]
Oh, I didn't know that and glad to see you fixed it! :)  You can rebase and send the patch to the GCC.

**Comment by ParkHanbum** [comment]
maybe it will be patched in next gcc version.
until then we could not use dynamic trace. 
I'm sad abot that.

**Comment by namhyung** [comment]
Changing compiler might take a long time (even longer to make its way to distros).  But bugs should be fixed ASAP.

**Comment by ParkHanbum** [comment]
@namhyung 
do you want commit about mount-dynamic.c?
it will work well with gcc that patched. 

see the following link for detail:
https://gcc.gnu.org/ml/gcc-patches/2017-11/msg01262.html

**Comment by namhyung** [comment]
Oh, it's applied already, nice!

For uftrace, do you have any workaround for non-patched gcc?

**Comment by ParkHanbum** [comment]
nope... ok. when do I commit that? 
after gcc updated?

**Comment by namhyung** [comment]
Please include it to your series.  Would it be possible for you to detect the error case and disable the dynamic patching internally?

**Comment by ParkHanbum** [comment]
when problem is not fixed, uftrace could not found 5 byte nop instructions.
then it will be exit!

**Comment by namhyung** [comment]
Yep, I think that's enough for us.  Please close this if you don't have no more issue.
