### ISSUE TITLE
-E linux:schedule fails in 4.10 kernel

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#239]
@namhyung `-E linux:schedule` related tests are failed in my Ubuntu 17.04 machine as follows:
```
$ ./runtest -v 163
=========== original ===========
# DURATION    TID     FUNCTION
            [14488] | main() {
            [14488] |   foo() {
            [14488] |     bar() {
   2.053 ms [14488] |       usleep();
   2.054 ms [14488] |     } /* bar */
   2.055 ms [14488] |   } /* foo */
   2.056 ms [14488] | } /* main */

===========  result  ===========
main() {
   foo() {
     bar() {
       usleep();
     } /* bar */
   } /* foo */
 } /* main */
=========== expected ===========
main() {
   foo() {
     bar() {
       usleep() {
         /* linux:schedule */
       } /* usleep */
     } /* bar */
   } /* foo */
 } /* main */
163 event_sched         : NG NG NG NG NG NG NG NG NG NG
```
The tests 163 ~ 167 are all failed.  The kernel version is `4.10.0-35-generic`.
Please take a look at it.

**Comment by namhyung** [comment]
Could you please show me debug messages?

**Comment by honggyukim** [comment]
I don't see any noticeable debug message. But in the buggy case, it doesn't show the below message:
```
fstack: no more perf data
```
The message is only shown in the working case.

**Comment by namhyung** [comment]
Hmm.. it seems debian/ubuntu changes `perf_event_paranoid` setting to 3 to disable it for unprivileged users.  It seems that it affects kernel version prior to 4.0 but I'm not entirely sure.

You can set it to 2 (or less) on your own risk.  Or just do it with sudo.

https://superuser.com/questions/980632/run-perf-without-root-rights
https://www.debian.org/security/2017/dsa-3791

**Comment by honggyukim** [comment]
Thanks for the check. If so, we can add a routine that checks `/proc/sys/kernel/perf_event_paranoid` is less than 3. Otherwise, we can warn it to users.

**Comment by honggyukim** [comment]
At least, we have to make a protect routine for test results.

**Comment by namhyung** [comment]
Well, I don't think we need to protect the test case.  It's not an issue of uftrace, if system was configured not to allow perf system for non-root users, I'd rather let it fail to indicate the problem to users.

Maybe we can add a warning when it failed to open a perf event with "permission denied".

**Comment by honggyukim** [comment]
I'm worrying about the misunderstanding that comes from `NG`. `NG` seems to be the problem of uftrace itself.

**Comment by namhyung** [comment]
Well, I think it's ok as long as it shows a proper warning message when user runs it actually.
