### ISSUE TITLE
kernel trace error in VMware context.

### ISSUE THREAD

**Issue by vngkv123** [namhyung/uftrace#244]
If i set `./uftrace -k [input file]` in VMware context ( specifically which installed VMwareTools ), 
VMware is stopped and some configurations in VMware setting corrupted.

**Test context**

- OS X Vmware Fusion Ubuntu 16.04 LTS Xenial.
- Windows 10 Vmware Workstation 11 Pro Ubuntu 16.04 LTS Xenial

I think maybe if VMwaretools are installed in target machine, collisions between the machine and `uftrace -k` are exist.
So, maybe it trigger target machine's kernel panic or Virtualization error.
I will upload something more specific errors.

**Comment by namhyung** [comment]
Hmm.. could you please verify running (kernel's) ftrace directly also has the problem?

Please run below as root:
```
# cd /sys/kernel/debug/tracing
# echo mono > trace_clock
# echo 1 > tracing_on
# echo function_graph > current_tracer
# cat trace
# echo nop > current_tracer
```

**Comment by taeguk** [comment]
I encountered this issue, too.
My environment is ```Ubuntu 18.04.1 x64``` running on ```Vmware Workstation 14 Player```.
My vmware is stopped when using '-k' option.
And the vmware is also stopped in ```echo function_graph > current_tracer``` when executing the commands above.

**Comment by namhyung** [comment]
Then it's a problem between Vmware and kernel.  Maybe we can skip kernel tracing with a warning if we can detect it runs on Vmware.

**Comment by gy741** [comment]
Hello, @namhyung 
I reported this problem to the ftrace team(Steven Rostedt).
And he modified the VMware source in the kernel.
Applying his patch solves the problem.

**Comment by taeguk** [comment]
@gy741 Wow, great!!

**Comment by honggyukim** [comment]
Great. Thanks for your work!

**Comment by namhyung** [comment]
Can I get a link for the patch?

**Comment by gy741** [comment]
The patch code has not been sent to the kernel git yet.
If he sends the patch code to kernel git, I will leave a link.

**Comment by gy741** [comment]
Hello @namhyung 

It was reflected in the kernel repository.

Link: https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/commit/?id=15035388439f892017d38b05214d3cda6578af64

**Comment by namhyung** [comment]
Thanks for doing that!
