### ISSUE TITLE
[question] Add 'uftrace recv' example

### ISSUE THREAD

**Issue by JangSoJin** [namhyung/uftrace#246]
Hi, I have one question. :)
I want to execute `uftrace recv`. 
When I wrote it, it didn't work. (nothing..)
So...Is this command right? or wrong?

```
$ gcc -pg -o abc abc.c
```

(**One terminal**) 
```
$ uftrace recv -H ubuntu-VirtualBox --run-cmd="uftrace replay"
```
(**the other terminal**) 
```
$ uftrace record abc -H ubuntu-VirtualBox
```

If it is a wrong command, please let me know the correct example..

**Comment by namhyung** [comment]
The recv command aims to be run on a different machine.  For example, it might have no enough space to save uftrace data on a small embedded device.  Then it can send the data through network to a development (host) machine running `uftrace recv`.  The `-H` option is for `uftrace record` to specify the name of the host.

**Comment by JangSoJin** [comment]
Thank you! I will try again. :)

**Comment by namhyung** [comment]
Please see #258.

**Comment by namhyung** [comment]
Oh, now I've found that you used the `-H` option after your program (abc).  Unfortunately uftrace will treat it as an argument of the program (not uftrace) so won't use it.

**Comment by JangSoJin** [comment]
I'll refer to #258 and your comment..Thank you so much!! 😊 I'll try again :)
