### ISSUE TITLE
'recover' trigger makes target binaries with '-finstrument-functions' crash.

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#25]
Since 'recover' is only for recovering original return addresses, it'd be better to ignore or invalidate 'recover' trigger. Binaries compiled with -finstrument-functions crash if 'recover' trigger is enabled.

**Comment by namhyung** [comment]
Argh, right.  It doesn't hook the return address when built with `-finstrument-functions` so 'recover' trigger will access an invalid address.

**Comment by honggyukim** [comment]
Please have a look at #26.
