### ISSUE TITLE
[suggestion] How about make a label for newbies, like 'good first contribution' or 'low hanging fruit'?

### ISSUE THREAD

**Issue by flavono123** [namhyung/uftrace#250]
There are some PRs for minor patches such as fix typo or add to doc a little...
(Surely, they are important PRs!:+1:)

I think, the label 'help wanted' of issues is currently used for above purposes included, but it seems like 'I need an EXPERT!:raising_hand:'

I wish a new label, the EXPERT tags it to feel free to contribute for newbies, and naming of that is just my opinion:joy:

**Comment by namhyung** [comment]
I'll try to find those issues and add the tag.

**Comment by flavono123** [comment]
@namhyung 🙇 Thanks! Hope to come more contributors, more uftrace! 🙌
