### ISSUE TITLE
Print the COMMAND through recording python scripts(`uftrace script`)

### ISSUE THREAD

**Issue by flavono123** [namhyung/uftrace#252]
Strongly inspired by [`pmap`](https://linux.die.net/man/1/pmap), the cmd line tool of the process memory map, I made the uftrace memory map, named `umap.py` run through `uftrace script -S`:

```
$ cat script/umap.py
def uftrace_begin():
    print("<uftace-cmd-options> </bin/name>: memory map")

def uftrace_entry(ctx):
    print('{0:12x}'.format(ctx["address"])\
            + ' ' + '[{0}]'.format(ctx["tid"])\
            + ' ' + " "*ctx["depth"]\
            + ctx["name"] + "()")

def uftrace_exit(ctx):
    pass

def uftrace_end():
    pass

$ uftrace record abc
$ uftrace script -S scripts/umap.py
<uftace-cmd-options> </bin/name>: memory map
561ded6d6812 [16894] main()
561ded6d67b4 [16894]  a()
561ded6d67c8 [16894]   b()
561ded6d67dc [16894]    c()
561ded6d6630 [16894]     getpid()
```

👋 **I'd like to print the command(e.g., `uftrace record abc`)** at the top of the results, in a python script with `uftrace_begin()`, but it is hard coded now.

P.S. And please *advise* me on followed:
+ Know the address of functions is useful?🤔; I just do above since `ctx` has it
+ Ordering by addresses is required?🤔, then a depth of functions(name) is meaningful?🤔
+ Any other data to show exists?🤔

**Comment by namhyung** [comment]
I don't get the purpose of this script.  The address is for function and what do you want to do it?  The given information itself has no meaning, you have to find out a way to organize them and make useful info from them.

By the way, passing more info to `uftrace_begin()` is a good item for the "first time contribution". :)

**Comment by flavono123** [comment]
@namhyung Thanks for reviews! 😍 
Adding to pass the command information to a python script is my works. 😂 

One more question to clarify, the `ctx` in `man uftrace-script` is just *mnemonic(?).* Confusing, since `list` and `value` are not keywords of neither C nor Python. 
I think `struct script_context`, in `cmd-script.c`, is that:
```
struct script_context sc_ctx = { 
                          .tid       = task->tid,
                          .depth     = depth,  /* display depth */
                          .timestamp = rstack->time,
                          .address   = rstack->addr,
                          .name      = symname,
                  };
```

And/Or the python dictionary is exists? May the @honggyukim knows about it?🤔

**Comment by honggyukim** [comment]
> One more question to clarify, the ctx in man uftrace-script is just mnemonic(?). Confusing,

It makes sense somehow.

> since list and value are one of keywords of neither C nor Python.

I think it's fine as is.

> And/Or the python dictionary is exists? May the @honggyukim knows about it?

I don't clearly understand your point. Could you explain more in details?

**Comment by flavono123** [comment]
@honggyukim Oh, sorry for lack of my English expressions 😅 
I mean the `ctx` in `man uftrace-script` and the `struct script_context` in `cmd-script.c`, followed, are same?(I think they are):

```
$ cat cmd-script.c
...
struct script_context sc_ctx = { 
                          .tid       = task->tid,
                          .depth     = depth,  /* display depth */
                          .timestamp = rstack->time,
                          .address   = rstack->addr,
                          .name      = symname,
                  };
```

```
$ man uftrace-script
...
EXAMPLES
...
             script_context = {
                  int       tid;
                  int       depth;
                  long      timestamp;
                  long      duration;    # exit only
                  long      address;
                  string    name;
                  list      args;        # entry only (if available)
                  value     retval;      # exit  only (if available)
              };

```

**Comment by namhyung** [comment]
Yes, they are the same thing.
