### ISSUE TITLE
Question about -S script option

### ISSUE THREAD

**Issue by vngkv123** [namhyung/uftrace#262]
Can i get register state by using python script?

If it can, i want to make binary analysis python scripts instead of inserting vulnerable function detection code in uftrace source file.

**Comment by namhyung** [comment]
Unfortunately there's no way to get full register contents from a script.  But passing argument is done via register on x86_64 so you may get a part of registers used for arguments.

**Comment by vngkv123** [comment]
Umm... Can i get some specific memory value by using python script?
ex) printf("Hello, world!\n"); -> "Hello, world!\n" string is actually in the `.rodata` section.
     So, adding `-T printf@filter,arg1` option is just show string address in memory.
     There is another way to get specific string value?

**Comment by namhyung** [comment]
Please use `arg1/s` instead of `arg1` to get the string.
