### ISSUE TITLE
uftrace appears not to correctly handle C++ programs that rethrow exceptions

### ISSUE THREAD

**Issue by taura** [namhyung/uftrace#285]
It appears that uftrace does not correctly handle programs that
rethrow an exception.  Here is a simplest program that can reproduce
it.  

<pre>
#include &lt;stdio.h&gt;

struct exc { };

void f() {
  try {
    printf("f throws exc\n");
    throw exc();
  } catch (const exc& e) {
    printf("f caught exc and rethrows it\n");
    throw;
  }
}

int main() {
  try {
    printf("main calls f\n");
    f();
  } catch (const exc& e) {
    printf("main caught exc\n");
  }
  return 0;
}
</pre>

(1) compile
`$ g++ -O0 -g -pg a.cc`

(2) the expected behavior (run without uftrace)

<pre>
$ ./a.out
main calls f
f throws exc
f caught exc and rethrows it
main caught exc
</pre>

(3) what happens with uftrace
<pre>
$ ./uftrace record ./a.out
main calls f
f throws exc
f caught exc and rethrows it
terminate called after throwing an instance of 'exc'
process crashed by signal 6: Aborted (si_code: -6)
child terminated by signal: 6: Aborted
</pre>

(4) FYI, If I compile the a.cc with -O3 option, it still causes an error, but the error is a bit different, if that matters. 
<pre>
$ ./uftrace record ./a.out
main calls f
f throws exc
f caught exc and rethrows it
Segmentation fault: address not mapped (addr: 0xd)
child terminated by signal: 11: Segmentation fault
</pre>

(5) other relevant info

<pre>
$ git log -n 1
commit 6382e1e57204bf5432c7fd7997273dec6e2a0409
Merge: 3c6a729 a1fdd36
Author: Namhyung Kim <namhyung@gmail.com>
Date:   Mon Dec 11 14:57:18 2017 +0900

    Merge branch 'trigger-update'
    
    Add 'd' format specifier and show long unsigned int as hex.
    
    Signed-off-by: Namhyung Kim <namhyung@gmail.com>
</pre>

<pre>
$ ./uftrace -V
uftrace v0.8.2-12-g6382
</pre>

<pre>
$ g++ -v
namopa:uftrace$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 6.3.0-12ubuntu2' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 6.3.0 20170406 (Ubuntu 6.3.0-12ubuntu2) 
</pre>

FYI, I tried to dig into it with gdb and learned that it wraps __cxa_throw so that it corrects return addresses of the functions in the stack.  I am not sure but in the same token, it might be necessary to also wrap __cxa_rethrow.  As I do not know exactly how C++ exception works and how it interacts with uftrace, I couldn't get deeper.

I encountered this issue when I tried to trace a large program (libreoffice).  uftrace is a great tool to investigate the internal workings of a software.

**Comment by namhyung** [comment]
Thank you for using uftrace and reporting the issue.  The C++ exception is a complex beast and currently uftrace only supports basic cases.  I was able to reproduce it in my setup, and will investigate more with your example code.

**Comment by namhyung** [comment]
Could you please check [check/exception-rethrow](https://github.com/namhyung/uftrace/compare/check/exception-rethrow) branch?  Although it cannot show the exact try-catch structure, it works for your simple case now. :)

```
$ uftrace --auto-args rethrow
main calls f
f throws exc
f caught exc and rethrows it
main caught exc
# DURATION     TID     FUNCTION
            [  4427] | main() {
  10.473 us [  4427] |   puts("main calls f") = 13;
            [  4427] |   f() {
   0.693 us [  4427] |     puts("f throws exc") = 13;
   2.070 us [  4427] |     __cxa_allocate_exception();
  31.781 us [  4427] |     __cxa_throw();
   0.703 us [  4427] |     puts("f caught exc and rethrows it") = 29;
  18.466 us [  4427] |     __cxa_rethrow();
  60.250 us [  4427] |   } /* f */
   0.540 us [  4427] |   puts("main caught exc") = 16;
  80.922 us [  4427] | } /* main */
```

**Comment by taura** [comment]
Thanks.  It worked with the program I posted.  When I go ahead with libreoffice calc, which I originally tried to look into using uftrace, it unfortunately got a segmentation fault.  I haven't looked into it (not even sure if it is still an exception handling issue or something else).  I'll come back if I get additional information.

**Comment by namhyung** [comment]
Thanks, I've merged this change into master but it won't show the throw functions as it caused a problem with `-finstrument-functions`.  If you find any exception handling issue with it, please reopen.
