### ISSUE TITLE
[question] automatic argument parsing work on shared library?

### ISSUE THREAD

**Issue by ParkHanbum** [namhyung/uftrace#288]
Hello. 
when target program and shared library have build with -pg option, --auto-args work on share library?
have used -g option, too.

**Comment by honggyukim** [comment]
Hi @ParkHanbum,
`--auto-args` is only for displaying args/retvals of well known shared library. It doesn't require shared library to be compiled with `-pg`.

**Comment by ParkHanbum** [comment]
@honggyukim ok I see. is it possible parsing and using dwarf info current?

**Comment by honggyukim** [comment]
You have to checkout the branch [review/dwarf-argspec-v3](https://github.com/namhyung/uftrace/compare/review/dwarf-argspec-v3) because it's not merged yet. And the user space functions doesn't show their args/retvals with `--auto-args`. You have to use `-A . -R .` instead.

**Comment by namhyung** [comment]
In the v3, it cannot use dwarf info in a library yet.
