### ISSUE TITLE
need usage about using uftrace with target program command line options.

### ISSUE THREAD

**Issue by ParkHanbum** [namhyung/uftrace#289]
Hello. I have used uftrace for tracing dalvikvm. it is very useful!
but when use uftrace with target program command line options, it is not work well. 
I think I don't understand about the usage that with target program command line options.

would you please review below command?

```
uftrace host/linux-x86/bin/dalvikvm
```
this is work... but I need more options for dalvikvm.

```
m@m-VirtualBox:~/out$ uftrace host/linux-x86/bin/dalvikvm -Xbootclasspath host/linux-x86/framework/core-hostdex.jar host/linux-x86/framework/bouncycastle-hostdex.jar host/linux-x86/framework/apache-xml-hostdex.jar -cp foo1.jar foo1
Unrecognized option '-Xbootclasspath'

dalvikvm: [options] class [argument ...]
dalvikvm: [options] -jar file.jar [argument ...]

The following standard options are recognized:
  -classpath classpath
  -Dproperty=value
  -verbose:tag  ('gc', 'jni', or 'class')
  -ea[:<package name>... |:<class name>]
  -da[:<package name>... |:<class name>]
```

this is not work... it seems to be fail passing options to dalvikvm.

**Comment by namhyung** [comment]
Hmm.. did you mean running dalvikvm directly with same option is ok?

**Comment by ParkHanbum** [comment]
@namhyung 
I have checked it again, and I have found some mistake about environment setup. it is not associate with uftrace. sorry!
