### ISSUE TITLE
With script and --record option, sometimes uftrace doesn't store task data files.

### ISSUE THREAD

**Issue by bavernet** [namhyung/uftrace#294]
When using script command with --record option, sometimes uftrace doesn't store task data files.
I compiled uftrace and tested it as follows:
```
$ gcc -pg tests/s-forkexec.c -o t-forkexec
$ uftrace script -S ./scripts/trace-memcpy.py --record t-forkexec 
0 times memcpy called
0 bytes copied
$ uftrace replay 
$ uftrace replay -v
uftrace: reading uftrace.data/task.txt file
fstack: setup argspec and/or retspec
uftrace: failed to search perf data file
fstack: cannot open task data file: uftrace.data/16848.dat: No such file or directory
fstack: cannot open task data file: uftrace.data/16855.dat: No such file or directory
fstack: fixup for some special functions

$ uftrace --version
uftrace v0.8.2-56-g06ee8
```

**trace-memcpy.py** script is to trace **memcpy** function. But, there is no **memcpy** calls in **t-forkexec**
In my opinion, when there is no trace information, uftrace misses storing task data files.

**Comment by namhyung** [comment]
Yep, the task data files are created when it saves trace info.  So no data, no files.

**Comment by bavernet** [comment]
I misunderstood that `--record` option was identical with `record` command.

**Comment by namhyung** [comment]
Oh, the `--record` option does same thing with the `record` command, but it didn't generate any data probably due to filter settings.  Does your script have `uftrace-option` in it?

**Comment by honggyukim** [comment]
@namhyung He used `trace-memcpy.py` that is included in `scripts` directory.
https://github.com/namhyung/uftrace/blob/master/scripts/trace-memcpy.py

**Comment by namhyung** [comment]
@honggyukim thanks, I forgot to check it.  It indeed has a filter setting for memcpy so other functions won't be recorded hence no data.

**Comment by Taeung** [comment]
Hum.. Don't we need to modify the below explanation of script man page ?
I thought it seems a bit ambiguous.. what do you think about that ? @honggyukim @namhyung 
```
       --record COMMAND [command-options]
              Record a new trace before running a given script.
```

**Comment by namhyung** [comment]
Could you suggest a better description?

**Comment by namhyung** [comment]
Please send a PR if you could come up with a better description, thanks.
