### ISSUE TITLE
Exception catched in function still throw out causing the program terminating

### ISSUE THREAD

**Issue by Xavier1994** [namhyung/uftrace#31]
```c++
void test()
{    
    try {
    ┊   throw exception();
    }   
    catch (exception& e)
    {   
    ┊   cout << "exception catched" << endl;
    }                                                                                                                                                                        
    return;
}       
        
int main()
{       
    test();
    return 0;
}
```
I have a file like above, expected the exception can be catched, when I run without uftrace, it did. but failed  running with uftrace. The exception can not be catched running with uftrace

**Comment by namhyung** [comment]
Thanks for the report.  I assume you are using `-pg` compiler option to build your program.  The C++ exception handling involves stack unwinding and it conflicts to the uftrace which also does some tricks with the return address on the stack.  To avoid this conflict you can build your application with `-finstrument-functions` instead of `-pg` and run uftrace with `--no-libcall` not to hook return address of library functions too.

```
$ g++ -finstrument-functions exception.cpp

$ uftrace --no-libcall a.out
exception catched
# DURATION    TID     FUNCTION
            [23396] | test() {
 132.483 us [23396] |   __static_initialization_and_destruction_0();
 134.235 us [23396] | } /* test */
            [23396] | main() {
            [23396] |   test() {
   0.103 us [23396] |     std::exception::exception();
  83.578 us [23396] |   } /* test */
  84.064 us [23396] | } /* main */
```

I'd like to remove this limitation of the `-pg` built binaries too.  But it requires very deep knowledge of C++ exception handling and probably some hacks.  Let's see what I can do.

**Comment by honggyukim** [comment]
One more note is that -pg option also works when --no-libcall is given.
```
$ g++ -pg exception.cpp

$ uftrace --no-libcall ./a.out
exception catched
# DURATION    TID     FUNCTION
            [ 2641] | test() {
 166.445 us [ 2641] |   __static_initialization_and_destruction_0();
 168.116 us [ 2641] | } /* test */
            [ 2641] | main() {
            [ 2641] |   test() {
   0.257 us [ 2641] |     std::exception::exception();
  93.948 us [ 2641] |   } /* test */
  94.699 us [ 2641] | } /* main */
```

**Comment by namhyung** [comment]
@honggyukim maybe it'd only work in limited situations like exception being thrown and caught in a same funtion.  When I tested an other case, it aborted in an exception.

I pushed a code that hooks the low-level C++ exception handling mechanism.  Ideally it needs to cowork with the personality routine but I just tried something looks simpler.  On my system, it seems to work with `-pg`-built binaries.  Please try `check/exception-v1` branch.

```
$ uftrace exception
exception catched
# DURATION    TID     FUNCTION
   2.437 us [20356] | __cxa_atexit();
            [20356] | test() {
            [20356] |   __static_initialization_and_destruction_0() {
 144.905 us [20356] |     std::ios_base::Init::Init();
   0.329 us [20356] |     __cxa_atexit();
 147.268 us [20356] |   } /* __static_initialization_and_destruction_0 */
 147.740 us [20356] | } /* test */
            [20356] | main() {
            [20356] |   test() {
   2.048 us [20356] |     __cxa_allocate_exception();
   0.144 us [20356] |     std::exception::exception();
   6.365 us [20356] |     __gxx_personality_v0();
   2.332 us [20356] |     __gxx_personality_v0();
  18.762 us [20356] |     std::operator <<();
  14.916 us [20356] |     std::basic_ostream::operator <<();
   1.042 us [20356] |     std::exception::~exception();
  88.872 us [20356] |   } /* test */
  89.221 us [20356] | } /* main */
   2.794 us [20356] | std::ios_base::Init::~Init();
```

**Comment by namhyung** [comment]
It seems like that `-pg` built binaries still have problems (esp with optimizations).  Anyway `-finstrument-functions` would work anyway with the commit b1057f8.
