### ISSUE TITLE
uftrace does not build on Mac OS

### ISSUE THREAD

**Issue by jmastrogiulio** [namhyung/uftrace#311]
I need to compile uftrace using libelf.a, but it currently only builds using libelf.so.

**Comment by honggyukim** [comment]
Hi @jmastrogiulio, thanks for using uftrace. In order to link `libelf.a` to uftrace, it has to be compile with `-fPIC` because `libelf` is also used for preloaded libraries such as `libmcount.so`.

**Comment by jmastrogiulio** [comment]
HI @honggyukim, thanks for your quick reply.  Do I need to modify the configure script in order to compile with -fPIC.  Can you describe how to configure and compile ufrace using -fPIC?

**Comment by honggyukim** [comment]
It requires some modification as of now but did you follow the instructions in [BUILD WITH ELFUTILS (libelf)](https://github.com/namhyung/uftrace/blob/master/INSTALL.md#build-with-elfutils-libelf)?

**Comment by jmastrogiulio** [comment]
No, I have followed those instruction with BUILD_WITH_ELFUTILS. I will do it now. Do I need to export all the variables shown in the instructions (i.e. set CROSS_COMPILE, etc).

**Comment by jmastrogiulio** [comment]
Actually I had tried running that script, but it didn't work because I'm trying to compile uftrace on mac os x.  I had to build libelf.a using another method.

**Comment by jmastrogiulio** [comment]
I'm basically trying to use uftrace on mac os x and I ran into these issues.

**Comment by jmastrogiulio** [comment]
i have libelf.a installed in /usr/local/lib and I would like to compile uftrace by linking /usr/local/lib/libelf.a

**Comment by honggyukim** [comment]
Ah.. ufrace works only on Linux as of now. Sorry about that.

**Comment by honggyukim** [comment]
Mac doesn't use ELF file format, it uses Mach-O file format instead.

**Comment by jmastrogiulio** [comment]
Ah ok.  Thanks for clarifying this.

**Comment by honggyukim** [comment]
Thank you too. I also would like to port uftrace to Mac OS but we cannot spend more resource on it yet.
