### ISSUE TITLE
? option doesn't work in zsh 

### ISSUE THREAD

**Issue by qpakzk** [namhyung/uftrace#319]
Hello,
I used zsh in Ubuntu 16.04.3 LTS. 
When I use ```-?``` option on the zsh, the result is below.

<img width="348" alt="zsh opt" src="https://user-images.githubusercontent.com/20490285/35921721-d2561fae-0c5e-11e8-8977-77c6a3fcdcd6.png">

In other words, zsh doesn't catch ```-?``` option.

**Comment by namhyung** [comment]
Hmm.. as far as I know it came from argparse in glibc, not from shell.  Does it work on bash?  Does zsh treat it specially?

**Comment by qpakzk** [comment]
Yes. When I use 'uftrace -?' on bash, it works well. Below is the result.

<img width="702" alt="screenshot 2018-02-08 13 46 53" src="https://user-images.githubusercontent.com/20490285/35956096-e32e63ae-0cd6-11e8-98c4-5348037ed091.png">

**Comment by chneukirchen** [comment]
Set `NONOMATCH` or quote the flag: `-\?`.

This is not a uftrace problem.

**Comment by qpakzk** [comment]
It works. Thank you!
<img width="688" alt="screenshot 2018-02-09 04 06 57" src="https://user-images.githubusercontent.com/20490285/35992810-b33edaca-0d4e-11e8-888e-f2ec5ce01c3d.png">

**Comment by namhyung** [comment]
@chneukirchen thanks for pointing that out.

In fact, I'd like to have a short option of the help message as `-h` instead (or both) of `-?`.

**Comment by qpakzk** [comment]
How about replacing ```-h``` with ```-?``` in the code when entering ```-h```?

**Comment by namhyung** [comment]
@qpakzk what about adding explicit `-h` option for help (although duplicated)?

**Comment by namhyung** [comment]
@qpakzk anyway I'd like to close this issue.  If you want to work on the help refactoring, please open another issue for that, thanks!
