### ISSUE TITLE
passing more info into script

### ISSUE THREAD

**Issue by namhyung** [namhyung/uftrace#320]
Sometimes a script needs to know more about the execution context.  Provide the info to `uftrace_begin()` so that it can control the behavior based on the info.  Currently following information is provided.

* version: uftrace version
* recording: whether it's called from record
* args: a list of command line arguments

The code is available at [review/script-info-v1](https://github.com/namhyung/uftrace/compare/review/script-info-v1).

Example:

```
$cat info.py
def uftrace_begin(ctx):
    print(ctx["version"])
    print(ctx["recording"])
    print(ctx["args"])

def uftrace_entry(ctx):
    pass
def uftrace_exit(ctx):
    pass

$ uftrace -S info.py tests/t-abc 1 2 3
v0.8.3-16-gc5a1
True
('tests/t-abc', '1', '2', '3')

$ uftrace script -S info.py -d abc.data x y
v0.8.3-16-gc5a1
False
('x', 'y')
```

**Comment by honggyukim** [comment]
Thanks for doing this! But I have two comments on this.
1. in script command, I think we better show the recorded arguments in `args` field.
In recording the arguments are shown correctly.
```
$ uftrace record -S info.py t-abc A B C
v0.8.3-16-g1fc9
True
('t-abc', 'A', 'B', 'C')
```
But I expect to see the recorded arguments `A B C`, not `X Y Z` in `script` command.
```
$ uftrace script -S info.py X Y Z
v0.8.3-16-g1fc9
False
('X', 'Y', 'Z')
```

2. I think we need to set recording field to false explicitly in `cmd-script.c`
```
diff --git a/cmd-script.c b/cmd-script.c
index 0e2fc48..8a34aa0 100644
--- a/cmd-script.c
+++ b/cmd-script.c
@@ -135,6 +135,7 @@ int command_script(int argc, char *argv[], struct opts *opts)
                .version        = UFTRACE_VERSION,
                .argc           = argc,
                .argv           = argv,
+               .recording      = false,
        };

        if (!SCRIPT_ENABLED) {
```
Thanks!

**Comment by honggyukim** [comment]
Ah.. Thinking again, the arguments in `script` command can be used replay time filtering argument. In this use case, I agree on it.

**Comment by elfring** [comment]
* Can it make sense to pass the desired information by any other data structure than [a Python dictionary](https://github.com/namhyung/uftrace/compare/review/script-info-v1#diff-6453549489d5c9d48d7f99783475b187R629 "Construction of a dictionary")?
* How do you think about to work better with classes (and corresponding methods)?

**Comment by namhyung** [comment]
@honggyukim maybe it'd be better support both arguments (if available).  And I don't want to set zero-initialized value explicitly.

@elfring what's the problem of the dictionary?  It's very flexible to add more data later.  And I don't want to enforce the OOP-style unnecessarily.

**Comment by honggyukim** [comment]
> And I don't want to set zero-initialized value explicitly.

@namhyung I'm okay then if you think so.

**Comment by elfring** [comment]
>what's the problem of the dictionary?

* I have got the impression that information is copied into this data structure. I prefer to avoid unnecessary data duplication.

* Dictionaries are mutable. - Would you really like to support that the version information can be changed by this programming interface?


>It's very flexible to add more data later.

There is similar flexibility also with other means.


>And I don't want to enforce the OOP-style unnecessarily.

I prefer object-oriented data management generally.

**Comment by Taeung** [comment]
@namhyung , I tested this code and I checked it works well.
And I read code of this changes. IMHO, Looks fine.

But I thought you already have a plan adding the above `info.py` to a `scripts/` folder
and a test script about this, right ?

In addition, when running a python script, if some errors occur,
I thought the error messages should be printed by [utils/script-python.c:450](https://github.com/namhyung/uftrace/blob/master/utils/script-python.c#L450) 
Isn't it ?

For example, if a python script can bring on error like below,
I expected the error message like `"NameError: name 'a' is not defined"`
```patch
--- old.info.py	2018-02-22 01:38:57.406516140 +0900
+++ info.py	2018-02-22 01:18:04.225732101 +0900
@@ -1,4 +1,5 @@
 def uftrace_begin(ctx):
+    a=a[0]
     print(ctx["version"])
     print(ctx["recording"])
     print(ctx["args"])
```

**Comment by elfring** [comment]
>I don't care about the duplication and mutability.

Will you ever care for any software design which could be safer and more efficient at this place?

**Comment by namhyung** [comment]
I think that sharing those info with scripts is much more dangerous.  So a copy is passed and then I don't care about the immutability of the copy.

**Comment by namhyung** [comment]
Updated [review/script-info-v2](https://github.com/namhyung/uftrace/compare/review/script-info-v2).

Changelog:
 * add test case
 * code refactoring
 * add some debug message

**Comment by Taeung** [comment]
@namhyung , In addition, what do you think about including this below patch ? or to another PR ?
Just calling `__PyObject_GetAttrString()` can generate an error like:
" AttributeError: 'module' object has no attribute 'UFTRACE_FUNCS' "

So, how about previously check it by `__PyObject_HasAttrString()` ?
```patch
diff --git a/utils/script-python.c b/utils/script-python.c
index e37d499..0986237 100644
--- a/utils/script-python.c
+++ b/utils/script-python.c
@@ -42,6 +42,7 @@ static PyAPI_FUNC(PyObject *) (*__PyErr_Occurred)(void);
 static PyAPI_FUNC(void) (*__PyErr_Print)(void);
 static PyAPI_FUNC(void) (*__PyErr_Clear)(void);
 
+static PyAPI_FUNC(PyObject *) (*__PyObject_HasAttrString)(PyObject *, const char *);
 static PyAPI_FUNC(PyObject *) (*__PyObject_GetAttrString)(PyObject *, const char *);
 static PyAPI_FUNC(int) (*__PyCallable_Check)(PyObject *);
 static PyAPI_FUNC(PyObject *) (*__PyObject_CallObject)(PyObject *callable_object, PyObject *args);
@@ -120,6 +121,7 @@ static int load_python_api_funcs(void)
         INIT_PY_API_FUNC(PyErr_Print);
         INIT_PY_API_FUNC(PyErr_Clear);
 
+        INIT_PY_API_FUNC(PyObject_HasAttrString);
         INIT_PY_API_FUNC(PyObject_GetAttrString);
         INIT_PY_API_FUNC(PyCallable_Check);
         INIT_PY_API_FUNC(PyObject_CallObject);
@@ -672,8 +674,8 @@ int script_init_for_python(struct script_info *info)
         }
 
         /* check if script has its own list of functions to run */
-        PyObject *filter_list = __PyObject_GetAttrString(pModule, "UFTRACE_FUNCS");
-        if (filter_list) {
+        if (__PyObject_HasAttrString(pModule, "UFTRACE_FUNCS")) {
+                PyObject *filter_list = __PyObject_GetAttrString(pModule, "UFTRACE_FUNCS");
                 int i, len;
 
                 /* XXX: type checking is hard */
```

**Comment by namhyung** [comment]
I added `__PyErr_Clear()` before calling `uftrace_begin` to remove previous error messages.  But your change is better IMO.  Could you please add it for `get_python_callback()` too?

**Comment by Taeung** [comment]
Sure, how about this ?
```patch
diff --git a/utils/script-python.c b/utils/script-python.c
index e37d499..2a8bafc 100644
--- a/utils/script-python.c
+++ b/utils/script-python.c
@@ -42,6 +42,7 @@ static PyAPI_FUNC(PyObject *) (*__PyErr_Occurred)(void);
 static PyAPI_FUNC(void) (*__PyErr_Print)(void);
 static PyAPI_FUNC(void) (*__PyErr_Clear)(void);
 
+static PyAPI_FUNC(PyObject *) (*__PyObject_HasAttrString)(PyObject *, const char *);
 static PyAPI_FUNC(PyObject *) (*__PyObject_GetAttrString)(PyObject *, const char *);
 static PyAPI_FUNC(int) (*__PyCallable_Check)(PyObject *);
 static PyAPI_FUNC(PyObject *) (*__PyObject_CallObject)(PyObject *callable_object, PyObject *args);
@@ -120,6 +121,7 @@ static int load_python_api_funcs(void)
         INIT_PY_API_FUNC(PyErr_Print);
         INIT_PY_API_FUNC(PyErr_Clear);
 
+        INIT_PY_API_FUNC(PyObject_HasAttrString);
         INIT_PY_API_FUNC(PyObject_GetAttrString);
         INIT_PY_API_FUNC(PyCallable_Check);
         INIT_PY_API_FUNC(PyObject_CallObject);
@@ -633,6 +635,10 @@ int python_atfork_prepare(void)
 
 static PyObject * get_python_callback(char *name)
 {
+        if (!__PyObject_HasAttrString(pModule, name)) {
+                pr_dbg("%s function doesn't exist\n", name);
+                return NULL;
+        }
         PyObject *func = __PyObject_GetAttrString(pModule, name);
 
         if (func && !__PyCallable_Check(func)) {
@@ -672,8 +678,8 @@ int script_init_for_python(struct script_info *info)
         }
 
         /* check if script has its own list of functions to run */
-        PyObject *filter_list = __PyObject_GetAttrString(pModule, "UFTRACE_FUNCS");
-        if (filter_list) {
+        if (__PyObject_HasAttrString(pModule, "UFTRACE_FUNCS")) {
+                PyObject *filter_list = __PyObject_GetAttrString(pModule, "UFTRACE_FUNCS");
                 int i, len;
 
                 /* XXX: type checking is hard */
```

**Comment by elfring** [comment]
>I think that sharing those info with scripts is much more dangerous.

Why are you so concerned there?


>So a copy is passed and then I don't care about the immutability of the copy.

I am curious on how the circumstances will evolve so that this data handling can change in other ways.

**Comment by namhyung** [comment]
@elfring What's the best way you think in this case?

**Comment by elfring** [comment]
I presented a bit of my imaginations about software design approaches which I would find more appropriate. The general development challenge is to achieve consensus on corresponding data structures.

**Comment by namhyung** [comment]
Pushed [review/script-info-v3](https://github.com/namhyung/uftrace/compare/review/script-info-v3)

Changelog
 * check (python) attribute before access (by Taeung)
 * add `strv` utility functions

@elfring I'd like to close this issue with the v3 unless you suggest a better alternative.

**Comment by elfring** [comment]
I propose to construct a class hierarchy as a better alternative for the attempt to introduce just another Python dictionary. I imagine that [higher level data modelling](https://en.wikipedia.org/wiki/Data_modeling "Description for approaches around data modelling") will be more appropriate.

**Comment by namhyung** [comment]
I don't know how to construct a class hierarchy with this.  Could you please show me an example script using the class hierarchy (assuming it's already implemented)?

**Comment by elfring** [comment]
>I don't know how to construct a class hierarchy with this.

I hope that involved software developers can agree to use [a more object-oriented design](https://en.wikipedia.org/wiki/Object-oriented_design "Description for the usage of object-oriented design").
* A few needed objects were identified already.
* I might be harder to achieve consensus on further data structure adjustments.
* [Additional development tools](https://en.wikipedia.org/wiki/Unified_Modeling_Language "Description for the usage of the unified modelling language") can make the introduction of a higher level software architecture (and [better collaboration with scripting languages](https://en.wikipedia.org/wiki/SWIG "Using the simplified wrapper and interface Generator")) more convenient to some degree.

**Comment by namhyung** [comment]
I'm not sure OOP is always a win and I don't know which objects are identified and how they can be invoked.

**Comment by elfring** [comment]
>I'm not sure OOP is always a win

You can get [more control over the data exchange](https://en.wikipedia.org/wiki/Object-oriented_programming#Features "Using object-oriented programming") than with the approach around a Python dictionary programming interface.


>and I don't know which objects are identified

Examples:
* Command arguments
* Record information
* Version data


>and how they can be invoked.

Are you used to the notation “`value = object.method(parameters)`”?

**Comment by namhyung** [comment]
I don't need the control.

Construct a class using those info is easy.  What I don't get is the whole picture of the script handling in an OOP way.  So I asked you an (ideal) example script you think of.

**Comment by elfring** [comment]
>I don't need the control.

I wonder about this view. - I am curious on how the different needs will be better clarified for interested software developers.


>Construct a class using those info is easy.

Such feedback sounds promising. - But there are further design challenges to consider.


>What I don't get is the whole picture of the script handling in an OOP way.

I find this view strange.

A programming language like [Python supports object-orientation directly](https://docs.python.org/3/tutorial/classes.html "Support for object-orientation by Python"). (I would appreciate to use this programming style also with other scripting languages.)

**Comment by namhyung** [comment]
I don't need the control because I don't want to *exchange* data between uftrace and script.  I just want script to see the info but don't want it to change so that uftrace is not affected by the change.

If we decide to support OOP for scripts, I'd like to convert it for whole not just a part of it.  But I don't know how to control script execution from uftrace in that way.

**Comment by elfring** [comment]
>I just want script to see the info but don't want it to change so that uftrace is not affected by the change.

I would like to support this view to some degree.


>If we decide to support OOP for scripts, I'd like to convert it for whole not just a part of it.

Such a development approach would be nice.


>But I don't know how to control script execution from uftrace in that way.

* Do we need to try any other communication tools out for better clarification of this information?
* Can corresponding class hierarchies be designed anyhow?

**Comment by namhyung** [comment]
What kind of tools do you mean?  Anyway I'd really appreciate if you could come up with a hierarchy.

**Comment by elfring** [comment]
>What kind of tools do you mean?

Examples:
* Telephone call
* Unified modelling language
* [Simplified wrapper and interface generator](http://www.swig.org/tutorial.html "Demonstration for SWIG usage")


>Anyway I'd really appreciate if you could come up with a hierarchy.

I am waiting for more promising feedback on your readiness to invest additional developments efforts for object-oriented software design.
The collaboration can eventually grow then.

**Comment by namhyung** [comment]
Well, I think that's ok to change it to OOP if it makes users writing their scripts more easily.  But I need to see how it can do since I have no idea yet.

**Comment by elfring** [comment]
>… I have no idea yet.

Are you used to working with classes in a programming language like Python?

**Comment by namhyung** [comment]
I don't need it - I learned OOP long ago but didn't have a chance working with it.

**Comment by elfring** [comment]
This is another promising information.
* Would you like to pick up the chance up to advance object-oriented programming also with your evolving software?
* Can any more OOP practice improve the clarification of design aspects?

**Comment by namhyung** [comment]
Well, I don't plan to learn more about OOP as of now.

**Comment by elfring** [comment]
I guess that [such kind of learning reluctance](https://www.harvardbusiness.org/blog/importance-practice-%E2%80%93-and-our-reluctance-do-it "Article “The Importance of Practice – and Our Reluctance to Do It” by Jennifer Long (2016-04-27)") will hinder better development also for this software.

**Comment by namhyung** [comment]
If you don't come up with a new design or patch, I'd like to merge the v3, thanks.

**Comment by elfring** [comment]
Please introduce a corresponding class for safe management of context data.
There are development tools available which can help for such a task.

**Comment by elfring** [comment]
I prefer a context management class that will be different from a “dictionary”.

**Comment by elfring** [comment]
I am still curious if safer object-orientation will ever be taken into account (besides Python dictionaries) also for this software.
