### ISSUE TITLE
stuck with the error unable to proceed 

### ISSUE THREAD

**Issue by RavikumarTulugu** [namhyung/uftrace#323]
I repeatedly get this error, i use LD_PRELOAD to point to the libmcount-fast.so library in a custom path. 
the application runs fine, but when the application exits, i get the below error and the trace is empty. 
Please advise. 
uftrace: /home/ravi/uftrace-0.8.1/cmd-record.c:1279:save_session_symbols
 ERROR: cannot find map files: Success

**Comment by honggyukim** [comment]
Hi @RavikumarTulugu, it would be helpful if you run uftrace with `-vv` and show the execution log.

**Comment by namhyung** [comment]
@RavikumarTulugu uftrace expects libmcount to save a memory map file in the data directory.  But why did you use `LD_PRELOAD` manually?  Once you installed uftrace you don't need to do it by yourself.
