### ISSUE TITLE
problem on function returning floating-point

### ISSUE THREAD

**Issue by yuanshuoastro** [namhyung/uftrace#329]
Dear Uftrace author(s),

I would like to trace a executabe which including a input file, like
`./a.out input.txt
`
the a.out will firstly read parameters in input.txt then run. 

but I went wrong when 
`uftrace ./a.out input.txt`

the a.out say that it did not read input.txt well. but without uftrace it runs well

Could help me?

Thank you very much.

**Comment by honggyukim** [comment]
Hi @yuanshuoastro,
I would be more helpful if you can share the program source code so that we can reproduce the same problem. Thanks.

**Comment by yuanshuoastro** [comment]
Hi @honggyukim ,
Thanks for your reply. 
Here I add the zip enclose.
[class263.zip](https://github.com/namhyung/uftrace/files/1803145/class263.zip)

A short summay:

1.  the codes (in zip file) is a gcc program running under Ubunt17.10
2. The execuable is named  `class`, by gcc-7 -gp (see more flags in Makefile)
3. The normal running is `./class lcdm.ini`, and works well.
4. Using the last version of uftrace will broken the running by arsing ErroMessege in class.
5. Using uftrace version v0.6 from` apt-get install` look fine.

Thank you very much!
Shuo
 - - - - 
 
Details are listed here:


Please let me show how the error happened. 

unzip this file, you can use the Makefile to build.

>make clean
>make -j8 class

The the class is the execuatble file:
>ldd class 
	linux-vdso.so.1 =>  (0x00007fff4b6c3000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fcf37124000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fcf36d44000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fcf377b9000)


The normal using will be looks like this:

> ./class lcdm.ini


It read the lcdm.ini as an inputfile, it will print on screen like:

>./class lcdm.ini 
*_* CLASS --->
Running CLASS version v2.6.3
Computing background
-> age = 13.461693 Gyr
-> conformal age = 13894.100411 Mpc
Computing thermodynamics
-> recombination at z = 1086.845754
    corresponding to conformal time = 278.779944 Mpc
    with comoving sound horizon = 142.281627 Mpc
    angular diameter distance = 12.515856 Mpc
    and sound horizon angle 100*theta_s = 1.045011
-> baryon drag stops at z = 1064.691266
    corresponding to conformal time = 283.069659 Mpc
    with comoving sound horizon rs = 144.186978 Mpc
-> reionization with optical depth = 0.084339
    corresponding to conformal time = 4458.125917 Mpc
-> free-streaming approximation can be turned on as soon as tau=361.964 Mpc
Computing sources
Evolving mode 1/1
Evolving ic 1/1
evolving 112 wavenumbers
Computing primordial spectra (analytic spectrum)
No non-linear spectra requested. Nonlinear module skipped.
No harmonic space transfer functions to compute. Transfer module skipped.
Computing unlensed linear spectra
 -> sigma8=0.877091 (computed till k = 1.05413 h/Mpc)
No lensing requested. Lensing module skipped.
Writing output files in output/test_... 
*_* CLASS Done <---



Looks fine. And that is the right output from class. But I start using uftrace (v0.8.x):

>uftrace class lcdm.ini 
*_* CLASS --->
Running CLASS version v2.6.3
Computing background
Error running background_init 
=>background_init(L:657) :error in background_solve(ppr,pba);
=>background_solve(L:1605) :error in generic_integrator(background_derivs, tau_start, tau_end, pvecback_integration, &bpaw, ppr->to
=>generic_integrator(L:112) :error in rkqs(&x, h, eps, &hdid, &hnext, derivs, parameters_and_workspace_for_derivs, pgi);
=>rkqs(L:146) :error in rkck(*x,h,derivs,parameters_and_workspace_for_derivs,pgi);
=>rkck(L:184) :error in (*derivs)(x+0.2*h, pgi->ytemp, pgi->ak2, parameters_and_workspace_for_derivs, pgi->error_message);
=>background_derivs(L:2173) :condition (pvecback[pba->index_bg_rho_g] <= 0.) is true; rho_g = 0.000000e+00 instead of strictly posi
DURATION     TID     FUNCTION
[ 32460] | main() {
3.403 us [ 32460] |   puts();
[ 32460] |   input_init_from_arguments() {
0.090 us [ 32460] |     strlen();
1.998 us [ 32460] |     strncpy();
0.127 us [ 32460] |     strcmp();
.....



It seems that some Errors are arised in class.

However I test the uftrace in Ubuntu apt install , which is v0.6, it works again:


>uftrace -V
uftrace v0.6.2

>uftrace class lcdm.ini 
*_* CLASS --->
Running CLASS version v2.6.3
Computing background
-> age = 13.461693 Gyr
-> conformal age = 13894.100411 Mpc
Computing thermodynamics
-> recombination at z = 1086.845754
    corresponding to conformal time = 278.779944 Mpc
    with comoving sound horizon = 142.281627 Mpc
    angular diameter distance = 12.515856 Mpc
    and sound horizon angle 100*theta_s = 1.045011
-> baryon drag stops at z = 1064.691266
    corresponding to conformal time = 283.069659 Mpc
    with comoving sound horizon rs = 144.186978 Mpc
-> reionization with optical depth = 0.084339
    corresponding to conformal time = 4458.125917 Mpc
-> free-streaming approximation can be turned on as soon as tau=361.964 Mpc
Computing sources
Evolving mode 1/1
Evolving ic 1/1
evolving 112 wavenumbers
Computing primordial spectra (analytic spectrum)
No non-linear spectra requested. Nonlinear module skipped.
No harmonic space transfer functions to compute. Transfer module skipped.
Computing unlensed linear spectra
-> sigma8=0.877091 (computed till k = 1.05413 h/Mpc)
No lensing requested. Lensing module skipped.
Writing output files in output/test_... 
*_* CLASS Done <---
DURATION    TID     FUNCTION
            [ 3264] | main() {
            [ 3264] |   input_init_from_arguments() {
            [ 3264] |     parser_read_file() {
   0.180 us [ 3264] |       parser_read_line();
   0.035 us [ 3264] |       parser_read_line();
   0.032 us [ 3264] |       parser_read_line();
   0.048 us [ 3264] |       parser_read_line();
   0.100 us [ 3264] |       parser_read_line();
   0.052 us [ 3264] |       parser_read_line();
:

**Comment by honggyukim** [comment]
@yuanshuoastro Thanks for sharing the code. I can reproduce the problem now.

Here is the execution result. The `class` executable runs fine without uftrace.
```
$ ./class lcdm.ini
*_* CLASS --->
Running CLASS version v2.6.3
Computing background
 -> age = 13.461693 Gyr
 -> conformal age = 13894.100411 Mpc
    ...
No non-linear spectra requested. Nonlinear module skipped.
No harmonic space transfer functions to compute. Transfer module skipped.
Computing unlensed linear spectra
 -> sigma8=0.877091 (computed till k = 1.05413 h/Mpc)
No lensing requested. Lensing module skipped.
Writing output files in output/test_...
*_* CLASS Done <---
```
But it shows different execution result as follows:
```
$ uftrace record ./class lcdm.ini
*_* CLASS --->
Running CLASS version v2.6.3
Computing background


Error running background_init
=>background_init(L:657) :error in background_solve(ppr,pba);
=>background_solve(L:1605) :error in generic_integrator(background_derivs, tau_start, tau_end, pvecback_integration, &bpaw, ppr->tol_background_integration, ppr->smallest_allowed_variation, &gi);
=>generic_integrator(L:112) :error in rkqs(&x, h, eps, &hdid, &hnext, derivs, parameters_and_workspace_for_derivs, pgi);
=>rkqs(L:146) :error in rkck(*x,h,derivs,parameters_and_workspace_for_derivs,pgi);
=>rkck(L:227) :error in (*derivs)(x+0.875*h, pgi->ytemp, pgi->ak6, parameters_and_workspace_for_derivs, pgi->error_message);
=>background_derivs(L:2173) :condition (pvecback[pba->index_bg_rho_g] <= 0.) is true; rho_g = 0.000000e+00 instead of strictly positive
```
But it runs fine if `--no-libcall` is given
```
$ uftrace record --no-libcall ./class lcdm.ini
*_* CLASS --->
Running CLASS version v2.6.3
Computing background
 -> age = 13.461693 Gyr
 -> conformal age = 13894.100411 Mpc
Computing thermodynamics
 -> recombination at z = 1086.845754
    corresponding to conformal time = 278.779944 Mpc
    with comoving sound horizon = 142.281627 Mpc
    angular diameter distance = 12.515856 Mpc
    and sound horizon angle 100*theta_s = 1.045011
 -> baryon drag stops at z = 1064.691266
    corresponding to conformal time = 283.069659 Mpc
    with comoving sound horizon rs = 144.186978 Mpc
 -> reionization with optical depth = 0.084339
    corresponding to conformal time = 4458.125917 Mpc
 -> free-streaming approximation can be turned on as soon as tau=361.964 Mpc
Computing sources
Evolving mode 1/1
Evolving ic 1/1
evolving 112 wavenumbers
Computing primordial spectra (analytic spectrum)
No non-linear spectra requested. Nonlinear module skipped.
No harmonic space transfer functions to compute. Transfer module skipped.
Computing unlensed linear spectra
 -> sigma8=0.877091 (computed till k = 1.05413 h/Mpc)
No lensing requested. Lensing module skipped.
Writing output files in output/test_...
*_* CLASS Done <---
```
I think that the problem comes from the library hooking so it works fine without library call tracing.
Another strange thing is that uftarce v0.6.2 doesn't work for it as well.
We may need some time to take a look at it. Please wait until then.

Thanks for the report.

**Comment by namhyung** [comment]
@yuanshuoastro thanks for using uftrace.  I'm in a business trip now so I can investigate it after returning.

**Comment by yuanshuoastro** [comment]
@namhyung Thank you very much!

**Comment by namhyung** [comment]
@yuanshuoastro I'm not sure it's related to input file handling.  It seems there's a problem with math functions.  Maybe related to the fast math routines in glibc?  Still investigating..

**Comment by namhyung** [comment]
I think I found what's the problem.  Floating-point return values seem to be clobberred during the mcount/plthook return path.

@yuanshuoastro could you please confirm that [below patch](https://github.com/namhyung/uftrace/files/1886440/arch-x86_64-Save-and-restore-xmm0-register.patch.txt) fixes your problem?

```diff
diff --git a/arch/x86_64/mcount.S b/arch/x86_64/mcount.S
index 64f4fc8..0f1a5a5 100644
--- a/arch/x86_64/mcount.S
+++ b/arch/x86_64/mcount.S
@@ -78,8 +78,10 @@ END(mcount)
 
 ENTRY(mcount_return)
 	.cfi_startproc
-	sub $32, %rsp
-	.cfi_def_cfa_offset 32
+	sub $48, %rsp
+	.cfi_def_cfa_offset 48
+
+	movdqu %xmm0, 16(%rsp)
 	movq %rdx, 8(%rsp)
 	.cfi_offset rdx, -24
 	movq %rax, 0(%rsp)
@@ -90,11 +92,13 @@ ENTRY(mcount_return)
 
 	/* returns original parent address */
 	call mcount_exit
-	movq %rax, 24(%rsp)
+	movq %rax, 40(%rsp)
 
 	movq 0(%rsp), %rax
 	movq 8(%rsp), %rdx
-	add $24, %rsp
+	movdqu 16(%rsp), %xmm0
+
+	add $40, %rsp
 	.cfi_def_cfa_offset 8
 	retq
 	.cfi_endproc
diff --git a/arch/x86_64/plthook.S b/arch/x86_64/plthook.S
index a055dba..48509e3 100644
--- a/arch/x86_64/plthook.S
+++ b/arch/x86_64/plthook.S
@@ -59,8 +59,10 @@ END(plt_hooker)
 
 ENTRY(plthook_return)
 	.cfi_startproc
-	sub $32, %rsp
-	.cfi_def_cfa_offset 32
+	sub $48, %rsp
+	.cfi_def_cfa_offset 48
+
+	movdqu %xmm0, 16(%rsp)
 	movq %rdx, 8(%rsp)
 	.cfi_offset rdx, -24
 	movq %rax, 0(%rsp)
@@ -70,11 +72,13 @@ ENTRY(plthook_return)
 	movq %rsp, %rdi
 
 	call plthook_exit
-	movq %rax, 24(%rsp)
+	movq %rax, 40(%rsp)
 
 	movq 0(%rsp), %rax
 	movq 8(%rsp), %rdx
-	add $24, %rsp
+	movdqu 16(%rsp), %xmm0
+
+	add $40, %rsp
 	.cfi_def_cfa_offset 8
 	retq
 	.cfi_endproc
```

**Comment by namhyung** [comment]
I consider it fixed now.  If you still see the same problem, please let me know.
