### ISSUE TITLE
specifying argument and retval in shared libraries

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#33]
There's some problems when displaying function arguments and return values in shared libraries.  If `t-arg` is compiled from `s-arg.c`, and `libabc_test_lib.so` is compiled from `s-lib.c`, the problem can be reproduced as follows:
```
$ ldd t-arg
        linux-vdso.so.1 =>  (0x00007ffe81724000)
        libabc_test_lib.so (0x00007f6d9c98a000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6d9c5aa000)
        /lib64/ld-linux-x86-64.so.2 (0x0000556c6968b000)

$ uftrace -A .*@arg1 -R .*@retval t-arg
# DURATION    TID     FUNCTION
   2.576 us [38912] | __cxa_atexit();
            [38912] | main(1) {
            [38912] |   foo(1) {
            [38912] |     lib_a() {
            [38912] |       lib_a() {
            [38912] |         lib_b() {
   1.236 us [38912] |           lib_c();
   3.182 us [38912] |         } /* lib_b */
   4.626 us [38912] |       } /* lib_a */
   6.376 us [38912] |     } /* lib_a */
   7.578 us [38912] |   } = 2057; /* foo */
   9.543 us [38912] | } = 0; /* main */
```
As you can see above, lib_a(), lib_b(), lib_c() do not show function arguments and return values here.

**Comment by honggyukim** [comment]
In addition to that, it shows lib_a() twice - one is from plt hooking, and the other is from the function in library itself.  it'd be better to show only one of those.

**Comment by namhyung** [comment]
You need to specify module (library) name to apply filters/triggers on symbols.  When no module is specified (default), it only searches the main binary and fallback to PLT only if no symbol found in the binary.  To get arguments from the library functions, add this option to the command line: `-A .*@libabc_test_lib,arg1`

I really need to write up the documentation for this..

**Comment by namhyung** [comment]
For showing duplicate "lib_a", yes it's a known problem.  I have no solution for that, you may want to disable the PLT hooking by passing `--no-libcall`.

**Comment by honggyukim** [comment]
I think the interface to explicitly write library name is not intuitive to users and it should be used only when the library is dlopened. If there are many libraries linked in the main binary, it may be confusing to users finding the library name that is matched with the function that users want to trace.

**Comment by namhyung** [comment]
I understand that explicit library name is annoying.  But normally uftrace cannot trace library functions (unless the library was built with instrumentation), so searching symbols in **ALL** library by default is mostly useless and inefficient IMHO.

I originally thought that if an user is developing some program, he/she knows which function is in which library.  But now I think that it might not be easy for some (very large) project.  What about adding something like "ANY" or "ALL" as a meta module name to tell uftrace to search symbols in libraries?

**Comment by honggyukim** [comment]
I see. The problem is that target program may have a lot of libraries from external projects so it may take a lot of time to search all of them.

If so, what about checking if the target library is tracable or not first, then decide whether to search or not?  It can be checked with the existing binary check routine.  It can skip most of external libraries.

**Comment by namhyung** [comment]
Hmm.. ok.  How about this then?

1. if given pattern has module name, use the matching symbols in the library.
1. if not, find main executable and use the matching symbols.
1. if no matching symbol found, search PLT of the main executable.
1. if no matching symbol found, search ALL trace-able libraries.

But in this case, you still need to specify module name or unique prefix to identify functions in the library.

**Comment by namhyung** [comment]
I changed to always match PLT symbols unless module name is given (06309be) so step 2 and 3 should be merged.

**Comment by namhyung** [comment]
@honggyukim I changed it to use all library unless it gives a module name specifically.  This would be useful when multiple libraries are traced (with `--nest-libcall` for example).  I pushed the code to [review/filter-module-v1](https://github.com/namhyung/uftrace/compare/review/filter-module-v1) branch.


A downside would be it now saves symbols files for all libraries.  I think this is needed since any library might be built with the instrumentation enabled (or dynamic tracing applied) and it would be hard to which one needs symbol file.  As it consumes smaller disk space than the tracing data itself, I think it can be acceptable for users.

**Comment by honggyukim** [comment]
@namhyung I've tested with gcc and node but found no problem. It seems to be working fine. Thanks very much for this work. The usage can be a lot simpler using this feature!

**Comment by honggyukim** [comment]
But please just fix the compiler warning.
```
  CC FPIC  arch/x86_64/symbol.op
/home/honggyu/work/uftrace/libmcount/mcount.c: In function ‘mcount_startup’:
/home/honggyu/work/uftrace/libmcount/mcount.c:1164:8: warning: variable ‘trigger_str’ set but not used [-Wunused-but-set-variable]
  char *trigger_str;
        ^
/home/honggyu/work/uftrace/libmcount/mcount.c:1163:8: warning: variable ‘filter_str’ set but not used [-Wunused-but-set-variable]
  char *filter_str;
        ^
  CC FPIC  libmcount/event-fast.op
  CC FPIC  libmcount/dynamic-fast.op
  CC FPIC  libmcount/record-fast.op
  LINK     arch/x86_64/mcount-entry.op
  CC FPIC  libmcount/mcount-single.op
  CC FPIC  libmcount/plthook-single.op
  CC FPIC  libmcount/event-single.op
  CC FPIC  libmcount/dynamic-single.op
  CC FPIC  libmcount/record-single.op
  CC FPIC  libmcount/mcount-fast-single.op
  CC FPIC  libmcount/plthook-fast-single.op
  CC FPIC  libmcount/event-fast-single.op
  CC FPIC  libmcount/dynamic-fast-single.op
  CC FPIC  libmcount/record-fast-single.op
/home/honggyu/work/uftrace/libmcount/mcount.c: In function ‘mcount_startup’:
/home/honggyu/work/uftrace/libmcount/mcount.c:1164:8: warning: variable ‘trigger_str’ set but not used [-Wunused-but-set-variable]
  char *trigger_str;
        ^
/home/honggyu/work/uftrace/libmcount/mcount.c:1163:8: warning: variable ‘filter_str’ set but not used [-Wunused-but-set-variable]
  char *filter_str;
        ^
  CC FPIC  libmcount/mcount-nop.op
  CC       uftrace.o
```

**Comment by namhyung** [comment]
Fixed in [review/filter-module-v2](https://github.com/namhyung/uftrace/compare/review/filter-module-v2).  Thanks!

**Comment by honggyukim** [comment]
I appreciate your work. I think it's stable enough.
Can you please merge this?

**Comment by namhyung** [comment]
Well, I'm not sure it's stable enough as I can see crashes for some corner cases.  But I think it works well for most cases.

Anyway, I pushed new code to [review/filter-module-v3](https://github.com/namhyung/uftrace/compare/review/filter-module-v3) with couple of cleanups (now in master).

**Comment by namhyung** [comment]
Pushed [review/filter-module-v4](https://github.com/namhyung/uftrace/compare/review/filter-module-v4).

Changelog:
* simplify symbol handling
