### ISSUE TITLE
--library-path option seems to do not work

### ISSUE THREAD

**Issue by Taeung** [namhyung/uftrace#337]
There are the necessary libraries `/usr/local/lib/libmcount*.so` like below:
```bash
$ ls /usr/local/lib/libmcount*
/usr/local/lib/libmcount-fast-single.so  /usr/local/lib/libmcount-single.so
/usr/local/lib/libmcount-fast.so         /usr/local/lib/libmcount.so
/usr/local/lib/libmcount-nop.so
```
However, when I used the option `-L`, I found this problem like below: 
```bash
$ uftrace -L /usr/local/lib t-fibonacci 1
ERROR: ld.so: object '/usr/local/lib/libmcount/libmcount-fast.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
uftrace: /home/taeung/git/uftrace-projects/namhyung/uftrace/cmd-record.c:1306:save_session_symbols
 ERROR: cannot find map files: Success
```

So, I read and temporally changed source code on `setup_child_environ()` like below:
```patch
diff --git a/cmd-record.c b/cmd-record.c
index 93b0eb2..bc504d4 100644
--- a/cmd-record.c
+++ b/cmd-record.c
@@ -246,7 +246,7 @@ static void setup_child_environ(struct opts *opts, int pfd)
                 setenv("UFTRACE_PATTERN", get_filter_pattern(opts->patt_type), 1);
 
         if (opts->lib_path)
-                snprintf(buf, sizeof(buf), "%s/libmcount/", opts->lib_path);
+                snprintf(buf, sizeof(buf), "%s/", opts->lib_path);
         else
                 buf[0] = '\0';  /* to make strcat() work */
```
Finally, it works as I expected. What do you think about this ? Is this a problem ?
```bash
$ uftrace -L /usr/local/lib t-fibonacci 1
# DURATION     TID     FUNCTION
   0.469 us [ 21404] | __monstartup();
   0.334 us [ 21404] | __cxa_atexit();
            [ 21404] | main() {
   0.518 us [ 21404] |   atoi();
   0.081 us [ 21404] |   fib();
   1.045 us [ 21404] | } /* main */
```

**Comment by Taeung** [comment]
In addition, I thought the below change is also needed.
Because I thought it isn't needed to append `/libmcount:` to a library path the user gave, no ?
```patch
diff --git a/cmd-record.c b/cmd-record.c
index 93b0eb2..2d9cc0e 100644
--- a/cmd-record.c
+++ b/cmd-record.c
@@ -95,7 +95,6 @@ static void setup_child_environ(struct opts *opts, int pfd)
 
         if (opts->lib_path) {
                 strcpy(buf, opts->lib_path);
-                strcat(buf, "/libmcount:");
         } else {
                 /* to make strcat() work */
                 buf[0] = '\0';
```

**Comment by Taeung** [comment]
And I'm thinking about the error messages:
(As another error case, if a user don't make install, there aren't `/usr/local/lib/libmcount*.so`,
so the user can see the below error messages )
```bash
$ uftrace  t-fibonacci 1
ERROR: ld.so: object '/usr/local/lib/libmcount/libmcount-fast.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
uftrace: /home/taeung/git/uftrace-projects/namhyung/uftrace/cmd-record.c:1306:save_session_symbols
 ERROR: cannot find map files: Success
```
First error "ERROR: ld.so: ... LD_PRELOAD .." is because the libmcount*.so libraries do not exists.

So I think we can previously check whether the libmcount*.so exits or not at `setup_child_environ`
like below (but the patch isn't perfect..):

What do you think about this ?
```patch
diff --git a/cmd-record.c b/cmd-record.c
index 93b0eb2..3829e72 100644
--- a/cmd-record.c
+++ b/cmd-record.c
@@ -267,6 +267,13 @@ static void setup_child_environ(struct opts *opts, int pfd)
                 else
                         strcat(buf, "libmcount.so");
         }
+
+        if (access(libmcount_path, X_OK) < 0 && errno == ENOENT) {
+                if (!opts->lib_path)
+                        pr_warn("Didn't make install ?\n");
+                pr_warn("cannot found %s\n", buf);
+        }
+
         pr_dbg("using %s library for tracing\n", buf);
 
         old_preload = getenv("LD_PRELOAD");
```

**Comment by namhyung** [comment]
Why did you use the `-L` option for `/usr/local/lib`?  It's basically to locate uftrace directory which is built from the source.  So as you know, if you run `make install` you don't need to use the option.

**Comment by Taeung** [comment]
Yep, I know that. But  I thought that the result should be same from `$ uftrace t-abc` and `$ uftrace -L /usr/local/lib t-abc`

So, I intentionally tested the `-L` option for `/usr/local/lib`,
(I thought it in the middle of reading source code on `setup_child_environ()`)

**Comment by namhyung** [comment]
Because of the source directory has the "libmcount" directory.  Hmm.. maybe we can try both (with or without the libmcount directory) when `-L` option is used.

**Comment by Taeung** [comment]
I got it, then I'll send new patch for this !

**Comment by Ansudeen** [comment]
Hi,
please check LD_LIBRARY_PATH is exported properly with right library path. i had same issue but after updating the ld_library_path it works well.
