### ISSUE TITLE
refactoring build process

### ISSUE THREAD

**Issue by namhyung** [namhyung/uftrace#35]
This patchset fixes and cleans up the uftrace build.  Currently it runs feature-checking code during `make` (if it's not run before) but it seems there's some race that misses existing dependency (usually libstdc++).

Main idea is moving featuring-checking into `configure` script.  The tricky part is calling the `configure` inside `make` (if it's not called before) and then build uftrace with a recursive `make` (with new feature-checking result).  It seems it doesn't work correctly in some (older) systems.  It's not a problem if users run the `configure` script manually before `make` though.  But I'd like to not require running `configure` before `make` if possible.

The code is pushed to `review/build-update-v1`.  It'd be really great if anyone can try it and can confirm it doesn't break. @thepaul could you please take a look at it?

**Comment by thepaul** [comment]
No objections; everything seems fine in connection with my packaging.

**Comment by namhyung** [comment]
@thepaul Thanks for review!
