### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by casionwoo** [namhyung/uftrace#350]
Hello 

I want to try this tracing tool on my work.
So I cloned and tried to build based on README.md file.

but when I typed ```make```, I got an error like below:

![image](https://user-images.githubusercontent.com/3404383/39605785-6a975e02-4f32-11e8-93cb-e68ea52bb836.png)

My work environment is non-native linux, I'm working on parallels on mac.
Please let me know if there's something that i missed..

**Comment by namhyung** [comment]
Thanks for using uftrace and reporting the bug.  There was a typo when there's no libncursesw on the system.  The [following patch](https://github.com/namhyung/uftrace/files/1972995/tui-fix-build-error.patch.txt) should fix it.

```diff
diff --git a/cmd-tui.c b/cmd-tui.c
index f3976f0d..35b6f340 100644
--- a/cmd-tui.c
+++ b/cmd-tui.c
@@ -1910,7 +1910,9 @@ int command_tui(int argc, char *argv[], struct opts *opts)

 #else /* !HAVE_LIBNCURSES */

-int comamnd_tui(int argc, char *argv[], struct opts *opts)
+#include "utils/utils.h"
+
+int command_tui(int argc, char *argv[], struct opts *opts)
 {
        pr_warn("TUI is not implemented (libncurses.so is missing)");
        return 0;

```

**Comment by honggyukim** [comment]
I also suggest you to install the necessary packages before compilation as described in QUICK installation guide. (I assume that you use ubuntu)
```
$ sudo apt-get install libelf-dev           # mandatory
$ sudo apt-get install pandoc               # for man pages (optional)
$ sudo apt-get install libpython2.7-dev     # for python scripting (optional)
$ sudo apt-get install libncursesw5-dev     # for TUI (optional)
```
I also think that you better build uftrace in a new repository. You may have some problems building the recent uftrace after updating it to newest one.
```
$ git clone https://github.com/namhyung/uftrace.git
$ cd uftrace
$ make
$ sudo make install
```
