### ISSUE TITLE
support regex for specifying function names?

### ISSUE THREAD

**Issue by bhatuzdaname** [namhyung/uftrace#354]
This would be very useful when debugging large code bases which have a recurring pattern in their function names and argument types.

**Comment by namhyung** [comment]
It's already supported.  You can use regex for function filters (`-F` and `-N`) and arguments (`-A` and `-R`).

**Comment by bhatuzdaname** [comment]
Ahh, my bad. I thought regex was supported only for filtering of functions. 
By the way, thank you very much for making this tool, it's a godsend!
