### ISSUE TITLE
Support exporting call graph to graphviz dotty format

### ISSUE THREAD

**Issue by rteja** [namhyung/uftrace#355]
Being able to serialize the call graph to standard formats like Graphviz dotty will be helpful for GUI visualization or convenience of further analysis. Request you to provide this feature.

**Comment by namhyung** [comment]
@rteja thanks for the suggestion.  I think it'll be helpful but I don't have time to work on it anytime soon.  You can take a look at `uftrace dump` command to export call graph to chrome tracing format or flamegraph.

**Comment by ParkHanbum** [comment]
@rteja  if there is some library for visualizing CFG, let me know. I want implement this but it is so hard without library.

**Comment by namhyung** [comment]
@ParkHanbum the [graphviz dot format](https://en.wikipedia.org/wiki/DOT_(graph_description_language)) is a simple text format but I don't know there's a library.  I know [gperftools](http://goog-perftools.sourceforge.net/doc/cpu_profiler.html) uses it to visualize profiling results so you may take a look at the sources.

**Comment by ParkHanbum** [comment]
@namhyung ![CFG](http://thimg.todayhumor.co.kr/upfile/201711/15100264346ac8e7be2a3a48c19f55035587d7e200__mn753841__w549__h828__f78235__Ym201711.png)

**Comment by namhyung** [comment]
I guess translating uftrace graph output to dot format is fairly straightforward so I'm not sure we really need a library.

**Comment by honggyukim** [comment]
I also think that it doesn't have to use an external library. You better see `cmd-dump.c` file to dump its output to chrome or flamegraph rather than referring `cmd-graph.c`.

It can be implemented as one-to-one mapping to `dot` format output by dumping its recorded data.

**Comment by ParkHanbum** [comment]
I am found the useful drawing library to draw CFG.
: `[pycallgraph](https://pycallgraph.readthedocs.io/en/master/examples/basic.html#generated-image)`
it drawn CFG nicely by using graphviz format. but unfortunately, it does not modulized to separate graphviz format and stylist. also, it does not export the graphic assets. so, there is need to analyze source-code. 

if you accept about use pycallgraph style and python library, then I want to try this. 

how do you think so?

**Comment by namhyung** [comment]
Do you like to do it in python scripting?  I'm ok with whether it's a script or bulitin C code (in dump command).

**Comment by ParkHanbum** [comment]
@namhyung I think it is necessary that separate it from tracer. with readable formatted data could make more usability to create another visualization tool even if no necessary to know about uftrace. also, python easy to use than C. and have a lot of modules for it.
