### ISSUE TITLE
Same starting address for stack/heap as system loader?

### ISSUE THREAD

**Issue by bhatuzdaname** [namhyung/uftrace#356]
I have disabled ASLR on my ubuntu machine. Consider this program:
```
int main(){
  int *p = malloc(sizeof(int));
  printf("%p %p\n",p,&p);
  return 0;
}
```
Every time I run the compiled program, I always get "0x402010 0x7fffffffe548" as output.
Even when I run the program under gdb I get the same output. 
However when I run the program with uftrace I get a different output (0x402cc0 0x7fffffffe408).

Is it possible to ensure that we get the same starting address for the stack and heap?
This will greatly help in debugging because I am printing pointer arguments in uftrace and want to set break conditions in gdb based on the value of those pointers.

**Comment by honggyukim** [comment]
Hi @bhatuzdaname, thanks for suggesting this feature.
I've just made a new PR #357, so please try it then.

Previously, the address position is changed all the time because of ASLR.
```
$ uftrace record ./test-ASLR
0x787d70 0x7ffe7b63c580

$ uftrace record ./test-ASLR
0x1682d70 0x7ffd9347cfe0

$ uftrace record ./test-ASLR
0x245fd70 0x7ffe604dbb20
```
If using `--no-randomize-addr` option, the address position doesn't change each execution.
```
$ uftrace record --no-randomize-addr ./test-ASLR
0x613d70 0x7fffffffe210

$ uftrace record --no-randomize-addr ./test-ASLR
0x613d70 0x7fffffffe210

$ uftrace record --no-randomize-addr ./test-ASLR
0x613d70 0x7fffffffe210

$ uftrace record --no-randomize-addr ./test-ASLR
0x613d70 0x7fffffffe210
```

**Comment by namhyung** [comment]
@bhatuzdaname do you want to see same pointer value with or without uftrace?  uftrace calls malloc() internally (before main) so it's hard to keep the same pointer value IMO.

**Comment by bhatuzdaname** [comment]
Hi @namhyung, thanks for the PR, it seems to work.

I would indeed like to see the same value with and without uftrace for both the stack and heap locations. For the malloc isssue, a work around could be to perhaps use mmap at some other fixed address and use that for internal use before main. However, I'm not sure how you would handle the stack issue. gdb seems to be able to do this, so it would be interesting to look at what they do. I'll try looking at the gdb source to see how they're handling it.

**Comment by honggyukim** [comment]
Right. My PR only fixes the address layout but your purpose is to fix addresses of heap and stack.

But it seems that gdb makes same address when it comes to heap but not for stack.  Please see below.
```
$ ./test-ASLR
0x602740 0x7fffffffe320

$ gdb -q -ex=r -ex=q ./test-ASLR
Reading symbols from ./test-ASLR...done.
Starting program: /home/honggyu/work/uftrace/git/final/test-ASLR
0x602740 0x7fffffffe2f0
```
In the above output, the heap address is same as original, but stack address is different.

**Comment by bhatuzdaname** [comment]
Another comment about the no-randomize-addr option. It seems that the option is redundant if I disable ASLR on my system. However is ASLR is enabled, then the option is necessary.
ASLR enabled:
```
echo 1 | sudo tee /proc/sys/kernel/randomize_va_space  #Enable ASLR
$ uftrace record a.out
0x402cc0 0x7ffc9ceb7718
$ uftrace record a.out
0x402cc0 0x7ffc1b2fbe98
$ uftrace record --no-randomize-addr a.out
0x402cc0 0x7fffffffe428
$ uftrace record --no-randomize-addr a.out
0x402cc0 0x7fffffffe428
```
ASLR disabled:
```
echo 0 | sudo tee /proc/sys/kernel/randomize_va_space  #Disable ASLR
$ uftrace record a.out
0x402cc0 0x7fffffffe428
$ uftrace record a.out
0x402cc0 0x7fffffffe428
$ uftrace record --no-randomize-addr a.out
0x402cc0 0x7fffffffe428
$ uftrace record --no-randomize-addr a.out
0x402cc0 0x7fffffffe428
```

**Comment by bhatuzdaname** [comment]
Ahh, I was about to reply with the same thing. I just tried the gdb experiment again and noticed the stack issue. 

So I have an idea. We could create a flag --adjust-stack-addr and when given that flag we could adjust the value of pointers when printing with /p option. The trick is to figure out how much stack space uftrace takes before transferring control to the user program. We have no control over a compiler's register allocation so I'm not sure how we could do that :/ 

Also I'm not sure how uftrace works. Are there transfers of control between uftrace and the user program in between? That would mucky up the stack and the above approach wouldn't work.

Another issue that arises is not all operands for /p are stack addresses, some could be from the heap too. I guess we could leave it up to the user to toggle between options and figure out.

**Comment by namhyung** [comment]
For heap to have a same address all uftrace internal allocations should use a different (custom) allocator which can be subtle.  Maybe it's good to have but I'm not inclined to implement it now just because of that.

And I believe uftrace doesn't affect the placement of the stack.  But uftrace adds a dozen of environment variables (depending on options it uses) and that's why you see the differences IMO.  It seems gdb also adds some env and I can see small difference between `$ printenv` and `(gdb) show environment`.
