### ISSUE TITLE
Getting source line number with --symbol-with-addr option

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#36]
Sometimes it'd be better to see information of source line numbers to understand the exact locations of the functions during replay, report, and graph commands.  To clearly address this issue, we may have to support libdwarf but I think we can go to a simpler way by just showing address with each symbol.

So why don't we add an option named `--symbol-with-addr` to show address with symbol. For example, the replay output looks like this.
```
$ uftrace replay --symbol-with-addr
# DURATION    TID     FUNCTION
   0.587 us [12264] | <400a90> __cxa_atexit();
            [12264] | <400e15> main() {
  30.911 us [12264] |   <400dd7> __static_initialization_and_destruction_0();
  31.037 us [12264] | } /* <400e15> main */
            [12264] | <400ca2> main() {
   0.627 us [12264] |   <400e4e> std::vector::vector();
   0.030 us [12264] |   <400ed8> __gnu_cxx::__normal_iterator::__normal_iterator();
   7.651 us [12264] |   <400ef6> std::vector::push_back();
    ...
```

In this case, we can see the source line number by using addr2line with the address above. If we want to see the location of `std::vector::push_back`, we can find it as follows.
```
$ addr2line -e a.out 400ef6
/usr/include/c++/4.8/bits/stl_vector.h:901
```

**Comment by honggyukim** [comment]
@namhyung Please have a look at it and give me some feedback.
https://github.com/namhyung/uftrace/compare/master...honggyukim:check/symbol-with-addr

**Comment by honggyukim** [comment]
If it's okay, I will add this option for report and graph commands.

**Comment by namhyung** [comment]
Well, I'm not sure how much value it can give.  You can get the address with `uftrace dump | grep std::vector::push_back`, right?

**Comment by honggyukim** [comment]
Yes, we can get the address using `uftrace dump` but I think it's better to see the address in the function execution flow. If I use dump command, I have to repeat dump and replay commands back and forth.

**Comment by namhyung** [comment]
I thought about the value of showing function address, and it could be used to distinguish functions have same (or similar) name.  I think it might be useful for report or graph which merges record by function names.

But I'd like to change the output little bit.  I've been trying to keep the output of replay to look like a C source code somehow.  I'm not sure it's very useful for others but don't want to break it now.  So I suggest configurable output format on the left side.  What about adding `-F/--field` option to specify the output?  The default value would be `duration,tid`

```
$ uftrace replay --field duration,tid,addr
# DURATION    TID         ADDR   FUNCTION
   0.587 us [12264]     400a90 | __cxa_atexit();
            [12264]     400e15 | main() {
  30.911 us [12264]     400dd7 |   __static_initialization_and_destruction_0();
  31.037 us [12264]     400e15 | } /* main */
            [12264]     400ca2 | main() {
   0.627 us [12264]     400e4e |    std::vector::vector();
   0.030 us [12264]     400ed8 |    __gnu_cxx::__normal_iterator::__normal_iterator();
   7.651 us [12264]     400ef6 |    std::vector::push_back();
    ...
```

**Comment by honggyukim** [comment]
I agree. I just made it with very simple code changes but It'd be better to make it as you showed in a long term. Thanks!

**Comment by namhyung** [comment]
I implemented the above concept and pushed the code to `check/replay-field` branch.  I also added some more field to show time little differently.  The 'time' field is for raw timestamp and 'delta' field shows time difference from previous event (in a same task).  You can check it with 'duration'.

```
$ uftrace replay -f time,delta,duration,addr -d abc.data --no-merge 
#     TIMESTAMP      TIMEDELTA  DURATION     ADDRESS     FUNCTION
   241325.123512960                             4004f0 | main() {
   241325.123513280   0.320 us                  40069f |   a() {
   241325.123513472   0.192 us                  400674 |     b() {
   241325.123513646   0.174 us                  400636 |       c() {
   241325.123514272   0.626 us                  400490 |         getpid() {
   241325.123515894   1.622 us   1.622 us       400490 |         } /* getpid */
   241325.123518785   2.891 us   5.139 us       400636 |       } /* c */
   241325.123519397   0.612 us   5.925 us       400674 |     } /* b */
   241325.123519694   0.297 us   6.414 us       40069f |   } /* a */
   241325.123519934   0.240 us   6.974 us       4004f0 | } /* main */
```

Also it's possible to pass 'none' to -f option in order to hide all the fields in the output.

```
$ uftrace replay -f none -d abc.data
# FUNCTION
 main() {
   a() {
     b() {
       c() {
         getpid();
       } /* c */
     } /* b */
   } /* a */
 } /* main */
```

**Comment by honggyukim** [comment]
It works fine and this satisfies my requirement. Thanks for the work!

**Comment by honggyukim** [comment]
As I mentioned, the graph output is a bit broken.
```
calling functions
================================
178.338 ms : (1) main
 96.008 us :  +-(1) v8::Shell::SetOptions
            :  |
450.341 us :  +-(1) v8::platform::CreateDefaultPlatform
            :  |
300.587 us :  +-(1) v8::V8::Initialize
            :  |
404.112 us :  +-(1) v8::internal::_GLOBAL__N_1::LoadFromFiles
402.737 us :  | (2) v8::internal::_GLOBAL__N_1::Load
```

**Comment by honggyukim** [comment]
The below change fixes it.
```
diff --git a/cmd-graph.c b/cmd-graph.c
index 76d6ed4..5bef612 100644
--- a/cmd-graph.c
+++ b/cmd-graph.c
@@ -357,7 +357,7 @@ static void print_graph_node(struct uftrace_graph *graph,

                if (&child->list != node->head.prev) {
                        /* print blank line between siblings */
-                       pr_out("%*s: ", 12, "");
+                       pr_out("%*s: ", 11, "");
                        pr_indent(indent_mask, indent, false);
                        pr_out("\n");
                }
```

**Comment by honggyukim** [comment]
One more request is that it would be better to use -f option to hide time in graph command as well.

**Comment by namhyung** [comment]
Thanks for testing!  It's fixed now and I'll think about the graph later.

**Comment by honggyukim** [comment]
Thanks for your work. I've checked it from master branch. graph command support can be done later on.
