### ISSUE TITLE
add python gdb helper script for debugging

### ISSUE THREAD

**Issue by namhyung** [namhyung/uftrace#361]
Recent gdb support python scripting to extend its functionality for custom debugging routines.  I borrowed some code from the Linux kernel source and add a few command to investigate uftrace/libmcount internally easily.  While this only provides very basic info, it can be improved later.

You may need to enable auto-loading of `uftrace-gdb.py`.

For example,
```
  (gdb) uft-mcount-data
  mtd: tid = 10224, idx = 4
  [0] main(int, char**) <== __libc_start_main
  [1] ns::ns1::foo::bar() <== main(int, char**)
  [2] ns::ns1::foo::bar1() <== ns::ns1::foo::bar()
  [3] ns::ns1::foo::bar2() <== ns::ns1::foo::bar1()

  (gdb) uft-plt-list
         Module Id      Base Address  Name
    0x7ffff7ffe100               0x0  af-pg
          0x613e30    0x7ffff75de000  libelf.so.1
          0x616350    0x7ffff6a16000  libz.so.1

  (gdb) uft-mcount-filters
  0x555555554a39 - 0x555555554ad8 :  F   main

  (gdb) uft-mcount-args
  0x5555555548da - 0x5555555548fb : A   ns::ns1::foo::foo
  0x5555555548fc - 0x55555555491c : A   ns::ns1::foo::bar1
  0x55555555491c - 0x55555555493c : A   ns::ns1::foo::bar2
  0x55555555493c - 0x555555554960 : A   ns::ns1::foo::bar3
  0x555555554960 - 0x555555554989 : A   ns::ns1::foo::bar
  0x555555554a39 - 0x555555554ad8 : AR  main

  (gdb) uft-mcount-triggers 1
  0x5555555548da - 0x5555555548fb :   0x40  ns::ns1::foo::foo
    triggers = ARGUMENT
  0x5555555548fc - 0x55555555491c :   0x40  ns::ns1::foo::bar1
    triggers = ARGUMENT
  ...
  0x555555554a39 - 0x555555554ad8 :  0x142  main
    triggers = FILTER|ARGUMENT|RETVAL
```

This also added `misc/symbols` tool to convert raw address to symbol name using symbol tables for each session.  Currently an address should be passed as an command line argument.

The code is available at [review/gdb-script-v1](https://github.com/namhyung/uftrace/compare/review/gdb-script-v1).

**Comment by honggyukim** [comment]
Looks very cool! I will try when I have time for debugging. Thanks a lot!

**Comment by honggyukim** [comment]
In addition to this, I think it'd be helpful if we have some kind of dump functions for those data structures such as `dump_mcount_data()`, `dump_mcount_filters()`, `dump_mcount_args()`, etc.
It's just debugging purposes so it doesn't have to be included in release build.

**Comment by namhyung** [comment]
What do you mean by "dump"?  Do you want to save them to files?

**Comment by honggyukim** [comment]
I mean to print its data to console just for debugging purpose. I sometimes want to see the internal data while writing code.  I think having a way to print its data in details can be better than manually using `printf`.  It's a different requirement from gdb support.

**Comment by honggyukim** [comment]
One simple comment. `symbol` binary is mistakenly included in the repository. And can you please explain the usage of `symbol` tool? It looks cool but I don't know how to use it.

**Comment by namhyung** [comment]
Oh, I forgot to add the usage in the commit log.  The `symbols` tool reads it from the stdin so you can do like

```
$ echo 0x1234 | misc/symbols
0x1234:  foo
```

**Comment by namhyung** [comment]
Pushed [review/gdb-script-v2](https://github.com/namhyung/uftrace/compare/review/gdb-script-v2).

Changelog:
 * rename to `uft-plthook-data`
 * show header line for mcount commands
 * add description of misc/symbols in the commit log
