### ISSUE TITLE
check the shared memory space before start tracing

### ISSUE THREAD

**Issue by ParkHanbum** [namhyung/uftrace#371]
my shared memory space was fulled before using uftrace. at this situation, I'm tried to use uftrace. deservedly, my trying was failed. but I could not found the reason immediatly. because it just printed the 'Bus error (core dumped)' which not real reason. 

```
m@m:~/git/uftrace$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            2.9G     0  2.9G   0% /dev
tmpfs           594M   24M  571M   4% /run
/dev/sda1        38G   31G  4.6G  87% /
tmpfs           2.9G  2.9G     0 100% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           2.9G     0  2.9G   0% /sys/fs/cgroup
tmpfs           594M   28K  594M   1% /run/user/108
tmpfs           594M     0  594M   0% /run/user/1000
m@m:~/git/uftrace$ ./uftrace -L.  ../test_pointer_arg
Bus error (core dumped)
```
if uftrace check shared memory before start tracing then can assist more helpful guide to user.

**Comment by namhyung** [comment]
It's a kind of exceptional case so I'm not sure we can check every possible error case before running.  Also it's hard to predict how much memory uftrace will use..

**Comment by ParkHanbum** [comment]
@namhyung it is right, I agree. 
I think this case can be solved easily. 
how about check shared memory to verify it was fulled before write it.

**Comment by namhyung** [comment]
You can send a PR for it.

**Comment by ParkHanbum** [comment]
@namhyung I forgot this issue, could you assign this issue to me?

**Comment by namhyung** [comment]
Sure.
