### ISSUE TITLE
code coverage report for uftrace code base

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#379]
I think it'd be helpful if we have a code coverage report for uftrace code itself to understand the internal code execution information.

So I've added a new PR #377 to generate the code coverage report very easily.  I just made a coverage report after running our entire test set by running `runtest.py`.
https://honggyukim.github.io/uftrace/runtest-coverage/index.html

It would be helpful how much portion of our uftrace code is being tested and it also provides useful information for other engineers who are not very familiar with uftrace code base.

I would like to hear some feedback on it.

**Comment by namhyung** [comment]
Looks useful.  I'll take a look at it later..
