### ISSUE TITLE
Source code location in TUI mode

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#390]
I think it'd be better to show source code location in TUI mode in its footer.
![image](https://user-images.githubusercontent.com/19642328/42071072-44a0b2c8-7b94-11e8-9164-417a1c428da1.png)
It currently shows session info and its binary location, but I think we can show source code location if debug info is supported soon.

**Comment by namhyung** [comment]
Sounds good. :)

**Comment by namhyung** [comment]
Pushed [review/dwarf-line-v1](https://github.com/namhyung/uftrace/compare/review/dwarf-line-v1).

**Comment by honggyukim** [comment]
Hmm.. it crashes when move next button is pushed.
Here is the debug info.
```
1035│ static void win_footer_graph(struct tui_window *win,
1036│                              struct ftrace_file_handle *handle)
1037│ {
1038│         char buf[COLS + 1];
1039│         struct tui_graph *graph = (struct tui_graph *)win;
1040│         struct tui_graph_node *node = win->curr;
1041│         struct uftrace_session *sess = graph->ug.sess;
1042│
1043│         if (tui_debug) {
1044│                 snprintf(buf, COLS, "uftrace graph: top: %d depth: %d, curr: %d depth: %d",
1045│                          graph->win.top_index, graph->top_depth,
1046│                          graph->win.curr_index, graph->curr_depth);
1047│         }
1048│         else if (tui_search) {
1049│                 snprintf(buf, COLS, "uftrace graph: searching \"%s\"  (%d match, %s)",
1050│                          tui_search, graph->win.search_count,
1051│                          "use '<' and '>' keys to navigate");
1052│         }
1053│         else {
1054│                 struct debug_location *dloc;
1055│
1056│                 dloc = find_file_line(&sess->symtabs, node->n.addr);
1057│                 if (dloc != NULL) {
1058├───────────────────────> snprintf(buf, COLS, "uftrace graph: %s [line:%d]",
1059│                                  dloc->file->name, dloc->line);
1060│                 }
1061│                 else {
1062│                         snprintf(buf, COLS, "uftrace graph: session %.*s (%s)",
1063│                                  SESSION_ID_LEN, sess->sid, sess->exename);
1064│                 }
1065│         }
1066│         buf[COLS] = '\0';
1067│
1068│         printw("%-*s", COLS, buf);
1069│
1070│         graph->disp_update = false;

/home/honggyu/work/uftrace/git/uftrace/cmds/tui.c
```
```
(gdb) p dloc
$2 = (struct debug_location *) 0x1c4e630

(gdb) p dloc->line
$3 = 0

(gdb) p dloc->file
$4 = (struct debug_file *) 0x0
```

**Comment by honggyukim** [comment]
It occurs when the cursor is on a function that doesn't have source code available such as `_GLOBAL__sub_I_foo`.

So I fixed the problem with below change.
```diff
diff --git a/cmds/tui.c b/cmds/tui.c
index 414fafc..55dee65 100644
--- a/cmds/tui.c
+++ b/cmds/tui.c
@@ -1054,7 +1054,7 @@ static void win_footer_graph(struct tui_window *win,
                struct debug_location *dloc;

                dloc = find_file_line(&sess->symtabs, node->n.addr);
-               if (dloc != NULL) {
+               if (dloc != NULL && dloc->file != NULL) {
                        snprintf(buf, COLS, "uftrace graph: %s [line:%d]",
                                 dloc->file->name, dloc->line);
                }
```
But still shows weird output such as `uftrace graph: ??? [line:0]` when the cursor is on standard functions such as `std::move` or something else.

**Comment by namhyung** [comment]
It seems some symbol didn't find debug info.  Does below patch fix it?

```diff
diff --git a/cmds/tui.c b/cmds/tui.c
index 414fafce..55dee65b 100644
--- a/cmds/tui.c
+++ b/cmds/tui.c
@@ -1054,7 +1054,7 @@ static void win_footer_graph(struct tui_window *win,
                struct debug_location *dloc;

                dloc = find_file_line(&sess->symtabs, node->n.addr);
-               if (dloc != NULL) {
+               if (dloc != NULL && dloc->file != NULL) {
                        snprintf(buf, COLS, "uftrace graph: %s [line:%d]",
                                 dloc->file->name, dloc->line);
                }
```

**Comment by namhyung** [comment]
It seems compiler didn't generate source/line info for those.  What about this?

```diff
diff --git a/cmds/tui.c b/cmds/tui.c
index 414fafce..efa2c0ca 100644
--- a/cmds/tui.c
+++ b/cmds/tui.c
@@ -1055,8 +1055,15 @@ static void win_footer_graph(struct tui_window *win,

                dloc = find_file_line(&sess->symtabs, node->n.addr);
                if (dloc != NULL) {
-                       snprintf(buf, COLS, "uftrace graph: %s [line:%d]",
-                                dloc->file->name, dloc->line);
+                       /* some symbols don't have source location */
+                       if (dloc->file == NULL || dloc->line == 0) {
+                               snprintf(buf, COLS, "uftrace graph: %s",
+                                        "source location is not available");
+                       }
+                       else {
+                               snprintf(buf, COLS, "uftrace graph: %s [line:%d]",
+                                        dloc->file->name, dloc->line);
+                       }
                }
                else {
                        snprintf(buf, COLS, "uftrace graph: session %.*s (%s)",
```

**Comment by honggyukim** [comment]
Thanks! It works fine. But it's unfortunate that the compiler doesn't provide source location info for STL headers.

**Comment by honggyukim** [comment]
One more thing is that the source location is only provided when `--auto-args` is given. Would it be possible to provide the source location info even if we don't record any args/retval using dwarf info?

**Comment by honggyukim** [comment]
Hmm.. I checked it once again but gdb can step into STL headers with its source line info so I think we may be able to find a way to get the source location of them.

**Comment by honggyukim** [comment]
We can simply test it with the example below:
```cpp
$ cat sort.cc
#include <iostream>
#include <vector>
#include <algorithm>

using namespace std;

int main()
{
        vector<int> v = { 7, 4, 8, 3, 2 };
        sort(v.begin(), v.end());
        for (auto a : v)
                cout << a << " ";
        cout << endl;
}
```
```
$ g++ -std=c++11 -pg -g a.out

$ grep stl_algo.h a.out
Binary file a.out matches
```
So I have checked it in text editor : )

X^@^@?^A4^@^C^N:^K;^EI^S^B^X^@^@?^A4^@^C^N:^K;^KI^S^B^X^@^@?^A^K^AU^W^@^@?^A.^A^C^N4^Y^Q^A^R^G@^X?B^Y^A^S^@^@?^A.^@^C^N4^Y^Q^A^R^G@^X?B^Y^@^@?^A4^@^C^NI^S?^Y4^Y<^Y^@^@?^A4^@G^S^B^X^@^@?^A4^@G^Sn^N^\^K^@^@?^A4^@G^Sn^N^\^M^@^@?^A4^@G^Sn^N^\^F^@^@?^A4^@G^Sn^N^\^E^@^@?^A4^@G^Sn^N^\^G^@^@^@?^N^@^@^B^@^Z^D^@^@^A^A?^N^M^@^A^A^A^A^@^@^@^A^@^@^A/usr/include/c++/5/bits^@/usr/include/c++/5^@/usr/include/c++/5/ext^@`/usr/include/x86_64-linux-gnu/c++/5/bits`^@/usr/include/c++/5/debug^@/usr/include^@/usr/lib/gcc/x86_64-linux-gnu/5/include^@/usr/include/x86_64-linux-gnu/bits^@^@predefined_ops.h^@^A^@^@stl_algobase.h^@^A^@^@sort.cc^@^@^@^@allocator.h^@^A^@^@initializer_list^@^B^@^@stl_vector.h^@^A^@^@`stl_algo.h`^@^A^@^@stl_iterator.h^@^A^@^@new_allocator.h^@^C^@^@stl_construct.h^@^A^@^@stl_iterator_base_funcs.h^@^A^@^@stl_uninitialized.h^@^A^@^@alloc_traits.h^@^A^@^@stl_iterator_base_types.h^@^A^@^@move.h^@^A^@^@stl_heap.h^@^A^@^@iostream^@^B^@^@cwchar^@^B^@^@exception_ptr.h^@^A^@^@c++config.h^@^D^@^@type_traits^@^B^@^@stl_pair.h^@^A^@^@debug.h^@^E^@^@char_traits.h^@^A^@^@cstdint^@^B^@^@clocale^@^B^@^@new^@^B^@^@cstdlib^@^B^@^@cstdio^@^B^@^@basic_string.h^@^A^@^@system_error^@^B^@^@ios_base.h^@^A^@^@cwctype^@^B^@^@algorithmfwd.h^@^A^@^@cmath^@^B^@^@uniform_int_dist.h^@^A^@^@random.h^@^A^@^@vector.tcc^@^A^@^@iosfwd^@^B^@^@numeric_traits.h^@^C^@^@alloc_traits.h^@^C^@^@stdio.h^@^F^@^@libio.h^@^F^@^@<built-in>^@^@^@^@stddef.h^@^G^@^@wchar.h^@^F^@^@time.h^@^F^@^@stdint.h^@^F^@^@locale.h^@^F^@^@types.h^@^H^@^@atomic_word.h^@^D^@^@stdlib.h^@^F^@^@_G_config.h^@^F^@^@wctype.h^@^F^@^@mathdef.h^@^H^@^@^@^@       ^BR^N@^@^@^@^@^@^C0^A?^B^B^@^A^A^@      ^B]^N@^@^@^@^@^@^C?^@^A?^B^B^@^A^A^@    ^Bh^N@^@^@^@^@^@^C?^@^A?^B^B^@^A^A^D^B^@        ^Bs^N@^@

**Comment by honggyukim** [comment]
One more tiny problem is that it sometimes shows strange note such as `uftrace graph: ??? [line:742]` for `_GLOBAL__N_1::EmitAssemblyHelper::EmitAssembly`. It's because its filename is "???" but line number is available.

Please see the `.dbg` file as below:
```
        ...
F: 1534220 _GLOBAL__N_1::EmitAssemblyHelper::openOutputFile
L: 0 ???
A: @arg1%rdx,arg2

F: 1534440 _GLOBAL__N_1::EmitAssemblyHelper::EmitAssemblyWithNewPassManager
L: 877 ???
A: @arg1%rdi,arg2/e:BackendAction%rsi,arg3

F: 15367b0 _GLOBAL__N_1::EmitAssemblyHelper::EmitAssembly
L: 742 ???
A: @arg1%rdi,arg2/e:BackendAction%rsi,arg3
        ...
```

**Comment by namhyung** [comment]
Pushed [review/dwarf-line-v2](https://github.com/namhyung/uftrace/compare/review/dwarf-line-v2)

Changelog:
 * use location info if decl file/line attributes don't exist
 * always save and load debug (location) info
 * show location from `misc/symbols` tool

**Comment by honggyukim** [comment]
Thanks for the update. It mostly shows the source location now including C++ headers.
But I see that `std::_Rb_tree::_M_erase` is not found in source location even though it's in `.dbg` file.

There are many different addresses for the same `std::_Rb_tree::_M_erase` function, so I think it'd be better that we provide address information if there is not source location info.

And I have one more tiny comment on that. It shows "uftrace graph: <source filepath> [line: number]" but I think "uftrace graph: " prefix doesn't give useful information.  So what about making it as follows:

Before:
- `uftrace graph: /home/honggyu/work/llvm/tools/clang/lib/CodeGen/BackendUtil.cpp [line:743]`

After:
- `(function file:line): /home/honggyu/work/llvm/tools/clang/lib/CodeGen/BackendUtil.cpp:743`

If it doesn't have source info, it could be as follows:

Before:
- `uftrace graph: source location is not available`

After:
- `(function address): 0xa79000`

**Comment by honggyukim** [comment]
One more request is to print `realpath` because my `libc++` function looks as follows:
```
/home/honggyu/usr/bin/../include/c++/v1/vector 
```
So I want to make it `/home/honggyu/usr/include/c++/v1/vector` with realpath.

**Comment by namhyung** [comment]
Pushed [review/dwarf-line-v3](https://github.com/namhyung/uftrace/compare/review/dwarf-line-v3)

Changelog:
 * show address when source location is not available (for PLT functions)

**Comment by honggyukim** [comment]
Thanks for the update. It cannot find location of a few of functions but mostly works as expected now.

**Comment by namhyung** [comment]
They probably are library functions (PLT) which are not defined in the executable so don't have source location info.
