### ISSUE TITLE
Assertion error: Assertion `sess' failed when reading multithreaded data

### ISSUE THREAD

**Issue by tahini** [namhyung/uftrace#40]
I don't know if it's me, a bug or just lack of documentation, but I get this message when trying to 'uftrace report' on data from a multithreaded application (compiled with -lpthread):

`uftrace: /home/me/sources/uftrace/utils/session.c:198: add_session_ref: Assertion `sess' failed.`

This is my task.txt file. It appears to have no way to identify the session for tid 9461. Shouldn't the SESS argument be the pid instead of the tid?

```
[me@me multithread]$ cat uftrace.data/task.txt 
SESS timestamp=2525026.536462738 tid=9460 sid=c979e932a604f4f8 exename="/home/me/sources/test/multithread/multithread"
TASK timestamp=2525026.536514704 tid=9460 pid=9457
TASK timestamp=2525026.536579834 tid=9461 pid=9457
```

I can work on a fix if need be.

**Comment by namhyung** [comment]
@tahini hi, thanks for using uftrace and reporting the bug.

Looking at the task file, the task 9460 seems not a main thread, right?  I'm not sure why task 9457 (the main thread, I guess) was not recorded and the session came from task 9460.  If your program is not too big, could you please share it to investigate more?

**Comment by tahini** [comment]
oh the program is not big at all! It's a toy program I did just to test and benchmark uftrace for students that may work with it next semester. 

See here for the code: https://git.dorsal.polymtl.ca/~gbastien/?p=testProjects;a=blob;f=multithread/main.cpp;h=5f1bc834a866b486136bf2b0ddcffd1f6339030c;hb=c12d510fc0261bbaf66280d6a2a00fed73e107b0

The sample I ran had 2 threads created (n=2), probably 9460 and 9461. The main thread did not leave the main function. Maybe that's it?

**Comment by namhyung** [comment]
Thanks for sharing.  Unfornately it works well on my system (I also changed to use 2 threads) like below.  How did you compile your program?  Is it reproducible?

```
$ g++ -o multithread -pg multithread_main.cpp -pthread

$ uftrace --report multithread
return 887459712#
# uftrace report
#
  Total time   Self time       Calls  Function
  ==========  ==========  ==========  ====================================
   14.032  s    9.151  s           2  effect
    7.118  s    6.477 us           1  main
    7.118  s    7.118  s           2  pthread_join
    4.881  s    4.881  s   100000000  bar
  185.632 us    0.712 us           1  iter
  184.920 us    2.996 us           1  __static_initialization_and_destruction_0
  181.327 us  181.327 us           1  std::ios_base::Init::Init
   94.754 us   94.754 us           2  pthread_create
   23.707 us   23.707 us           1  std::ios_base::Init::~Init
   19.325 us   19.325 us           1  printf
    4.234 us    4.234 us           2  __cxa_atexit

#
# uftrace replay
#
# DURATION    TID     FUNCTION
   3.637 us [ 4481] | __cxa_atexit();
            [ 4481] | iter() {
            [ 4481] |   __static_initialization_and_destruction_0() {
 181.327 us [ 4481] |     std::ios_base::Init::Init();
   0.597 us [ 4481] |     __cxa_atexit();
 184.920 us [ 4481] |   } /* __static_initialization_and_destruction_0 */
 185.632 us [ 4481] | } /* iter */
            [ 4481] | main() {
  58.890 us [ 4481] |   pthread_create();
  35.864 us [ 4481] |   pthread_create();
            [ 4481] |   pthread_join() {
            [ 4486] | effect() {
   0.120 us [ 4486] |   bar();
   0.090 us [ 4486] |   bar();
   0.085 us [ 4486] |   bar();
  ...
```

**Comment by tahini** [comment]
You are right, using this compilation command works here too.

I was using a qtcreator project and the automatically generated Makefile to build my project. The compilation commands it was generating are the following:

```
$ make
g++ -c -lpthread -finstrument-functions -g -Wall -W -D_REENTRANT -fPIC -DQT_QML_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I../../testProjects/multithread -I. -isystem /usr/include/qt -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtCore -I. -I/usr/lib/qt/mkspecs/linux-g++ -o main.o ../../testProjects/multithread/main.cpp
g++  -o multithread main.o   -lQt5Gui -lQt5Core -lGL -lpthread 
```
Trying to find the faulty option, it appears that removing the -lQt5Gui and -lQt5Core does the trick. That said, I have no idea what those options do to make it fail and why...

But thanks! At least I can make it work!

**Comment by namhyung** [comment]
Maybe the qt5 libraries have some serious init functions.  I have a plan to fix the assertion anyway as it caused some other problems too.

I think your idea of using pid instead of tid looks good.  Actually I expected tid and pid would be same when it saw a SESS message - I guess kernel will change pid if a non-main thread calls execve().  But it'd also require a change in read_task_txt_file() to read pid as a fallback (for compatibility).  Is it possible for you to send a patch for this?

**Comment by tahini** [comment]
Sure, but that may not be until january as christmas vacations are rapidly arriving!

**Comment by namhyung** [comment]
No problem! :)

**Comment by namhyung** [comment]
@tahini Hi, how's it going?  I just pushed v0.6.1 with a change not aborting on this.  But I think it still needs your patch to find session from the non-main threads.

**Comment by tahini** [comment]
I just tested v0.6.1 with my application and it now finds the main thread (I have 3 TASK lines instead of just 2). Thanks!
I may still work on the fix for pid instead of tid, just to get into the code of uftrace ;-)

**Comment by namhyung** [comment]
Could you please show me your task.txt?  I'd like to be sure that pid and tid is same for SESS lines.

**Comment by tahini** [comment]
With the exact same program that caused the task.txt to be what it was in my first comment on this issue, here is the task.txt with v0.6.1:

```
SESS timestamp=321703.691099144 tid=20219 sid=463dfd967e6146b9 exename="/home/me/sources/multithread/multithread"
TASK timestamp=321703.691132708 tid=20219 pid=20219
TASK timestamp=321703.691323153 tid=20222 pid=20219
TASK timestamp=321703.691373256 tid=20223 pid=20219
```
