### ISSUE TITLE
--auto-args would be better to apply to user functions with dwarf info

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#405]
I think the name `--auto-args` can be used for user functions with dwarf info. It doesn't have to be applied only to the library functions.

What do you think?

**Comment by namhyung** [comment]
I'm ok with the idea.  Let me see how I can change it.

**Comment by namhyung** [comment]
Pushed [review/dwarf-autoargs-v1](https://github.com/namhyung/uftrace/compare/review/dwarf-autoargs-v1).

**Comment by honggyukim** [comment]
Thanks for doing this. It works fine : )

**Comment by namhyung** [comment]
Pushed [review/dwarf-autoargs-v2](https://github.com/namhyung/uftrace/compare/review/dwarf-autoargs-v2)

Changelog:
 * add (and fix) test case
 * update documentation

**Comment by honggyukim** [comment]
Thanks. I just made a few minor comments regarding the document.

**Comment by namhyung** [comment]
Thanks for the review!
