### ISSUE TITLE
Support number of executed instructions using PMU

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#408]
We can currently get the below stats from PMU.
- "pmu-cycle": cpu cycles and instructions using Linux perf-event syscall
- "pmu-cache": (cpu) cache-references and misses using Linux perf-event syscall
- "pmu-branch": branch instructions and misses using Linux perf-event syscall

I think providing the number of executed instructions can also be meaningful because measuring the execution time can be slightly different on every execution. So I think the number of executed instructions can be one of the solid metrics to measure the performance.

I think the name can be "pmu-inst" for this.

**Comment by honggyukim** [comment]
It's not an urgent issue at all but leaving a note just to remember.

**Comment by namhyung** [comment]
The "pmu-cycle" event already provides number of instructions.  Do you want anything different?

**Comment by honggyukim** [comment]
Ah.. right. It already has instruction counts. Thanks.
