### ISSUE TITLE
Total time missing for some functions in TUI graph mode

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#417]
There are som functions that don't have total time in TUI graph mode as follows:
![image](https://user-images.githubusercontent.com/19642328/43120732-43251bfc-8f56-11e8-9d93-0001864fc208.png)
Especially, `main`, `ChromeMain`, `content::ContentMain` and other functions don't have their `TOTAL TIME` on the left.

**Comment by namhyung** [comment]
I guess it's because those functions are not properly finished

**Comment by honggyukim** [comment]
Okay for this case. I will upload again if I see another problem that finishes normally.

**Comment by namhyung** [comment]
Could you please check [check/tui-fix](https://github.com/namhyung/uftrace/compare/check/tui-fix) branch?

**Comment by honggyukim** [comment]
Thanks! I can see the artificially added the exit record and works fine when finding its longest child.
