### ISSUE TITLE
automatic recovery of return address in libmcount

### ISSUE THREAD

**Issue by namhyung** [namhyung/uftrace#418]
Basically uftrace relies on hooks which replace return address of calling function so that it can be executed when the function is exited.  But there are cases target program also makes use of the return address in their body (with certain assumptions).  Sometimes it resulted in a crash (or malfunctioning) because uftrace-hooked return address doesn't fulfill their assumption.  So uftrace provides the `recover` trigger but it's hard for user to apply it properly.

This changes it by applying recovery logic to every single function so that only current function's return address is hooked.  This will minimize the problematic space (but cannot eliminate it entirely).  I tentatively add `mcount_auto_recover` variable to control the behavior but it's always set to true currently and no other method changing it from outside for now.  With this change, I can run a minimal nodejs script with no crash.

The code is available at [review/auto-recover-v1](https://github.com/namhyung/uftrace/compare/review/auto-recover-v1) but there's no change from the users' point of view.

**Comment by honggyukim** [comment]
I've tested it using `clang` as well. This patch seems not to be that slow compared to the original without any recover actions.
**3. with this patch**
```
$ uftrace record --time ./clang hello.c
elapsed time: 23.838248691 sec
 system time: 0.488000000 sec
   user time: 23.340000000 sec

$ uftrace record --time ./clang hello.c
elapsed time: 24.132093099 sec
 system time: 0.592000000 sec
   user time: 23.528000000 sec

$ uftrace record --time ./clang hello.c
elapsed time: 22.957244118 sec
 system time: 0.500000000 sec
   user time: 22.448000000 sec
```
**4. previous master without any recover action**
```
$ uftrace record --time ./clang hello.c
elapsed time: 22.750733265 sec
 system time: 0.576000000 sec
   user time: 22.164000000 sec

$ uftrace record --time ./clang hello.c
elapsed time: 22.630192682 sec
 system time: 0.536000000 sec
   user time: 22.084000000 sec

$ uftrace record --time ./clang hello.c
elapsed time: 23.465210520 sec
 system time: 0.524000000 sec
   user time: 22.932000000 sec
```

**Comment by namhyung** [comment]
Thanks a lot for this detailed tests and analysis.  It's nice to hear that it doesn't slow things down much.

**Comment by honggyukim** [comment]
So I think it can be the default method for safe tracing without worrying about serious slowdown.

**Comment by namhyung** [comment]
OK, I will enable it unconditionally.  Later we might add an option to disable it if performance is a critical issue.

**Comment by honggyukim** [comment]
I'm okay with it. Thanks a lot for this!
