### ISSUE TITLE
Chrome browser cannot read json file if it has strange characters

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#425]
It seems that if the recorded data contains some kind of unusual characters, the output generated by `dump --chrome` cannot be read by chrome browser.

The example is shown below:
![image](https://user-images.githubusercontent.com/19642328/43363008-a801e26c-9334-11e8-9157-ce03732808d4.png)

It becomes as follows:
```
{ ... "name":"std::operator<<","args":{"arguments":"(0x7ffce459ff00, \"x^Q?\")"}},
```
In the above case, we need to reshape those kind of string characters such as `^Q?`.

**Comment by honggyukim** [comment]
One possible solution is to drop the argument or return value if it contains non-ascii characters.

**Comment by namhyung** [comment]
That would be simpler, but I think it's better escaping them like "\x95".

**Comment by honggyukim** [comment]
Hmm.. Do you have any idea how we can detect such cases?

**Comment by namhyung** [comment]
Well, you just can scan every character and escape it if needed.

**Comment by honggyukim** [comment]
I mean I'm not sure which character has to be escaped after scanning it.

**Comment by namhyung** [comment]
`isprint()`?

**Comment by namhyung** [comment]
Maybe you'd better escaping some whitespace characters (like `'\n'`, `'\t'`, ...) differently

**Comment by honggyukim** [comment]
Thanks. I will think about it too.

**Comment by honggyukim** [comment]
Please see #456. Thanks!
