### ISSUE TITLE
update libelf install script for recent version to avoid conflict with gdb.

### ISSUE THREAD

**Issue by ParkHanbum** [namhyung/uftrace#426]
recently gdb version higher than 8 seemed to use libelf version 1.7.
so, installed libelf libs by using misc/install-elfutils.sh will conflict with gdb. 
maybe this is not a big problem to user who can control libs path totally.

**Comment by honggyukim** [comment]
As far as I remember, since `elfutils-0.170`, it has more dependency so cannot compile it independently to build `libelf` and `libdw` so I chose to use `elfutils-0.164`.

If the target board already has `gdb` installed, then I think the system already has `libelf` so I think we can just use the installed version when compiling `uftrace` instead of building it using `misc/install-elfutils.sh`.

**Comment by honggyukim** [comment]
From `elfutils-0.170`, I got this error.
```
  CC       dwarf_peel_type.os
make: *** No rule to make target `../lib/libeu.a', needed by `libdw.so'.  Stop.
make: *** Waiting for unfinished jobs....
  CC       dwarf_default_lower_bound.os
```

**Comment by honggyukim** [comment]
I can see `libelf.so` and `libdw.so` after this change. We also have to test  it for ARM environment but please check if it works in your environment first.
```
$ ./misc/install-elfutils.sh --prefix=`pwd`/build.host
        ...

$ ls -R build.host/
build.host/:
include  lib

build.host/include:
dwarf.h  elfutils  gelf.h  libelf.h  nlist.h

build.host/include/elfutils:
elf-knowledge.h  known-dwarf.h  libdw.h

build.host/lib:
libdw-0.173.so  libdw.a  libdw.so  libdw.so.1  libelf-0.173.so  libelf.a  libelf.so  libelf.so.1
```

**Comment by ParkHanbum** [comment]
@honggyukim thanks you for detailed comment. 
Cflags needs more option that '-Wimplicit-fallthrough=0' to compile libelf.
but same issue were occurred after installed.

```
gdb: /usr/local/lib/libelf.so.1: version `ELFUTILS_1.7' not found (required by /usr/lib/x86_64-linux-gnu/libdw.so.1)
```

**Comment by honggyukim** [comment]
In that case, uftrace and gdb have to be compiled with the same `libelf.so`. It seems that you're using different `libelf.so` for them.

**Comment by honggyukim** [comment]
Maybe we can talk more about it on Thursdays.

**Comment by namhyung** [comment]
I don't know why gdb depends on the libelf since it would use libbfd for ELF (or other binary) file manipulation AFAIK.  Did you compile and install gdb by yourself?

**Comment by namhyung** [comment]
This seems a configuration problem.  In your error message, libelf is a local library you compiled but libdw is a system one.  It's rare for users compile gdb by themselves and I don't want to complicate the script not necessariliy.
