### ISSUE TITLE
Support build on Android (AOSP)

### ISSUE THREAD

**Issue by gigony** [namhyung/uftrace#433]
Thank you for developing a great tool!
It would be very nice if makefile of uftrace is applicable for Android platform.

Current uftrace source code heavily depends on argp.
Unfortunately, Android's [bionic](https://en.wikipedia.org/wiki/Bionic_(software)) doesn't implement argp so uftrace is not buildable for arm-based Android, showing argp-related error messages (attached build error messages: [build_failure.txt](https://github.com/namhyung/uftrace/files/2261830/build_failure.txt)).

https://android.googlesource.com/platform/external/elfutils/+/master/bionic-fixup/argp.h

```
export TOP=/build/gbae/dev-other-next
# cp $TOP/external/elfutils/bionic-fixup/argp.h $TOP/prebuilts/ndk/r11/platforms/android-21/arch-arm/usr/include/    <== used for fixing include-related error but argp implementation is missing..
export CFLAGS="-march=armv7-a --sysroot=$TOP/prebuilts/ndk/r11/platforms/android-21/arch-arm"
./configure --prefix=`pwd`/build --with-elfutils=$TOP/external/elfutils
make
```

I wonder if you have any idea on making uftrace available on Android.

**Comment by namhyung** [comment]
@gigony thanks for kind words.  Currently uftrace is tested on glibc-based systems only so I'm not sure it works well on Android too.  Unfortunately I'm not familiar with the Android code base..

For argp errors, it looks like there's a standalone argp library.  Is it possible for you to try to build with it?

**Comment by gigony** [comment]
@namhyung Thanks for the reply!

It seems that there were similar issues with v4l-utils.
   https://patchwork.kernel.org/patch/7117581/

I think I can try to build library with https://github.com/jahrome/argp-standalone on Android.
I am not sure if it would work without significant modifications because Android is using Clang as a default compiler nowadays.
Would let you know when I am able to build it.

**Comment by ParkHanbum** [comment]
google offer the strace that has compiled statically by trace tool. 
because Android OS environment could be customized by OS vendor. 
if there is the way to build by statically, could helpful for these cases.

**Comment by honggyukim** [comment]
In termux project, they maintain some local patches for Android porting. Maybe we can apply some of their local patches into uftrace.

One of the major obstacles for porting uftrace to Android is to provide `shm_open`/`shm_unlink`.

@namhyung What do you think about having our custom `shm_open`/`shm_unlink` implementation just like termux does in https://github.com/termux/termux-packages/blob/master/packages/uftrace/cmds-record.c.patch?

**Comment by namhyung** [comment]
We can have an abstraction layer for shmem.  On posix, we can use `shm_*` APIs and fallback to tmpfs if not available.

**Comment by namhyung** [comment]
Note that we already got rid of `argp` parser from v0.10.
