### ISSUE TITLE
Skip symbol loading for record command

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#44]
Sometimes symbol loading takes too much time when target binary is really big. (e.g. chrome)
It'd be a lot better to save time when I only run `record` command without symbol related options such as `-F`, `-N`, `-T`, `-A`, and `-R`. In most cases, I prefer to use only time-filter option(`-t`) so please skip symbol loading as default.

**Comment by namhyung** [comment]
Hmm.. makes sense.

Currently uftrace loads symbol table at least twice - one in the libmcount to setup filters and another in uftrace record to write symbol files.  If the process starts a new session (usually by `exec`) it loads another symbol table (again).  I think we can get rid of the first loading if not needed (as you mentioned).  Not sure about the second case though.

**Comment by namhyung** [comment]
I uploaded the code to skip symbol table loading in libmcount.  Please take a look at `check/skip-symtab-v1` branch.

**Comment by namhyung** [comment]
Merged: deb86e7
