### ISSUE TITLE
memory leak in Multiple functions

### ISSUE THREAD

**Issue by gy741** [namhyung/uftrace#441]
Hello.

I found a memory leak bug.

In the load_debug_file, read_events_file, read_task_txt_file, read_session function.

For the first parameters used in the getline() function, free() function is not used.

So, I think there can be a memory leak.

What do you think?

Thanks.

Example:

1.Problem Code : utils/dwarf.c:1309 
https://github.com/namhyung/uftrace/blob/957332a69716679d01a9c227709b43575e06ae99/utils/dwarf.c#L1277-L1375

2.Good Code : uftrace.c:936
https://github.com/namhyung/uftrace/blob/f2537c8f9bf164f8a0f3898e8f3cff8ec8a0e3ea/uftrace.c#L881-L938

**Comment by honggyukim** [comment]
Hi @gy741, could you please send a pull request instead of writing it as an issue?

**Comment by gy741** [comment]
@honggyukim 

Hello,

I sent a pull request.

Thanks.
