### ISSUE TITLE
meaningless condition check in cmds/record.c

### ISSUE THREAD

**Issue by gy741** [namhyung/uftrace#442]
Hello.

I think, the if conditional statement in cmds/record.c on line 1367 is useless.

The if conditional statement is always true.

what do you think?

Thanks.

https://github.com/namhyung/uftrace/blob/bee18bdfcf65cce26aede6d16ba4f5b5cfc441ad/cmds/record.c#L1365-L1368

Test code
```
#include<stdio.h>

int main() {
    char sid[20] = { 0, };
    if (sid[0] == '\0'){
        printf("Always true");
    }
}
```

**Comment by honggyukim** [comment]
Could you please send a pull request for this as well?

**Comment by gy741** [comment]
@honggyukim

Hello,

I sent a pull request.

Thanks.
