### ISSUE TITLE
How to record and replay simultaneously?

### ISSUE THREAD

**Issue by taeguk** [namhyung/uftrace#444]
Currently, it seems that ```uftrace``` doesn't support the feature which enables performing ```record``` and ```replay``` simultaneously.
So, there are two steps for performing 'record' and 'replay', both.
First, an user perform ```record``` at first, and then the user perform ```replay```.
But I want to perform them simultaneously with just one command.
Is there no way to do that way?

**Comment by ParkHanbum** [comment]
maybe you can use `live` command.

**Comment by honggyukim** [comment]
Hi @taeguk.

As you said, uftrace currently doesn't support actual live record and replay but it can be done using a python script in a limited way.

Here is a simple program that prints a meesage.
```c
$ cat hello.c
#include <stdio.h>

int main()
{
    printf("Hello World!\n");
    return 0;
}
```

`live` command does record first then replay after the execution.
```
$ gcc -pg hello.c

$ uftrace live a.out
Hello World!
# DURATION     TID     FUNCTION
   1.154 us [160618] | __monstartup();
   1.083 us [160618] | __cxa_atexit();
            [160618] | main() {
   7.957 us [160618] |   puts();
   8.904 us [160618] | } /* main */
```
If you use [scripts/replay.py](https://github.com/namhyung/uftrace/blob/master/scripts/replay.py) script, the tracing output is printed during execution.
```
$ uftrace record -S scripts/replay.py a.out
            [160569] | __monstartup() {
  52.181 us [160569] | } /* __monstartup */
            [160569] | __cxa_atexit() {
  14.437 us [160569] | } /* __cxa_atexit */
            [160569] | main() {
            [160569] |   puts() {
Hello World!
  16.703 us [160569] |   } /* puts */
  46.201 us [160569] | } /* main */
```
For more information, you can refer to [uftrace-record.md#script-execution](https://github.com/namhyung/uftrace/blob/master/doc/uftrace-record.md#script-execution).

**Comment by taeguk** [comment]
@honggyukim Thanks for your kind descriptions :)
