### ISSUE TITLE
Enable scheduling event by default (if available)

### ISSUE THREAD

**Issue by namhyung** [namhyung/uftrace#450]
The linux perf event subsystem provides a way to record task scheduling event without root privilege.  As it already has been using task-related events by default, also enable this schedule event for more precise execution information.  It requires a recent kernel (4.3+ according to the [manual page](http://man7.org/linux/man-pages/man2/perf_event_open.2.html) - see `perf_event_attr.context_switch` part), and the value of `/proc/sys/kernel/perf_event_paranoid` being 2 or smaller.

It adds two more configure item in the output to show its availability like below:

```
$ ./configure
uftrace detected system features:
...         prefix: /usr/local
...         libelf: [ on  ] - more flexible ELF data handling
...          libdw: [ on  ] - DWARF debug info support
...   libpython2.7: [ on  ] - python scripting support
...    libncursesw: [ on  ] - TUI support
...   cxa_demangle: [ on  ] - full demangler support with libstdc++
...     perf_event: [ on  ] - perf (PMU) event support
...       schedule: [ on  ] - scheduler event support
```

Enabling this also shows some points that need to care.  And test results can be affected by random context switchs due to kernel's decision.  Many of this change includes test output adjustments.

The code is available at [review/schedule-update-v1](https://github.com/namhyung/uftrace/compare/review/schedule-update-v1).

**Comment by namhyung** [comment]
I'm not sure we need an option to hide it just for the documentation.  The schedule event is inherently non-deterministic so we have to live with it.

**Comment by namhyung** [comment]
The schedule event should be filtered using `-t`/`--time-filter` option.  Also apply `--no-event` option to dump, report, graph and tui commands as well.

The code was pushed to [review/schedule-update-v3](https://github.com/namhyung/uftrace/compare/review/schedule-update-v3).

**Comment by namhyung** [comment]
Hmm.. ok.  My simple test worked but I didn't test it with highly-parallel programs.  Maybe because they are scheduled on a different cpu.

Currently it only looks ahead a perf event from the same cpu to match schedule event and check the time filter.  Fixing this looks not an easy task though..

**Comment by namhyung** [comment]
I think we should go with this for now and fix it later..

**Comment by namhyung** [comment]
New code is pushed to [review/schedule-update-v4](https://github.com/namhyung/uftrace/compare/review/schedule-update-v4).

**Comment by namhyung** [comment]
I find it fixed on my system now.  Do you still see the problem?

**Comment by honggyukim** [comment]
I also see the problem is fixed now. Thanks!

**Comment by honggyukim** [comment]
I tested it on the current master.

**Comment by namhyung** [comment]
Cool!
