### ISSUE TITLE
meaningless condition check in utils/symbol.c

### ISSUE THREAD

**Issue by gy741** [namhyung/uftrace#452]
Hello.

I think, the if conditional statement in utils/symbol.c on line 1301 is useless.

The if conditional statement is always true.

what do you think?

Thanks.

https://github.com/namhyung/uftrace/blob/fe5e6dcea5be5cacf92b61b02ea56bed65b9fab3/utils/symbol.c#L1263-L1310

**Comment by namhyung** [comment]
Indeed, please send a PR. :)
