### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by thepaul** [namhyung/uftrace#454]
Hi! I'm looking at uploading a fix for https://bugs.debian.org/906512 (regarding the failure of uftrace to build cleanly from source on a newer toolchain). It looks like you have fixed the problem already, probably with commit fe5e6dcea5be5cacf92b61b02ea56bed65b9fab3, so that's nice.

Do you think uftrace is almost ready for a new release version? If so, I will wait for that and package it. Otherwise, I'll try packaging 0.8.3 and then just cherry-picking fe5e6dc to see if it can solve the problem on its own.

**Comment by thepaul** [comment]
Here are results from testing the current master, merged with #450, on Debian sid and Debian Buster (aka Debian Testing). I'm not sure which of the test failures, if any, are expected.

[results-on-sid.txt](https://github.com/namhyung/uftrace/files/2337867/results-on-sid.txt)
[results-on-buster.txt](https://github.com/namhyung/uftrace/files/2337870/results-on-buster.txt)

It looks pretty good, though.

**Comment by namhyung** [comment]
Thanks a lot!

Currently I'm aware of failures in nested functions (t052) with `-finstrument-functions`, recv with `--run-cmd` (t151) and some DWARF tests with optimization (t203, t204).  But depending on configuration, some more tests may fail.

**Comment by namhyung** [comment]
[v0.9](https://github.com/namhyung/uftrace/releases/tag/v0.9) is out!

**Comment by thepaul** [comment]
🍾 🎉 🙌

**Comment by honggyukim** [comment]
Hi @thepaul,

Can you please include all the required packages in the dependency list when you package `uftrace-0.9`?

uftrace can be compiled without them but it misses many useful updated features.
Please make sure that all the fields are `on` in configure result.
```
$ ./configure
uftrace detected system features:
...         prefix: /usr/local
...         libelf: [ on  ] - more flexible ELF data handling
...          libdw: [ on  ] - DWARF debug info support
...   libpython2.7: [ on  ] - python scripting support
...    libncursesw: [ on  ] - TUI support
...   cxa_demangle: [ on  ] - full demangler support with libstdc++
...     perf_event: [ on  ] - perf (PMU) event support
...       schedule: [ on  ] - scheduler event support
```
Thanks a lot for your effort!

**Comment by honggyukim** [comment]
Cool! Thanks a lot!
