### ISSUE TITLE
memory leak in setup_trigger(utils/filter.c)

### ISSUE THREAD

**Issue by gy741** [namhyung/uftrace#458]
Hello.

I think there is a memory leak at setup_trigger:927.

Possible memory leaks from usage of strdup without free().

Am I missing something or it really miss free() call?

What do you think?

Thanks.

problem code:
https://github.com/namhyung/uftrace/blob/58ef456a63b6de89978d2bc007c579f15fc1e821/utils/filter.c#L882-L1001

in my opinion, fix code:
```
diff --git a/utils/filter.c b/utils/filter.c
index c505f49..76cc275 100644
--- a/utils/filter.c
+++ b/utils/filter.c
@@ -927,7 +927,7 @@ static void setup_trigger(char *filter_str, struct symtabs *symtabs,
 		name = demangle(name);
 
 		init_filter_pattern(ptype, &patt, name);
-
+		free(name);
 		if (module) {
 			/* is it the main executable? */
 			if (!strncmp(module, basename(symtabs->filename),
```

**Comment by namhyung** [comment]
Looks ok.  Please send the fix, but I'd like to group them to clarify the lifetime of the name and reason of the demangling:

```c
      ...
   }

   /* use demangled name for triggers (some auto-args need it) */
   name = demangle(name);
   init_filter_pattern(ptype, &patt, name);
   free(name);

   if (module) {
      ...
```

**Comment by gy741** [comment]
@namhyung 

> I'd like to group them to clarify the lifetime of the name and reason of the demangling.

Hmm... Sorry, I don't know what you mean.
I sent pull request.

**Comment by honggyukim** [comment]
@gy741 He wants to make the following change.
```diff
diff --git a/utils/filter.c b/utils/filter.c
index c505f49..6ba4ac3 100644
--- a/utils/filter.c
+++ b/utils/filter.c
@@ -925,8 +925,8 @@ static void setup_trigger(char *filter_str, struct symtabs *symtabs,

                /* demangle the name before setting a trigger */
                name = demangle(name);
-
                init_filter_pattern(ptype, &patt, name);
+               free(name);

                if (module) {
                        /* is it the main executable? */
```
And the code becomes as follows:
```c
      ...
   }

   /* use demangled name for triggers (some auto-args need it) */
   name = demangle(name);
   init_filter_pattern(ptype, &patt, name);
   free(name);

   if (module) {
      ...
```

**Comment by gy741** [comment]
@honggyukim 
Thank you for your reply.
Aha, I understand.
need to reduce the lines and change the annotations and add free().
Am I right?

**Comment by gy741** [comment]
@honggyukim 

Okay.:)
I fix Pull request.
https://github.com/namhyung/uftrace/blob/4ff029c692b2a2e3a30145b79371134eb99230bc/utils/filter.c#L925-L931
