### ISSUE TITLE
Do not turn on pager during record in live mode

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#465]
There are some problems when running record command with pager.
- ~~unable to receive user input using scanf, etc. just like gdb~~
- doesn't nicely finish when user sends SIGINT with Ctrl-C.
- still couldn't fix node problem in #333.
- sometimes works badly for other programs that use TUI interface.

Considering all these, I think it'd be better to turn on pager after record in live mode.

- Before: launch live mode -> turn on pager -> record command -> replay command
- After: launch live mode -> record command -> turn on pager -> replay command

We better just provide an option `-p` / `--pager` to explicitly turn on pager earlier than record command. So the sequence will become as follows with `--pager` option.

- with `--pager`: launch live mode -> turn on pager -> record command -> replay command

**Comment by namhyung** [comment]
Hmm.. but it'll lose output from the target process and uftrace record.

**Comment by namhyung** [comment]
OK, I'm ok with this.  It'll handle the cases like #536 as well.

**Comment by honggyukim** [comment]
Yes, it doesn't make a problem on node with it.
