### ISSUE TITLE
Finding target binary in $PATH

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#474]
uftrace can also be used for pre-built binaries with `--force` or `--nest-libcall` so I think it can just find target binary in $PATH instead of writing its full path, which doesn't seem to be intuitive.

I think It makes easier to use for new users. Please let me know how you think about it.

**Comment by namhyung** [comment]
Maybe we can enable it when those options are given, or (full) dynamic tracing is available.

**Comment by honggyukim** [comment]
Okay. I'm fine with that.

**Comment by honggyukim** [comment]
We now have dynamic tracing support so I implemented it in #741.
