### ISSUE TITLE
[Questions] about scope of contribution

### ISSUE THREAD

**Issue by gy741** [namhyung/uftrace#475]
Hello.

Is libtraceevent included in the scope of contribution?

Hmm, Looks like it has not changed for a long time.

And, Similar source code exists in the kernel.

Thanks.

**Comment by honggyukim** [comment]
`libtraceevent` to handle ftrace data recorded by kernel and it is copied from Linux kernel source tree.
So I think you better not to modify it unless it has some important side effect.

**Comment by gy741** [comment]
Thank you for your reply. :)
