### ISSUE TITLE
TUI problem in nested graph construction

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#476]
In tui mode, `g` key requests to restructure graph based on the currently pointing function.   But it doesn't work in nested manner. 

Here is the sequence to reproduce it.
- step 1. open tui without target function
- step 2. choose a function and press `g` key to restructure graph based on it.
- step 3. In the same window, choose another function and press `g` key

After running step 3. it doesn't restructure the graph based on the next target function, but just go to the top in the same graph.

**Comment by namhyung** [comment]
Right, I missed to check the partial_graph condition.  The following patch will fix:

```diff
diff --git a/cmds/tui.c b/cmds/tui.c
index 1b3411a9..45de2ad5 100644
--- a/cmds/tui.c
+++ b/cmds/tui.c
@@ -2395,7 +2395,7 @@ static void tui_main_loop(struct opts *opts, struct ftrace_file_handle *handle)
                        }
                        break;
                case 'g':
-                       if (win == &graph->win) {
+                       if (win == &graph->win || win == &partial_graph.win) {
                                struct tui_report_node *func;
                                struct tui_graph_node *curr = win->curr;
 
```
