### ISSUE TITLE
 How do I troubleshoot problems installing uftrace

### ISSUE THREAD

**Issue by u0jin** [namhyung/uftrace#504]
I had an error installing vmware with the following code

$ sudo apt-get install libdw-dev pandoc \
       libpython2.7-dev libncursesw5-dev

libncursesw system is off  so , I had install libncursesw 5-dev 
But it turns out the system is still off.

**Comment by gy741** [comment]
Hello,

Please try ```sudo apt-get install pkg-config``` and build.

Thanks.

**Comment by u0jin** [comment]
Thank you~!!!!
I solved the problem.

**Comment by namhyung** [comment]
There's a doc [INSTALL.md](../blob/master/INSTALL.md) to describe how to do it.  I think we need to add `pkg-config` to the quick guide section.

**Comment by ParkHanbum** [comment]
@honggyukim I think adding information about pkg-config to uftrace.github.io could good to new users.
