### ISSUE TITLE
Error from uftrace while capturing multi-threaded application

### ISSUE THREAD

**Issue by AmeyaVS** [namhyung/uftrace#512]
While capturing a trace from a multi-threaded application, I have received the following error from uftrace:

```sh
mcount: /home/ameya/apps/src/uftrace/libmcount/plthook.c:877:plthook_exit
 ERROR: <3> invalid dynsym idx: -269488145
```
After debugging the application directly through gdb, I found that the uftrace missed some trace events.

Following is the scenario:
1. Application creates `pthreads` with the attributes `PTHREAD_CREATE_DETACHED`.
2. Which would be blocked immediately by a pthread condition variable.
3. The Entry-point of the function for the thread is captured in the trace event.
4. But since the thread is never really allowed to execute using the pthread_condition variable as a blocker
5. No exit event is ever captured since the application force exits and the threads are killed.

**Note**:
I have attached the script which reproduces the issue.
* Following lines in the script are important once the library is built and installed:
  * line:**102 to 129**

**Disclaimer**:
* I am not very good at `bash` scripting : P
* You have been **Warned to review the script before executing it!!!**

**Prerequisites**
* `cmake`
* `wget`
* `perl`
* **Internet connection**: Downloads the library and its regression test suite.

[systemc-build.txt](https://github.com/namhyung/uftrace/files/2393415/systemc-build.txt)

**Comment by namhyung** [comment]
Thanks for explanation and the script, I will check it out soon..

**Comment by namhyung** [comment]
cannot find `systemc/1666-2011-compliance/living_dead_bug/systemc.exe`.

**Comment by AmeyaVS** [comment]
Sorry for issue but can you look into the directory for a file:(See if the file is created?)
`systemc-regressions-2.3.2/run/systemc/1666-2011-compliance/living_dead_bug/living_dead_bug.log`

In-case it is not created you can just focus on the lines(**102-129**) from the file shared with you, if the above lines have executed without any errors.

**Comment by namhyung** [comment]
```
$ ls systemc/1666-2011-compliance/living_dead_bug/
living_dead_bug  living_dead_bug.log  living_dead_bug.o

$ cat systemc/1666-2011-compliance/living_dead_bug/living_dead_bug.log 
/usr/bin/ld: cannot find -lsystemc
collect2: error: ld returned 1 exit status
```

**Comment by AmeyaVS** [comment]
ok is the `LD_LIBRARY_PATH` set to the location of the installed library `libsystemc.so.2.3.2`?

Or you can also specify the command line option to the `verfiy.pl` script.

```sh
../scripts/verify.pl -L $SYSTEMC_HOME/lib -g -v -no-cleanup -o "-std=c++11 -finstrument-functions" systemc/1666-2011-compliance/living_dead_bug
```
-Ameya

**Comment by namhyung** [comment]
I managed to build it with below patch:

```diff
$ diff -u systemc-regressions-2.3.2/scripts/verify.pl{.orig,}
--- systemc-regressions-2.3.2/scripts/verify.pl.orig	2018-09-20 00:07:25.373793562 +0900
+++ systemc-regressions-2.3.2/scripts/verify.pl	2018-09-20 00:12:05.420713983 +0900
@@ -856,7 +856,7 @@
     $rt_debug_ldflags = "";
     $rt_optimize_flag = "-O2";
     $rt_systemc_include = "$rt_systemc_home/include";
-    $rt_systemc_ldpath  = "$rt_systemc_home";
+    $rt_systemc_ldpath  = "$rt_systemc_home/lib64";
 
     # predefined macros
     @rt_defines = ();
```

**Comment by AmeyaVS** [comment]
Sorry for the delayed response, are you by any chance running the test in a recent distro release?
What Linux system are you using?
Actually the test runs to completion in Ubuntu 16.04 LTS but hangs in Ubuntu 18.04 LTS.
It seems to be a deadlock issue which I am working on.

Thought it might be useful to compare the traces on different systems to narrow down the issue.

Thanks for the capture I will look into it.

Regards,
Ameya

**Comment by namhyung** [comment]
As you can see from the `uftrace info` it runs pretty recent versions.  I'm running ArchLinux with kernel 4.16, glibc 2.27 and GCC 8.1.  But maybe Ubuntu has some custom settings..

**Comment by AmeyaVS** [comment]
**Update:** The original issue with the error message:
```text
mcount: /home/ameya/apps/src/uftrace/libmcount/plthook.c:877:plthook_exit
 ERROR: <3> invalid dynsym idx: -269488145
```

Has been fixed with the latest commit from git master branch:`018956b9`.

But it seems uftrace is not capturing all the threads traces, here is the log from a gdb run on Ubuntu 16.04 LTS
```text
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./systemc.exe...done.
(gdb) b sc_main
Breakpoint 1 at 0x403adf: file ./living_dead_bug/living_dead_bug.cpp, line 77.
(gdb) r
Starting program: /home/ameya/apps/src/systemc-regressions-2.3.2/runInstrument/systemc/1666-2011-compliance/living_dead_bug/systemc.exe 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

        SystemC 2.3.2-Accellera --- Sep 18 2018 21:31:23
        Copyright (c) 1996-2017 by all Contributors,
        ALL RIGHTS RESERVED

Breakpoint 1, sc_main (argc=1, argv=0x644290) at ./living_dead_bug/living_dead_bug.cpp:77
77	{
(gdb) c
Continuing.
[New Thread 0x7ffff7fd3700 (LWP 11738)]
[New Thread 0x7ffff7f92700 (LWP 11739)]

Warning: (W558) disable() or dont_initialize() called on process with no static sensitivity, it will be orphaned: top.target
In file: /home/ameya/apps/src/systemc-2.3.2/src/sysc/kernel/sc_simcontext.cpp:766
[New Thread 0x7ffff7f51700 (LWP 11740)]

Warning: (W558) disable() or dont_initialize() called on process with no static sensitivity, it will be orphaned: top.control.dyn_target
In file: /home/ameya/apps/src/systemc-2.3.2/src/sysc/kernel/sc_simcontext.cpp:1219
In process: top.control @ 0 s

Success
[Thread 0x7ffff7f92700 (LWP 11739) exited]
[Thread 0x7ffff7f51700 (LWP 11740) exited]
[Thread 0x7ffff7fd3700 (LWP 11738) exited]
[Inferior 1 (process 11734) exited normally]
(gdb) q
```

From the messages:`[New Thread *]` there are three of them not including the main thread.(So a total of four threads)

But from the captured traces(attached) only two of them are being displayed on the `chrome://tracing` viewer.

-Ameya

[no_error.json.txt](https://github.com/namhyung/uftrace/files/2402227/no_error.json.txt)

**Comment by namhyung** [comment]
> Update: The original issue with the error message:
> Has been fixed with the latest commit from git master branch:018956b9

Good!

> From the messages:[New Thread *] there are three of them not including the main thread.(So a total of four threads)
> 
> But from the captured traces(attached) only two of them are being displayed on the chrome://tracing viewer.

Hmm.. my data file had 4 threads:

```
$ uftrace dump --chrome -d uftrace-systemc.data
{"traceEvents":[
{"ts":0,"ph":"M","pid":11750,"name":"process_name","args":{"name":"[11750] systemc.exe"}},
{"ts":0,"ph":"M","pid":11750,"name":"thread_name","args":{"name":"[11750] systemc.exe"}},
{"ts":0,"ph":"M","pid":11752,"name":"process_name","args":{"name":"[11752] systemc.exe"}},
{"ts":0,"ph":"M","pid":11752,"name":"thread_name","args":{"name":"[11752] systemc.exe"}},
{"ts":0,"ph":"M","pid":11753,"name":"process_name","args":{"name":"[11753] systemc.exe"}},
{"ts":0,"ph":"M","pid":11753,"name":"thread_name","args":{"name":"[11753] systemc.exe"}},
{"ts":0,"ph":"M","pid":11754,"name":"process_name","args":{"name":"[11754] systemc.exe"}},
{"ts":0,"ph":"M","pid":11754,"name":"thread_name","args":{"name":"[11754] systemc.exe"}},
{"ts":19020038007.455,"ph":"B","pid":11750,"name":"_GLOBAL__sub_I_sc_main"},
{"ts":19020038007.790,"ph":"B","pid":11750,"name":"__static_initialization_and_destruction_0"},
{"ts":19020038008.206,"ph":"B","pid":11750,"name":"std::ios_base::Init::Init"},
{"ts":19020038009.520,"ph":"E","pid":11750,"name":"std::ios_base::Init::Init"},
...
```

**Comment by AmeyaVS** [comment]
Closing the issue as the original error message was fixed in the master branch.
