### ISSUE TITLE
doc : Need to use different Package name when installing the uftrace.

### ISSUE THREAD

**Issue by ClaudiaJKang** [namhyung/uftrace#519]
When installing the uftrace, 
RHEL, Fedora, and CentOS machines need to install different Package name. 

- Package names 

  |Ubuntu|RHEL, CentOS, Fedora|
  |---|---|
  |libdw-dev|elfutils-devel|
  |libpython2.7|python2-devel|
  |pandoc|pandoc|
  |libncursesw|ncurses-devel|
  |pkg-config|pkgconf-pkg-config|

How about adding this contents in INSTALL.md?

**Comment by ParkHanbum** [comment]
@ClaudiaJKang is apt-get available in non-ubuntu linux package?

**Comment by ClaudiaJKang** [comment]
@ParkHanbum Sorry. It's my mistake. apt-get is not available in non-ubuntu Linux. I fixed command in PR.
