### ISSUE TITLE
Recording currently running core number for each function

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#522]
I think it'd be better to provide a way to record which core is running the current function.
Once it's recorded, then it can be displayed with `-f core` or `-f cpu` in replay output.

A single system call `getcpu(2)` provides the currently running core number as follows:
```
#include <stdio.h>
#include <unistd.h>
#include <sys/syscall.h>

// int getcpu(unsigned *cpu, unsigned *node, struct getcpu_cache *tcache);

int main(void)
{
    int ret;
    unsigned cpu;

    ret = syscall(SYS_getcpu, &cpu, NULL, NULL);
    printf("cpu = %u\n", cpu);

    return 0;
}
```
The core number has to be recorded for each function entry and exit considering schedule in and out.

**Comment by namhyung** [comment]
And `getcpu(2)` is usually implemented in vDSO so you don't need to use the `syscall` macro - actually it's gonna be worse..

**Comment by namhyung** [comment]
I pushed [review/watch-support-v1](https://github.com/namhyung/uftrace/compare/review/watch-support-v1) to implement it as an watchpoint.

```
$ uftrace -W cpu -F main t-abc-pg
# DURATION     TID     FUNCTION
            [ 22057] | main() {
            [ 22057] |   /* watch:cpu (cpu=2) */
            [ 22057] |   a() {
            [ 22057] |     b() {
            [ 22057] |       c() {
   0.655 us [ 22057] |         getpid();
   1.831 us [ 22057] |       } /* c */
   2.142 us [ 22057] |     } /* b */
   2.502 us [ 22057] |   } /* a */
   3.892 us [ 22057] | } /* main */
```

**Comment by honggyukim** [comment]
You're right. It doesn't have to be recorded every entry and exit. Actually, I prefer to display it as a replay field but I think this is also great. We can think about replay field later if possible. Thanks a lot for this work!

**Comment by honggyukim** [comment]
I'm okay with it as well. Thanks!

**Comment by honggyukim** [comment]
There are some warnings so please take a look at it before merging it.
```
  CC FPIC  libmcount/record.op
/home/honggyu/work/uftrace/libmcount/record.c: In function ‘save_watchpoint’:
/home/honggyu/work/uftrace/libmcount/record.c:757:4: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
    *(int *)event->data = cpu;
    ^
/home/honggyu/work/uftrace/libmcount/record.c: At top level:
cc1: warning: unrecognized command line option ‘-Wno-stringop-truncation’
  CC FPIC  libmcount/plthook.op
```

**Comment by namhyung** [comment]
Thanks, pushed [review/watch-support-v2](https://github.com/namhyung/uftrace/compare/review/watch-support-v2).

Changelog:
 * fix compile warning
 * always record watch point at init
 * add test case and documentation

**Comment by honggyukim** [comment]
Thanks!
