### ISSUE TITLE
Notifying .PLT.GOT section not found with warn or error message?

### ISSUE THREAD

**Issue by DanielTimLee** [namhyung/uftrace#529]
Any chance of notifying .PLT.GOT section not found with warn or error message?

I was kinda hard to find out why my `/bin/ls` is not traceable with plt_hooking.

```bash
$ uftrace --force --no-pager /bin/ls -l
total 24
-rw-r--r-- 1 vagrant vagrant    84 10월  5 01:37 a.c
-rwxr-xr-x 1 vagrant vagrant 17000 10월  5 01:37 a.out
WARN: cannot open record data: /tmp/uftrace-live-yAytxj: No data available

$ uftrace -vv --force --no-pager /bin/ls -l
mcount: setup PLT hooking                                                                                                                                                                              
mcount: setup plthook data for /usr/bin/ls (offset: 56386399e000)                                                                                                                                      
mcount: opening executable image: /usr/bin/ls                                                                                                                                                          
mcount: no PLTGOT nor BIND-NOW.. ignoring...                                                                                                                                                           
mcount: mcount setup done                                                                                                                                                                              
total 24
-rw-r--r-- 1 vagrant vagrant    84 10월  5 01:37 a.c
-rwxr-xr-x 1 vagrant vagrant 17000 10월  5 01:37 a.out
uftrace: MSG FINISH
uftrace: all process/thread exited                                                                                                                                                                     
uftrace: child terminated with exit code: 0   
...
uftrace: live-record finished.. 
uftrace: start live-replaying...
WARN: cannot open record data: /tmp/uftrace-live-kENa1j: No data available
uftrace: removing /tmp/uftrace-live-kENa1j directory
```

How about notifying with 
`WARN: cannot find .PLT.GOT in ELF. Is your executable compiled with --no-plt?`

(+ I think this message should be ERROR not WARN. Cause the execution of this command has been failed completely.)

**Comment by DanielTimLee** [comment]
Just out of curiosity,

I'm totally aware that this project will not explain everything about .PLT.GOT or ELF section things.
If this Project directional doesn't match with adding a bunch of comments about the desired functionality, It's totally fine. I stand up for that idea.

But in this case, with all due respect, 
doesn't program has to inform about why it won't work as it desired unless it is a bug?

`uftrace` offers tracing functionality, 
however, for now, it doesn't support library call hooking with `--no-plt` compiled program.

Wouldn't it be more user friendly to inform users about why it won't work correctly?
Or at least, simply shows users about whether the result is desired or not with `WARN` or `ERROR`?

In my experience, 
when the `uftrace` result just shows me a `WARN` message (which means it's desired result) and with no tracing result, I start to think about what I have been doing wrong (maybe missing args with gcc?).

I'm not saying this tool have to explain bits and pieces about why it won't work as it is.

But if command results provide some more informative messages, it would be a lot more helpful for users to debug.

**Comment by namhyung** [comment]
Users can use `-v` option to see detailed messages when something goes wrong.
