### ISSUE TITLE
need modification in tutorial

### ISSUE THREAD

**Issue by iamwonseok** [namhyung/uftrace#53]
When I read a tutorial of function-depth filter part, I was difficult to understand from your assumption.

I'm attaching the original text as below and marking the bold the part of your assumption that I was confused.

========== text from tutorial ==========
The next is function-depth filter. You can use -D or --depth to limit function call depth to be recorded. Below is apply depth-2 filter on the uftrace itself when replay the hello world program. **To make it clearer, I named the binary built with the compiler instrumentation as "uftrace-pg" and assume the trace data is in hello.data.** The "--" in the command line is to tell the option parser that it's the end of the option. For simplicity, I omitted the output of replaying hello world from the uftrace-pg:
$ uftrace -D 2 -- uftrace-pg replay -d hello.data
========== text from tutorial ==========

The confusion came from how to create hello.data. Even if uftrace can record the trace data to specific directory and you discussed at the front of tutorial, there is no kindly guideline to store tracing data to specific directory.

When I was executed "uftrace record hello -d hello.data" at the first time, because I followed replay command in the example. After I executed the command, only “uftrace.data” was created. The reason made me confused. Anyway, I found the way to store data with directory name. There are two ways to use “uftrace -d hello.data record hello” or “uftrace record -d hello.data hello”.

The command “uftrace record hello -d hello.data” is no effect to directory’s name, Is it your intention? or is the problem in parsing the argument in uftrace? 

Anyway, the goal of the paragraph is to show feature of function-depth tracing, isn’t it? If so, it would be better to use a simpler example for user like me (newbie) instead of uftrace-pg and hello.data. You know, the newbie like me, expects examples in the tutorial will run without modification.

**Comment by namhyung** [comment]
Thanks for using uftrace and giving your opinion.  I admit that the example is complicated more than necessary.  As you mentioned I just wanted to show how to use depth and time filters.  But I thought the original hello example is too short to demonstrate the features.  Now, thinking it again, I can use it for simpilcity.

Also with regard to the argument processing, it's a current limitation to have uftrace options before name of the program you want to run.  Otherwise it'd be confused which option goes to the uftrace or the user program.  I need to describe it in the man page and tutorial.  Thank you again!

**Comment by namhyung** [comment]
I updated the tutorial based on your feedback.  Are you ok with the change? :)

https://github.com/namhyung/uftrace/wiki/Tutorial/_compare/f2dde599ed3a84acddff1d82624c04c79ffc5642...707e1b3a5a236f9eff7acb759c8ab1ad6942f42b

**Comment by iamwonseok** [comment]
Sure, I think the latest revision of tutorial is more intuitive than before.

**Comment by namhyung** [comment]
Thanks!
