### ISSUE TITLE
Method to clean project without removing test?

### ISSUE THREAD

**Issue by DanielTimLee** [namhyung/uftrace#530]
Building target `test` takes lots of time.

But when to pull the latest source and recompile it, 
`make clean` command always prosecute clean the target of `test`.

Is there any method to clean proj. without removing `test`?

**Comment by DanielTimLee** [comment]
Or how about adding `update` target, which only cleans up related files and re-compile?

**Comment by DanielTimLee** [comment]
Well yes, target `test` is supposed to run series of tests, 
but when I try to 'debug' the `uftrace`, these unittest binaries are pretty good examples to start up with.

Without re-inventing the wheel, we can start tracing lots of use-cases in a timely manner.
(with no need to create and compile new source)

If you don't prefer `test` target is used in a way that's not meant to be, then how about creating a new target `sample` which is described at here? #457

**Comment by honggyukim** [comment]
Yes, we would like to make a target such as `sample` to generate all the sample binaries that we're using in our examples. It would be grateful if you can work on it. Thanks!

**Comment by DanielTimLee** [comment]
Any suggestions? @namhyung 

If `sample` targets might be the best option for this issue, 
I'll close this thread and start a new conversation at #457 about which example should be included in the `sample` target.

**Comment by namhyung** [comment]
Many test cases share same source and binary.  So you just need to build all the source files started with `s-` in the name with all combinations of the compile options.  But some test cases like dealing with PIE or library need some custom build options.

**Comment by DanielTimLee** [comment]
That would be much more effective than compile the whole `test` target!

Thanks!
