### ISSUE TITLE
Misc: Unable to pass extra argument in install-deps.sh

### ISSUE THREAD

**Issue by DanielTimLee** [namhyung/uftrace#531]
https://github.com/namhyung/uftrace/blob/2c058c375e18a82d9f61f18f5f7636bc544fd96f/misc/install-deps.sh#L12-L22

There is no `-y` argument in the installation script.

I think an extra parameter might be useful for the automated environment. (ex. Vagrant)

**Comment by honggyukim** [comment]
Thanks for your suggestion, but I think it would be better to explicitly ask users for installation. They need to check which packages are installed after running the script. I think typing 'y' once is not a serious burdun for users.

**Comment by DanielTimLee** [comment]
Yes it is no such thing for users, but this script cannot be executed in automated env.

So how about not defaulting a '-y' option but letting users to pass their arguments to use in special cases?

**Comment by honggyukim** [comment]
I'm fine with having `-y` option in `misc/install-deps.sh`.

**Comment by DanielTimLee** [comment]
I just updated my PR commit with not defaulting a `-y` option.
