### ISSUE TITLE
How about to create build script to build programs under subdirectory misc?

### ISSUE THREAD

**Issue by ParkHanbum** [namhyung/uftrace#541]
The uftrace build script contains scripts to build misc programs.
I think it can be separated from the build script to build uftrace.

After extracting the build script that builds misc programs from the uftrace Makefile. Building misc programs by adding additional commands such as "misc" will be helpful for users.

how do you think?

**Comment by namhyung** [comment]
Are you talking about adding `make misc`?  I'm ok with that.

**Comment by ParkHanbum** [comment]
@namhyungI have request the PR!
