### ISSUE TITLE
How about adding a Python script that describes filtering by argument values?

### ISSUE THREAD

**Issue by ParkHanbum** [namhyung/uftrace#543]
Sometimes filtering by argument values can be useful for reducing trace records. Also, as far as I know, uftrace does not provide filtering by argument value. So it seems more necessary.

how do you think?

**Comment by namhyung** [comment]
Yep, it's on the TODO list.

**Comment by namhyung** [comment]
Wait, do you want to do it in a python script?

**Comment by ParkHanbum** [comment]
@namhyung yep, In python, it can be filter by arguments. What about creating an example of that?

**Comment by namhyung** [comment]
Why python?  I'd like to add it in uftrace itself..

**Comment by ParkHanbum** [comment]
@namhyung Of course, uftrace also needs this feature, I'm totally agree with that.
but now, python script can show to user that filtering by argument can be done. 
So why do not add example?

**Comment by namhyung** [comment]
What do you mean by example?  If you could implement it in python, please send a PR.  The point what I want to see is how to select an argument and its range in the command line.

**Comment by ParkHanbum** [comment]
```
def uftrace_entry(ctx):
    # read arguments
    _tid = ctx["tid"]
    _depth = ctx["depth"]
    _fn = ctx["name"]

    if _fn is "target":
        if ctx["args"][0] > 100:
            indent = _depth * 2
            space = " " * indent

            buf = " %10s [%6d] | %s%s() {" % ("", _tid, space, _fn)
            print(buf)
```

how about this for example?

**Comment by namhyung** [comment]
But it should **change the script everytime** you want to apply different filter to different functions.
