### ISSUE TITLE
How about adding user-metadata feature?

### ISSUE THREAD

**Issue by ParkHanbum** [namhyung/uftrace#544]
Let me explain user-metadata feature. 

When you are programming, you usually include comments as a comment, a description of the function argument values, and a description of the function's return value. These comments are very helpful in understanding what the function does, even if you do not know the internal structure of the function.

If you can put meta-data on the tracing data recorded by Uftrace, someone will be able to understand the program more intuitively through the meta-data that the program analyzes and records. Also, sharing meta-data will help others.

What do you think?

**Comment by namhyung** [comment]
I don't understand what do you want.  Could you please show me an example?

**Comment by ParkHanbum** [comment]
@namhyung Yep, I will show you ASAP.

**Comment by ParkHanbum** [comment]
```
    0.572 us :  │  │  │  │     ├─(1) make_pass_copy_prop                                                                                                                                                                 0.060 us :  │  │  │  │     │  ├─(1) operator new
             :  │  │  │  │     │  │
    0.318 us :  │  │  │  │     │  └─(1) _GLOBAL__N_1::pass_copy_prop::pass_copy_prop
    0.225 us :  │  │  │  │     │    (1) gimple_opt_pass::gimple_opt_pass
    0.096 us :  │  │  │  │     │    (1) opt_pass::opt_pass
```

**Comment by namhyung** [comment]
Who's gonna write the description?

**Comment by honggyukim** [comment]
@ParkHanbum Hmm.. I don't actually get the point of this. Do you want to show the description of some specific function in the middle of replay output?

**Comment by ParkHanbum** [comment]
For example, if you are tracing to find a problem, 
you must keep information about the tracing to reduce range of problem range. 
If uftrace provides an interface that can do this easily, there may be people who use it.
I was mention it as user-metadata.

Whether or not to share the information is up to users, 

but I've often seen people sharing open-source knowledge 
by adding comment to source code such as linux kernel. 
I would like to analyze the open source such as gcc and share the information.

**Comment by ParkHanbum** [comment]
@honggyukim If the metadata exists and user want to see the metadata, 
then show the metadata with the results of the tracing.

**Comment by ParkHanbum** [comment]
@namhyung Yes, you are right. I will not deny it. That's why when people study open source, do not find annotate. but some hopefully thing are here also.
