### ISSUE TITLE
memory leak in parse_enum_string()

### ISSUE THREAD

**Issue by gy741** [namhyung/uftrace#555]
Hello.

I think, there is a memory leak at parse_enum_string:611.

Possible memory leaks from usage of xstrdup without free().

Am I missing something or it really miss free() call?

What do you think?

Thanks.

problem code:
https://github.com/namhyung/uftrace/blob/6b2345ac6a0280fb4452e0d9a8ea5b98a2cb4859/utils/auto-args.c#L609-L614

in my opinion, fix code:
```diff
diff --git a/utils/auto-args.c b/utils/auto-args.c
index 7678e05..2ff77d6 100644
--- a/utils/auto-args.c
+++ b/utils/auto-args.c
@@ -439,6 +439,7 @@ static void free_enum_def(struct enum_def *e_def)
                free(e_val->str);
                free(e_val);
        }
+       free(e_def->name);
        free(e_def);
 }
```

**Comment by namhyung** [comment]
Look correct, please send PR.
