### ISSUE TITLE
Null Pointer Dereference in get_event_name()

### ISSUE THREAD

**Issue by gy741** [namhyung/uftrace#556]
Hello.

handle->kernel can sometimes be NULL. (due to corrupt data)

So, a segmentation fault occurs.

I added a null pointer check code.

what do you think?

Thanks.

gdb log:
```
Program received signal SIGSEGV, Segmentation fault.
0x00005555555998ef in get_event_name (handle=0x7fffffffe190, evt_id=17134)
    at /root/uftrace/utils/fstack.c:1279
1279			event = pevent_find_event(handle->kernel->pevent, evt_id);
(gdb) p handle->kernel
$1 = (struct uftrace_kernel_reader *) 0x0
```

In my opinion, Fix code:
```diff
diff --git a/utils/fstack.c b/utils/fstack.c
index f95d3c2..15ac52b 100644
--- a/utils/fstack.c
+++ b/utils/fstack.c
@@ -1275,8 +1275,10 @@ char *get_event_name(struct ftrace_file_handle *handle, unsigned evt_id)
        }
 
        /* kernel events */
-       event = pevent_find_event(handle->kernel->pevent, evt_id);
-       xasprintf(&evt_name, "%s:%s", event->system, event->name);
+       if (has_kernel_data(handle->kernel)) {
+               event = pevent_find_event(handle->kernel->pevent, evt_id);
+               xasprintf(&evt_name, "%s:%s", event->system, event->name);
+       }
 
 out:
        return evt_name;
```

**Comment by namhyung** [comment]
Looks correct, please send PR.

Just for your information, if you have a clear problem and the fix you don't need to create an issue and PR separately.  I think issue is good for discussion or reporting a problem without a solution.  Anyway thanks for your work!

**Comment by gy741** [comment]
Thank you for your kind reply.
Sometimes, I can not find a solution.
So, I make the issue create first.
After the time has elapsed, update issue if a solution is found.
Anyway, I agree with you. :)
