### ISSUE TITLE
[suggest] improve user UI with Web.

### ISSUE THREAD

**Issue by ParkHanbum** [namhyung/uftrace#593]
<img width="600" alt="default" src="https://user-images.githubusercontent.com/1003760/48392478-f6ddda80-e74e-11e8-89e7-79eab7c5c733.png">

[link](http://hanbum.asuscomm.com/show/flame)

uftrace have many methods to visualization from tracing-data. I think it can be good that all this visualization methods has been shown in web browser. also, there is no longer to learn how to see the chrome-tracing viewer or flamegraph. and web is easier than console to develope other visualization or interface, how do you think?

**Comment by namhyung** [comment]
Do you want to build a web service to upload users' uftrace.data and display graph like above?

**Comment by ParkHanbum** [comment]
@namhyung  it would be good too. 

what I say is that make all visualization features see on the web using command, like visualization. not only include currently supported visualization, but also Includes visualization features that support in the future.

service server is not required, and a local web server is sufficient.

you can found an example on Go-lang.
[SRE: Performance Analysis: Tuning Methodology Using a Simple HTTP Webserver In Go](https://medium.com/dm03514-tech-blog/sre-performance-analysis-tuning-methodology-using-a-simple-http-webserver-in-go-d475460f27ca?fbclid=IwAR2WiIzL9ZZ78g3Sv0LutawmzFRf6YUJnVq3kEW7n3K-wnXo-iB46Fac7tQ)
