### ISSUE TITLE
[suggest] add runtest.py Document & questions

### ISSUE THREAD

**Issue by lee5black** [namhyung/uftrace#601]
I used `uftrace/tests/runtest.py` for the first time through the following issues:
[https://github.com/namhyung/uftrace/issues/577](url)

What I noticed is that there is no guidance for this test tool.
So I have written some tips for these tools.
[uftrace-test.pdf](https://github.com/namhyung/uftrace/files/2604898/uftrace-test.pdf)

Could you give feedback on the documentation?

and I would also like to ask you about additional questions about  `uftrace/tests/runtest.py`

```
1. Invalid argument handling
2. Add user test code
```

### 1. Invalid argument handling

I have confirmed that there is no processing for the arguments after the -f and -O options.
Of course, you can check for errors with the -v option, and the compiler will not issue big errors by printing the error. However, I would like to ask if you need to handle these invalid arguments.

My idea is to create a list of flags for -f, and exit the program if the argument is not in the list of flags. If -O, exit the program if it encounters any characters other than 0123s.

![image](https://user-images.githubusercontent.com/30280839/48853758-8e989400-edf3-11e8-9ef6-66975e8a3193.png)

![image](https://user-images.githubusercontent.com/30280839/48853804-a7a14500-edf3-11e8-9061-97faecc52b96.png)

![image](https://user-images.githubusercontent.com/30280839/48853785-9d7f4680-edf3-11e8-9e29-17a398c72327.png)

![image](https://user-images.githubusercontent.com/30280839/48854109-652c3800-edf4-11e8-88f1-2d86ba520ed2.png)

![image](https://user-images.githubusercontent.com/30280839/48854156-89881480-edf4-11e8-953e-84b993a61acb.png)

### 2. Add user test code guide

I would like to walk you through how to add a test case to developers who want to develop new features of uftrace. You can of course modify your existing test case. I want to show you that you can test your newly developed code.

And I'm thinking of automating this process more easily. 

If you generate some source code and run a script called create.py, it will do all of the following steps automatically.

- Example To add the desired test case:

**first > create `s-[TEST CASE NAME].c` / `s-[TEST CASE NAME].cpp` (In your preferred language)**

```
root@ubuntu:~/uftrace/tests# cat s-USER_TEST.c 
#include<stdio.h>

void TEST(void);

int main()
{
	TEST();

	return 0;
}

void TEST(void){
	printf("USER_TEST_CODE\n");
}

```

**second > Apply the default gcc and uftrace options in `runtest.py` to get the following results:**
(If you want, you can optionally modify your runtest.py to give your own default gcc option or uftrace.)

```
root@ubuntu:~/uftrace/tests# gcc -o t-USER_TEST -fno-inline -fno-builtin -fno-ipa-cp -fno-omit-frame-pointer -D_FORTIFY_SOURCE=0  -finstrument-functions -Os  s-USER_TEST.c
<command-line>:0:0: warning: "_FORTIFY_SOURCE" redefined
<built-in>: note: this is the location of the previous definition
root@ubuntu:~/uftrace/tests# uftrace --no-pager --no-event -L.. t-USER_TEST
USER_TEST_CODE
# DURATION     TID     FUNCTION
            [  6053] | main() {
            [  6053] |   TEST() {
 149.720 us [  6053] |     printf();
 151.607 us [  6053] |   } /* TEST */
 152.396 us [  6053] | } /
```

**Third > create `t[TEST CASE NUMBER]_[TEST CASE NAME].py` / (paste second result)**

```
#!/usr/bin/env python

from runtest import TestBase

class TestCase(TestBase):
    def __init__(self):
        TestBase.__init__(self, 'USER_TEST', """
# DURATION     TID     FUNCTION
   0.858 us [  6053] | __monstartup();
   0.332 us [  6053] | __cxa_atexit();
            [  6053] | main() {
            [  6053] |   TEST() {
 131.151 us [  6053] |     printf();
 132.454 us [  6053] |   } /* TEST */
 132.658 us [  6053] | } /* main */
 """)

        def runcmd(self):
            return '%s -N c %s' % (TestBase.uftrace_cmd, 't-USER_TEST')

```

**Finally, you can get the following results:**

![image](https://user-images.githubusercontent.com/30280839/48859058-65323500-ee00-11e8-9d60-af0059b421e3.png)

![image](https://user-images.githubusercontent.com/30280839/48859098-8430c700-ee00-11e8-893d-eb9ca48b28df.png)

I would also appreciate your feedback on additional details!

If you are positive about the content, I will receive your feedback and send you a PR after document modification.

**Comment by honggyukim** [comment]
IMHO, it may also be useful to guide users and developers to run `runtest.py` script. I sometimes want to run only a single test, but `make test TESTARG='-pdO2 filter' requires to spend time on building `unittests`, then runs the given test code.

**Comment by lee5black** [comment]
Good feedback Thank you so much. I will send you a quick PR! 

And I'll check the code.`$ make test TESTARG='-pdO2 filter'`
