### ISSUE TITLE
Adding extra attribute at class TestBase for serialized/parallel test?

### ISSUE THREAD

**Issue by DanielTimLee** [namhyung/uftrace#620]
There is some tests needs to run in serialized order.
To acheive this, we need to add some extra attributes at class TestBase to figure out at runtime.

https://github.com/namhyung/uftrace/issues/616#issuecomment-444324794
> Ideally we would make some part serialized if needed. For example, checking mlock limit before running cases and run perf event (sched) test cases serially. Also kernel tests always need to be run serially.

What do you think? Any other suggestions than adding attribute to TestBase?

**Comment by namhyung** [comment]
I think it's ok
