### ISSUE TITLE
Scroll bar or percenatge on tui?

### ISSUE THREAD

**Issue by DanielTimLee** [namhyung/uftrace#625]
GNU less supports displaying the current line number, **total lines and percentage** as well as shown below:
(when pressing ctrl+g)

lines 51-100/185 byte 3228/5886 54% (press RETURN)

Any plans to support similar functionality in tui?

To search function inside tui or replay, it has to jump here and there and it's kinda distracting.
but what if there is a scroll-bar in tui, it could help to visualize the previous flow (before searching), and easily track the tracing progress.

(win_footer_graph)

**Comment by namhyung** [comment]
We can add it to the lower right corner.  But you need to be careful when source line number and current line number have to overlap due to screen width.

**Comment by DanielTimLee** [comment]
In `tui`, is there any logic or variable that tracks total number of nodes (which is not folded)?

When I see the code, I can't really find such thing exists.

In my guess, the only way to get number of unfolded node is 
just iterate all over the node to figure out it is folded or not.

Is it right?

(I'm trying to figure out the last node index (considering with fold) in `tui_main_loop`, 
but I can't find nicer way than just looping through all nodes.)

**Comment by honggyukim** [comment]
Hi @DanielTimLee, @namhyung is on a travel now so may take some time to answer. I'm not very familiar with tui code based, but leave some comments based on my limited understanding.

> In tui, is there any logic or variable that tracks total number of nodes (which is not folded)?

I think it's not.

I would rather suggest you to take a look at `graph_prev_node` and `graph_next_node` functions.  They already handle whether the prev and next node is folded or not. When up and down keys are pressed, they reply on those functions.

IMHO, you can calculate the current position based on how many times prev and next move can be successful in the current graph (without actually moving the cursor). It may have to be updated if some graph is folded.

Please be aware that the change has to be applied to both graph and report windows. Please see `struct tui_window_ops`.

**Comment by DanielTimLee** [comment]
Is there any way to figure out which type of window is currently shown in `struct tui_window *win`?

**Comment by honggyukim** [comment]
This code snippet will be helpful to you.
```c
static void tui_main_loop(struct opts *opts, struct uftrace_data *handle)
{
    struct tui_graph *graph   = tui_graph_init(opts);
    struct tui_report *report = tui_report_init(opts);
    struct tui_list *info     = tui_info_init(opts, handle);
    struct tui_list *session  = tui_session_init(opts);
    struct tui_window *win;
        ...
    while (true) {
        switch (key) {
            ...
        case 'g':
            if (win == &graph->win || win == &partial_graph.win) {
                struct tui_report_node *func;
                struct tui_graph_node *curr = win->curr;

                func = (void *)report_find_node(&report->name_tree,
                                curr->n.name);
                if (func == NULL)
                    break;
                build_partial_graph(func, graph);
            }
            else if (win == &report->win) {
                build_partial_graph(win->curr, graph);
            }
            else {
                break;
            }

            win = &partial_graph.win;

            tui_window_move_home(win);
            tui_window_search_count(win);
            full_redraw = true;
            break;
            ...
        }
            ...
    }
        ...
}
```

**Comment by DanielTimLee** [comment]
Thanks for the detailed tip!
I'm really sorry, but what I meant was figuring out only with `struct tui_window *win`.

by comparing address of `tui_window` at main loop can achieve it, 
but what I was trying to do is figuring out itself type on it's own.
