### ISSUE TITLE
Invalid rstack read error with auto-args

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#633]
The current master has some rstack read error as follows:
```
$ uftrace record -a ./d8 --expose-gc -e 'gc()'
$ uftrace replay -F main -t 100ms --no-event
WARN: invalid rstack read
# DURATION     TID     FUNCTION
            [ 64603] | main(4, 0x7ffd61d19238) {
            [ 64603] |   v8::Shell::Main(4, 0x7ffd61d19238) {
            [ 64603] |     v8::Shell::RunMain(0x55d600f98170, 0x55d600edfa88, 0, 1) {
            [ 64603] |       v8::Shell::CreateEvaluationContext(0x55d600f98170) {
            [ 64603] |         v8::Shell::CreateGlobalTemplate(0x55d600f98170) {
            [ 64603] |           v8::ObjectTemplate::SetAccessor(0x55d60100a2d0, 0x55d60100a368, &v8::Shell::RealmSharedGet, &v8::Shell::RealmSharedSet, 0, DEFAULT, DontDelete|Do
            [ 64603] |             v8::_GLOBAL__N_1::MakeAccessorInfo(0x55d600f98170, 0x55d60100a368, &v8::Shell::RealmSharedGet, &v8::Shell::RealmSharedSet, 0, DEFAULT, 0x7ffd61

uftrace stopped tracing with remaining functions
================================================
task: 64603
[6] v8::_GLOBAL__N_1::MakeAccessorInfo
[5] v8::ObjectTemplate::SetAccessor
[4] v8::Shell::CreateGlobalTemplate
[3] v8::Shell::CreateEvaluationContext
[2] v8::Shell::RunMain
[1] v8::Shell::Main
[0] main
```
You can reproduce the result using the tarball - [uftrace.data.issue-633.tar.gz](https://github.com/namhyung/uftrace/files/2704573/uftrace.data.issue-633.tar.gz)

**Comment by namhyung** [comment]
The `MakeAccessorInfo()` has 9 arguments but only 8 was recorded.  And it seems suspicious that same register (rcx) was used twice for different args.  I need to look the real DWARF info of the function.

```
$ grep -A 3 uftrace.data.issue-633/d8.dbg
F: 664ee0 v8::_GLOBAL__N_1::MakeAccessorInfo
L: 1612 ../../src/api.cc
A: @arg1%rdi,arg2%rsi,arg3/p%rdx,arg4/p%rcx,arg5%r8,arg6/e:AccessControl%r9,arg7%stack+3,arg8%rcx,arg9
R: @retval
...
```

**Comment by honggyukim** [comment]
The full binary may be too big to attach here, but I will post the output if you give me some command to look into the DWARF info.

**Comment by honggyukim** [comment]
And the output log that I posted above was cut due to the width of my terminal. Here is the full arguments for `MakeAccessorInfo()`.
```
v8::_GLOBAL__N_1::MakeAccessorInfo(0x55d600f98170, 0x55d60100a368, &v8::Shell::RealmSharedGet, &v8::Shell::RealmSharedSet, 0, DEFAULT, 0x7ffd61d18b00, 0x7ffd61d18b00, 0x4857fb1ff2146) {
```
I can see that it has 9 arguments from the output.

**Comment by honggyukim** [comment]
I found that the problem is shown since eb883a0 was committed.

**Comment by namhyung** [comment]
OK, that's a good information.  So you can check the d8.dbg files to have difference in the 'A:' line for the `MakeAceessorInfo()` before and after the commit.

And it'd be nice if you could show me the output of `readelf -wi d8` having `DW_TAG_formal_parameter` under the `MakeAceessorInfo` (`DW_TAG_subprogram`).  The below is for the `main()` function (just for example):

```
 <1><2fc>: Abbrev Number: 18 (DW_TAG_subprogram)
    <2fd>   DW_AT_external    : 1
    <2fd>   DW_AT_name        : (indirect string, offset: 0x170): main
    <301>   DW_AT_decl_file   : 1
    <302>   DW_AT_decl_line   : 2
    <303>   DW_AT_prototyped  : 1
    <303>   DW_AT_type        : <0x62>
    <307>   DW_AT_low_pc      : 0x76a
    <30f>   DW_AT_high_pc     : 0x2f
    <317>   DW_AT_frame_base  : 1 byte block: 9c 	(DW_OP_call_frame_cfa)
    <319>   DW_AT_GNU_all_tail_call_sites: 1
    <319>   DW_AT_sibling     : <0x33a>
 <2><31d>: Abbrev Number: 19 (DW_TAG_formal_parameter)
    <31e>   DW_AT_name        : (indirect string, offset: 0x10f): argc
    <322>   DW_AT_decl_file   : 1
    <323>   DW_AT_decl_line   : 2
    <324>   DW_AT_type        : <0x62>
    <328>   DW_AT_location    : 2 byte block: 91 6c 	(DW_OP_fbreg: -20)
 <2><32b>: Abbrev Number: 19 (DW_TAG_formal_parameter)
    <32c>   DW_AT_name        : (indirect string, offset: 0xed): argv
    <330>   DW_AT_decl_file   : 1
    <331>   DW_AT_decl_line   : 2
    <332>   DW_AT_type        : <0x33a>
    <336>   DW_AT_location    : 2 byte block: 91 60 	(DW_OP_fbreg: -32)
 <2><339>: Abbrev Number: 0
```

Or a screenshot of [dwarview](https://github.com/namhyung/dwarview) (search for `*MakeAccessorInfo*`) would be great!

**Comment by honggyukim** [comment]
Here is the info of `d8.dbg` that reverted the problematic commit eb883a0.
```
$ grep MakeAccessorInfo -A3 d8.dbg
F: 664ee0 v8::_GLOBAL__N_1::MakeAccessorInfo
L: 1612 ../../src/api.cc
A: @arg1%rdi,arg2%rsi,arg3/p%rdx,arg4/p%rcx,arg5%r8,arg6/e:AccessControl%r9,arg7%stack+3,arg8%rcx,arg9
R: @retval
F: 665350 v8::_GLOBAL__N_1::MakeAccessorInfo
L: 1612 ../../src/api.cc
A: @arg1%rdi,arg2%rsi,arg3/p%rdx,arg4/p%rcx,arg5%r8,arg6/e:AccessControl%r9,arg7%stack+3,arg8%rcx,arg9%rsi
R: @retval
```
I found that the above info is same as attached [uftrace.data.issue-633.tar.gz](https://github.com/namhyung/uftrace/files/2704573/uftrace.data.issue-633.tar.gz).

**Comment by namhyung** [comment]
OK, I found that it's because the duplicate register args (arg4 and arg8 both use the rcx register).  With eb883a0 it ignore the register part when replay so they are considered different arguments.  But on record, it's same register so libmcount collapse them into one - so end result is saving total 8 data rather than 9.

There are many issues around the problem and it needs some time to fix/support it correctly.  I'll fix it with reverting the commit first and then will work on the correct fix.

**Comment by honggyukim** [comment]
Thanks. The problem is gone now.
