### ISSUE TITLE
Passing child_time to scripts

### ISSUE THREAD

**Issue by abenbachir** [namhyung/uftrace#641]
Hi @namhyung,
Similar thread was opened [196](https://github.com/namhyung/uftrace/issues/196) and [320](https://github.com/namhyung/uftrace/issues/320). Can uftrace pass the child_time or self_time to scripts ?  Other than that this is my needs:

I would like to dump the following information for each function call: name, parent, self_time, total_time, depth, arguments.
I saw in the source code that add_graph_exit use child_time, is that the child_time of individual function or for all functions that has similar name ?
`node->child_time += fstack->child_time;`

This is an example of what I would like to do :
```
func_a(int i) {
  func_b() {
    func_c();
    func_c();
    func_c();
    func_d();
  }
```
CSV output from script:
```
#name, parent, self_time, total_time, depth, arguments.
func_a, main, 1, 10, 1, []
func_b, func_a, 2, 9, 2, []
func_c, func_b, 1, 1, 3, []
func_c, func_b, 1, 1, 3, []
func_c, func_b, 1, 1, 3, []
func_d, func_b, 4, 4, 3, []
```

**Comment by namhyung** [comment]
Hi @abenbachir 

The child time is time spent during functions called by current function.  In other words:
```
self time = total time - child time
```

And all the timing (duration) info is available at function exit so you need to keep the functions somehow.  Maybe I can add child time as well but that'll be available only for script command as I don't want add overhead and complexity to libmcount code as long as possible.  But by keeping running functions in your script, you could easily calculate child/self time IMO.

**Comment by abenbachir** [comment]
Perfect I will compute the child_time in the script as you suggested.

**Comment by abenbachir** [comment]
It worked, I will close this one.
