### ISSUE TITLE
Display time according to --time-range option

### ISSUE THREAD

**Issue by Taeung** [namhyung/uftrace#66]
Good morning, Namhyung :smile: 

I found a problem. Is it a problem ? or I did wrong usage for it ? :worried: 
I tested on current master branch (58639c)
```
$ uftrace ./a.out
# DURATION    TID     FUNCTION
   0.834 us [16683] | __monstartup();
   0.419 us [16683] | __cxa_atexit();
            [16683] | main() {
   5.181 us [16683] |   fgets();
            [16683] |   get_values_from() {
   0.576 us [16683] |     strdup();

... (It hasn't any problems)
```
But if using `-r` or `--time-range` with `+` prefix, it isn't work with a warning message as below.
```
$ uftrace -r +1us ./a.out
invalid time range: +1us (ignoring...)
# DURATION    TID     FUNCTION
   0.635 us [16628] | __monstartup();
   0.404 us [16628] | __cxa_atexit();
            [16628] | main() {
   4.102 us [16628] |   fgets();
            [16628] |   get_values_from() {
   0.561 us [16628] |     strdup();
...
```
Should we fix it ? and
Add test scripts for `time-range` such as `t053_filter_time.py` ? :smile:

**Comment by namhyung** [comment]
@Taeung Hi, the `--time-range` option requires 2 time values separate by `~`.  You can omit one of them but not the `~`.  So you should use `+1us~` (if you want to see functions after 1us from the beginning) or `~+1us` (to see functions before 1us from the beginning) instead.

**Comment by Taeung** [comment]
Ah, I understood it.

After `uftrace record`
```
$ uftrace record ./a.out
```
In accardance  with the **elapsed time**, we can see **a part** of function graph as below.
```
$ uftrace replay -f elapsed -r +20us~
#  ELAPSED    FUNCTION
  20.034 us |     } /* strdup */
  20.206 us |     strsep();
  20.432 us |     atoi();
  20.721 us |     atoi();
  20.954 us |   } /* get_values_from */
  21.060 us |   fgets();
  21.302 us |   get_values_from() {
...
```
But I think **duration** of default view can cause confusion from the point of view of newbies.
For example, If the user just do `uftrace replay -r +20us~` after recording,
```
$ uftrace replay -r +20us~
# DURATION    TID     FUNCTION
            [22335] |     } /* strdup */
   0.091 us [22335] |     strsep();
   0.150 us [22335] |     atoi();
   0.122 us [22335] |     atoi();
   0.920 us [22335] |   } /* get_values_from */
   0.128 us [22335] |   fgets();
            [22335] |   get_values_from() {
...
```
But the time of `--time-range` option isn't related to **duration**. (confusing point, IMHO)
So the user can check with `-f elapsed` as below.
```
uftrace replay -f elapsed -r +20us~
#  ELAPSED    FUNCTION
  20.034 us |     } /* strdup */
  20.206 us |     strsep();
  20.432 us |     atoi();
  20.721 us |     atoi();
  20.954 us |   } /* get_values_from */
  21.060 us |   fgets();
  21.302 us |   get_values_from() {
...
```
Additionally if the user want to see both **duration** and **elaped time**,
the user can supplementally use `-f duration,elapsed` as below
```
uftrace replay -f duration,elapsed -r +20us~
# DURATION    ELAPSED    FUNCTION
             20.034 us |     } /* strdup */
   0.091 us  20.206 us |     strsep();
   0.150 us  20.432 us |     atoi();
   0.122 us  20.721 us |     atoi();
   0.920 us  20.954 us |   } /* get_values_from */
   0.128 us  21.060 us |   fgets();
             21.302 us |   get_values_from() {
...
```
I think it is better to show function graph **with elapsed time by default** when the user use `time-range` like `-r +20us` with **elapsed time**.
And if the user use `time-range` option with **time stamp**, we can show function graph **with time stamp by default**.

What do you think about it ?

**Comment by namhyung** [comment]
I'm not sure that's what user want always.  I think I want to see duration anyway but time range is used only to limit the data range displayed.

**Comment by Taeung** [comment]
What about this ? Adding **timestamp** or **elapsed time** column to default veiw when using `time-range`
For example,
1) If using `time-range` with **timestamp**, we can show as below by default.
```
$ uftrace replay -r 184832.543807090~184832.543817869
#     TIMESTAMP      DURATION    TID     FUNCTION
   184832.543807090            [22335] |   get_values_from() {
   184832.543807281   0.829 us [22335] |     strdup();
   184832.543808362   0.670 us [22335] |     strsep();
   184832.543809277   0.754 us [22335] |     atoi();
   184832.543810195   0.217 us [22335] |     atoi();
   184832.543810580   3.490 us [22335] |   } /* get_values_from */
...
```
2) If using `time-range` with **elapsed time**, we can show as below by default.
```
$ uftrace replay -r +20us~
#  ELAPSED   DURATION    TID     FUNCTION
  20.034 us            [22335] |     } /* strdup */
  20.206 us   0.091 us [22335] |     strsep();
  20.432 us   0.150 us [22335] |     atoi();
  20.721 us   0.122 us [22335] |     atoi();
  20.954 us   0.920 us [22335] |   } /* get_values_from */
...
```
It is just my opinion :smile:

**Comment by namhyung** [comment]
Looks ok to me.
