### ISSUE TITLE
--time-range option seems to be not working

### ISSUE THREAD

**Issue by Taeung** [namhyung/uftrace#67]
Additionally I tested `--time-range` option and I think it seems to be not working.
(Same environment : on current master branch; 58639c)

I think there are problems not only about #66 but also when using `TIME~TIME`
I checked `--time-range` usage as below.
```
$ uftrace --help | grep range
  -r, --time-range=TIME~TIME Show output within the TIME range only
```
But it seems to be not working as below
```
$ uftrace -r 1us~2us ./a.out
invalid timestamp string
invalid timestamp string
# DURATION    TID     FUNCTION
```
And if we check `TIME STAMP` as below,
```
$ uftrace -f time ./a.out
#     TIMESTAMP       FUNCTION
   174103.519727780 | __monstartup();
   174103.519731523 | __cxa_atexit();
   174103.519733068 | main() {
   174103.519733166 |   fgets();
   174103.519738659 |   get_values_from() {
   174103.519738847 |     strdup();
   174103.519739937 |     strsep();
   174103.519740778 |     atoi();
   174103.519741701 |     atoi();
   174103.519742074 |   } /* get_values_from */
...
```
and if using `--time-range` option, the case not work, too.
```
$ uftrace -r 174103.519738659~174103.519742074 ./old < input.txt 
# DURATION    TID     FUNCTION
```
But time stamp values are always changed each time `uftrace` work.
How to use `--time-range` ?
Is wrong my usage for it ? :worried:

**Comment by namhyung** [comment]
The time range option is basically for replay (and report, dump, graph) which you already know the timestamp.  But it can still use relative time (using `+`) which means time delta from the first timestamp for live command.

**Comment by namhyung** [comment]
Currently uftrace shows options for all subcommand.  You'd be better to see man pages for reference.

**Comment by namhyung** [comment]
@honggyukim I think we need to update man page of live subcommand for the time range option.  It doesn't make sense to receive timestamp..

**Comment by honggyukim** [comment]
@namhyung I've created a PR #68. It just removes "+" prefix to make it simpler to use.  Identifying whether it is timestamp or elapsed time can automatically parsed only with <time_unit> postfix.  So please have a look at it!

**Comment by Taeung** [comment]
@namhyung  I got it.
I saw `uftrace replay` man pages to know a `time-range`usage.
But as you said, I think it it needed to add examples for `time-range` to man pages or wiki. :smile: 

In the proper way you said I used `time-range` after recording as below.
```
uftrace replay -f time -r 184832.543807090~184832.543817869
#     TIMESTAMP       FUNCTION
   184832.543807090 |   get_values_from() {
   184832.543807281 |     strdup();
   184832.543808362 |     strsep();
   184832.543809277 |     atoi();
   184832.543810195 |     atoi();
   184832.543810580 |   } /* get_values_from */
   184832.543810804 |   malloc();
   184832.543814224 |   fgets();
   184832.543814658 |   get_values_from() {
   184832.543814758 |     strdup();
   184832.543815198 |     strsep();
   184832.543815480 |     atoi();
   184832.543815829 |     atoi();
   184832.543816128 |   } /* get_values_from */
   184832.543816287 |   fgets();
   184832.543816589 |   get_values_from() {
   184832.543816669 |     strdup();
   184832.543817015 |     strsep();
   184832.543817241 |     atoi();
   184832.543817530 |     atoi();
   184832.543817763 |   } /* get_values_from */
   184832.543817869 |   fgets() {

uftrace stopped tracing with remaining functions
================================================
task: 22335
[0] fgets
```
But I think it is better to add **'time stamp or elapsed time'** on the help message.
(I think it is better that there is the mention not only in man page but also help message)
So currently we can know a `time-stamp` usage with `--help` option as below.
```
$ uftrace --help | grep time-range
  -r, --time-range=TIME~TIME Show output within the TIME range only
```
But I suggest this as below
```
$ uftrace --help | grep time-range
  -r, --time-range=TIME~TIME Show output within the TIME(time stamp or elapsed time) range only
```
What do you think about it ?

**Comment by honggyukim** [comment]
Hi @Taeung, I hope it can be easier you to understand the usage of --time-range with #68 .

**Comment by Taeung** [comment]
I sent PR https://github.com/namhyung/uftrace/pull/69 about above my reply  :smile:

**Comment by namhyung** [comment]
Merged both PR. Thanks for your contribution!
