### ISSUE TITLE
"inverted time"

### ISSUE THREAD

**Issue by kobi-ca** [namhyung/uftrace#699]
I'm seeing "inverted time" error as part of the replay output.
I also unable to generate any graphs from the raw generated binary.
I think it is related. Any idea how to solve this?

**Comment by honggyukim** [comment]
It seems that the recorded data is somehow broken. It may be helpful if you can attached the "broken" recorded data. But it's not possible, we need to know the execution command you used for record and replay.

**Comment by kobi-ca** [comment]
hi @honggyukim  - I'll send you more info tomorrow when I'm back in office. thank you and take care.

**Comment by honggyukim** [comment]
@kobi-ca Don't worry and please share it when you have free time. Thanks for your feedback.

**Comment by kobi-ca** [comment]
with --no-event no inverted time.

**Comment by namhyung** [comment]
@kobi-ca did you use kernel tracing?

**Comment by kobi-ca** [comment]
@namhyung - no kernel tracing
record --no-libcall
when I add --no-event - this issue goes away.
the linux:schedule is literally flooding the tracing output
