### ISSUE TITLE
Unable to filter out linux:schedule 

### ISSUE THREAD

**Issue by kobi-ca** [namhyung/uftrace#700]
I'm trying to filter out linux:schedule with -N or --notrace but I still see it in the replay output.
Am I using it wrong?

**Comment by honggyukim** [comment]
Hi @kobi-ca, sorry for late answer and thanks for your feedback.
`linux:schedule` is an event so cannot be turned off by `-N`/`--notrace`. Instead, you can record and replay with `--no-event` to hide scheduling events.

**Comment by kobi-ca** [comment]
thank you @honggyukim 
great tool BTW. I love it.
