### ISSUE TITLE
chrome tracing crash with a big file (500M)

### ISSUE THREAD

**Issue by kobi-ca** [namhyung/uftrace#706]
is there a decent way to handle big files? split it?
right now I manually splitting it while maintaining the footer. Any other way to load big files?

**Comment by honggyukim** [comment]
It’s mostly the problem of chrome itself from my experience. Please reduce the size of record with time filter when you run uftrace dump, for example using -t 10ms.

**Comment by kobi-ca** [comment]
thanks.

**Comment by honggyukim** [comment]
It’s good to have more feedback for the project. Please feel free to ask any kind of questions. Thank you too :)

**Comment by kobi-ca** [comment]
my pleasure . thanks!
