### ISSUE TITLE
dynamic tracing with shared objects

### ISSUE THREAD

**Issue by ParkHanbum** [namhyung/uftrace#719]
Some programs perform key functions on shared objects such as v8. I think it is very important to support dynamic patching of shared objects in dynamic tracing. How about adding dynamic patching for shared objects to the dynamic tracing feature?

**Comment by honggyukim** [comment]
It’s better to do it but we have to make the basic dynamic tracing more stable. This work can be the next step.

**Comment by honggyukim** [comment]
@ParkHanbum Could you please test [review/dynamic-trace-v6](https://github.com/namhyung/uftrace/compare/review/dynamic-trace-v6)?
I found some segfault while running it. I've written the reproducible sequence.

**Comment by honggyukim** [comment]
It's needed especially for prebuilt `chrome` as it contains just small amount of code and mostly implemented in shared objects.
```
$ lt -h /opt/google/chrome/chrome
-rwxr-xr-x 1 root root 115M Sep 21  2017 /opt/google/chrome/chrome
```
```
$ uftrace record -P. --no-libcall --no-event -t 1ms \
           /opt/google/chrome/chrome --no-sandbox \
           --disable-gpu --headless https://www.google.com

$ uftrace replay
# DURATION     TID     FUNCTION
            [ 82621] | ChromeMain() {
   1.930 ms [ 82653] | FT_Load_Glyph();
   8.523 ms [ 82653] | FT_Load_Glyph();
   8.571 ms [ 82653] | FT_Load_Glyph();
   1.891 ms [ 82653] | FT_Load_Glyph();
   1.727  s [ 82621] | } /* ChromeMain */
```

**Comment by honggyukim** [comment]
It has to handle libraries that are loaded by `dlopen` call. It's heavily used in some programs such as firefox.

**Comment by ParkHanbum** [comment]
maybe I can handle this issue if anyone not working on here.
I think it can be better that add a option to specify which library to be traced.

**Comment by namhyung** [comment]
@ParkHanbum thanks for volunteering.  I think -P option also can have module suffix like `-P ^xxx@libxxx.so`.

**Comment by ParkHanbum** [comment]
@namhyung Is there any code I can refer?

**Comment by namhyung** [comment]
No, but I think you can just iterate `symtabs->maps` and call `do_dynamic_update` for each map.  You need to check upcoming module symbol table change in #727.
