### ISSUE TITLE
symbol and debug info caching

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#727]
I often run analysis commands a lot of times for the same recorded data.
But currently uftrace load the same symbol and debug info from nothing and it take too much time especially when I run analysis commands for chrome.

It'd be really helpful if there is a way to caching those info and speed up analysis for the same record data.

**Comment by honggyukim** [comment]
It can also be used for `record` command. If there is already recorded data in `uftrace.data` before rename it to `uftrace.data.old`, uftrace first checks the build-ID if it's same then use the existing `.sym` and `.dbg` files.

I think it will be make a lot faster launching.

**Comment by honggyukim** [comment]
Maybe we should also check the build IDs of shared libraries as well.

**Comment by honggyukim** [comment]
If all these check is not reliable, then we can provide an option for user to decide whether to reuse existing symbol and debug info. It may be `--reuse-data`.

**Comment by namhyung** [comment]
I've checked chrome tracing data you provided and found that it has a couple of sessions for the chrome binary.  So the loading time is multiplied by the number and caching should work even in a single processing pass.

I'm working on it and see a nice speedup.  Will push a branch for testing after fixing some bugs in the code.

**Comment by honggyukim** [comment]
Thanks for the work. I'm looking forward to having it.

**Comment by namhyung** [comment]
Pushed [review/module-symtab-v1](https://github.com/namhyung/uftrace/compare/review/module-symtab-v1).

Note that it still has some bugs and fails many tests.  But works for me for the simple cases.

**Comment by honggyukim** [comment]
Thanks for the work. I roughly tested it and found that the following chrome record data launched a lot faster from 30 seconds to now 9 seconds.

But as you mentioned, I see many errors on other recorded datas showing the following message.
```
$ uftrace replay
fstack: /home/honggyu/work/uftrace/utils/fstack.c:1413:read_task_ustack
 ERROR: record missing argument info
```

**Comment by namhyung** [comment]
Pushed [review/module-symtab-v2](https://github.com/namhyung/uftrace/compare/review/module-symtab-v2)

Changelog:
 * update for dynamic tracing change
 * fix dwarf argument handling

**Comment by honggyukim** [comment]
Thanks a lot for doing this! I just tested it and it mostly works fine and never crashed. But I found only one record that cannot find symbols so shows addresses instead.
```
$ uftrace replay
# DURATION     TID     FUNCTION
            [ 15474] | <55ea1cd2ce8b>() {
   0.693 us [ 15474] |   <55ea1d7cfdc0>();
            [ 15474] |   <55ea1d67c9ad>() {
   0.267 us [ 15474] |     <55ea1d7d0140>();
   3.246 us [ 15474] |   } = 0xb55bfab299b; /* <55ea1d67c9ad> */
   0.326 us [ 15474] |   <55ea1d7cfdc0>();
   0.137 us [ 15474] |   <55ea1d7cfdc0>();
   0.240 us [ 15474] |   <55ea1d7cfdc0>();
   0.154 us [ 15474] |   <55ea1d7cfdc0>();
   0.222 us [ 15474] |   <55ea1d7cfdc0>();
   0.178 us [ 15474] |   <55ea1d7cfdc0>();
   0.244 us [ 15474] |   <55ea1d7cfdc0>();
  33.957 us [ 15474] | } /* <55ea1cd2ce8b> */
   5.394 us [ 15474] | <55ea1d7d0400>(0x55ea1d8510a0) = 0;
   0.226 us [ 15474] | <55ea1d7d0420>(0x55ea1d8510a0) = 0;
   0.184 us [ 15474] | <55ea1d7d0400>(0x55ea1d8510a0) = 0;
...
```
Here is the trace record data. Please take a look at it as well. Thanks!
[uftrace.data.v8.GC.tar.gz](https://github.com/namhyung/uftrace/files/3148162/uftrace.data.v8.GC.tar.gz)

**Comment by honggyukim** [comment]
I found one more case with the attached trace data. - 
[uftrace.data.clang.module-symtab-v2-fail.tar.gz](https://github.com/namhyung/uftrace/files/3148188/uftrace.data.clang.module-symtab-v2-fail.tar.gz)
```
$ uftrace replay -t 1ms
fstack: /home/honggyu/work/uftrace/utils/fstack.c:1413:read_task_ustack
 ERROR: record missing argument inf
```

**Comment by namhyung** [comment]
It seems there's a bug when writing proc maps file.  Could you please show me the real file in the `/proc` diretory for firefox?

**Comment by honggyukim** [comment]
Hmm.. what do you mean by the real file in `/proc` of firefox?
I attached record data directories for V8 and clang.

**Comment by namhyung** [comment]
`/proc/self/maps`

**Comment by honggyukim** [comment]
Do you mean it's for #750? It looks a different issue.

**Comment by namhyung** [comment]
Oops sorry, it's v8.

**Comment by honggyukim** [comment]
Hmm.. It's recorded a year ago, so cannot produce the record. I just recorded it using the current master, then try to replay it with [review/module-symtab-v2](https://github.com/namhyung/uftrace/compare/review/module-symtab-v2), but its symbol is shown correctly.

**Comment by namhyung** [comment]
I found a bug in map processing and fixed it in f2023e8a (in the review/module-symtab-v2 branch) also there are some changes in the symbol searching.  AFAICS the recorded address is correct but map is not.  If you change the end address of the first map (for d8) in the map file to cover the faulting address range, you can see the symbols.

**Comment by namhyung** [comment]
Pushed [review/module-symtab-v3](https://github.com/namhyung/uftrace/compare/review/module-symtab-v3)

Changelog:
 * fix invalid access to dwarf arguments
 * skip unnecessary filter settings
 * fix bug in debug info init

**Comment by honggyukim** [comment]
Thanks a lot for the update. It seems that all the recorded data can be replayed without a problem and got a lot faster :)

However, it seems that there is some bugs during `record`. Please take a look at the following segfault.
```
$ uftrace record -a -t 1ms ./clang ~/hello.c
child terminated by signal: 11: Segmentation fault

$ cgdb --args uftrace record -a -t 1ms ./clang ~/hello.c
    ...
(gdb) r
    ...
Thread 2.1 "clang" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff7fc5800 (LWP 152980)]
0x00000000003bcd06 in ?? ()

Warning: dissasemble address 0x3bcd06 failed.
(gdb) bt
#0  0x00000000003bcd06 in ?? ()
#1  0x00000000008f9509 in _start ()

Warning: dissasemble address 0x3bcd06 failed.
```
But the record is done normally for the same program if `--no-libcall` is given as follows:
```
$ uftrace record --no-libcall ./clang ~/hello.c
```

**Comment by honggyukim** [comment]
It can be easily reproduced with a very simple program.
```
$ uftrace record t-abc
child terminated by signal: 11: Segmentation fault
```
```
$ uftrace record -vv t-abc
...
plthook: restore GOT[7] from "__cxa_atexit"(0x400566) to PLT(base + 0x17d7cb0)
plthook: restore GOT[8] from "atoi"(0x400576) to PLT(base + 0x17d9970)
mcount: mcount setup done
uftrace: all process/thread exited
child terminated by signal: 11: Segmentation fault
uftrace: stop writer thread 9
uftrace: stop writer thread 5
uftrace: stop writer thread 6
...
```

**Comment by honggyukim** [comment]
This segfault doesn't happened before the following commit.
- 8505263 symbol: Get rid of SYMTAB_FL_ADJ_OFFSE

The record works fine right after reverting the commit above.
```
$ git log --oneline -7
9bd0b40 (HEAD -> refs/heads/review/module-symtab-v3) Revert "symbol: Get rid of SYMTAB_FL_ADJ_OFFSET"
0cf40f4 (refs/remotes/origin/review/module-symtab-v3) fstack: Improve debug message for missing argspec
0ee5659 dwarf: Fix invalid access in find_dwarf_argspec()
1c416bd filter: Ignore arguments with no (auto) argspecs
e7e9328 filter: Fix PLT filter handling
d7021af symbol: Consolidate symbol table handling
8505263 symbol: Get rid of SYMTAB_FL_ADJ_OFFSET

$ uftrace record t-abc

$ uftrace replay
# DURATION     TID     FUNCTION
   1.100 us [164350] | __monstartup();
   0.866 us [164350] | __cxa_atexit();
            [164350] | main() {
            [164350] |   a() {
            [164350] |     b() {
            [164350] |       c() {
   0.680 us [164350] |         getpid();
   1.767 us [164350] |       } /* c */
   2.260 us [164350] |     } /* b */
   2.610 us [164350] |   } /* a */
   3.043 us [164350] | } /* main */
```

**Comment by honggyukim** [comment]
It seems that it has a significant speed up even during record command running.
**Before**
```
$ uftrace record --time ./clang ~/hello.c
elapsed time: 23.933440360 sec
 system time: 0.444000000 sec
   user time: 23.484000000 sec
```
**After** (with reverting 8505263)
```
$ uftrace record --time ./clang ~/hello.c
elapsed time: 0.276971673 sec
 system time: 0.036000000 sec
   user time: 0.236000000 sec
```
It becomes from 23 seconds to 0.2 seconds.

**Comment by honggyukim** [comment]
Hmm.. it doesn't have such significant speed up when recording with `--auto-args`.
**Before**
```
$ uftrace record --time -a ./clang ~/hello.c
elapsed time: 26.207910894 sec
 system time: 0.552000000 sec
   user time: 25.652000000 sec
```
**After** (with reverting 8505263)
```
$ uftrace record --time -a ./clang ~/hello.c
elapsed time: 21.914641833 sec
 system time: 0.412000000 sec
   user time: 21.500000000 sec
```

**Comment by honggyukim** [comment]
It doesn't have much difference when it comes to full dynamic tracing for prebuilt clang.
**Before**
```
$ uftrace record --time -P. /usr/bin/clang ~/hello.c
elapsed time: 4.758336062 sec
 system time: 0.448000000 sec
   user time: 4.304000000 sec
```
**After** (with reverting 8505263)
```
$ uftrace record --time -P. /usr/bin/clang ~/hello.c
elapsed time: 4.639179271 sec
 system time: 0.384000000 sec
   user time: 4.248000000 sec
```
It may be a lot faster if it has `libmcount-dynamic-fast.so` as mentioned in #757.

**Comment by namhyung** [comment]
Could you attach the `t-abc` binary?  I don't have the problem but it maybe related to PIE.  I cannot build `-fno-pie` for some reason.

**Comment by honggyukim** [comment]
To sums up, it requires some changes as follows:
- need to fix 8505263 to avoid segfault during record
- have to decide whether to create `.dbg` file when recording without any argument related options. (used to see its line info at least even if no argument is recorded, but got slower.)
- `uftrace record -a clang hello.c` generates `.dbg` file, but didn't use it when recording arguments of user functions.

**Comment by honggyukim** [comment]
> Could you attach the t-abc binary? I don't have the problem but it maybe related to PIE. I cannot build -fno-pie for some reason.

Sure. Please take a look at [t-abc.txt](https://github.com/namhyung/uftrace/files/3173346/t-abc.txt).

**Comment by honggyukim** [comment]
Hmm.. The full text in `clang.dbg` looks too short when recording with `uftrace record -a clang hello.c`.
```
: e70580 llvm::DenseMap::grow
L: 621 /home/honggyu/work/llvm/release/7.0.1/llvm-7.0.1.src/include/llvm/ADT/DenseMap.h
A: @arg1/p%rdi,arg2%rsi
F: e77310 llvm::DenseMap::grow
L: 32 /home/honggyu/work/llvm/release/7.0.1/llvm-7.0.1.src/lib/Analysis/CallGraph.cpp
A: (null)
F: 10fc640 llvm::DenseMapBase::FindAndConstruct
L: 3262 /home/honggyu/work/llvm/release/7.0.1/llvm-7.0.1.src/lib/CodeGen/MachinePipeliner.cpp
A: @arg1/p%rdi,arg2/p%rsi
F: 11d9500 llvm::DenseMap::grow
L: 1639 /usr/include/c++/5/bits/stl_tree.h
A: @arg1/p%rdi,arg2%rsi
F: 125afa0 llvm::DenseMapIterator::DenseMapIterator
L: 835 /home/honggyu/work/llvm/release/7.0.1/llvm-7.0.1.src/lib/IR/DataLayout.cpp
A: @arg1/p%rdi,arg2/p%rsi,arg3/p%rdx,arg4/p%rcx,arg5%r8
F: 1838ff0 llvm::DenseMapBase::LookupBucketFor
L: 72 /home/honggyu/work/llvm/release/7.0.1/llvm-7.0.1.src/lib/Transforms/Utils/LoopUnrollPeel.cpp
A: @arg1/p%rdi,arg2/p%rsi,arg3/p%rdx
F: 1993160 std::vector::_M_emplace_back_aux
L: 186 /usr/include/c++/5/bits/move.h
A: @arg1/p%rdi
F: 1a20780 std::vector::emplace_back
L: 91 /usr/include/c++/5/bits/vector.tcc
A: (null)
F: 202c2a0 std::_Rb_tree::_M_erase
L: 6144 /home/honggyu/work/llvm/release/7.0.1/llvm-7.0.1.src/lib/CodeGen/SelectionDAG/SelectionDAG.cpp
A: @arg1/p%rdi,arg2/p%rsi
F: 257ad40 std::vector::_M_emplace_back_aux
L: 28 /home/honggyu/work/llvm/release/7.0.1/llvm-7.0.1.src/tools/clang/lib/StaticAnalyzer/Frontend/ModelInjector.cpp
A: @arg1/p%rdi
F: 25c9ea0 llvm::SmallVectorTemplateBase::grow
L: 851 /home/honggyu/work/llvm/release/7.0.1/llvm-7.0.1.src/include/llvm/ADT/SmallVector.h
A: (null)
F: 2678bd0 llvm::DenseMap::grow
L: 594 /home/honggyu/work/llvm/release/7.0.1/llvm-7.0.1.src/include/llvm/ADT/ImmutableSet.h
A: (null)
F: 2760dc0 std::vector::_M_emplace_back_aux
L: 368 /home/honggyu/work/llvm/release/7.0.1/llvm-7.0.1.src/include/llvm/Support/Allocator.h
A: @arg1/p%rdi
F: 28b49a0 llvm::DenseMap::grow
L: 549 /home/honggyu/work/llvm/release/7.0.1/llvm-7.0.1.src/include/llvm/ADT/ImmutableSet.h
A: (null)
F: 2cfadc0 std::__introsort_loop
L: 5240 /usr/include/c++/5/bits/basic_string.h
A: @arg1%rdi,arg2%rsi,arg3%rdx,arg4
```

**Comment by honggyukim** [comment]
I found that it works fine in my Ubuntu 18.04 machine. Its gcc is configured with `--enable-default-pie`, but Ubuntu 16.04 doesn't have it and the problem is only shown in Ubuntu 16.04 machine.

**Comment by namhyung** [comment]
Thanks for the info.  I was thinking it's safe to remove `SYMTAB_FL_ADJ_OFFSET` as it's unconditionally used.  But actually plthook code didn't use it purposely and it caused the crash.  Also I found a mistake address handling in debug info access in the patch.

Pushed [review/module-symtab-v4](https://github.com/namhyung/uftrace/compare/review/module-symtab-v4)

Changelog:
 * revive `SYMTAB_FL_ADJ_OFFSET` change
 * fix address used when accessing dwarf info for non-PIE

**Comment by honggyukim** [comment]
Thanks for the update. It seems that it still has a few problems.

**1. performance issue**
It seems that the record time looks slower compared to the result in master(26 seconds).
```
$ uftrace record --time -a ./clang ~/hello.c
elapsed time: 41.504042548 sec
 system time: 1.000000000 sec
   user time: 31.880000000 sec
```
**edit**: I recorded again but it took only 26 seconds same as master. (so doesn't look like a problem)
```
$ uftrace record --time -a ./clang ~/hello.c
elapsed time: 26.842805535 sec
 system time: 0.432000000 sec
   user time: 26.404000000 sec
```
**2. debug line info in TUI**
I cannot see source line info in TUI for `t-abc` example, but strangely I can see it for `clang` recorded data.
```
$ gcc -pg -g tests/s-abc.c -o t-abc

$ uftrace record -a t-abc

$ uftrace tui
  TOTAL TIME : FUNCTION
   12.123 us : (1) t-abc
    1.453 us :  ├─(1) __monstartup
             :  │
    0.950 us :  ├─(1) __cxa_atexit
             :  │
>>> 9.720 us :  └─(1) main <<< selection bar is here!
    7.634 us :    (1) a
    6.917 us :    (1) b
    5.990 us :    (1) c
    0.777 us :    (1) getpid

uftrace graph: source location is not available [at 0x40072a]
```
But it has `t-abc.dbg` file and it contains source line info.
```
$ cat uftrace.data/t-abc.dbg
F: 6c6 a
L: 11 tests/s-abc.c
R: @retval
F: 6d9 b
L: 16 tests/s-abc.c
R: @retval
F: 6ec c
L: 21 tests/s-abc.c
R: @retval
F: 71d main
L: 26 tests/s-abc.c
A: @arg1,arg2/p
R: @retval
```

**Comment by honggyukim** [comment]
In terms of debug line info, I think we can disable generating `.dbg` files in basic record behavior, but provide a way to explicitly generate it.  Here are the possible cases.

**1. basic record**
It doesn't generate `.dbg` files so it doesn't have to waste time reading its debug info.

**2. basic record with `--debug-line` option**
It generates `.dbg` files including source line info only.

**3. record with `--auto-args` option**
It generates `.dbg` files including source line and function arguments/return type info

**Comment by honggyukim** [comment]
In addition to the above ways, I think it'd be really helpful if we can provide a way to export and import `.dbg` files for a given binary.

It has following advantages:
- It can especially be faster when launching the program with pre-generated `.dbg` files.
- The pre-generated `.dbg` files can be used when recording a binary that doesn't have debug info.
  - It would had been striped after the `.dbg` file is generated.
- We can have a easier way to debug DWARF handling code.

**Comment by namhyung** [comment]
Oh, I think following change should be added for line numbers in TUI:

```diff
diff --git a/utils/dwarf.c b/utils/dwarf.c
index 5b1de99..106fc8c 100644
--- a/utils/dwarf.c
+++ b/utils/dwarf.c
@@ -1451,7 +1451,7 @@ struct debug_location *find_file_line(struct symtabs *symtabs, uint64_t addr)
        dinfo = &map->mod->dinfo;
 
        if (debug_info_has_location(dinfo))
-               sym = find_sym(symtab, addr);
+               sym = find_sym(symtab, addr - map->start);
 
        if (sym == NULL)
                return NULL;
```

**Comment by namhyung** [comment]
The reason it didn't save debug file was it didn't load symbol tables anymore when no filter or argument is used.  Anyway I agree with your suggestion.  Will work toward the direction.

**Comment by namhyung** [comment]
Pushed [review/module-symtab-v5](https://github.com/namhyung/uftrace/compare/review/module-symtab-v5)

Changelog:
 * fix source line display
 * convert dlopen'ed libraries to use module symtab

**Comment by honggyukim** [comment]
Thanks for the update. It mostly works fine, but there's a broken case as follows:
```
$ uftrace record --time -a ./chrome --no-sandbox --headless https://www.google.com
elapsed time: 604.917977432 sec
 system time: 26.408000000 sec
   user time: 560.276000000 sec

$ uftrace replay
fstack: /home/honggyu/work/uftrace/utils/fstack.c:1419:read_task_ustack
 ERROR: record missing argument info for base::_GLOBAL__N_1::ThreadFunc
```
I cannot attach the data because it's too big.
```
$ cd uftrace.data

$ du -hs
43G     .
```

**Comment by honggyukim** [comment]
I tested it once again with time-filter and it also gets failed.
```
$ uftrace record --time -t 100ms -a ./chrome --no-sandbox --headless https://www.google.com
[0517/012511.001404:WARNING:spdy_session.cc(3180)] Received HEADERS for invalid stream 17
[0517/012511.024862:WARNING:spdy_session.cc(3180)] Received HEADERS for invalid stream 19
elapsed time: 320.671122128 sec
 system time: 13.820000000 sec
   user time: 289.932000000 sec

$ uftrace replay
fstack: /home/honggyu/work/uftrace/utils/fstack.c:1419:read_task_ustack
 ERROR: record missing argument info for base::_GLOBAL__N_1::ThreadFunc
```
You can download the recorded data so please take a look at it.
[uftrace.data.chrome.args.fail.module-symtab-v5.tar.gz](https://github.com/namhyung/uftrace/files/3188077/uftrace.data.chrome.args.fail.module-symtab-v5.tar.gz)

**Comment by honggyukim** [comment]
It works fine if I record chrome without `--auto-args` option.

**Comment by namhyung** [comment]
Pushed [review/module-symtab-v6](https://github.com/namhyung/uftrace/compare/review/module-symtab-v6)

Changelog:
 * fix filter/argument setting for the second (or later) sesssions

**Comment by honggyukim** [comment]
@namhyung Thanks very much for your effort on this. I just tested it and found that all works fine for chrome, node, and clang. It also reduced the analysis time of chrome from `1m3.732s` to `0m25.035s`, which looks great.
**1. chrome**
```
$ uftrace record -t 10ms -a ./chrome --no-sandbox --headless https://www.google.com

$ time uftrace replay --no-pager | head
# DURATION     TID     FUNCTION
            [ 16560] | _GLOBAL__sub_I_spinlock.cc() {
            [ 16560] |   NumCPUs() {
            [ 16560] |     InitializeSystemInfo() {
            [ 16560] |       RunningOnValgrind() {
            [ 16560] |         getenv("RUNNING_ON_VALGRIND") {
  18.187 ms [ 16560] |           /* linux:schedule */
  19.188 ms [ 16560] |         } = "NULL"; /* getenv */
  19.192 ms [ 16560] |       } = 0; /* RunningOnValgrind */
   6.429 ms [ 16560] |       /* linux:schedule */

real    0m25.035s
user    0m24.724s
sys     0m0.308s
```
After changing uftrace to master version.
```
$ time uftrace replay --no-pager | head
# DURATION     TID     FUNCTION
            [ 16560] | _GLOBAL__sub_I_spinlock.cc() {
            [ 16560] |   NumCPUs() {
            [ 16560] |     InitializeSystemInfo() {
            [ 16560] |       RunningOnValgrind() {
            [ 16560] |         getenv("RUNNING_ON_VALGRIND") {
  18.187 ms [ 16560] |           /* linux:schedule */
  19.188 ms [ 16560] |         } = "NULL"; /* getenv */
  19.192 ms [ 16560] |       } = 0; /* RunningOnValgrind */
   6.429 ms [ 16560] |       /* linux:schedule */

real    1m3.732s
user    1m3.020s
sys     0m0.712s
```
**2. node**
```
$ uftrace record -P. -a ./node --expose-gc --trace-gc -e gc()

$ time uftrace replay --no-pager | head
# DURATION     TID     FUNCTION
   4.383 us [ 18402] | OPENSSL_ia32_cpuid();
            [ 18402] | _GLOBAL__sub_I__register_cares_wrap() {
   4.757 us [ 18402] |   uv_mutex_init(0x25a4560);
   8.295 us [ 18402] | } /* _GLOBAL__sub_I__register_cares_wrap */
            [ 18402] | _GLOBAL__sub_I_node::reverted() {
   0.279 us [ 18402] |   uv_mutex_init(0x25a4ca0);
   0.241 us [ 18402] |   uv_mutex_init(0x25a4d20);
  17.794 us [ 18402] | } /* _GLOBAL__sub_I_node::reverted */
            [ 18402] | _GLOBAL__sub_I_node::http2::Http2Session::callback_struct_saved() {

real    0m0.664s
user    0m0.632s
sys     0m0.028s
```
After changing uftrace to master version.
```
$ time uftrace replay --no-pager | head
# DURATION     TID     FUNCTION
   4.383 us [ 18402] | OPENSSL_ia32_cpuid();
            [ 18402] | _GLOBAL__sub_I__register_cares_wrap() {
   4.757 us [ 18402] |   uv_mutex_init(&node::cares_wrap::_GLOBAL__N_1::ares_library_mutex);
   8.295 us [ 18402] | } /* _GLOBAL__sub_I__register_cares_wrap */
            [ 18402] | _GLOBAL__sub_I_node::reverted() {
   0.279 us [ 18402] |   uv_mutex_init(&node::per_process_opts_mutex);
   0.241 us [ 18402] |   uv_mutex_init(&node::node_isolate_mutex);
  17.794 us [ 18402] | } /* _GLOBAL__sub_I_node::reverted */
            [ 18402] | _GLOBAL__sub_I_node::http2::Http2Session::callback_struct_saved() {

real    0m0.709s
user    0m0.644s
sys     0m0.064s
```
**3. clang**
```
$ uftrace record -P. -a ./clang ~/hello.c

$ time uftrace replay --no-pager | head
# DURATION     TID     FUNCTION
            [ 18629] | _GLOBAL__sub_I_cc1_main.cpp() {
            [ 18629] |   getenv("bar") {
   8.244 ms [ 18629] |     /* linux:schedule */
   8.464 ms [ 18629] |   } = "NULL"; /* getenv */
   8.470 ms [ 18629] | } /* _GLOBAL__sub_I_cc1_main.cpp */
   1.767 us [ 18629] | llvm::cl::Option::setArgStr(&SpillAlignedNEONRegs, 0x2ddf55c);
            [ 18629] | llvm::cl::Option::addArgument(&SpillAlignedNEONRegs) {
            [ 18629] |   llvm::ManagedStaticBase::RegisterManagedStatic(0x3c4b858, &llvm::object_creator::call, &llvm::object_deleter::call) {
            [ 18629] |     pthread_once(0x3c4c180, &__once_proxy) {

real    0m1.482s
user    0m1.388s
sys     0m0.092s
```
After changing uftrace to master version.
```
$ time uftrace replay --no-pager | head
# DURATION     TID     FUNCTION
            [ 18629] | _GLOBAL__sub_I_cc1_main.cpp() {
            [ 18629] |   getenv("bar") {
   8.244 ms [ 18629] |     /* linux:schedule */
   8.464 ms [ 18629] |   } = "NULL"; /* getenv */
   8.470 ms [ 18629] | } /* _GLOBAL__sub_I_cc1_main.cpp */
   1.767 us [ 18629] | llvm::cl::Option::setArgStr(&SpillAlignedNEONRegs, 0x2ddf55c);
            [ 18629] | llvm::cl::Option::addArgument(&SpillAlignedNEONRegs) {
            [ 18629] |   llvm::ManagedStaticBase::RegisterManagedStatic(&GlobalParser, &llvm::object_creator::call, &llvm::object_deleter::call) {
            [ 18629] |     pthread_once(&mutex_init_flag, &__once_proxy) {

real    0m2.981s
user    0m2.916s
sys     0m0.064s
```
Thank you very much for this work!

**Comment by honggyukim** [comment]
In terms of recording time, it doesn't look like there's a great performance improvement.

**review/module-symtab-v6**
```
# chrome
$ uftrace record --time -t 100ms -a ./chrome --no-sandbox --headless https://www.google.com
[0520/093550.692663:WARNING:spdy_session.cc(3180)] Received HEADERS for invalid stream 17
[0520/093550.760251:WARNING:spdy_session.cc(3180)] Received HEADERS for invalid stream 19
elapsed time: 279.327840862 sec
 system time: 12.144000000 sec
   user time: 270.148000000 sec

# node
$ uftrace record --time -P. -a ./node --expose-gc --trace-gc -e 'gc()'
[21011:0xb6f1dd0]      960 ms: Scavenge 2.4 (4.2) -> 2.1 (5.2) MB, 21.7 / 0.1 ms  (average mu = 1.000, current mu = 1.000) allocation failure
[21011:0xb6f1dd0]     1411 ms: Scavenge 2.6 (5.2) -> 2.5 (6.2) MB, 21.7 / 0.0 ms  (average mu = 1.000, current mu = 1.000) allocation failure
[21011:0xb6f1dd0]     2193 ms: Mark-sweep 3.5 (6.2) -> 3.2 (8.2) MB, 44.0 / 0.1 ms  (average mu = 1.000, current mu = 1.000) testing GC in old space requested
elapsed time: 9.713681701 sec
 system time: 0.264000000 sec
   user time: 9.480000000 sec

# clang
$ uftrace record --time -P. -a ./clang ~/hello.c
elapsed time: 48.564032502 sec
 system time: 1.248000000 sec
   user time: 47.312000000 sec
```
**master**
```
# chrome
$ uftrace record --time -t 100ms -a ./chrome --no-sandbox --headless https://www.google.com
[0520/093015.877711:WARNING:spdy_session.cc(3180)] Received HEADERS for invalid stream 17
[0520/093015.906890:WARNING:spdy_session.cc(3180)] Received HEADERS for invalid stream 19
elapsed time: 282.419343146 sec
 system time: 12.072000000 sec
   user time: 270.776000000 sec

# node
$ uftrace record --time -P. -a ./node --expose-gc --trace-gc -e 'gc()'
[20269:0xabd8b10]      920 ms: Scavenge 2.4 (4.2) -> 2.1 (5.2) MB, 14.5 / 0.1 ms  (average mu = 1.000, current mu = 1.000) allocation failure
[20269:0xabd8b10]     1207 ms: Scavenge 2.6 (5.2) -> 2.5 (6.2) MB, 11.8 / 0.0 ms  (average mu = 1.000, current mu = 1.000) allocation failure
[20269:0xabd8b10]     2047 ms: Mark-sweep 3.5 (6.2) -> 3.2 (8.2) MB, 47.3 / 0.1 ms  (average mu = 1.000, current mu = 1.000) testing GC in old space requested
elapsed time: 9.844468486 sec
 system time: 0.236000000 sec
   user time: 9.640000000 sec

# clang
$ uftrace record --time -P. -a ./clang ~/hello.c
elapsed time: 49.883659957 sec
 system time: 1.388000000 sec
   user time: 48.492000000 sec
```

**Comment by namhyung** [comment]
Pushed [review/symbol-cleanup-v1](https://github.com/namhyung/uftrace/compare/review/symbol-cleanup-v1).

It gets huge speedup by using RB tree for srcline in the debug info.  Also it has some small cleanups.

**Comment by honggyukim** [comment]
I can also see the huge speedup with the above change. Thanks a lot!
**1. original replay time**
```
$ time uftrace replay | head
# DURATION     TID     FUNCTION
            [159826] | main(4, 0x7ffe9df4f878) {
            [159826] |   ChromeMain(4, 0x7ffe9df4f878) {
            [159826] |     headless::HeadlessShellMain(0x7ffe9df4f750) {
            [159826] |       headless::HeadlessShellMain(4, 0x7ffe9df4f878) {
            [159826] |         headless::HeadlessBrowserMain(0x7ffe9df4f328, 0x7ffe9df4f2f8) {
            [159826] |           headless::_GLOBAL__N_1::RunContentMain(0x7ffe9df4f0d0, 0x7ffe9df4f0c8) {
            [159826] |             content::ContentMain(0x7ffe9df4ee68) {
            [159826] |               service_manager::Main(0x7ffe9df4edd8) {
            [159826] |                 /* linux:task-name (name=chrome) */

real    0m22.441s
user    0m21.992s
sys     0m0.448s
```
**replay time of `review/symbol-cleanup-v1`**
```
$ time uftrace replay | head
# DURATION     TID     FUNCTION
            [159826] | main(4, 0x7ffe9df4f878) {
            [159826] |   ChromeMain(4, 0x7ffe9df4f878) {
            [159826] |     headless::HeadlessShellMain(0x7ffe9df4f750) {
            [159826] |       headless::HeadlessShellMain(4, 0x7ffe9df4f878) {
            [159826] |         headless::HeadlessBrowserMain(0x7ffe9df4f328, 0x7ffe9df4f2f8) {
            [159826] |           headless::_GLOBAL__N_1::RunContentMain(0x7ffe9df4f0d0, 0x7ffe9df4f0c8) {
            [159826] |             content::ContentMain(0x7ffe9df4ee68) {
            [159826] |               service_manager::Main(0x7ffe9df4edd8) {
            [159826] |                 /* linux:task-name (name=chrome) */

real    0m4.878s
user    0m4.380s
sys     0m0.500s
```
It becomes from 22.4 seconds to 4.8 seconds. It's more than 4 times faster.

**Comment by honggyukim** [comment]
I have one more request for this. `uftrace replay` currently doesn't have to source location info so it'd be better to skip reading it to make it even more faster.

**Comment by namhyung** [comment]
Will add.

**Comment by honggyukim** [comment]
Thanks :)

**Comment by namhyung** [comment]
Let's discuss it in #759

**Comment by namhyung** [comment]
I think we can close this now.

**Comment by honggyukim** [comment]
Sure. Thanks for your hard work.
