### ISSUE TITLE
schedule event needs to be fixed

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#739]
I think current `linux:schedule` event is not mature and it has the following problems as of now.
- It doesn't work well with record time time-filter
  - So when distributing the recorded data, always have to mention to use time-filter for analysis.
  - otherwise, the output screen is covered by too many noisy scheduling events as mentioned in  https://github.com/namhyung/uftrace/issues/699#issuecomment-474568996.
- `--no-event` simply hides this scheduling events, but it also disables task-name event as well.
  - The only way to work around this is to use `--no-event -E linux:task-name`, but it doesn't look nice.

In most cases, I'm only interested in task-name and not interested in scheduling event.
I would like to suggest the following choices.
1. `--no-sched` option to disable only schedule event.
2. disable schedule event by default and add `--sched` option to turn it on.
3. https://github.com/namhyung/uftrace/issues/658#issuecomment-458010226 can be a solution

**Comment by honggyukim** [comment]
As we discussed today, I think we better provide a way to apply default options from a pre-defined opt file that is inside of `uftrace.data`.

We can generate the opt file inside `uftrace.data` to apply the time-filter used by `record` command. This can be the simplest fix as wrote in "3" above.

**Comment by honggyukim** [comment]
Otherwise, It would be also good to always use `-E linux:task-name` even if `--no-event` is used.

**Comment by honggyukim** [comment]
> Otherwise, It would be also good to always use -E linux:task-name even if --no-event is used.

@namhyung What about applying this as well? Is there any benefit of not recording `linux:task-name`?

**Comment by namhyung** [comment]
Well, it doesn't honor the meaning of **NO** events and maybe sometimes users want to remove overhead of perf events at all.
