### ISSUE TITLE
Subtle different execution when tracing with uftrace

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#742]
It seems that the result of `pwd` might be different when tracing with uftrace.

Here is the basic steps to reproduce it.
```
$ pwd
/home/honggyu/test

$ mkdir realdir

$ ln -s realdir linkdir

$ ls -l
lrwxrwxrwx 1 honggyu honggyu     7 May  4 12:36 linkdir -> realdir
drwxrwxr-x 2 honggyu honggyu  4096 May  4 12:36 realdir
```
Let's see the result of `pwd` in `linkdir`, which is a soft link to `realdir` directory.
```
$ cd linkdir

$ pwd
/home/honggyu/test/linkdir

$ pwd -P
/home/honggyu/test/realdir
```
It shows that `pwd` shows the currently working directory, but it shows its real location with `-P` option.

But the thing is that the result is different when tracing it with uftrace.
```
$ uftrace --force -a -F ^get /bin/pwd
/home/honggyu/test/realdir
# DURATION     TID     FUNCTION
 327.812 us [184544] | getenv("POSIXLY_CORRECT") = "NULL";
   3.136 us [184544] | getopt_long(1, 0x7ffcbafcb178, "LP") = -1;
   9.317 us [184544] | getcwd(0, 0) = "/home/honggyu/test/realdir";
```
It doesn't have `-P` option, but it shows its real location.

It might be a minor issue but it could make a future problem, so summarized it here.

**Comment by namhyung** [comment]
I think it's difference between shell builtin and the pwd binary.  By invoking `pwd` shell builtin is used, but using a full path or calling `exec*` it will use the binary.  So it's not a problem of uftrace IMO.

```
$ pwd
/home/namhyung/tmp/linkdir
$ type pwd
pwd is a shell builtin
$ /usr/bin/pwd
/home/namhyung/tmp/realdir
```

**Comment by honggyukim** [comment]
Ah.. It's running different things.
```
$ pwd
/home/honggyu/linkdir

$ pwd -P
/home/honggyu/realdir

$ type pwd
pwd is a shell builtin

$ /bin/pwd
/home/honggyu/realdir

$ uftrace --force -a -F ^get /bin/pwd
/home/honggyu/realdir
# DURATION     TID     FUNCTION
 343.663 us [  2274] | getenv("POSIXLY_CORRECT") = "NULL";
   2.957 us [  2274] | getopt_long(1, 0x7fff3466ecf8, "LP") = -1;
   8.231 us [  2274] | getcwd(0, 0) = "/home/honggyu/realdir";
```
It's not an issue of uftrace so I will close this. Thanks for checking this.
