### ISSUE TITLE
Why don't we have libmcount-dynamic-fast.so?

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#757]
It seems that we can have `libmcount-dynamic-fast.so`, which includes dynamic tracing feature but it doesn't have any filter setting code just like `libmcount-fast.so`.

**Comment by honggyukim** [comment]
Its tracing overhead will be same as `libmcount-fast.so` after finishing dynamic patching during launching time.

**Comment by namhyung** [comment]
I don't want to add the variants of libmcount anymore.  Actually it'd be nice to make it just a single library for the maintenance reason.

**Comment by honggyukim** [comment]
I'm also fine with it. Then I will close this issue.
