### ISSUE TITLE
Providing network transmission info

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#774]
It's just an idea but what about providing network transmission (delta) info between function entry and exit?

It can be shown as an event just like `read=proc/statm` info, but I personally think that it'd better to be shown as a new replay field.

I think it'd be useful to network engineers.

**Comment by namhyung** [comment]
I'm not sure whether it's a good idea.  Did you get this from a real use case?  AFAIK network transmission is complex and maybe it's done in a different context due to many reasons.

And how would you get the information?

**Comment by honggyukim** [comment]
I do have a picture in mind but It's not an urgent work at all. So I will just close it until I get more realistic idea. Thanks.
