### ISSUE TITLE
uftrace info --list to show the list of recorded data

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#779]
I often see some difficulty to search the proper `uftrace.data` from the current directory. It's because I usually create many different `uftrace.data` records to the current directory. So I would like to have a way to scan the list of recorded data as follows:
```
$ uftrace info --list
uftrace.data.srcline: # cmdline             : uftrace record --time -a -D1 --no-libcall --no-event -d uftrace.data.srcline ./chrome --no-sandbox --headless https://www.google.com
uftrace.data.no-srcline: # cmdline             : uftrace record --time -a -D1 --no-libcall --no-event --no-srcline -d uftrace.data.no-srcline ./chrome --no-sandbox --headless https://www.google.com
...
```
It can directly scan the current directory and its child directories that contains `info` file in a proper format.

It'd be helpful to find the record that user wants.

**Comment by namhyung** [comment]
Well I'm not convinced.. it's not a problem of uftrace, if you want to keep many data, you should give a proper name or write up a script to do what you describe using `uftrace info | grep cmdline`.

**Comment by honggyukim** [comment]
It's a matter of preference so it's okay if you disagree with it. Never mind.
