### ISSUE TITLE
enhance the logic to check whether an instrument is available in a function.

### ISSUE THREAD

**Issue by ParkHanbum** [namhyung/uftrace#785]
currently, uftrace check the prologue of function to judge whether instrumentable. for now, this rules are very rough and minimize. so, it is need to enhanced. for this, first of all, I want to add some code to show more detail debugging message. it will not affect to users, if make it compile only with specified flag like DEBUG.

**Comment by namhyung** [comment]
Do you mean `disasm_check_insns()`?
