### ISSUE TITLE
Let's remove useless message "Didn't you run "make install?"

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#796]
The message is misprinted in a normal execution.
```
# uftrace record --force pwd
WARN: Didn't you run 'make install' ?
/home/root
```
The record looks fine though.

**Comment by namhyung** [comment]
So do you see this message even after you installed it?  The message is printed when it cannot find the libmcount in the install path.

**Comment by honggyukim** [comment]
I cross compiled and copied the installed directory to the target board. But couldn't install it in the default directory `/usr/bin` and `/usr/lib` as usual because it's read-only file system.

**Comment by honggyukim** [comment]
The same message is shown in https://github.com/namhyung/uftrace/issues/729#issuecomment-484369233 as well.

**Comment by honggyukim** [comment]
It's because `INSTALL_LIB_PATH` is set to the directory for install target on the same machine.
```
$ cat Makefile
    ...
CFLAGS_$(objdir)/cmds/record.o = -DINSTALL_LIB_PATH='"$(libdir)"'
CFLAGS_$(objdir)/cmds/live.o = -DINSTALL_LIB_PATH='"$(libdir)"'
    ...
```
It could be changed when it comes to cross compilation environment. In this case, the compiled binaries can be directly copied to the target board.

**Comment by namhyung** [comment]
You can set the `prefix` when you build it.

**Comment by honggyukim** [comment]
I'm not sure if this message is really necessary. If the filesystem is read-only, the compiled binaries, `uftrace`, `libmcount*.so`, can be sent to someone else and set their own environment to use. We don't have to fix the location for its execution.

**Comment by namhyung** [comment]
@Taeung are you ok with removing the message?

**Comment by honggyukim** [comment]
@Taeung Could you please take a look?

**Comment by honggyukim** [comment]
@Taeung Gentle ping~

**Comment by Taeung** [comment]
Really sorry, I missed the notification... I think you are right. I also think it is better to remove the message
because there can be cases like cross compilation environment.

**Comment by honggyukim** [comment]
I made a request to change this in #832. Thanks!
