### ISSUE TITLE
Maybe we need a more user friendly way for -P.

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#799]
For v0.9.3, full-dynamic tracing is the major feature. But it seems that the current usage with `-P.` looks a bit cryptic and doesn’t look intuitive.

IMHO, we better have a way to apply the same effect with a simper and more user friendly option name just `-a`/`--auto-args` for `-A. -R.`

It could be `--dynamic` or we could also reuse `--force` option for this.

**Comment by namhyung** [comment]
I don't think `-P <regex>` is not too annoying or cryptic.  Maybe there's better way to specify all functions in regex (or glob) but it's anyway user's choice.

**Comment by honggyukim** [comment]
I will also close this if you disagree with it.

**Comment by honggyukim** [comment]
What about providing `-p` option for `-P.` just like `-a` for `-A. -R.`?
