### ISSUE TITLE
Providing extra information to uftrace info output

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#801]
It may be difficult to identify if user created many uftrace data records.

So I would like to add extra info to `uftrace info` output. For example, we can create a file `note.txt` inside `uftrace.data` and the content of the file can be printed at the end of `uftrace info` output.

**Comment by namhyung** [comment]
Not sure it's worth.  Anyway users should create the file, right?  Then why not just change the dirname?

**Comment by honggyukim** [comment]
I will close this if you disagree with it as it's just a matter of preference.
