### ISSUE TITLE
dynamic tracing with existing `-pg -mfentry -mnop-mcount`

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#814]
I'm just wondering if it's possible to apply dynamic patching only for the target `NOP`s, which are generated by `-pg -mfentry -mnop-mcount`.

After having full-dynamic tracing, it gets a bit complicated to use `-pg -mfentry -mnop-mcount` options. Even if the target binary has a bug when it comes to full-dynamic tracing, it should work fine with `-pg -mfentry -mnop-mcount`. However, it seems that it's not possible to distinguish between those two features.

**Comment by namhyung** [comment]
I don't understand.  What's your problem?

**Comment by honggyukim** [comment]
If the target binary cannot be recorded with full-dynamic tracing due to some mishandled cases, we can never trace it even if it's already compiled with `-pg -mfentry -mnop-mcount`.

It's because it can also try to patch some unsafe function if it's not covered by `-pg -mfentry -mnop-mcount`. I'm not sure yet if we already handled all the edge cases including the case in cross-function jump instructions.

**Comment by namhyung** [comment]
I don't understand.  What's your problem?

**Comment by honggyukim** [comment]
For example, I think chrome that is compiled with `-pg -mfentry -mnop-mcount` cannot be traced even with previously existing dynamic tracing feature. It will try to use full-dynamic tracing for some unsafe functions and will get crashed if we cannot fully handle all the cases for full dynamic tracing.

**Comment by honggyukim** [comment]
I think the current implementation decides whether to patch `__dentry__` or `__fentry__` depending on the function. But if some functions don't have `__fentry__` somehow, it may try to patch `__dentry__` to some unsafe function and can make the target program crashed.

**Comment by namhyung** [comment]
Currently it checks the first 5 functions to have known patterns (for `-pg -mfentry -mnop-mcount`) and treat the whole module in a same way.  IOW, it marks the result in the `adi->type` and use it for all functions.

**Comment by honggyukim** [comment]
Okay. I see. Thanks for the explanation.
