### ISSUE TITLE
Arguments with non printable characters mess up chrome reports

### ISSUE THREAD

**Issue by kfir-drivenets** [namhyung/uftrace#820]
Lets take the following example
```c
#include <stdio.h>
#include <string.h>

int foo(const char *str) {
	printf("my str len %lu\n", strnlen(str, 100));
	return 0;
}

int main(int argc, char **argv) {
	foo("\x01\x02\x03\x00");
	return 0;
}
```

Now we'll compile, dump as json and test the file
```
gcc -g -pg main.c -o main
uftrace record --auto-args main
uftrace dump --chrome > main.json
cat main | jq "."
parse error: Invalid numeric literal at line 1, column 57
```

The resulting json file contains invalid character as part of the argument reported in the strnlen call. This in turn makes the json file invalid for using in chrome.

**Comment by honggyukim** [comment]
I believe it's fixed in the current master as well. I've handled this in #736.
Please let me know if you have any other problem. Thanks for your feedback!

**Comment by namhyung** [comment]
Did you run `cat main.json` instead of `main` (binary)?

**Comment by kfir-drivenets** [comment]
@namhyung, it's a copy paste issue when I opened the ticket. It was on the json file :)

**Comment by kfir-drivenets** [comment]
I just ran the same test with the latest master (git clone & build & run again) the resulting json file was valid. So it looks like the issue was really solved :)
