### ISSUE TITLE
missing argument error during replay

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#837]
Please take a look at the following execution sequence.
```
$ uftrace --version
uftrace v0.9.3 ( dwarf python tui perf sched dynamic )

$ uftrace record -P. -la -t 1ms ./git fetch

$ uftrace replay
fstack: /home/honggyu/work/uftrace/utils/fstack.c:1419:read_task_ustack
 ERROR: record missing argument info for <4061e5>
```
It shows that it cannot find argument info. Here is the data recorded.
- [uftrace.data.git.missing.args.tar.gz](https://github.com/namhyung/uftrace/files/3438739/uftrace.data.git.missing.args.tar.gz)

I would also like to have a way to skip argument info as I suggested in #595.

**Comment by honggyukim** [comment]
Here is the `git` executable binary - [git.txt](https://github.com/namhyung/uftrace/files/3438749/git.txt)

**Comment by namhyung** [comment]
I think it doesn't matter we print args or not since it's about the parsing.  The argument and return value have variable-length so it needs argspec/retspec to parse the size correctly.  I'll take a look at the problem..

**Comment by namhyung** [comment]
It seems record has no problem and it's the `main` function with correct arguments (loaded at 0x400000).
```
F: 61e0 main
L: 26 /home/honggyu/src/git/git/common-main.c
A: @arg1%rdi,arg2/p%rsi
R: @retval
```

But I found a suspicious lines in the task file as it calls system git image from your built one.  As we use basename for symbol and debug info, it might be confused which binary was used and might access with different address.. 

```
uftrace.data.git.missing.args$ cat task.txt 
SESS timestamp=14683526.004373321 pid=2719 sid=8501b282d0c27b21 exename="/home/honggyu/src/git/git/git"
TASK timestamp=14683526.004483017 tid=2719 pid=2719
FORK timestamp=14683526.592842148 pid=2730 ppid=2719
SESS timestamp=14683526.621741111 pid=2730 sid=c4c83ff4ef37df92 exename="/usr/bin/git"
TASK timestamp=14683526.621845038 tid=2730 pid=2730
FORK timestamp=14683526.685786267 pid=2731 ppid=2719
SESS timestamp=14683526.713708582 pid=2731 sid=23d87c14ba10a6e5 exename="/usr/bin/git"
TASK timestamp=14683526.713805233 tid=2731 pid=2731
FORK timestamp=14683526.815782929 pid=2732 ppid=2719
SESS timestamp=14683526.843855396 pid=2732 sid=8638e2b1379c34ef exename="/usr/bin/git"
TASK timestamp=14683526.843956190 tid=2732 pid=2732
```

**Comment by honggyukim** [comment]
I see. I also see that it's executed with the system `git` binary. It seems that it's not a problem of uftrace. If you also think so, I will close this issue then. Thanks for the clarification.

**Comment by namhyung** [comment]
Ideally it could detect such mismatch and do something.  But let's leave it as a future work and close this for now.

**Comment by honggyukim** [comment]
Okay. I will close it. Thanks!
