### ISSUE TITLE
Function Argument: fetching all argument with one position specifier (args)

### ISSUE THREAD

**Issue by DanielTimLee** [namhyung/uftrace#841]
Currently with `function argument`, to fetch arguments, all of the argument must specified with each position specifier.

```
int do_load_unload_xdp(int *progfd, enum net_load_type *load_type, int *ifindex)

$ F=do_load_unload_xdp
$ uftrace -A $F@arg1,arg2,arg3 -F $F -D 1 -a $B net load id 16 xdp enp3s0
# DURATION     TID     FUNCTION
  47.718 us [ 18486] | do_load_unload_xdp(0x7ffffa244460, 0x7ffffa244458, 0x7ffffa24445c);
```

If all of the argument can be fetched with only one position specifier, something like `args`, it will be really convenient.

For example, like this.

```
$ F=do_load_unload_xdp
$ uftrace -A $F@args -F $F -D 1 -a $B net load id 16 xdp enp3s0
# DURATION     TID     FUNCTION
  47.718 us [ 18486] | do_load_unload_xdp(0x7ffffa244460, 0x7ffffa244458, 0x7ffffa24445c);
```

or something like `-A Func@arg*` would be great too.

**Comment by namhyung** [comment]
You can use `-A func` if you have dwarf info.

**Comment by DanielTimLee** [comment]
It's true but in case when it doesn't have dwarf data this feature would be
useful.

Since full dynamic tracing support has been added to uftrace, I use `-P .`
a lot with binary that doesn't have debug info.

In this case, I think fetching all argument with one position specifier
will be useful.

2019년 7월 31일 (수) 23:10, Namhyung Kim <notifications@github.com>님이 작성:

**Comment by namhyung** [comment]
But then it knows nothing about the functions and arguments.

**Comment by DanielTimLee** [comment]
Seems there are no valid option to implement this feature without debug info.
I'll close the issue.
