### ISSUE TITLE
Function Argument: fetching the args which is not belonged to the function

### ISSUE THREAD

**Issue by DanielTimLee** [namhyung/uftrace#844]
Function Argument option `-A`, can access the argument which is not belonged to the function. 

```
# from tests/s-arg.c
int foo(unsigned n)

$ uftrace -F foo -A foo@arg1,arg2,arg3,arg4,arg5,arg6 ./t-arg 
# DURATION     TID     FUNCTION
            [ 14826] | foo(3, 0x7ffd0def0538, 0x7ffd0def0548, 0x7f89f0139360, 0x7f89f0826a40, 0) {
            [ 14826] |   bar() {
   1.390 us [ 14826] |     strcmp();
   2.178 us [ 14826] |   } /* bar */
            [ 14826] |   bar() {
   0.054 us [ 14826] |     strcmp();
   0.255 us [ 14826] |   } /* bar */
            [ 14826] |   bar() {
   0.059 us [ 14826] |     strcmp();
   0.215 us [ 14826] |   } /* bar */
   4.048 us [ 14826] | } 
```

As you can see here, function foo only has one argument, but when using `-A` argument with
arg2, arg3, arg4, arg5, arg6, It fetches all of the values which is not owned by the function.

Well, it's just fetching `rdi, rsi, rdx, rcx, r8, r9` (on x86_64) register which is done in 'mcount.S',
But I'm wondering if this is a desired action or not.

Isn't it supposed to be blocked (or not shown) when the argument is not belonged to the function?

**Comment by namhyung** [comment]
Again, uftrace cannot know about the arguments.  Like the C programming language, uftrace honors user's intention and doesn't prevent what users want to do. :)

**Comment by DanielTimLee** [comment]
I see.

Even with dwarf info, blocking the action of 
"fetching the argument which is not belong to the function"
seems pointless.

I'll close the issue right away.
