### ISSUE TITLE
dynamic tracing support for AArch64

### ISSUE THREAD

**Issue by namhyung** [namhyung/uftrace#846]
I implemented the dynamic tracing feature on AArch64.  The basic idea is similar to x86_64 and currently it only disallows the PC-relative addressing.  This can be easily done with or without capstone so I added the both version to the [review/dynamic-aarch64-v1](https://github.com/namhyung/uftrace/compare/review/dynamic-aarch64-v1) branch.

I now can run uftrace itself (not record) with dynamic tracing.

```
$ gcc -o hello hello.c

$ uftrace record -P. hello

$ uftrace -P. -t 1ms -D3 uftrace replay --no-pager
# DURATION     TID     FUNCTION
            [  3812] | main() {             <-- replay of hello
   6.404 ms [  3812] |   puts();
   6.426 ms [  3812] | } /* main */
# DURATION     TID     FUNCTION
            [ 18359] | main() {             <-- replay of uftrace
            [ 18359] |   open_data_file() {
  41.551 ms [ 18359] |     create_session();
  42.274 ms [ 18359] |   } /* open_data_file */
            [ 18359] |   fstack_setup_filters() {
  33.843 ms [ 18359] |     walk_sessions();
  33.955 ms [ 18359] |   } /* fstack_setup_filters */
            [ 18359] |   print_header() {
   5.683 ms [ 18359] |     vfprintf();
   5.733 ms [ 18359] |   } /* command_replay */
   5.746 ms [ 18359] |   vfprintf();
   5.772 us [ 18359] |   vfprintf();
   5.748 ms [ 18359] |   vfprintf();
   2.435 ms [ 18359] |   close_data_file();
 101.998 ms [ 18359] | } /* main */
```

But many of functions have instructions using PC-relative addressing.  The success rate was not high.

```
$ uftrace -v -P. uftrace replay --no-pager
...
dynamic: dynamic patch stats for 'uftrace'
dynamic:    total:      665
dynamic:  patched:      462 (69.47%)
dynamic:   failed:      194 (29.17%)
dynamic:  skipped:        9 ( 1.35%)
dynamic: no match:        0
...
```

**Comment by honggyukim** [comment]
Thanks a lot for this work! I also tested it on my raspberry pi board and it works fine for `uftrace` itself. But I gets some segfault when trying to run `cgdb` binary as follows:
```
$ uftrace record -P. cgdb -q -ex=r -ex=q a.out
WARN: Segmentation fault: address not mapped (addr: (nil))
WARN: Backtrace from uftrace:
WARN: =====================================
WARN: [4] (annotations_parser_at_miscellaneous_prompt[aaaad6c88058] <= tgdb_run_or_queue_request[aaaad6c82294])
WARN: [3] (tgdb_run_or_queue_request[aaaad6c821f0] <= tgdb_open_new_tty[aaaad6c82358])
WARN: [2] (tgdb_open_new_tty[aaaad6c822e8] <= tgdb_initialize[aaaad6c825d4])
WARN: [1] (tgdb_initialize[aaaad6c824c0] <= main[aaaad6c73980])
WARN: [0] (main[aaaad6c736e8] <= __libc_start_main[ffffa3d74d24])
WARN: child terminated by signal: 11: Segmentation fault
```
The disassembly of `annotations_parser_at_miscellaneous_prompt` is as follows:
```asm
000000000001d058 <annotations_parser_at_miscellaneous_prompt(annotations_parser*)>:
   1d058:       39438800        ldrb    w0, [x0, #226]
   1d05c:       d65f03c0        ret
```
It seems that we need to handle more patterns. Thanks!

**Comment by honggyukim** [comment]
In addition, I think it'd be really helpful if we can have a way to export non-stripped binary, then import it when tracing stripped binary. If possible, we can use it more practical way.

**Comment by honggyukim** [comment]
I tested it again for `cgdb` with `uftrace` without capstone and it seems that the record looks fine. But uftrace doesn't finish and go to sleep status at cleanup phase.

**Comment by namhyung** [comment]
It seems there's a kind of infinite loop - maybe because return address was not calculated properly.  Anyway I updated the instruction check with capstone so that it can reject the RET instruction (which includes access to the PC).  It's available on the [review/dynamic-aarch64-v2](https://github.com/namhyung/uftrace/compare/review/dynamic-aarch64-v2)

**Comment by namhyung** [comment]
I tested it with plain gdb but result was similar.  It looks like not a problem with dynamic tracing but somehow related to vfork() IMO.  Anyway below patch make it finish:

```diff
diff --git a/cmds/record.c b/cmds/record.c
index d09cbb4..8655b46 100644
--- a/cmds/record.c
+++ b/cmds/record.c
@@ -1833,6 +1833,7 @@ static int stop_tracing(struct writer_data *wd, struct opts *opts)
 {
        int status = -1;
        int ret = UFTRACE_EXIT_SUCCESS;
+       int wait_count = 0
 
        /* child finished, read remaining data in the pipe */
        while (!uftrace_done) {
@@ -1843,6 +1844,7 @@ static int stop_tracing(struct writer_data *wd, struct opts *opts)
 
                if (remaining) {
                        read_record_mmap(wd->pipefd, opts->dirname, opts->bufsize);
+                       wait_count = 0;
                        continue;
                }
 
@@ -1863,6 +1865,10 @@ static int stop_tracing(struct writer_data *wd, struct opts *opts)
                        break;
                }
 
+               if (child_exited && wait_count++ > 1000) {
+                       break;
+               }
+
                pr_dbg2("waiting for FORK2\n");
        }
 
```

**Comment by honggyukim** [comment]
I tested it again with `cgdb` and it works fine for both capstone and manual dynamic tracing.
They both need to apply the `wait_count` change to make it finish normally. Thanks!

**Comment by honggyukim** [comment]
It seems that there are not much difference in terms of the number of records between capstone and manually traced records.
```
honggyu@rpi3:~/uftrace.data.cgdb.nocapstone$ uftrace  replay --no-pager | wc -l
3219876

honggyu@rpi3:~/uftrace.data.cgdb.capstone$ uftrace  replay --no-pager | wc -l
3243274
```

**Comment by honggyukim** [comment]
I tested it again with non-pg compiled `node` and it also works fine as follows:
```
$ uftrace record -a ./node.orig --trace-gc --expose-gc -e 'gc()'
uftrace: /home/honggyu/uftrace/cmds/record.c:1622:check_binary
 ERROR: Can't find 'mcount' symbol in the './node.orig'.
        It seems not to be compiled with -pg or -finstrument-functions flag
        which generates traceable code.  Please check your binary file.

$ uftrace record -P. -a ./node.orig --trace-gc --expose-gc -e 'gc()'
[14816:0xaaaacc4715c0]     2946 ms: Scavenge 2.5 (4.2) -> 2.2 (5.2) MB, 43.8 / 0.3 ms  (average mu = 1.000, current mu = 1.000) allocation failure 
[14816:0xaaaacc4715c0]     4198 ms: Scavenge 2.7 (5.2) -> 2.6 (5.2) MB, 47.2 / 0.1 ms  (average mu = 1.000, current mu = 1.000) allocation failure 
[14816:0xaaaacc4715c0]     7171 ms: Mark-sweep 3.6 (5.2) -> 3.2 (5.7) MB, 369.2 / 0.1 ms  (average mu = 1.000, current mu = 1.000) testing GC in old space requested
```

**Comment by honggyukim** [comment]
It's not directly related to this issue but I cannot trace some aarch64 binary with `--nest-libcall` as described in #834.
```
$ uftrace record -l ./node --trace-gc --expose-gc -e 'gc()'
plthook: /home/honggyu/uftrace/libmcount/plthook.c:790:__plthook_entry
 ERROR: invalid function idx found! (idx: 2305843009213567819/862, module: /usr/lib/aarch64-linux-gnu/libstdc++.so.6)
```
It can be reproduced with the binary `node` and it can be downloaded in [here](https://honggyu.zetacode.com/node).

Please take a look at it if possible. Thanks!

**Comment by honggyukim** [comment]
The same repeating problem was also shown in https://github.com/namhyung/uftrace/issues/731#issuecomment-485199951.

After running with `cgdb` in x86_64, uftrace doesn't finish.
```
$ uftrace record -P. `which cgdb` -ex="b main" -ex="r" -ex="q" hello
(... running forever ...)
```
I found that it keeps printing the below debug message while waiting.
```
    ...
uftrace: waiting for FORK2
uftrace: waiting for FORK2
uftrace: waiting for FORK2
uftrace: waiting for FORK2
uftrace: waiting for FORK2
uftrace: waiting for FORK2
uftrace: waiting for FORK2
uftrace: waiting for FORK2
    ...
```
It seems to be a very rare case so better to handle in a separate issue. What about merging this work, then handle this problem later?

**Comment by honggyukim** [comment]
It seems to be very exceptional case. I found that uftrace tries to patch the target program `hello` as well as `gdb` so makes the problem.
```
$ uftrace record -P. -v `which gdb` -q -ex="b main" -ex="r" -ex="q" a.out
uftrace: checking binary /usr/bin/gdb
uftrace: removing uftrace.data.old directory
uftrace: using /home/honggyu/usr/lib/libmcount.so library for tracing
uftrace: creating 10 thread(s) for recording
mcount: initializing mcount library
dynamic: dynamic patch type: 0 (none)
dynamic: dynamic patch stats for 'gdb'
dynamic:    total:     5527
dynamic:  patched:     3503 (63.37%)
dynamic:   failed:     1894 (34.26%)
dynamic:  skipped:      130 ( 2.35%)
dynamic: no match:        0
plthook: setup PLT hooking "/usr/bin/gdb"
mcount: mcount setup done
mcount: new session started: d7ca65332771ced4: gdb
Reading symbols from a.out...done.
Breakpoint 1 at 0x40052a: file /home/honggyu/hello.c, line 5.
Starting program: /home/honggyu/work/uftrace/git/uftrace/a.out
mcount: initializing mcount library
dynamic: dynamic patch type: 0 (none)
dynamic: dynamic patch stats for 'bash'
dynamic:    total:     1463
dynamic:  patched:      676 (46.20%)
dynamic:   failed:      772 (52.76%)
dynamic:  skipped:       15 ( 1.02%)
dynamic: no match:        0
plthook: setup PLT hooking "/bin/bash"
mcount: mcount setup done
mcount: new session started: 648f769d1cb81fdc: bash
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
mcount: initializing mcount library
dynamic: dynamic patch type: 0 (none)
dynamic: patched all (1) functions in 'a.out'
plthook: setup PLT hooking "/home/honggyu/work/uftrace/git/uftrace/a.out"
mcount: mcount setup done
mcount: new session started: 97354567f1583ceb: a.out

Program received signal SIGTRAP, Trace/breakpoint trap.
0x00007ffff7fee005 in ?? ()
A debugging session is active.

        Inferior 1 [process 103607] will be killed.

Quit anyway? (y or n) y
uftrace: waiting for FORK2
uftrace: waiting for FORK2
uftrace: waiting for FORK2
    ...
```

**Comment by honggyukim** [comment]
It seems that the pair between "mcount init" and "mcount fini" are not matched.
```
$ uftrace record -P. --no-libcall -v `which gdb` -q -ex="r" -ex="q" a.out
uftrace: checking binary /usr/bin/gdb
uftrace: removing uftrace.data.old directory
uftrace: using /home/honggyu/usr/lib/libmcount.so library for tracing
uftrace: creating 10 thread(s) for recording
mcount: initializing mcount library
dynamic: dynamic patch type: 0 (none)
dynamic: dynamic patch stats for 'gdb'
    ...
mcount: initializing mcount library
dynamic: dynamic patch type: 0 (none)
dynamic: dynamic patch stats for 'bash'
    ...
mcount: initializing mcount library
dynamic: dynamic patch type: 0 (none)
dynamic: dynamic patch stats for 'a.out'
    ...
Hello World!
mcount: mcount trace finished
mcount: exit from libmcount
[Inferior 1 (process 104366) exited normally]
mcount: mcount trace finished
mcount: exit from libmcount

(... running forever ...)
```
As shown above, `mcount: initializing mcount library` are shown 3 times for `gdb`, `bash`, and `a.out`. However, `mcount: mcount trace finished` are only shown twice for maybe `gdb` and `bash`. It seems that gdb does something for `a.out`, so missed to get the finish from uftrace side.

**Comment by namhyung** [comment]
Pushed [review/dynamic-aarch64-v3](https://github.com/namhyung/uftrace/compare/review/dynamic-aarch64-v3)

Changelog:
 * just rebased to master

**Comment by namhyung** [comment]
Merged: 117901c

**Comment by sgkimsm** [comment]
Hi @namhyung ,

May I assume that this kind of dynamic tracing has its own overhead, so very frequently called function may show more self time usage than "-pg" instrumented profiling?

**Comment by namhyung** [comment]
Yes, that's true.  For dynamic tracing, it needs to look up the saved code and execute one more jump.  But it's hard to say about the overhead since `-pg` affects the code generation and the body of the code may be different when it's not used.  Also dynamic tracing might not trace some functions due to technical/implementation problems.

**Comment by sgkimsm** [comment]
Ok, thank you for the answer.
Then can I think that dynamic tracing can show which functions are mostly bottleneck when only few functions consume large CPU, but when the CPU usage is distributed evenly, it may be hard to say which functions should be optimized or the profiling result is so precise or correct due to the effect of dynamic tracing as you mentioned?
With statistical profiling approach like perf, the profiling result may not be so correct in the mentioned case above, isn't it?

**Comment by namhyung** [comment]
Well, the performance impact of uftrace is large when tracing function is so small and called very frequently.  But it's already included in the target function so you should be which function has the overhead for that case too.

For perf, profiling should be correct as long as the process runs long enough (or consumes enough cpu cycles).  But I'd say that's the most case so you don't usually need to worry about that.

**Comment by sgkimsm** [comment]
Ok, thank you again for the clarification and the great work to add this cool feature. :)

**Comment by namhyung** [comment]
You're very welcome!

**Comment by sgkimsm** [comment]
Sorry for many questions, but I forgot one.
I can't reproduce below result, but I think the statistics may be quite useful sometimes. Then could you advise how I get these debug info with current implementation?

> $ uftrace -v -P. uftrace replay --no-pager
...
dynamic: dynamic patch stats for 'uftrace'
dynamic:    total:      665
dynamic:  patched:      462 (69.47%)
dynamic:   failed:      194 (29.17%)
dynamic:  skipped:        9 ( 1.35%)
dynamic: no match:        0
...

**Comment by honggyukim** [comment]
@sgkimsm It's our pleasure to answer questions. The stat info can be printed simply with `-v` or `--debug-domain dynamic:1`. Could you please try again?

**Comment by honggyukim** [comment]
Here is a simpler example.
```
$ uftrace -P. --debug-domain dynamic:1 ./uftrace
dynamic: dynamic patch type: uftrace: 0 (none)
dynamic: dynamic patch stats for 'uftrace'
dynamic:    total:      765
dynamic:  patched:      619 (80.91%)
dynamic:   failed:      137 (17.90%)
dynamic:  skipped:        9 ( 1.17%)
dynamic: no match:        0
Usage: uftrace [OPTION...]
            [record|replay|live|report|info|dump|recv|graph|script|tui]
            [<program>]
Try `uftrace --help' or `uftrace --usage' for more information.
# DURATION     TID     FUNCTION
            [ 74408] | argp_parse() {
   1.554 us [ 74408] |   parse_option();
            [ 74408] |   /* linux:task-exit */

uftrace stopped tracing with remaining functions
================================================
task: 74408
[0] argp_parse
```

**Comment by sgkimsm** [comment]
Oh, I got the result as expected, but strangely I couldn't read it from the terminal, probably due to wrong text color setting of my terminal.
Thank you for the help!

**Comment by honggyukim** [comment]
You can also save the debug log into a file with `--logfile` option.
```
$ uftrace -P. --debug-domain dynamic:1 --logfile=log ./uftrace
Usage: uftrace [OPTION...]
            [record|replay|live|report|info|dump|recv|graph|script|tui]
            [<program>]
Try `uftrace --help' or `uftrace --usage' for more information.
# DURATION     TID     FUNCTION
            [ 76148] | argp_parse() {
   1.500 us [ 76148] |   parse_option();
            [ 76148] |   /* linux:task-exit */

uftrace stopped tracing with remaining functions
================================================
task: 76148
[0] argp_parse

$ cat log
dynamic: dynamic patch type: uftrace: 0 (none)
dynamic: dynamic patch stats for 'uftrace'
dynamic:    total:      765
dynamic:  patched:      619 (80.91%)
dynamic:   failed:      137 (17.90%)
dynamic:  skipped:        9 ( 1.17%)
dynamic: no match:        0
```

**Comment by sgkimsm** [comment]
It's very good to know that there is an option for this. Thanks!

**Comment by honggyukim** [comment]
Please let us know if you have any other questions. Thank you too!
