### ISSUE TITLE
Unhandled cmdline pattern by chrome trace viewer

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#857]
The problem is that the following json output cannot be read by chrome trace viewer.
```
$ uftrace record -t 1ms ./python -c "print('Hello')"

$ uftrace info | grep cmdline
# cmdline             : uftrace record -t 1ms ./python -c print(\'Hello\')

$ uftrace dump --chrome | grep command_line
"command_line":"uftrace record -t 1ms ./python -c print(\'Hello\')"
```
But the following works fine.
```
$ uftrace record -t 1ms ./python -c 'print("Hello")'

$ uftrace info | grep cmdline
# cmdline             : uftrace record -t 1ms ./python -c print(\"Hello\")

$ uftrace dump --chrome | grep command_line
"command_line":"uftrace record -t 1ms ./python -c print(\"Hello\")"
```

**Comment by honggyukim** [comment]
It works fine after fixing the json file manually.
```diff
--- bad.json    2019-09-07 15:11:58.639573230 +0900
+++ bad-fix.json        2019-09-07 15:11:06.899241973 +0900
@@ -1922,5 +1922,5 @@
 ], "displayTimeUnit": "ns", "metadata": {
 "version":"uftrace v0.9.3-8-g533cb ( dwarf python tui perf sched dynamic )",
 "recorded_time":"Sat Sep  7 15:09:56 2019",
-"command_line":"uftrace record -t 1ms ./python -c print(\'Hello\')"
+"command_line":"uftrace record -t 1ms ./python -c print(\"Hello\")"
 } }
```

**Comment by honggyukim** [comment]
It seems that the following `strquote` has to be fixed.
```c
static int fill_cmdline(void *arg)
{
        struct fill_handler_arg *fha = arg;
        char *buf = fha->buf;
...
        p = strquote(buf, &ret);
...
}
```

**Comment by honggyukim** [comment]
It needs to fix the following code.
```c
$ cat utils/utils.c
...
/* escape quotes with backslash - caller should free the returned string */
char * strquote(char *str, int *len)
{
        char *p = str;
        int quote = 0;
        int i, k;
        int orig_len = *len;

        /* find number of necessary escape */
        while ((p = strpbrk(p, QUOTES)) != NULL) {
                quote++;
                p++;
        }

        p = xmalloc(orig_len + quote + 1);

        /* escape single- and double-quotes */
        for (i = k = 0; i < orig_len; i++, k++) {
                if (str[i] == QUOTE) {
                        p[k++] = '\\';
                        p[k] = QUOTE;
                }
                else if (str[i] == DQUOTE) {
                        p[k++] = '\\';
                        p[k] = DQUOTE;
                }
                else
                        p[k] = str[i];
        }
        p[k] = '\0';
        *len = k;

        return p;
}
...
```

**Comment by lntuition** [comment]
Is this real problem about strquote function?
I know single quote string is not standard of json format.

From <http://json.org/>
> A value can be a string in double quotes, or a number, or true or false or null, or an object or an array. These structures can be nested.

**Comment by honggyukim** [comment]
The problem seems to be that a single quote shouldn't be escaped like `print(\'Hello\')`. This makes chrome trace viewer cannot load the `.json` file.

It can simply be changed to `print('Hello')`, then it can be loaded without a problem.

**Comment by honggyukim** [comment]
As you can see from the following output.
```
$ uftrace record -t 1ms ./python -c "print('Hello')"

$ uftrace info | grep cmdline
# cmdline             : uftrace record -t 1ms ./python -c print(\'Hello\')
```
The `'Hello'` string is escaped by `strquote` function when it's written to `cmdline` info. I mentioned that it should be fixed unless there is another reason to do it.

@namhyung Is there any reason to escape a single quote to write it to `cmdline`?

**Comment by lntuition** [comment]
I check that strquote function is only called cmds/info.c which is related json format.
If there are no reason for escaping single quote to write it to `cmdline`,
then i will(i think it should be) remove logic about escaping single quote.

After remove logic, i think function name is unclear.
Maybe we can change name from strquote to strdbquote or str_doublequote.
Or we can just modify comments. 

Is it okay? I want to listen other people's opinions.

**Comment by namhyung** [comment]
I cannot remember, maybe just for generality.  I'm ok with the change.  How about the name `json_quote`?

**Comment by lntuition** [comment]
Sounds good! I will make the patch and create PR.
