### ISSUE TITLE
Need another expression for special character argument

### ISSUE THREAD

**Issue by lntuition** [namhyung/uftrace#860]
I found some bug(?) at displaying function argument with 'c'(character) format. 
Maybe another user can be confused with this option.
Test code and result are as follows.

Code

``` C
void arg_test(char ch, int i) 
{
    return;
}

int main()
{
    for(int i = 0; i < 128; ++i) {
        arg_test(i, i);
    }
}
```

Result
```
$ uftrace -A arg_test@arg1/c,arg2/i a.out
# DURATION     TID     FUNCTION
   0.382 us [ 19898] | __monstartup();
   0.106 us [ 19898] | __cxa_atexit();
            [ 19898] | main() {
   0.469 us [ 19898] |   arg_test(';
   0.071 us [ 19898] |   arg_test('^A', 1);

   // skipped

   0.056 us [ 20007] |   arg_test(', 8);
   0.055 us [ 19898] |   arg_test('     ', 9);
   0.055 us [ 19898] |   arg_test('
', 10);

   // skipped
```

With above result, ASCII code number 0('\0') is considered end of string. So it didn't print arg2. 
Similarly(i think this is not critical), ASCII code number 8('backspace') remove quote. 

I think we need another expression to show special character such as '\0', (backspace), etc... 
If this issue is vaild, we need to talk about expression format for special character.

**Comment by honggyukim** [comment]
I agree. They should be printed in a better way. Here is a simpler example based on your test.
```
$ cat issue860.c
void arg_test(char ch, int i)
{
}

int main()
{
        arg_test(0, 0);
        arg_test(8, 8);
}

$ gcc -pg issue860.c
```
The replay output doesn't look good as follows:
```
$ uftrace -F main -A arg_test@arg1/c,arg2/i a.out
# DURATION     TID     FUNCTION
            [ 85263] | main() {
   2.104 us [ 85263] |   arg_test(';
   0.320 us [ 85263] |   arg_test(', 8);
   5.244 us [ 85263] | } /* main */
```
It can be printed in a better way as follows:
```
$ uftrace -F main -A arg_test@arg1/c,arg2/i a.out
# DURATION     TID     FUNCTION
            [ 85263] | main() {
   2.104 us [ 85263] |   arg_test('\0', 0);
   0.320 us [ 85263] |   arg_test('\b', 8);
   5.244 us [ 85263] | } /* main */
```

**Comment by namhyung** [comment]
Please do it for the string arguments too.

**Comment by lntuition** [comment]
I only apply escape sequence to '\0'(null), '\b'(backspace), '\n'(line feed). Because i think current expression of the other unprintable character such as '\t'(tab) is more easy to understand.

If anyone find cleaner solution(general expression for unprintable character), modify this solution plz.

**Comment by namhyung** [comment]
Hmm.. considering unicode (UTF-8) I don't know what's the better approach.  For ASCII, escaping would be better but it might break some UTF-8 encodings too.
