### ISSUE TITLE
convert to getopt_long for option parsing

### ISSUE THREAD

**Issue by namhyung** [namhyung/uftrace#871]
Currently it uses `argp_parse()` to parse command line options.  But it's glibc-specific so has some portability problems.  While there's a supporting library for this, it'd be nice to avoid using it.  I think it's rather straight-forward to convert the option parser to use `getopt_long()` instead.

**Comment by honggyukim** [comment]
This is one of the most valuable work items as a first step to support Android.

**Comment by gonapps** [comment]
I want to contribute this issue!

**Comment by honggyukim** [comment]
> I want to contribute this issue!

Great! Please go ahead.

**Comment by namhyung** [comment]
@binkoni can I take this over?

**Comment by binkoni** [comment]
@namhyung
Sure you can :)

2020년 3월 29일 (일) 오후 4:37, Namhyung Kim <notifications@github.com>님이 작성:

**Comment by namhyung** [comment]
Pushed [review/getopt-v1](https://github.com/namhyung/uftrace/compare/review/getopt-v1).

**Comment by honggyukim** [comment]
Thanks a lot for the update. It mostly works fine, but it doesn't properly pass target options.
```
$ uftrace record -P. ./chrome --no-sandbox --headless https://www.google.com
uftrace: unrecognized option '--no-sandbox'
uftrace: /home/honggyu/work/uftrace/cmds/record.c:1542:find_in_path
 ERROR: Cannot trace '--headless': No such executable file.
```
It requires explicit `--` mark as follows.
```
$ uftrace record -P. -- ./chrome --no-sandbox --headless https://www.google.com
```

**Comment by honggyukim** [comment]
The simpler example is as follows.
```
$ gcc -pg -o t-abc tests/s-abc.c

$ ./t-abc
$ uftrace ./t-abc
# DURATION     TID     FUNCTION
   1.459 us [ 19883] | __monstartup();
   1.019 us [ 19883] | __cxa_atexit();
            [ 19883] | main() {
            [ 19883] |   a() {
            [ 19883] |     b() {
            [ 19883] |       c() {
   0.815 us [ 19883] |         getpid();
   2.005 us [ 19883] |       } /* c */
   2.578 us [ 19883] |     } /* b */
   3.002 us [ 19883] |   } /* a */
   3.473 us [ 19883] | } /* main */
```
The following `--target-option` is expected to be used as an option for `t-abc` itself instead of `uftrace` option, but it doesn't work.
```
$ ./t-abc --target-option
$ uftrace ./t-abc --target-option
uftrace: unrecognized option '--target-option'
uftrace -- function (graph) tracer for userspace

Usage: uftrace [COMMAND] [OPTION...] [<program>]

 COMMAND: record|replay|live|report|graph|info|dump|recv|script|tui

```

**Comment by namhyung** [comment]
Thanks for testing.  I don't know how I can control that..

**Comment by namhyung** [comment]
Oh, I found that we can control non-option behavior using the short option string prefix ("+").  Please check [review/getopt-v2](https://github.com/namhyung/uftrace/compare/review/getopt-v2).

from the man page of [getopt_long(3)](https://linux.die.net/man/3/getopt_long):
> By default, getopt() permutes the contents of argv as it scans, so that eventually all the nonoptions are at the end. Two other modes are also implemented. If the first character of optstring is '+' or the environment variable POSIXLY_CORRECT is set, then option processing stops as soon as a nonoption argument is encountered. If the first character of optstring is '-', then each nonoption argv-element is handled as if it were the argument of an option with character code 1. (This is used by programs that were written to expect options and other argv-elements in any order and that care about the ordering of the two.) The special argument "--" forces an end of option-scanning regardless of the scanning mode.

**Comment by honggyukim** [comment]
I tested and confirmed that it works fine now. Thanks a lot for your work!

**Comment by namhyung** [comment]
Thanks for the testing!
