### ISSUE TITLE
Support man pages written in Korean

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#880]
It can be simply copied from `doc/*.md` to `doc/ko/*.md`, then translated in Korean language. Then it can be compiled after applying the following change.
```diff
diff --git a/Makefile b/Makefile
index 38b68ef..c93dc00 100644
--- a/Makefile
+++ b/Makefile
@@ -32,6 +32,10 @@ etcdir = $(prefix)/etc
 mandir = $(prefix)/share/man
 docdir = $(srcdir)/doc

+ifeq ($(DOCLANG), ko)
+  docdir = $(srcdir)/doc/ko
+endif
+
 srcdir = $(CURDIR)
 # set objdir to $(O) by default (if any)
 ifeq ($(objdir),)
```
The build command can be as follows:
```
$ make DOCLANG=ko install
```

**Comment by honggyukim** [comment]
The PR #885 is submitted for better start of this issue.

**Comment by honggyukim** [comment]
It's done by #885, so close it now.

**Comment by DanielTimLee** [comment]
If the Korean document is not displayed, it is probably a locale problem.

Make sure the locale is set to `LANG=ko_KR.UTF-8`.

```bash
$ man uftrace-recv
No manual entry for uftrace-recv

$ export LANG=ko_KR.UTF-8

$ locale
LANG=ko_KR.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="ko_KR.UTF-8"
LC_NUMERIC=ko_KR.UTF-8
LC_TIME=ko_KR.UTF-8
LC_COLLATE="ko_KR.UTF-8"
LC_MONETARY=ko_KR.UTF-8
LC_MESSAGES="ko_KR.UTF-8"
LC_PAPER=ko_KR.UTF-8
LC_NAME=ko_KR.UTF-8
LC_ADDRESS=ko_KR.UTF-8
LC_TELEPHONE=ko_KR.UTF-8
LC_MEASUREMENT=ko_KR.UTF-8
LC_IDENTIFICATION=ko_KR.UTF-8
LC_ALL=
```

**Comment by honggyukim** [comment]
This work is done by the following pull requests.
- uftrace: #924
- record: #991
- live: #991
- replay: #992
- report: #933
- dump: #929
- graph: #969
- tui: #984
- script: #948
- info: #995
- README: #986
