### ISSUE TITLE
Support Arch Linux for required dependency install

### ISSUE THREAD

**Issue by henrychoi7** [namhyung/uftrace#883]
Since I'm using Arch Linux for uftrace, is it okay to add support for the dependency install in `misc/install-deps.sh`? I've already added few lines, tested the installation and it worked fine on running kernel `5.2.14-arch2-1-ARCH`. I also separated the capstone in case of old distros. (#833)

Where I'm trying to add it:
https://github.com/namhyung/uftrace/blob/29b53352a972c43d7d2c4b62c4f9635dfc204d48/misc/install-deps.sh#L25

**Comment by honggyukim** [comment]
Sure. Please go ahead. @namhyung also uses Arch Linux by the way.

**Comment by henrychoi7** [comment]
Thank you. I'll create a new PR for this issue later on.

**Comment by namhyung** [comment]
@honggyukim not anymore :(

@henrychoi7 please do!

**Comment by honggyukim** [comment]
@namhyung I didn't know that. I'm just wondering about your new distro. :)

**Comment by namhyung** [comment]
Well, I'm using Ubuntu now...

**Comment by honggyukim** [comment]
Thanks. We now have only Ubuntu, so may have to care more about other distros then.

**Comment by gonapps** [comment]
@henrychoi7 
No pull request yet? I could add arch linux dependencies if you are busy

**Comment by honggyukim** [comment]
@gonapps Thanks for your passion, but I think you don't have to make him hurry :)

**Comment by henrychoi7** [comment]
@gonapps Sorry about the delay. Please let me know if anything goes wrong.
