### ISSUE TITLE
Reshape graph --task output

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#884]
As I mentioned in https://github.com/namhyung/uftrace/issues/645#issuecomment-529554699, the task display with `--task` can be improved as follows:
- I think `graph --task` output can be shown exactly same as normal function-level graph output, but at task-level.
- It doesn't work well with time-filter. I expect the time-filter work to hide based on the task time. It could be total or self time.

For other readers, I prefer to make the following task-level output almost same as function-level output.
```
      $ uftrace graph --task
      ========== TASK GRAPH ==========
      # TOTAL-TIME   SELF-TIME : TASK
          9.002  m    1.041  m : [168086] chrome
                               :  +-[168130] chrome
                               :  |
          7.018  m    1.020  m :  +----[168131] chrome
                               :  |     |
          2.039  m    2.802  s :  |     +----[168200] chrome
                               :  |     |     +-[168201] chrome
          2.039  m   16.797 ms :  |     |     +-[168202] TaskSchedulerFo
          2.039  m  432.881 ms :  |     |     +-[168204] Chrome_ChildIOT
```

**Comment by namhyung** [comment]
Fixed by #1050
