### ISSUE TITLE
Support docker images

### ISSUE THREAD

**Issue by gonapps** [namhyung/uftrace#886]
I'm thinking of adding Dockerfiles to this project.
If I add Dockerfiles for various distros such as ubuntu, arch, centos, apine..
It would be easier to test uftrace in other environments.

According to [this post](https://twitter.com/brendangregg/status/508094166769737728?lang=en) it seems possible to trace kernel functions inside containers.

**Comment by honggyukim** [comment]
Thanks. It looks useful when testing for multiple distros.

**Comment by DanielTimLee** [comment]
Is uftrace currently hosted from docker hub?
Any plan when it will be hosted?

**Comment by namhyung** [comment]
I don't have any plan for it.
