### ISSUE TITLE
dynamic tracing gcc

### ISSUE THREAD

**Issue by kuongee** [namhyung/uftrace#891]
Hi, 

I'm trying to trace gcc with uftrace, and I have one question in result of replay.

1. I tried like this: 

<pre><code>$ uftrace record -F main /usr/local/bin/gcc 
$ uftrace replay </code></pre>

It showed like below in the last of replay,
<pre><code>uftrace stopped tracing with remaining functions
================================================
task: 5585
[7] exit
[6] diagnostic_action_after_output
[5] diagnostic_report_diagnostic
[4] diagnostic_impl
[3] fatal_error
[2] driver::prepare_infiles
[1] driver::main
[0] main</pre></code>

2. After that, I traced gcc with **-P main** option
<pre><code>$ uftrace record -P main /usr/local/bin/gcc 
$ uftrace replay </code></pre>

uftrace replayed and the last paragraph showed like this:
<pre><code>
uftrace stopped tracing with remaining functions
================================================
task: 5608
[8] exit
[7] diagnostic_action_after_output
[6] diagnostic_report_diagnostic
[5] diagnostic_impl
[4] fatal_error
[3] driver::prepare_infiles
[2] driver::main
[1] main
[0] main
</code></pre>

As you can see, there are 2 main in the result of dynamic tracing replay.

I'm not sure, but I think both result should be same.
Is there anything that I missed?

I'm working on Ubuntu 18.04 on Virtual box and I referenced wiki page to build gcc. 
If it's a little different from a wiki page, I just add 'go' in option --enable-languages, like --enable-languages=c,c++,go.

Thank you!

Reference
- https://golang.org/doc/install/gccgo

**Comment by honggyukim** [comment]
Hi @kuongee, the manual is written to compile gcc with `-pg` option and it makes `gcc` binary already tracable. Since you manually patch `main` function again with `-P main`, the `main` function has `mcount` calls twice simply speaking.

The dynamic tracing feature with `-P` is better to be used when the target binary is not compiled with tracable compiler option such as `-pg` or `-finstrument-functions`.

Thanks for the try anyway. :)

**Comment by honggyukim** [comment]
If you try the following example, then it's might be easier to understand.
```
$ gcc -pg tests/s-abc.c -o t-abc

$ uftrace t-abc
# DURATION     TID     FUNCTION
   1.313 us [163081] | __monstartup();
   0.864 us [163081] | __cxa_atexit();
            [163081] | main() {
            [163081] |   a() {
            [163081] |     b() {
            [163081] |       c() {
   0.773 us [163081] |         getpid();
   1.720 us [163081] |       } /* c */
   2.287 us [163081] |     } /* b */
   2.730 us [163081] |   } /* a */
   3.267 us [163081] | } /* main */

$ uftrace -P. t-abc
# DURATION     TID     FUNCTION
   1.826 us [163095] | __monstartup();
   0.976 us [163095] | __cxa_atexit();
            [163095] | main() {
            [163095] |   main() {
            [163095] |     a() {
            [163095] |       b() {
            [163095] |         c() {
   0.793 us [163095] |           getpid();
   1.960 us [163095] |         } /* c */
   2.547 us [163095] |       } /* b */
   3.050 us [163095] |     } /* a */
   3.567 us [163095] |   } /* main */
  14.640 us [163095] | } /* main */
```
Please note that full dynamic tracing with `-P` might fail to insert tracable code to some functions under some restrictions. For example, if the target function is too small, then it may not be possible.

In this case, only `main` function is successful to insert `mcount` call with `-P` option.

**Comment by kuongee** [comment]
I added -P option because I was just wondering how to use.
And that's why that happened!!
Anyway, thank you for your kind reply! :)

**Comment by honggyukim** [comment]
You will better understand dynamic tracing by reading the followings:
- [man uftrace record](https://github.com/namhyung/uftrace/blob/master/doc/uftrace-record.md#dynamic-tracing)
- [dynamic tracing in slide tutorial](https://uftrace.github.io/slide/#dynamic-tracing)
- [full-dynamic tracing in slide tutorial](https://uftrace.github.io/slide/#full-dynamic-tracing)

Welcome and thanks for the first issue :)
