### ISSUE TITLE
Tracing SpiderMonkey JavaScript engine

### ISSUE THREAD

**Issue by henrychoi7** [namhyung/uftrace#896]
Hello,

I'm trying to trace SpiderMonkey, which is available as a standalone interactive shell (Also, Mozilla Firefox uses SpiderMonkey JS interpreter but I want to start it with the engine first). I used the source code version 59.0 and tested with the debug build (with `-pg` compiler flags).

Tracing result looked fine with no errors and I was wondering if it's okay to write down the Wiki about tracing this JavaScript command-line shell. It seems to be less popular than Node.js JavaScript shell but I think it's worth a try according to this [article](http://programmingeducator.com/2019/04/08/javascript-shells-spidermonkey/).

**Comment by honggyukim** [comment]
Sure. Please do not hesitate writing the doc in wiki page. Thanks for your try :)

**Comment by henrychoi7** [comment]
Thank you! I’ll update the Wiki soon.
