### ISSUE TITLE
support a way to change sort key in TUI report mode

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#907]
The current TUI doesn't support to change a sort key and it fixes the key to "total".

We have to provide a key to change the sort key in TUI report mode. I personally think that `s` can be used to change the key.

The key can be changed in order whenever `s` key is pressed.

**Comment by hjongkim** [comment]
I want to try this issue.

**Comment by honggyukim** [comment]
Thanks. Please go ahead :)
