### ISSUE TITLE
uftrace-gdb.py Error

### ISSUE THREAD

**Issue by junhoryu** [namhyung/uftrace#912]
![Screenshot from 2019-09-28 12-18-48](https://user-images.githubusercontent.com/7580915/65810807-553a6d00-e1ea-11e9-89d8-f9e771dd7f10.png)

I executed uftrace-gdb.py, the output error like above.
I do not know what problem it is.

thank you.

**Comment by DanielTimLee** [comment]
It is not intended to be run individually.
GDB has scripting feature (python), and the file `uftrace-gdb.py` that you tried to run was actually intended to be loaded when debugging uftrace.

https://github.com/namhyung/uftrace/blob/df0921fb7be57552340b71c9ff694d9ca68547ea/uftrace-gdb.py#L15-L17

As you can see, from the content of the `uftrace-gdb.py`, it fetches modules from `gdb/` directory which are basically a helper for debugging uftrace.

This might help understanding further about GDB scripting feature.
https://www.kernel.org/doc/html/v4.10/dev-tools/gdb-kernel-debugging.html
