### ISSUE TITLE
Add usage description for script --record option

### ISSUE THREAD

**Issue by henrychoi7** [namhyung/uftrace#976]
Hi there,

According to the man page for [uftrace-script](https://github.com/namhyung/uftrace/blob/master/doc/uftrace-script.md#script-options), the command could be executed like below:

```
$ uftrace script -S scripts/strings.py --record pwd
/home/(username)/uftrace
"POSIXLY_CORRECT"
---
"en_US.UTF-8"
---
"/"
---
"coreutils"
---
"pwd"
---
"LP"
---
"NULL"
---
"/home/(username)/uftrace"
---
"/usr/share/locale"
---
```

But, I couldn't find any description about `--record` option in the usage output.
https://github.com/namhyung/uftrace/blob/efa568409286a7b56d3bee9598e7b6cec06d0d4d/cmds/script.c#L148

Therefore, I'm thinking of adding `[--record]`, and is it okay to put it between `[-S|--script]` and `[<script_file>]`? If I put it in the end of the command, it doesn't seem to record a new trace before running a given script.

**Comment by namhyung** [comment]
> is it okay to put it between [-S|--script] and [<script_file>]?is it okay to put it between [-S|--script] and [<script_file>]?

No, it should be after the `<script_file>` since it's the argument of the `-S` option.

> If I put it in the end of the command, it doesn't seem to record a new trace before running a given script.

Then it's a bug.  What was your exact command line?

**Comment by henrychoi7** [comment]
Oh, sorry. I meant the end of the command line. My command line was exact same as the above. There was no bug about this. Then, is it okay to put it after the `<script_file>`?

Also, when there were no arguments or options in using `record` and `live`, the output description was same like below:

```
$ uftrace record
Usage: uftrace [OPTION...]
            [record|replay|live|report|info|dump|recv|graph|script|tui]
            [<program>]
Try `uftrace --help' or `uftrace --usage' for more information.
$ uftrace live
Usage: uftrace [OPTION...]
            [record|replay|live|report|info|dump|recv|graph|script|tui]
            [<program>]
Try `uftrace --help' or `uftrace --usage' for more information.
$ uftrace script
Usage: uftrace script [-S|--script] [<script_file>]
```

Aren't these supposed to be different like `script`?

**Comment by honggyukim** [comment]
`record` and `live` accept `COMMAND` for target program binary, but `script` is an analysis command just like `replay`, `report` and others.

**Comment by namhyung** [comment]
Yes, but `uftrace script --record` should accept `COMMAND` as well.  But `-S` option is mandatory so I think the usage should remove the "[ ]" (which means optional arguments) like below:

```
Usage: uftrace script (-S|--script) <script_file>
```

The --record option is different and I think it's better to add another line in the synopsis section of the uftrace-script manpage.

**Comment by henrychoi7** [comment]
Okay, I understand what you mean. I'll remove `[]` in the usage description.

Then, is it okay to add something like:
```
uftrace script [*options*] COMMAND [*command-options*]
```
in the synopsis section of the uftrace-script man page? I'm not sure if it's fine to replace it with the original one.

It's out of the question, also I found that there is `[live]` in the [synopsis section](https://github.com/namhyung/uftrace/blob/master/doc/uftrace-live.md#synopsis) of the uftrace-live man page. Shouldn't this `[]` be removed?

**Comment by namhyung** [comment]
> I'm not sure if it's fine to replace it with the original one.

Don't replace, just add it.

```
SYNOPSIS
========
uftrace script (-S|--script) <script file> [*options*]
uftrace script (-S|--script) <script file> [*options*] --record COMMAND
```

> It's out of the question, also I found that there is [live] in the synopsis section of the uftrace-live man page. Shouldn't this [] be removed?

No, the "live" part is really optional.

**Comment by henrychoi7** [comment]
Thank you for your opinion! I'll leave a PR for this later.
