### ISSUE TITLE
x86_64: handling CALL instruction for dynamic tracing

### ISSUE THREAD

**Issue by namhyung** [namhyung/uftrace#988]
Currently it rejects functions having CALL in the prologue due to its PC-relative addressing for return address.  But as it's basically same as PUSH + JMP we can handle it like others.  Actually we already use JMP at the end of the copied instructions to move to the original function.

So to support CALL we can convert it to PUSH and adjust target address of JMP.  After applying this I could trace the typical `t-abc` example like below - it was not possible since a, b and c are small functions and have CALL in their prologue.

```
$ uftrace -P.  tests/t-abc
# DURATION     TID     FUNCTION
            [ 63770] | main() {
            [ 63770] |   a() {
            [ 63770] |     b() {
            [ 63770] |       c() {
   5.104 us [ 63770] |         getpid();
  11.402 us [ 63770] |       } /* c */
  12.460 us [ 63770] |     } /* b */
  13.607 us [ 63770] |   } /* a */
  16.028 us [ 63770] | } /* main */
```

I test it with the C-python interpreter and gets ~1% of increased success.

The code is available at [review/dynamic-x86-call-v1](https://github.com/namhyung/uftrace/compare/review/dynamic-x86-call-v1) branch.

**Comment by honggyukim** [comment]
Thanks for doing this work, but it needs to be rebased to avoid a recent bug.

I tested it after rebasing and it works good.

**Before**
```
$ uftrace -P. --debug-domain dynamic:1 t-abc
dynamic: dynamic patch type: abc: 0 (none)
dynamic: dynamic patch stats for 'abc'
dynamic:    total:        4
dynamic:  patched:        1 (25.00%)
dynamic:   failed:        3 (75.00%)
dynamic:  skipped:        0 ( 0.00%)
dynamic: no match:        0
# DURATION     TID     FUNCTION
            [159602] | main() {
   1.426 us [159602] |   getpid();
   8.097 us [159602] | } /* main */
```

**After**
```
$ uftrace -P. --debug-domain dynamic:1 t-abc
dynamic: dynamic patch type: abc: 0 (none)
dynamic: patched all (4) functions in 'abc'
# DURATION     TID     FUNCTION
            [160094] | main() {
            [160094] |   a() {
            [160094] |     b() {
            [160094] |       c() {
   1.947 us [160094] |         getpid();
   8.527 us [160094] |       } /* c */
   9.560 us [160094] |     } /* b */
  10.623 us [160094] |   } /* a */
  13.014 us [160094] | } /* main */
```

**Comment by honggyukim** [comment]
Here is disassembly output of `a` function.
```asm
0000000000400566 <a>:
  400566:       55                      push   %rbp
  400567:       48 89 e5                mov    %rsp,%rbp
  40056a:       e8 05 00 00 00          callq  400574 <b>
  40056f:       83 e8 01                sub    $0x1,%eax
  400572:       5d                      pop    %rbp
  400573:       c3                      retq
```
The fifth byte is the beginning of `callq` instruction so it was failed in the current master, but handled with this change.

**Comment by namhyung** [comment]
Thanks for the test, rebased and force pushed to the branch.

**Comment by namhyung** [comment]
@ParkHanbum are you ok with this?
