### ISSUE TITLE
error when using multiple command lines

### ISSUE THREAD

**Issue by rls1004** [namhyung/uftrace#996]
steps to reproduce this error : 
```
$ uftrace ./fmt "
> "


uftrace: /home/rls1004/uftrace/utils/data-file.c:493:open_info_file
 ERROR: cannot read uftrace header info!
```

**Comment by honggyukim** [comment]
Could you please explain more about it?

**Comment by rls1004** [comment]
For example, in this case
```
$ uftrace record ./test "a
b"
```
The recorded cmdline is shown below.
```
...
cmdline:uftrace record ./fmt a
b
cpuinfo:lines=2
...
```

The `read_cmdline()` read it using the `fgets()`, so reading stops after a newline.

https://github.com/namhyung/uftrace/blob/7817a96eb33f28e0fbb931301a493c633994af65/cmds/info.c#L249-L257

The `read_cpuinfo()` reads the next line as well.
An error occurs because the string "cpuinfo:" cannot be read.
